### ISSUE TITLE
Maxent Classifier:  Failed to minimize multi-class objective function

### ISSUE THREAD

**Issue by justinsowhat** [haifengl/smile#107]
Hi,
When I used the Maxent classifier to run again my data set, I ran into this error message. I basically converted my data set with the Nominal2SparseBinary class (my data set was working for other classifiers), and then used the binary features to train a Maxent classifier. However, I kept running into the following error. Any pointer on how to debug/solve it will be appreciated. Thanks!

[main] ERROR smile.classification.Maxent - Failed to minimize multi-class objective function of Maximum Entropy Classifier
java.lang.ArrayIndexOutOfBoundsException: 208
	at smile.classification.Maxent.dot(Maxent.java:870)
	at smile.classification.Maxent.access$200(Maxent.java:53)
	at smile.classification.Maxent$MultiClassObjectiveFunction.f(Maxent.java:743)
	at smile.math.Math.min(Math.java:5102)
	at smile.classification.Maxent.<init>(Maxent.java:255)
	at smile.classification.Maxent$Trainer.train(Maxent.java:151)
	at smile.classification.Maxent$Trainer.train(Maxent.java:84)
	at smile.validation.Validation.cv(Validation.java:457)

**Comment by haifengl** [comment]
Can you share the data with me for debugging? I won't share the data with others. Thanks!

**Comment by justinsowhat** [comment]
I serialized the AttributeDataset and attached it here. 
[samle_attribute_dataset.zip](https://github.com/haifengl/smile/files/371636/samle_attribute_dataset.zip)

**Comment by haifengl** [comment]
Thanks! I will check it out.

**Comment by haifengl** [comment]
How did you save the data? I cannot open it with read.xstream.

**Comment by haifengl** [comment]
Hi, MaxEnt takes sparse data as input. Each sample is represented by a set of sparse
 binary features. The features are stored in an integer array, of which
 are the indices of nonzero features.

Your data doesn't look like sparse array encoding. If your data are dense matrix, I suggest that you use logistic regression instead, which is same as MaxEnt mathematically.

**Comment by justinsowhat** [comment]
Oh ok, that's why. Thanks! So if I were to use the MaxEnt model, my dataset should be a SparseDataset object instead AttributeDataset? And when should I use Nominal2SparseBinary?

**Comment by haifengl** [comment]
Please check out http://haifengl.github.io/smile/api/java/index.html, which has detailed information on data format.

Only if your nominal data is binary and very sparse (e.g. bag of words in NLP), you should use Nominal2SparseBinary.

**Comment by justinsowhat** [comment]
Great, thank you!
