### ISSUE TITLE
problem with save

### ISSUE THREAD

**Issue by gkhanacer** [haifengl/smile#109]
Hello,
I want to draw a QQ plot and save it as png or jpeg. 
When i examine your code, it draws the plot on a JFrame and when i right click and hit save, it saves the plot to a file.
However, I don't want to use a JFrame (since this plot will be a part of web application). So, I set JFrame's visibility to false and call the save method with a file parameter. But the resulted file is always empty. 
Here is my code

``` java
File file=new File(filePath);
GaussianDistribution normal = new GaussianDistribution(data);
PlotCanvas canvas = QQPlot.plot(data, normal);
canvas.setTitle("Uniform (Smile)");
canvas.setSize(new Dimension(720, 480));
JFrame frame = new JFrame("QQ Plot");
frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
frame.setLocationRelativeTo(null);
frame.setSize(500, 500);
frame.setVisible(false);
canvas.save(file);
```

How can I draw a QQ plot and save it as a file without displaying the JFrame?
Thanks in advance.

**Comment by haifengl** [comment]
Hi, you can do a headless plot:

val canvas = ScatterPlot.plot(x, '.', java.awt.Color.BLACK)

val headless = new Headless(canvas);
headless.pack();
headless.setVisible(true);

canvas.save(new java.io.File("zone.png"))

Note that you should run JVM with option -Djava.awt.headless=true

Besides, this feature is not in release 1.1 but in master branch. You need to build the master branch by yourself for now.

**Comment by haifengl** [comment]
smile 1.2 is just released with headless plot. please have a try. Thanks!

**Comment by gkhanacer** [comment]
Thank you very much!
