### ISSUE TITLE
Library is not deterministic

### ISSUE THREAD

**Issue by stuz5000** [haifengl/smile#110]
Its not straightforward in Smile to have experiment reproducibility because random seeds and random number generators are no externalized. 

This could be solved in several ways:
 - allowing a random seed to be provided wherever a random number generator is used, or
 - allowing a random number generator to be provided 
 - allowing the call for a random number to be overridden

**Comment by haifengl** [comment]
Many algorithms are multithreaded and each thread has their own random number generator, for example random forest. It is not right to initialize every thread with the same seed in this case. What're your suggestions for this?

**Comment by stuz5000** [comment]
Random sequences need to be assigned to tasks/algorithms, not threads.

Suppose we have, an algorithm that wants to start 20 tasks in 5 threads.
And suppose that tasks(6) wants to start 8 jobs in 2 thread. Each job in
this tree needs to work with a random number generator that's determined by
its position in the tree:

We'd like the functional dependence:
   getRandomGenerator( tasks(6.3.4) )
where job 6 started job 6.3, which started job 6.3.4.

One way to do this is:

---
def sometask(seed:Long):
 val  rnd = getRandomGenerator(seed)  # rnd is used for
  for n in numSubTasks:
      subtask( seed=rnd.generateInt() )
----

subtask could executed immediately or in a thread.

If this method doesn't have degenerate cases, then I think its sufficient
if:

 - that every algorithm that requires a random number generator is required
to be provided a seed
 - every subalgorithm started that requires a random number generator must
be issued the seed for its own generator by the parent algorithm

Alternatively we could provide a random number generator directly for all
algorithms (instead of the seed):

---
def sometask(rnd1:RandomGenerator):
  for n in numSubTasks:
      subtask( rnd2=RandomGenerator(rnd1.generateInt()) )
---

This is equivalent, but care needs to be taken that rnd1 isn't accidentally
passed as rnd2 in the case where a subtask is executed in another thread.

**Comment by haifengl** [comment]
It is much more complicated by passing a sequence of random numbers:

1. it is not clear how many random numbers are needed for many algorithms. Also it breaks the encapsulation as the caller has to know the details of algorithms.
2. Some algorithms need many kinds of random numbers (integers in a given range and/or real values). Passing plain random bits make life more complicated.

A work around is to ensure only one thread when you want repeatable results. This should be fine as one want repeatable results for debugging/testing. For production, you can still use multithreading. To us only one threads, use

-Dsmile.threads=1 

for java command line.

**Comment by stuz5000** [comment]
If you want functional determinism ( a requirement for repeatable
experiments, and also deterministic unit tests) one of 3 things has to
happen:
  - the algorithm is passed a seed
  - the algorithm is passed an interface that generates the rand one
numbers,
  - the algorithm is made deterministic by internally using a fixed seed.

I think all this means is that they should use either the supplied seed or
random number interface to generate its numbers or initialize further
random generators.


Setting the number of threads to 1 doesn't lead to determinism if algorithm
randomly pick their own seeds.
Threading isn't the major issue (although I can understand it makes it
difficult at the edges). It's not worth tackling the non determinism caused
by multi threading until the basic single threaded versions and
functionally determined by their parameters.

>

**Comment by haifengl** [comment]
call smile.math.Math.setSeed before call an algorithm to set the seed

**Comment by stuz5000** [comment]
My point is, supplying the means to be deterministic is no bad thing for an
ML algorithm, or any algorithm where you want repeatable behavior.

Preserving encapsulation isn't a good argument for behavior that is
required to be externally sepecified. IF you want to be able to externally
determine the pseudorandom sequence then it MUST be externally specified. I
don't see that it breaks encapsulation any more than others parameters to
algorithms.

**Comment by haifengl** [comment]
You have not gotten the point of multithreading. Each random number generator maintain an internal state so that it is not multithread-safe. If multithreads share a random number generator, we have to use locks, which significant reduce the performance.

So each thread has its own random number generator. And each thread should use different seeds for its own random number generator. Otherwise, algorithms like random forest won't work properly. Now, the caller must know how many system threads are running and passes an array of seeds or generators. That interface/contract is not really nice.

**Comment by haifengl** [comment]
By my experience, the only case that repeatable results matter is to test and/or verify an algorithm. I think that -Dsmile.threads=1 and smile.math.Math.setSeed should be sufficient for that purpose.

**Comment by ngorelick** [comment]
I would like to reopen this issue.  Repeatability is pretty crucial for some uses (including mine) that aren't just test & verification.

You can manage the multi-threading issue by using a global seed value (lets say 0) and for each task, increment the seed.  In RandomForest.java, for instance, the threading is done with TrainingTask()s built in a for-loop.  Passing a new seed to each TrainingTask of (userSeed + i) would fulfill the requirements for repeatability and still give each thread its own unique seed with which it could start its own random number generator.

**Comment by stuz5000** [comment]
+1
