### ISSUE TITLE
CoverTree fails when only 1 element is indexed

### ISSUE THREAD

**Issue by jkirsch** [haifengl/smile#116]
In the extreme case, when there is only one element indexed, the covertree fails

This line in [CoverTree.java#L519](https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/neighbor/CoverTree.java#L519) just returns an empty array

I think the fix would be to add the root to the created index, before returning

`a1[0] = n1;`

**Comment by haifengl** [comment]
Thank you very much! We have fixed the bug as you suggest. It is pushed to master now.

**Comment by jkirsch** [comment]
Thanks for looking into this
