### ISSUE TITLE
KMeans Lloyd changes the centroids around with the exact same data (just by restarting the code)

### ISSUE THREAD

**Issue by Xyclade** [haifengl/smile#117]
I have created a set up where I have the data to cluster stored in a file, and am performing a K-means clustering with K = 3, and 100 iterations

What I found was that the first run, the centroids where:
[0] 102.54
[1] 612.23
[2] 214.92

Thats fine, but what happened next was that after I re-ran the same code, the centroids were:

[0] 612.13
[1] 214.82
[2] 102.64

The problem is not the small variance in the numbers here (which is normal when it comes to clustering in iterations), but the ordering of the centroids.

In my set up I want to use the labels from this K-means clustering model for a classification algorithm, but this is not possible when it keeps changing the order of the centroids, and thus the clustering labels.

Is this a bug, or is this by design?

If it is by design I will work around it by ordering the centroids based on their value, and then creating a mapping of the label to these new indexes, otherwise this might be an option as final step in the algorithm?

**Comment by haifengl** [comment]
It is by design. Stochastic algorithms work in this way.

**Comment by Xyclade** [comment]
Ok, I will work around it.
