### ISSUE TITLE
GradientTreeBoost constructor y is not double[]

### ISSUE THREAD

**Issue by jahin** [haifengl/smile#118]
Hi Smile Community,

It will be nice to have some more examples both in Scala and Java.

**Comment by haifengl** [comment]
So you figured out the issue of double[] y?

**Comment by jahin** [comment]
Yes figured that one. If you can provide some examples it will be really helpful to use such fast library.

**Comment by haifengl** [comment]
Cool. We have some examples in Scala because the Scala API is simple and easy to use. The Java API is more complete and complicated. We will continue improving the documents and examples. Thanks!
