### ISSUE TITLE
Scala 2.10

### ISSUE THREAD

**Issue by elbamos** [haifengl/smile#119]
Is is impossible to use smile in a scala 2.10 environment?  Many of us are on Spark 1.6/Scala 2.10 stacks, and it would be nice to be able to try smile in that environment.

**Comment by haifengl** [comment]
All core algorithms are in Java. So you should be fine to use them in Scala 2.10. 

The smile-scala is only a wrapper of Java algorithms into Scala functions. They are useful for training in the shell. However, it is not necessary to use trained models in spark.

**Comment by haifengl** [comment]
I am working on cross build for both 2.10 and 2.11.

**Comment by haifengl** [comment]
We support 2.10 now in master branch. Please pull the latest version and do

sbt ++2.10.6 scala/package

to build 2.10 version of scala api.

Thanks!

**Comment by elbamos** [comment]
Do you have an alpha/beta of the cross build?

**Comment by haifengl** [comment]
Please see my previous comment. Thanks!

**Comment by elbamos** [comment]
Thanks, @haifengl 
```
[info] Compiling 141 Java sources to /vhome/amos.elberg/smile/math/target/classes...
[error] javac: invalid source release: 1.8
[error] (math/compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 6 s, completed Oct 4, 2016 8:22:52 PM
```

Any suggestions?

**Comment by haifengl** [comment]
You need JDK8.

**Comment by elbamos** [comment]
I'm using Jdk 8.

**Comment by haifengl** [comment]
I am not sure what's wrong. I have no issues at all. Can you do 

sbt clean

first?

**Comment by elbamos** [comment]
That was the first thing I tried :(

**Comment by haifengl** [comment]
The error message says that javac doesn't recognize source level 1.8. Can you double check your javac version? Thanks!

**Comment by elbamos** [comment]
I did double check the javac version, and it was definitely 1.8. That said, I've subsequently gotten it to work on some systems, but not on others.  It seems to be sbt/scala weirdness, but weirdness that's beyond your control, so I'm closing this issue.  Thanks for your help, and I'm really enjoying the software!

**Comment by haifengl** [comment]
Maybe some machines have open jdk while others have oracle jdk? I strongly recommend oracle jdk.  Besides, smile could be slower on open jdk sometimes. Thanks!

**Comment by bruce-campbell-sensus** [comment]
I saw the same issue using Oracle.  I also wasn't sure what the problem was.  I got it building inside the IntelliJ IDE but not from the command line.  Same SDK and Scala version in and outside the IDE.

I too am enjoying the software!

**Comment by haifengl** [comment]
Thanks @elbamos and @bruce-campbell-sensus !! Really confused about this weirdness. Glad it doesn't block you moving forward.

**Comment by elbamos** [comment]
Haifeng it resolved when I added library dependencies for the scala library and scala compiler to the sbt file. I know that's not supposed to be necessary but that's what worked.

**Comment by haifengl** [comment]
Interesting. Thanks!
