### ISSUE TITLE
setResponseIndex in wiki

### ISSUE THREAD

**Issue by chriscamacho** [haifengl/smile#12]
Mentioned multiple times in "gentle" introduction (wiki) without any explanation...

**Comment by haifengl** [comment]
In supervised learning, we need a response variable for each sample to train the model. For classification, it is the class label. For regression, it is a real value. If a dataset contains such response variable, the method setResponseIndex is used to indicate which one (by column index, starting with 0).

I will update the tutorial. Thanks!
