### ISSUE TITLE
Implementing Pre-Image computation for K-PCA

### ISSUE THREAD

**Issue by vincenzodentamaro** [haifengl/smile#123]
Dear all, is it possible to implement inside K-PCA the pre-image reconstruction or point me in the right direction to implement it.

https://www.aaai.org/Papers/ICML/2003/ICML03-055.pdf

Thanks

**Comment by haifengl** [comment]
We don't support this algorithm directly. But we do have multiple MDS algorithms. You can calculate the distance matrix after KPCA and then feed it to one of our MDS algorithm.
