### ISSUE TITLE
Custom lancaster stemmer rules file

### ISSUE THREAD

**Issue by mjunsilo** [haifengl/smile#125]
I recently wrapped the SMILE lancaster stemmer in a DKPro UIMA wrapper for use in an Apache UIMA pipeline:

https://github.com/dkpro/dkpro-core/tree/master/dkpro-core-lancaster-asl

However, I would like the rules to be customisable as it often the case with a Paice-Husk stemmer implementation.

I imagine that the default rules remain but that a resource path to a custom rules file could be specified in the constructor.

**Comment by haifengl** [comment]
Thanks for the suggestion. I just added this feature and it is in master now. You can pass an InputStream of additional rules to constructors now.

**Comment by mjunsilo** [comment]
Thanks a lot. I'll integrate when its available from a new Maven Central distribution.

**Comment by haifengl** [comment]
v1.2.1 is just released to Maven Central with this update. Thanks!

**Comment by mjunsilo** [comment]
Finally I found time to integrate the new rules feature but I was surprised to find that I can only add rules, not replace the default rules entirely with new rules. I tried to overwrite the existing rules just by applying the existing rules again in the constructor, but I got an array index out of bounds exception in line 83 of the stemmer. This was just a simple dry shot to see if my integration worked as intended, but I was surprised about the implementation. I thought specifying some input stream would completely override the existing rules, but that is not the case. I can see the benefits of just overwriting, if that is the intention with the addition approach, but it brings with it some peculiarities in edge cases, e.g. removing some rules requires specifying no op rules to replace them.

Sorry for not coming back earlier with this, I should have inspected the code, when it was committed the first time in master, but I simply didn't find the time. Its also not easy for me to test it, unless I have access to public snapshot distributions, do you have this somewhere?

**Comment by haifengl** [comment]
Sorry, I misunderstood your request "the default rules remain". Let me change the behavior. You can git clone the repo and "sbt package" to build the jars.

**Comment by haifengl** [comment]
Please test the new fix. If everything is okay, I will push a new release soon. Thanks!

**Comment by mjunsilo** [comment]
The changes seem to work as expected. I have now included the new feature in the DKPro UIMA wrapper:

https://github.com/mjunsilo/dkpro-core/commit/d9f8cf875b45b1eb306e3d1fa1b22b99cd7c7f81

A DKPro issue has also been created for the change request:

https://github.com/dkpro/dkpro-core/issues/1001

I will make a pull request once you pushed the 1.2.2 release to Maven Central.

**Comment by mjunsilo** [comment]
BTW if you have some links to how the rule syntax works then I'll include it. I think its probably clear to someone who knows how the stemmer works, so I don't think its crucial if you don't have it.

**Comment by haifengl** [comment]
version 1.2.2 is released. It may take a couple of days to be available on maven central repo. Thanks!

**Comment by haifengl** [comment]
In old time, we can find the syntax info at http://www.comp.lancs.ac.uk/computing/research/stemming/Links/paice.htm

Unfortunately, this page is gone now. Sorry
