### ISSUE TITLE
About LDA classification 

### ISSUE THREAD

**Issue by caomiaoke** [haifengl/smile#129]
Hello 
I'm the Smiler and just reading your code; I have some confusion about LDA( smile/core/src/main/java/smile/classification/LDA.java) in line 339-369. Actually, I don't the last step of classification. Could you give me some tips or some Readings.

**Comment by haifengl** [comment]
Note that we distinguish LDA and Fisher's linear discriminant (FLD class in smile). When you google LDA, most pages actually talk about FLD, which doesn't require the normal distribution assumption. In our LDA implementation, we assume that each class follows a normal distribution (with same variance matrix) and use Bayes decision theory to learn the decision boundary. The predict method actually use this idea to calculate the posteriori probability (we don't calculate posteriori probability in FLD though).  Some old text book on Pattern Recognition describes this approach. I need to check my bookshelf to find the reference :) Thanks!

**Comment by haifengl** [comment]
Please check the book "Pattern Classification" by Duda, etc. Page 39 for details.

**Comment by caomiaoke** [comment]
Thanks for your warm explanation.
