### ISSUE TITLE
Demo / DataSets

### ISSUE THREAD

**Issue by sebastian-alfers** [haifengl/smile#13]
thanks for your work, looks interesting!

Could you publish your DataSets and publish the source code of the demo on github?

Greetings
Sebastian

**Comment by haifengl** [comment]
The datasets were collected from Internet. They are open dataset so that I can use them for testing the library. However, it is not okay for me to publish them in the project as they belong to others.

**Comment by sebastian-alfers** [comment]
or could you link them?

**Comment by haifengl** [comment]
There are a lot and collected from everywhere. But you can always go to UCI machine learning repository https://archive.ics.uci.edu/ml/datasets.html to find something interesting for testing.

**Comment by haifengl** [comment]
The demo source code (SmileDemo) is imported. Please have a look. Thanks!
