### ISSUE TITLE
GradientTreeBoost is not serializable

### ISSUE THREAD

**Issue by lanastazia** [haifengl/smile#130]
Hello,

 I've just noticed that it's impossible to serialize GradientTreeBoost, because some children objects like RegressionTree are not serializable. Is it intentional to keep the Regression Tree non serializable? 

If not, I could work on this topic

**Comment by haifengl** [comment]
Are you using 1.2.0 or 1.2.1? v1.2.1 was just released and should fixed this problem. Thanks!

**Comment by lanastazia** [comment]
the new version 1.2.1 fixed this issue, thank you!
