### ISSUE TITLE
about the implementation of naive bayes classifier

### ISSUE THREAD

**Issue by leo-xin** [haifengl/smile#132]
Hi,li. 
I have read your code of naive bayes, you have used a dense array to represent a text instance, i think that is a bit bad idea. Why not try a sparse method to code the  instances like sickit-learn does?

**Comment by haifengl** [comment]
Python is dynamic type while Java is static type. NaiveBayes class is of Classifier<double[]>, mostly to provide a compatible interface with other classifiers. It is easy to add additional learn and predict function that take a sparse format. Would you like to add them? Thanks!

**Comment by haifengl** [comment]
I add the support of sparse input in NaiveBayes now. The fix is pushed to master. Please clone the repo and do "sbt package" to build the libraries locally. See http://haifengl.github.io/smile/index.html#quickstart for details. If everything is okay, I will push a new release soon. Thanks!

**Comment by leo-xin** [comment]
oh,my God.Your productivity is amazing!
thank for the effort.

**Comment by haifengl** [comment]
Thank you! Please have a try the new methods and report any encountered issues. Thanks!

**Comment by haifengl** [comment]
version 1.2.2 is released. It may take a couple of days to be available on maven central repo. Thanks!
