### ISSUE TITLE
About NeuralNetwork classification

### ISSUE THREAD

**Issue by subways** [haifengl/smile#133]
Hello
I'm the Smiler and I have some confusion about (smile/core/src/main/java/smile/classification/NeuralNetwork.java) in line 713,when ErrorFunction is CROSS_ENTROPY and ActivationFunction is LOGISTIC_SIGMOID,we should return the last outputneuron's error?

**Comment by haifengl** [comment]
What's your exact confusion? Can you please elaborate? Thanks!

**Comment by haifengl** [comment]
I got your confusion. See line 447. For CROSS_ENTROPY and LOGISTIC_SIGMOID combination, the last layer should have only one output neuron.
