### ISSUE TITLE
Serialization of clustering algorithm

### ISSUE THREAD

**Issue by beckgael** [haifengl/smile#134]
First thank you for this amazing library with a great diversity of algorithm.

I would like to know why clustering algorithms aren't extend from Serializable, specificaly Hclust, proximity and partition from HierarchicalClustering class. It don't allow me to solve my problem in a concise and accurate way. Maybe i can serialize those in another way but i don't find enough hints to solve my problems.

For the moment i encapsulate those methods inside a Scala object extends serializable but i'm not sure it's the best way.

Thank you and continue :) with :)

**Comment by haifengl** [comment]
in shell or scala, use write.xstream to save any object/model. If you have to use Java serialization, we can add the support to clustering and other alorithms.

**Comment by haifengl** [comment]
I make all clustering algorithms serializable now. The fix is pushed to master. Please clone the repo and do "sbt package" to build the libraries locally. See http://haifengl.github.io/smile/index.html#quickstart for details. If everything is okay, I will push a new release soon. Thanks!

**Comment by beckgael** [comment]
It works like a charm for my needs, try to build new scala/spark algorithm on sparknotebook using your gorgeous building blocs, thank you for your reactivity.
I will inform you if i encounter any new issue with it.
Mery Christmas :)

**Comment by haifengl** [comment]
version 1.2.2 is released. It may take a couple of days to be available on maven central repo. Thanks!

Happy new year!!
