### ISSUE TITLE
Project website is broken?

### ISSUE THREAD

**Issue by asmaier** [haifengl/smile#136]
I have problems navigating the website https://haifengl.github.io/smile/ . All internal links (e.g. to the User Guide, Quickstart, Gallery, FAQ) seem to be broken. I tried this with Chrome Version 55 and Safari 10 . Is it just me or is there a problem with the page?

**Comment by haifengl** [comment]
I am using Chrome on windows and has no problems. Are you on mobile devices? Thanks!

**Comment by douglasArantes** [comment]
I had the same problem, but now it's back to normal.

**Comment by asmaier** [comment]
I still have the problem with Chrome on Mac OS X. But the webpage works now with Safari and on my iPhone 4S. It seems to me that Chrome thinks that there is "active mixed content" on the website.

**Comment by asmaier** [comment]
According to https://www.whynopadlock.com the problem is that jquery doesn't use an https link. Instead the webpage includes jquery via the unsafe link http://code.jquery.com/jquery.min.js .

**Comment by haifengl** [comment]
@asmaier I updated index.html as you suggested. We use https://code.jquery.com/jquery.min.js now. Hope it fixes the problem. Thanks!

**Comment by asmaier** [comment]
I can confirm that the problem is fixed.

**Comment by haifengl** [comment]
Thanks!
