### ISSUE TITLE
Publish to Maven repository

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#14]
I'd love it if you could make these libraries available via Maven. It would make it much easier to include them in my own application. It should be pretty easy to add them to the central Maven repo since you already have a Maven build file

**Comment by haifengl** [comment]
Good idea. Will figure out how to do it. Thanks!

**Comment by haifengl** [comment]
Refactored pom.xml in preparation of maven central repository.

**Comment by haifengl** [comment]
It is in the maven central repository now. Please try

<dependency>
  <groupId>com.github.haifengl</groupId>
  <artifactId>smile-core</artifactId>
  <version>1.0.0</version>
</dependency>

Thanks!

**Comment by benmccann** [comment]
Thank you!!

**Comment by experquisite** [comment]
Yes this is awesome, thanks!

**Comment by experquisite** [comment]
Is there a link to find it on maven.org ? I can't seem to see it.

**Comment by experquisite** [comment]
I found it at https://repo1.maven.org/maven2/com/github/haifengl/ , but it seems to be trying to pull in smile-all which doesn't exist?  (I'm doing this from within an sbt file for a scala project)

**Comment by haifengl** [comment]
Smile-all is the parent pom to build all these modules. It is not really needed. Maybe I didn't do it right to publish to central repository. Any ideas? Thanks!

**Comment by experquisite** [comment]
Regrettably I am not an expert.  In my build.sbt I have:
`
resolvers += Resolver.sonatypeRepo("releases")

libraryDependencies += "com.github.haifengl" % "smile-core" % "1.0.0"
`
Which, when I 'sbt compile', results in:
`
[info] Resolving com.github.haifengl#smile-all;1.0.0 ...
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/com/github/haifengl/smile-core/1.0.0/smile-core-1.0.0.pom: Impossible to load parent for file:/home/s.thornington/.ivy2/cache/com.github.haifengl/smile-core/ivy-1.0.0.xml.original. Parent=com.github.haifengl#smile-all;1.0.0
[info] Resolving com.github.haifengl#smile-all;1.0.0 ...
[warn] io problem while parsing ivy file: https://oss.sonatype.org/content/repositories/releases/com/github/haifengl/smile-core/1.0.0/smile-core-1.0.0.pom: Impossible to load parent for file:/home/s.thornington/.ivy2/cache/com.github.haifengl/smile-core/ivy-1.0.0.xml.original. Parent=com.github.haifengl#smile-all;1.0.0
[warn]  module not found: com.github.haifengl#smile-core;1.0.0
[warn] ==== local: tried
[warn]   /home/s.thornington/.ivy2/local/com.github.haifengl/smile-all/1.0.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/haifengl/smile-all/1.0.0/smile-all-1.0.0.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/github/haifengl/smile-all/1.0.0/smile-all-1.0.0.pom
`

**Comment by haifengl** [comment]
I will figure out how to fix it. In short term, maybe you can download the parent pom from github to your local ivy2 directory?

**Comment by haifengl** [comment]
Can you please try again with version 1.0.1? Thanks! If maven cannot find this version, please just wait a couple of hours.

**Comment by experquisite** [comment]
1.0.1 works perfectly, thanks!

**Comment by haifengl** [comment]
Great! Thanks for quick response!

**Comment by experquisite** [comment]
Sorry to follow up on a closed ticket, but I might be having some trouble with resources.  I am getting a crash when creating a plot:

java.lang.NullPointerException

from the ImageIcon constructor here in PlotCanvas:

    private class SaveAction extends AbstractAction {

        public SaveAction() {
            super("Save", new ImageIcon(PlotCanvas.class.getResource("images/save16.png")));
        }

I don't see that these images are in the maven jar file.  jar tf smile-plot-1.0.1.jar  didn't list them anyway.  Should they be?

**Comment by haifengl** [comment]
Can you please try version 1.0.2 now? Thanks!

**Comment by Xyclade** [comment]
I noticed the same issue as @experquisite, but it seems fixed now with 1.0.2 via maven for me :+1:

**Comment by haifengl** [comment]
Great. Thanks guys!
