### ISSUE TITLE
Multinormial distribution

### ISSUE THREAD

**Issue by leo-xin** [haifengl/smile#141]
Hi, Li,
I wonder if there is a multinormial distribution implemetation in smile.stat.distribution?
I can not find it in source, is there a plan to write one?

**Comment by haifengl** [comment]
multinomial or multi-variate normal/Gaussian distribution? We don't have multinomial but have MultiVariateGaussian. BTW, smile.classification.NaiveBayes supports multinomial model. Is it what you are looking for?

**Comment by leo-xin** [comment]
oh,sorry. I have a mis-spelling in the issue. I mean multinomial distribution, not multi Gaussian.
It is a generalization of binomial distribution. I want to simulate a series of random trial from that distributon.

**Comment by haifengl** [comment]
So what you care is the random number generation?

**Comment by haifengl** [comment]
If all you need is that multinomial random number generator, there is a function in smile.math.Math

public static int random(double[] prob)

Given a set of n probabilities, it will generate a random number in [0, n).

**Comment by leo-xin** [comment]
yes,  I have It according  to your instruction. That is just what I want, thank you so much.

**Comment by haifengl** [comment]
You are welcome!
