### ISSUE TITLE
KDTree difficult to use from Scala

### ISSUE THREAD

**Issue by the21st** [haifengl/smile#142]
Hi, first off, thanks for the work on this amazing library!

I wanted to use Smile's `KDTree` in a Scala project, but quickly ran into issues with primitive types (`AnyVal`). Self-contained example that won't compile because of type erasure issues:

```scala
import smile.neighbor.KDTree

val keys = Array(
	Array(5.0),
	Array(7.0)
)
val values = Array(0, 1)
val tree = new KDTree[Int](keys, values)
tree.nearest(Array(5.5))
```

Could this be made to work? I have been using [this KD tree](http://home.wlu.edu/~levys/software/kd/) in Scala without any issues, but it is a mutable interface. Obviously, an immutable one, like in Smile, would be preferred.

**Comment by haifengl** [comment]
KDTree is designed for multiple dimensional data. Your example is of only on dimension. If you have only dimension, I suggest that you sort and binary search your data. Much faster.

**Comment by the21st** [comment]
@haifengl thanks for your quick reply! My example was intended to be a minimal illustration of the problem.

My data are actually 3-dimensional, but I still need to store primitives as values, because they are indices of my data.

So this is a full example:

```scala
import smile.neighbor.KDTree

val keys = Array(
	Array(5.0, 6.0, 7.0),
	Array(9.0, 0.0, 9.5),
	Array(5.0, 5.0, 3.5)
)
val values = Array(0, 1, 2)
val tree = new KDTree[Int](keys, values)
val result = tree.nearest(Array(6.3, 2.7, 5.9))
```

**Comment by haifengl** [comment]
Your question is really about Scala/Java interoperation. Make sure your values are boxed integer (thus objects):

val values = Array(0, 1, 2).map(Int.box(_))

and your KDTree is of type Integer (not Int, which is int in Java)

val tree = new KDTree[Integer](keys, values)
