### ISSUE TITLE
Sparse Data Memory Consumption

### ISSUE THREAD

**Issue by hrzafer** [haifengl/smile#146]
Do I have to create a sparse matrix to train a classifier on Smile?
I am trying to train a logistic regression model with 300.000 examples and 40.000 features. This requires a `new double[300000][40000]` which consumes approximately 96 GB of memory. However, I am able to train a logistic regression model with StanfordNLP with the same data using dense Counter objects.

How can I train smile with dense vectors?

**Comment by haifengl** [comment]
Please use smile.classification.Maxent (maximum entropy) classifier, which is essentially a logistic regression. But it takes sparse input.

**Comment by hrzafer** [comment]
Thanks for the response. I've checked constructors for both. All I can see is they accept the data as a matrix. The only difference is the MaxEnt's data type being int[][] rather than double[][]. I want to be able to train the models with dense inputs pairs like {feature_index, feature_value}.

**Comment by haifengl** [comment]
Well, we assume double[][] be a dense matrix. In your case, it is 300000 x 40000. But for int[][], we assume it is a sparse binary matrix. The entry is the index of nonzero features.

**Comment by hrzafer** [comment]
From the JavaDoc `x - training samples. Each sample is represented by a set of sparse binary features. The features are stored in an integer array, of which are the indices of nonzero features.`

Now I got it. So the parameter `p` will be the actual number of features (size of feature space) and an element with n features will be represented with an array of n length.  Thanks.

**Comment by haifengl** [comment]
exactly. Let me know if you have any other questions.

**Comment by hrzafer** [comment]
Hi, I've one more related question. Do the indices of nonzero features have to be ordered in the array?

**Comment by haifengl** [comment]
Yes

**Comment by hrzafer** [comment]
Does the index start with 0 or 1? For example {0, 3, 11} vs {1, 4, 12} ?

**Comment by haifengl** [comment]
0

**Comment by hrzafer** [comment]
Thanks a lot.

**Comment by haifengl** [comment]
How's it work? How's the speed and accuracy compared to StandfordNLP? Thanks!

**Comment by hrzafer** [comment]
Hi,

I was going to open another issue regarding the accuracy and the following exception which I encounter occasionally. I can continue on this thread if you want.

`java.lang.IllegalArgumentException: Line Search: the search direction is not a descent direction, which may be caused by roundoff problem.`

**Comment by haifengl** [comment]
Do you have full stack trace? Very likely, the optimization process is not stable on this data. Thanks!

**Comment by hrzafer** [comment]
I'll send the stack trace shortly. But before that, I want to make sure that the problem is not arising from my code. There is a parameter `int p` for the `MaxEnt.Trainer` constructor. It supposed to be equal to the number of features right?. When I try numOfFeats-1 or any value greater than numOfFeats, I get no error.

**Comment by haifengl** [comment]
Yes, p should be the number of features. In this case, p should be 40000. In the input x, the value should be in [0, 40000). It is interesting that the error is raised here. Thanks!

**Comment by haifengl** [comment]
How many classes do you have?

**Comment by hrzafer** [comment]
I have just 2 classes

**Comment by hrzafer** [comment]
I've prepared a small test set to see what is going on. My test set has 5 instances and 6 binary features as following:

```
{1,1,1,1,1,0}
{1,1,1,1,1,0}
{1,0,0,0,0,1}
{0,0,1,0,0,1}
{0,0,0,0,1,1}
```

The first two instances belong to class-1 and the rest belong to class-2. The corresponding sparse int matrix for this dataset is this:

```
{0,1,2,3,4}
{0,1,2,3,4}
{0,5}
{2,5}
{4,5}
```
MaxEnt successfully converges and the following tests pass. (I've wrapped the MaxEnt class)
```
assertEquals(d1.label(), classifier.classOf(d1));
assertEquals(d2.label(), classifier.classOf(d2));
assertEquals(d3.label(), classifier.classOf(d3));
assertEquals(d4.label(), classifier.classOf(d4));
assertEquals(d5.label(), classifier.classOf(d5));
```

When I apply a feature occurrence threshold and eliminate features occurring in less than 3 instances, the data set becomes like this. 2nd, and 4th features of the initial data set is eliminated. 

```
{0,1,1,1}
{0,1,1,1}
{1,1,0,0}
{1,0,1,0}
{1,0,0,1}
```
And the corresponding sparse int matrix is:

```
{1,2,3}
{1,2,3}
{0,1}
{0,2}
{0,3}
```
Here the 6th feature of the initial set becomes the first feature. This is because I'm using a hashmap internally which does not preserve order. However, theoretically, this should not be a problem. But MaxEnt fails to optimize tests fail.

If I preserve the order of features when applying the feature threshold, the dense and sparse matrices become like this and tests pass.

```
{1,1,1,0}
{1,1,1,0}
{1,0,0,1}
{0,1,0,1}
{0,0,1,1}
```
```
{0, 1, 2},
{0, 1, 2},
{0, 3},
{1, 3},
{2, 3}}
```

The order of features, in other words changing the order of columns in a dataset should not be a problem I suppose? I'll send more feedback shortly.

**Comment by haifengl** [comment]
The order should not be an issue mathematically. But it may become a problem if underflow happens. It is tricky and also depends on the order of samples. Your y takes values of 0 and 1, right?

**Comment by hrzafer** [comment]
Yes the vector is {1,1,0,0,0}.

**Comment by hrzafer** [comment]
He is the all necessary data to reproduce the following exception.

dataset as binary sparse matrix and y :  [smile-test.txt](https://www.dropbox.com/s/zko1e4o602xqq64/smile-test.txt?dl=1)

```
[main] INFO smile.math.Math - L-BFGS: initial function value: 16473
[main] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 746.75
[main] INFO smile.math.Math - L-BFGS: the function value after  20 iterations: 156.15
[main] INFO smile.math.Math - L-BFGS: the function value after  30 iterations: 27.074
[main] INFO smile.math.Math - L-BFGS: the function value after  40 iterations: 3.2807
[main] INFO smile.math.Math - L-BFGS: the function value after  50 iterations: 2.2741
[main] INFO smile.math.Math - L-BFGS: the function value after  60 iterations: 1.6914
[main] INFO smile.math.Math - L-BFGS: the function value after  70 iterations: 1.5584
[main] INFO smile.math.Math - L-BFGS: the function value after  80 iterations: 1.5533
[main] INFO smile.math.Math - L-BFGS: the function value after  90 iterations: 1.5434
[main] ERROR smile.classification.Maxent - Failed to minimize binary objective function of Maximum Entropy Classifier
java.lang.IllegalArgumentException: Line Search: the search direction is not a descent direction, which may be caused by roundoff problem.
	at smile.math.Math.linesearch(Math.java:5011)
	at smile.math.Math.min(Math.java:5197)
	at smile.classification.Maxent.<init>(Maxent.java:246)
	at smile.classification.Maxent$Trainer.train(Maxent.java:153)
	at com.diligen.ai.classification.smile.SmileMaxentFactory.train(SmileMaxentFactory.java:47)
	at com.diligen.parafix.Benchmark.test(Benchmark.java:101)
	at com.diligen.parafix.Benchmark.main(Benchmark.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by hrzafer** [comment]
Can I train the SVM  implementation in Smile with a binary sparse matrix (int[][]) ?

**Comment by haifengl** [comment]
Yes, we have several kernels for binary sparse data. Check out smile.math.kernel package.

**Comment by haifengl** [comment]
When you train maxent, can you call trainer.setTolerance(0.01)? This will terminate the optimization early and should still give good accuracy.

**Comment by hrzafer** [comment]
Hi,

Setting tolerance worked with this small data set. However, it didn't work for the larger one with more than 300.000 examples. When the data set grows, the feature space also grows. This is the output for 382876 examples with 39056 features. 

```[main] INFO smile.math.Math - L-BFGS: initial function value: 2.6539e+05
Classifier is trained in 138
[main] INFO smile.math.Math - L-BFGS: the function value after   1 iterations: 2.6539e+05
```

I apply k=5 threshold for features. If I don't apply this threshold, the feature space becomes 188433 but I don't get any error with smile. Also I don't get any error for both with StanfordNLP LogReg.

The accuracy is usually %1-%3 better with StanfordNLP with different dataset sizes and feature space.

**Comment by hrzafer** [comment]
For the following code,

```
        SVM<int[]> svm = new SVM<int[]>(new BinarySparseLinearKernel(), 0);
        svm.learn(matrix, vector);// matrix is binary sparse
        svm.finish();
```

I got this error:

```
java.lang.NullPointerException
	at smile.classification.SVM$LASVM.smo(SVM.java:588)
	at smile.classification.SVM$LASVM.reprocess(SVM.java:846)
	at smile.classification.SVM$LASVM.learn(SVM.java:506)
	at smile.classification.SVM$LASVM.learn(SVM.java:438)
	at smile.classification.SVM.learn(SVM.java:1191)
	at smile.classification.SVM.learn(SVM.java:1145)
```

Since this SVM is an online classifier, I can also use it with dense vectors without having any memory issue. However, I couldn't find a code example for this.

**Comment by haifengl** [comment]
Why do you want to set C = 0 here? Can you try C = 1 or 10? These numbers are not optimal but want to check if C = 0 causes this problem. Thanks!

**Comment by haifengl** [comment]
I am confusing why the feature filtering causes the problem. Trying to find out any possible bug. For accuracy, you test it on the training data or separate test data?

**Comment by hrzafer** [comment]
I test it on a separate test set with 200.000 examples. I have written several unit-tests to find possible bugs but everything seems work fine. Besides I've converted the feature filtered data set to ARFF sparse format and tested with WEKA without any problems. 

For the C, actually I don't know what it is, I just tried 0 :)

**Comment by hrzafer** [comment]
Thanks for all the quick responses. As a conclusion, I think changing the order of a feature in the dataset should not affect the accuracy in any way.  This is the case I've seen with other libraries such as StanfordNLP and WEKA. I think the very small dataset I've provided above with 5 examples and 6 features is a good point to start to find out a possible bug.

**Comment by haifengl** [comment]
I tried the small test dataset in smile shell without any problem

```
smile> val x = Array(Array(1,2,3),
     | Array(1,2,3),
     | Array(0,1),
     | Array(0,2),
     | Array(0,3)
     | )
x: Array[Array[Int]] = Array(Array(1, 2, 3), Array(1, 2, 3), Array(0, 1), Array(0, 2), Array(0, 3))
smile> 
smile> val y = Array(1,1,0,0,0)
y: Array[Int] = Array(1, 1, 0, 0, 0)
smile> maxent(x,y,4)
[main] INFO smile.math.Math - L-BFGS: initial function value: 3.4657
[main] INFO smile.math.Math - L-BFGS: the function value after   5 iterations: 1.8836
[main] INFO smile.util.package$ - runtime: 17.362722 ms
res0: smile.classification.Maxent = smile.classification.Maxent@44a6a68e
```

Are you using OpenJDK? It is better to use Oracle JDK. People met weird numeric problems with other smile algorithms on OpenJDK before.

**Comment by hrzafer** [comment]
Nop, I am using Oracle JDK on Windows 10.  

Right now I am testing the SVM. It gives better accuracy but slower than MaxEnt. Do you think using any kernel other than BinarySparseLinearKernel or using dense double[] vectors gets it faster?

**Comment by hrzafer** [comment]
I've just try the following:

```
  int[][] x = new int[][]{
                {1, 2, 3},
                {1, 2, 3},
                {0, 1},
                {0, 2},
                {0, 3}};

        int[] y = new int[]{1, 1, 0, 0, 0};

        Maxent maxent = new Maxent.Trainer(4).train(x, y);
```
and  get this:

```
[main] INFO smile.math.Math - L-BFGS: initial function value: 3.4657
[main] ERROR smile.classification.Maxent - Failed to minimize binary objective function of Maximum Entropy Classifier
java.lang.IllegalArgumentException: Line Search: the search direction is not a descent direction, which may be caused by roundoff problem.
	at smile.math.Math.linesearch(Math.java:5011)
	at smile.math.Math.min(Math.java:5197)
	at smile.classification.Maxent.<init>(Maxent.java:246)
	at smile.classification.Maxent$Trainer.train(Maxent.java:153)
	at com.diligen.ai.TestMain.main(TestMain.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

My JDK:
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
````

And I'm using smile-core 1.2.2.

**Comment by haifengl** [comment]
We are using the same data and setting, but I don't have issues. I am using mac. I guess that there is something wrong with environment. Will try on a windows box.

**Comment by haifengl** [comment]
Try the binary sparse Gaussian kernel. If you choose the right kernel parameter, it should have better accuracy.

**Comment by haifengl** [comment]
I tried the small test data on Windows 10 without problems:

```
smile> smile.classification.maxent(x,y,4)
[main] INFO smile.math.Math - L-BFGS: initial function value: 3.4657
[main] INFO smile.math.Math - L-BFGS: the function value after   5 iterations: 1.8836
[main] INFO smile.util.package$ - runtime: 33.689975 ms
res1: smile.classification.Maxent = smile.classification.Maxent@2c768ada
smile>
```

My java version is

```
D:\github\smile>java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

It is essentially same as yours. I don't know what other environment things could cause the failure on your machine.

**Comment by hrzafer** [comment]
I've created an empty maven project just added the smile dependency and tested it on both windows and ubuntu (Oracle JDK 1.8.1_121).  I did not see any error. However when I enabled the logging, I have seen the same error on both linux and windows. To enable logging I've added the following dependency. Please download the project from [here](https://www.dropbox.com/s/c59kyc9fcevcfb5/smiletest.zip?dl=1) and run on your environment. 

```
        <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-jdk14</artifactId>
        <version>1.7.22</version>
        </dependency>
```

**Comment by haifengl** [comment]
I use smile shell, which has dependency to logger too. I guess that it is not the root cause. But it does reminder that this may be caused by some race condition in multithreading. Can you please pass

-Dsmile.threads=1

to JVM. I hope that this will solve the problem. The training will be slower though. Thanks!

**Comment by hrzafer** [comment]
I've just tried that option. It is still the same. Also, I get the following error when I try to use the shell on Windows. 

```
C:\Users\harun\Desktop\smile-1.2.1\bin>smile
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.NoClassDefFoundError: Could not initialize class scala.tools.fusesource_embedded.jansi.internal.Kernel32
        at scala.tools.fusesource_embedded.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
        at scala.tools.jline_embedded.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
        at scala.tools.jline_embedded.WindowsTerminal.init(WindowsTerminal.java:82)
        at scala.tools.jline_embedded.TerminalFactory.create(TerminalFactory.java:101)
        at scala.tools.jline_embedded.TerminalFactory.get(TerminalFactory.java:158)
        at scala.tools.jline_embedded.console.ConsoleReader.<init>(ConsoleReader.java:229)
        at scala.tools.jline_embedded.console.ConsoleReader.<init>(ConsoleReader.java:221)
        at scala.tools.jline_embedded.console.ConsoleReader.<init>(ConsoleReader.java:209)
        at scala.tools.nsc.interpreter.jline_embedded.JLineConsoleReader.<init>(JLineReader.scala:62)
        at scala.tools.nsc.interpreter.jline_embedded.InteractiveReader.<init>(JLineReader.scala:34)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$scala$tools$nsc$interpreter$ILoop$$instantiater$1$1.apply(ILoop.scala:858)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$scala$tools$nsc$interpreter$ILoop$$instantiater$1$1.apply(ILoop.scala:855)
        at scala.tools.nsc.interpreter.ILoop.scala$tools$nsc$interpreter$ILoop$$mkReader$1(ILoop.scala:862)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$21$$anonfun$apply$9.apply(ILoop.scala:873)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$21$$anonfun$apply$9.apply(ILoop.scala:873)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$21.apply(ILoop.scala:873)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$21.apply(ILoop.scala:873)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
        at scala.collection.immutable.Stream.collect(Stream.scala:435)
        at scala.tools.nsc.interpreter.ILoop.chooseReader(ILoop.scala:875)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$apply$mcZ$sp$2.apply(ILoop.scala:914)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:914)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
        at smile.shell.Main$.runTarget$1(Main.scala:70)
        at smile.shell.Main$.run$1(Main.scala:83)
        at smile.shell.Main$.process(Main.scala:94)
        at smile.shell.Main$.delayedEndpoint$smile$shell$Main$1(Main.scala:29)
        at smile.shell.Main$delayedInit$body.apply(Main.scala:26)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at smile.shell.Main$.main(Main.scala:26)
        at smile.shell.Main.main(Main.scala)


                                                       ..::''''::..
                                                     .;''        ``;.
     ....                                           ::    ::  ::    ::
   ,;' .;:                ()  ..:                  ::     ::  ::     ::
   ::.      ..:,:;.,:;.    .   ::   .::::.         :: .:' ::  :: `:. ::
    '''::,   ::  ::  ::  `::   ::  ;:   .::        ::  :          :  ::
  ,:';  ::;  ::  ::  ::   ::   ::  ::,::''.         :: `:.      .:' ::
  `:,,,,;;' ,;; ,;;, ;;, ,;;, ,;;, `:,,,,:'          `;..``::::''..;'
                                                       ``::,,,,::''

  Welcome to Smile Shell; enter 'help<RETURN>' for the list of commands.
  Type ":quit<RETURN>" to leave the Smile Shell
  Version 1.2.1, Scala 2.11.8, SBT 0.13.11, Built at 2016-12-02 20:49:58.541
===============================================================================

smile>
```

**Comment by haifengl** [comment]
It is a known issue on Windows (because of SBT or Scala). You can use the shell as usual. You just have to import smile libraries by yourself.

**Comment by haifengl** [comment]
So far, I cannot repeat the training problem on my machines (including Windows, Mac, and Linux). No clues right now why this error happens to you. Will keep working on this. Thanks!

**Comment by hrzafer** [comment]
I've tried the shell on Linux.  Here is the output:

```
smile> val me = maxent(x,y,4)
[main] INFO smile.math.Math - L-BFGS: initial function value: 3.4657
[main] INFO smile.math.Math - L-BFGS: the function value after   5 iterations: 1.8836
[main] INFO smile.util.package$ - runtime: 7.839131 ms
me: smile.classification.Maxent = smile.classification.Maxent@110e9982
smile> me.predict(Array(1,2,3))
res5: Int = 0
smile> 
```

As you may notice, the prediction is not correct. The model tends to predict everything as 0.

**Comment by hrzafer** [comment]
By the way if you could try to run the actual Java code, you may get the same result.

**Comment by haifengl** [comment]
Yes, I noticed that yesterday. Training finishes without problems but predictions are not okay. The possible reason is that we have only 5 samples here (and the model has 5 parameters) here. The model is not correctly trained.

**Comment by haifengl** [comment]
Scala api is only a thin wrap of Java API (which provides the real algorithms). We should get the same result.

**Comment by hrzafer** [comment]
`Scala api is only a thin wrap of Java API (which provides the real algorithms). We should get the same result.` I know. But still...  :)

**Comment by haifengl** [comment]
Can you train the large data set on Linux?

**Comment by hrzafer** [comment]
Hi,

I've changed something on feature filtering code and I don't have the issue anymore. But I couldn't diagnose the problem. So I am still not sure. I'll take a deeper look tomorrow. My brain is exhausted for Today. Thanks for all your support.

On the other hand, I've tried the SVM with Linear and Gaussian kernels. The Gaussian kernel is terribly slow. I've given 1 for sigma. The Linear kernel is faster but again 4-5 times slower than MaxEnt. 

I'll keep giving feedback and creating new issues :) Thanks.

**Comment by haifengl** [comment]
With Gaussian, you are training a non linear SVM, which is slower. But the main problem here is sigma. Your choice of sigma = 1 is way from optimal given your data. In general, your kernel value is close to zero with this setting. A good sigma should be close to typical distance between samples. I suggest that you calculate the distance of samples and plot the histogram. Then choose sigma close to the peak or median. Then fine tune it. Given your data (so many features), I guess that is value should be pretty big.

Thank you very much for all the feedbacks and issues! I look forward to more!!

**Comment by haifengl** [comment]
Notice you use 1.2.1. Can you upgrade to latest version 1.2.2. Or even better clone the repo and build the latest version. Thanks!
