### ISSUE TITLE
unable to parse following file with DelimiterParser

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#148]
Hi hai,
I am using DelimiterParser to parse this file and i am using the default delimiter but it fails on this record
7000 	0.0 	RTC 	"CREDIT UNP" 	3543    
as it thinks CREDIT UNP are two different column values. Is there a work around for this or do u suggest any other of ur parser.
AmountBase	Flg	        ChannelCode	 TypeCode	Beneficiary	
5000 	0.0 	                RTCRT 	Payment 	3035	   
6000 	1.0 	                GFEFT 	CONSOWERLIDAT 	343      
7000 	0.0 	                BFBRTC 	"CREDIT UNPREWR" 	3543    
8000 	0.0 	                GFEFT 	"CREDITWE TRA" 	333535 

Thanks,

**Comment by haifengl** [comment]
Sorry for inconvenience. We currently don't support space in quotes. A quick work around is to use different separator such as csv or tab. Or you can replace space with underscores in the quoted fields. Thanks!

**Comment by aminaaslam** [comment]
Thanks
