### ISSUE TITLE
SimpleTokenizer Table of Contents Line

### ISSUE THREAD

**Issue by hrzafer** [haifengl/smile#153]
This is a line extracted from the table of contents part of a document:

`1.2 Interpretation.....................................................................................................................3`

The SimpleTokenizer splits this line into two tokens as follows:
`[1.2, Interpretation.....................................................................................................................3]`

I think the output should be 4 tokens like below:

`[1.2, Interpretation, ....................................................................................................................., 3]`

**Comment by haifengl** [comment]
SimpleTokenizer is designed for natural language. I am not sure your example is what we target. Besides, if we changed the rules for your case, it won't work well for things like U.S.

**Comment by hrzafer** [comment]
I think MS Word and PDF documents are considered as natural language. And ToC is not unusual in those documents.  Besides using `......` is quite common in forms to indicate blank fields. Actually, I already have a workaround for this. But for a wider range of use cases, this change could be nice.

I don't think the rules for this case and the `U.S.` case have to conflict.

**Comment by haifengl** [comment]
Now we are clear your use case. I add a new rule to handle this case. It is in master branch now. Thanks!

**Comment by hrzafer** [comment]
Thanks a lot. Not related but what is a typical good choice of parameters for the NeuralNetwork class. I've a big binary dataset and with two classes and I get around 94% accuracy with MaxEnt. Since a linear model is doing okay with this data. I keep hidden layers small (dimensionx3x2).  Also what would you advise for the error and activation function?

**Comment by haifengl** [comment]
For your case, cross entropy cost function and logistic activation function should be fine.

**Comment by hrzafer** [comment]
Thanks. I don't see the verison 1.2.2 neither on github releases page nor on the home page. I guess it is only on maven. I'll update the pom. Thanks again.
