### ISSUE TITLE
Allow to see the structure of (or export) the induced Decision Tree

### ISSUE THREAD

**Issue by jeffman-co** [haifengl/smile#154]
Could the DecisionTree object provide a means to see the structure of the tree and possibly export?

One of the advantages of DecisionTree learning is that they are simple to understand and interpret. without this internal structure of the Tree, we can only just use the Tree for prediction without knowing the decisions made for each variable at each node.

**Comment by haifengl** [comment]
Thanks!  A community member is working on exporting decision tree to PMML.

**Comment by myui** [comment]
Please feel free to porting [Graphviz export](https://github.com/apache/incubator-hivemall/blob/master/core/src/main/java/hivemall/smile/classification/DecisionTree.java#L367) to Smile.

It can visualize a DecisionTree seen in [this link](https://gist.github.com/myui/a83ba3795bad9b278cf8bcc59f946e2c).

**Comment by haifengl** [comment]
@myui Thanks! We implement a dot() function to export the tree to graphviz. The algorithm is different from yours though.
