### ISSUE TITLE
Random Split of training data

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#155]
Hi Hai,
I want to try validation on my training data.
e.g. i want to use 60% of my data for training the model and 40% for validating. 
Is this functionality available in Smile. If yes please guide what class to look at.

Thanks,

**Comment by haifengl** [comment]
smile.validation.CrossValidation

**Comment by aminaaslam** [comment]
hi hai,
This is how i am trying to use Cross Validation for Split Validation 

splitPct =0.6
`int trainSize = (int) (data.size()*(this.splitPct));
	     int valSize = (int) (data.size()*(1-this.splitPct)); 
	     double[][] x = data.toArray(new double[data.size()][]);
		 CrossValidation cv = new CrossValidation(trainSize, 2); 
		 int error = 0;
	     int[] y = data.toArray(new int[data.size()]);
	     
	     double[][] trainx = Math.slice(x, cv.train[0]);
	     int[] trainy = Math.slice(y, cv.train[0]);
		
	      model = new DecisionTree( data.attributes(),trainx, trainy, this.maxNodes, this.rule);
	      cv = new CrossValidation(valSize, 1); 
	      double[][] testx = Math.slice(x, cv.test[0]);
          int[] testy =   Math.slice(y,  cv.test[0]);
          //model = new DecisionTree( data.attributes(),testx, testy, this.maxNodes, this.rule);
          prediction = new int[testx.length];
          for (int j = 0; j < testx.length; j++) {
            	prediction[j] = model.predict(testx[j]);
                if (testy[j] != prediction[j]){
	                error++;
	            }
	        }`

But when i try to use  1 in the number of folds it doesnot give me anything in train array of CV. CrossValidation cv = new CrossValidation(trainSize, 2); 
so i am not able to train my model on the entire training data. Can you please guide me by looking at my code.

**Comment by haifengl** [comment]
CrossValidation is not designed for split test. In fact, cross validation is better than split test and it is why I suggest it. If you have to do split test, do a smile.math.Math.permutate(n), where n is your sample size. Then use the returned index to split your data.

**Comment by aminaaslam** [comment]
thanks hai.
