### ISSUE TITLE
ArrayIndexOutOfBounds Exception while doing Cross Validation in NeuralNetwork

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#156]
Hi hai, 
learn method of NeuralNetwork throws this exception when i am trying to make it learn training instances. Can you please help me with it.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at smile.classification.NeuralNetwork.learn(NeuralNetwork.java:908)
	at smile.classification.NeuralNetwork.learn(NeuralNetwork.java:858)
	at smile.classification.NeuralNetwork.learn(NeuralNetwork.java:925)

`double[][] x = data.toArray(new double[data.size()][]);
		 CrossValidation cv = new CrossValidation(data.size(), this.numFolds); 
		 int error = 0;
	     int[] y = data.toArray(new int[data.size()]);
	     for (int i = 0; i < this.numFolds; i++) {
	    	double[][] trainx = Math.slice(x, cv.train[i]);
		    int[] trainy = Math.slice(y, cv.train[i]);
		    double[][] testx = Math.slice(x, cv.test[i]);
	        int[] testy =   Math.slice(y,  cv.test[i]);
            model = new NeuralNetwork(this.errorFunction, this.activationFunction, x[0].length, this.units_layer_1,this.units_layer_2, 1);
            //for (int j = 0; j < 30; j++) {
              model.learn(trainx, trainy);
           // }*/
            
            //NeuralNetwork.Trainer.this.train(trainx, trainy);
            this.prediction = new int[testx.length];
            for (int j = 0; j < testx.length; j++) {
            	prediction[j] = model.predict(testx[j]);
                if (testy[j] != prediction[j]){
	                error++;
	            }
	        }`

**Comment by aminaaslam** [comment]
Please dont worry about it. I was able to resolve it.

**Comment by aminaaslam** [comment]
hi hai,
I keep encountering this issue off and on. I am not sure whats going on? Can you please look into it and guide me. Here is my code.

` double[][] x = data.toArray(new double[data.size()][]);
		 CrossValidation cv = new CrossValidation(data.size(), this.numFolds); 
		 int error = 0;
	     int[] y = data.toArray(new int[data.size()]);
	     NeuralNetwork.Trainer trainer = new NeuralNetwork.Trainer(this.errorFunction, this.activationFunction, x[0].length, this.units_layer_1,this.units_layer_2, 1);
           for (int i = 0; i < this.numFolds; i++) {
	    	double[][] trainx = Math.slice(x, cv.train[i]);
		    int[] trainy = Math.slice(y, cv.train[i]);
		    double[][] testx = Math.slice(x, cv.test[i]);
	        int[] testy =   Math.slice(y,  cv.test[i]);
            model = trainer.train(trainx, trainy);
            this.prediction = new int[testx.length];
            this.confidence = new double[testx.length];
            for (int j = 0; j < testx.length; j++) {
            	double[] probability = new double[1];
	            prediction[j] = model.predict(testx[j],probability);
	        	this.confidence[j] = probability[0];
	            if ( prediction[j]!= testy[j]) {
	                error++;
	            }
	        }`

This is the exception that i keep getting.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at smile.classification.NeuralNetwork.learn(NeuralNetwork.java:908)
	at smile.classification.NeuralNetwork.learn(NeuralNetwork.java:858)
	at smile.classification.NeuralNetwork.learn(NeuralNetwork.java:925)
	at smile.classification.NeuralNetwork$Trainer.train(NeuralNetwork.java:374)

**Comment by haifengl** [comment]
You have two classes, right? And I guess that you are NOT using cross entropy as the error function, right? If so, your last layer should have two neurons. You have only one here. Thanks!

**Comment by aminaaslam** [comment]
Hi Hai,
Thanks for your help. Yes i have two classes and i get this problem when i use least.mean.square as error function. It means with least.mean.square output neurons =2 and if i am using cross.entropy then output neurons = 1
**error function = least.mean.square**
NeuralNetwork.Trainer trainer = new NeuralNetwork.Trainer(this.errorFunction, this.activationFunction, x[0].length, this.units_layer_1,this.units_layer_2, 2);
model = trainer.train(trainx, trainy);

**error function = cross.entropy**

NeuralNetwork.Trainer trainer = new NeuralNetwork.Trainer(this.errorFunction, this.activationFunction, x[0].length, this.units_layer_1,this.units_layer_2, 1);
model = trainer.train(trainx, trainy);

**Comment by haifengl** [comment]
Correct.

**Comment by aminaaslam** [comment]
Thanks Sir!!!!!
