### ISSUE TITLE
AUC calculation issue

### ISSUE THREAD

**Issue by DataOmbudsman** [haifengl/smile#157]
As I was evaluating the predictions of algorithms in Smile, it occurred to me that the calculated AUC is not always bounded between 0 and 1.

Here's a snippet of Scala that reproduces the issue:
```
val n = 100000
val trueLabels = Seq.fill(n)(Random.nextInt(2)).toArray
val probabilities = Seq.fill(n)(Random.nextDouble).toArray

println(AUC.measure(trueLabels, probabilities)) // -1.89...
```

I observed it using only longer arrays. So my guess is that it is an integer overflow problem, probably in this line of AUC.scala:

`auc = (auc - (pos * (pos+1) / 2.0)) / (pos * neg);`

**Comment by haifengl** [comment]
I cannot run your code in smile shell. Which "Random" object do you refer? BTW, the double value 2.0 is used in the line you talked about. All calculation will be lifted to double. So there is no integer overflow. Thanks!

**Comment by DataOmbudsman** [comment]
I used scala.util.Random. Here is the complete code with imports:

```
object AUCIssue extends App {
  import scala.util.Random
  import smile.validation.AUC

  val n = 100000
  val trueLabels = Seq.fill(n)(Random.nextInt(2)).toArray
  val probabilities = Seq.fill(n)(Random.nextDouble).toArray

  println(AUC.measure(trueLabels, probabilities)) // -1.89...
}
```

Maybe `(pos * neg)` is lifted to double after the overflow?

**Comment by haifengl** [comment]
Thanks! I change pos and neg to double. It reports 0.50 now.
