### ISSUE TITLE
My project use Java 1.7 version, how could I use smile?

### ISSUE THREAD

**Issue by xuejianbest** [haifengl/smile#158]
When I compile the program I got the error like this:
Exception in thread "main" java.lang.UnsupportedClassVersionError: smile/clustering/KMeans : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)

**Comment by haifengl** [comment]
You are using JDK 7. Please use JDK8.

**Comment by haifengl** [comment]
Just notice your issue title. We don't support JDK7 anymore as Oracle doesn't support it.

**Comment by xuejianbest** [comment]
Thinks, I have solved it by using Java1.7 to recompile it.

**Comment by medke** [comment]
@xuejianbest Can you please tell me how you did it? or maybe send me the recompiled jar files ?

**Comment by takun2s** [comment]
https://github.com/takun2s/smile_1.5.0_java7
Maybe this can help you , i modified the code for java7/jdk1.7

**Comment by medke** [comment]
Thanks.
