### ISSUE TITLE
RandomForest constructor

### ISSUE THREAD

**Issue by CreateRandom** [haifengl/smile#159]
Hi there,

The constructor `RandomForest(Attribute[] attributes, double[][] x, int[] y, int ntrees, int maxNodes, int nodeSize, int mtry, double subsample)` allows the user to specify `maxNodes` and `nodeSize`, but then goes on to make a chained call with maxNodes = 100 and nodeSize = 5. I wondered whether that was intentional because it seems to be somewhat misleading.

**Comment by haifengl** [comment]
Thanks! I fixed it.
