### ISSUE TITLE
PMML  support for Neural Network

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#160]
Hi Hai,
I am working on generating PMML from Neural Network model of smile. I have a question regarding handling of categorical attributes and the weights assigned to each category of a categorical feature.

e.g. This is my PMML file 
It has 5 features and 3 of them are categorical. If you look at the NeuralInputs tag, each category of a feature is treated as a separate input to the neuron of the next layer. My question is in your implementation of Neural Network how are you assigning weights to a category of a feature which is then propogated to the next layer? In otherwords how are you calculating the weights that are propogated from the input layer to the first hidden layer.

<?xml version="1.0" ?>
  <PMML version="4.0" xmlns="http://www.dmg.org/PMML-4_0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Header copyright="DMG.org"/>
    <DataDictionary numberOfFields="5">
      <DataField name="gender" optype="categorical" dataType="string">
        <Value value="  female"/>
        <Value value="    male"/>
      </DataField>
      <DataField name="no of claims" optype="categorical" dataType="string">
        <Value value="       0"/>
        <Value value="       1"/>
        <Value value="       3"/>
        <Value value="     &gt; 3"/>
        <Value value="       2"/>
      </DataField>
      <DataField name="domicile" optype="categorical" dataType="string">
        <Value value="suburban"/>
        <Value value="   urban"/>
        <Value value="   rural"/>
      </DataField>
      <DataField name="age of car" optype="continuous" dataType="double"/>
      <DataField name="amount of claims" optype="continuous" dataType="integer"/>
    </DataDictionary>
    <NeuralNetwork modelName="Neural Insurance"
               functionName="regression"
               activationFunction="logistic"
               numberOfLayers="2">
    <MiningSchema>
      <MiningField name="gender"/>
      <MiningField name="no of claims"/>
      <MiningField name="domicile"/>
      <MiningField name="age of car"/>
      <MiningField name="amount of claims" usageType="predicted"/>
    </MiningSchema>
    <NeuralInputs numberOfInputs="10">
      <NeuralInput id="0">
        <DerivedField optype="continuous" dataType="double">
          <NormContinuous field="age of car">
            <LinearNorm orig="0.01" norm="0"/>
            <LinearNorm orig="3.07897" norm="0.5"/>
            <LinearNorm orig="11.44" norm="1"/>
          </NormContinuous>
        </DerivedField>
      </NeuralInput>
      <NeuralInput id="1">
        <DerivedField optype="continuous" dataType="double">
          <NormDiscrete field="gender" value="    male"/>
        </DerivedField>
        </NeuralInput>
        <NeuralInput id="2">
          <DerivedField optype="continuous" dataType="double">
            <NormDiscrete field="no of claims" value="       0"/>
          </DerivedField>
        </NeuralInput>
        <NeuralInput id="3">
          <DerivedField optype="continuous" dataType="double">
            <NormDiscrete field="no of claims" value="       1"/>
          </DerivedField>
        </NeuralInput>
        <NeuralInput id="4">
          <DerivedField optype="continuous" dataType="double">
            <NormDiscrete field="no of claims" value="       3"/>
          </DerivedField>
        </NeuralInput>
        <NeuralInput id="5">
          <DerivedField optype="continuous" dataType="double">
            <NormDiscrete field="no of claims" value="     &gt; 3"/>
          </DerivedField>
        </NeuralInput>
        <NeuralInput id="6">
          <DerivedField optype="continuous" dataType="double">
            <NormDiscrete field="no of claims" value="       2"/>
          </DerivedField>
        </NeuralInput>
        <NeuralInput id="7">
          <DerivedField optype="continuous" dataType="double">
            <NormDiscrete field="domicile" value="suburban"/>
          </DerivedField>
         </NeuralInput>
         <NeuralInput id="8">
          <DerivedField optype="continuous" dataType="double">
            <NormDiscrete field="domicile" value="   urban"/>
          </DerivedField>
         </NeuralInput>
         <NeuralInput id="9">
          <DerivedField optype="continuous" dataType="double">
            <NormDiscrete field="domicile" value="   rural"/>
          </DerivedField>
        </NeuralInput>
      </NeuralInputs>
      <NeuralLayer numberOfNeurons="3">
        <Neuron id="10">
          <Con from="0" weight="-2.08148"/>
          <Con from="1" weight="3.69657"/>
          <Con from="2" weight="-1.89986"/>
          <Con from="3" weight="5.61779"/>
          <Con from="4" weight="0.427558"/>
          <Con from="5" weight="-1.25971"/>
          <Con from="6" weight="-6.55549"/>
          <Con from="7" weight="-4.62773"/>
          <Con from="8" weight="1.97525"/>
          <Con from="9" weight="-1.0962"/>
        </Neuron>
        <Neuron id="11">
          <Con from="0" weight="-0.698997"/>
          <Con from="1" weight="-3.54943"/>
          <Con from="2" weight="-3.29632"/>
          <Con from="3" weight="-1.20931"/>
          <Con from="4" weight="1.00497"/>
          <Con from="5" weight="0.033502"/>
          <Con from="6" weight="1.12016"/>
          <Con from="7" weight="0.523197"/>
          <Con from="8" weight="-2.96135"/>
          <Con from="9" weight="-0.398626"/>
        </Neuron>
        <Neuron id="12">
          <Con from="0" weight="0.904057"/>
          <Con from="1" weight="1.75084"/>
          <Con from="2" weight="2.51658"/>
          <Con from="3" weight="-0.151895"/>
          <Con from="4" weight="-2.88008"/>
          <Con from="5" weight="0.920063"/>
          <Con from="6" weight="-3.30742"/>
          <Con from="7" weight="-1.72251"/>
          <Con from="8" weight="-1.13156"/>
          <Con from="9" weight="-0.758563"/>
        </Neuron>
      </NeuralLayer>
      <NeuralLayer numberOfNeurons="1">
        <Neuron id="13">
          <Con from="10" weight="0.76617"/>
          <Con from="11" weight="-1.5065"/>
          <Con from="12" weight="0.999797"/>
        </Neuron>
      </NeuralLayer>
      <NeuralOutputs numberOfOutputs="1">
        <NeuralOutput outputNeuron="13">
          <DerivedField optype="continuous" dataType="double">
            <NormContinuous field="amount of claims">
              <LinearNorm orig="0" norm="0.1"/>
              <LinearNorm orig="1291.68" norm="0.5"/>
              <LinearNorm orig="5327.26" norm="0.9"/>
            </NormContinuous>
          </DerivedField>
        </NeuralOutput>
      </NeuralOutputs>
    </NeuralNetwork>
  </PMML>

**Comment by haifengl** [comment]
Neural network cannot handle categorical data directly. The typical approach is to use one hot encoding. If a categorical variable has three levels, you convert this variable to three binary variables.

**Comment by vruusmann** [comment]
@aminaaslam Nice to see that you're working on your own set of converter tools. Will you be publishing them when ready?

Regarding the one-hot-encoding of NN input fields, then this is typically done using the `NormDiscrete` element:
```XML
<NeuralInput id="ohe(x1=A)" optype="continuous" dataType="double">
  <NormDiscrete field="x1" value="A"/>
</NeuralInput>
```

For example, here's a sample R/Rattle model:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-rattle/src/test/resources/pmml/NeuralNetworkAudit.pmml#L97-L126

**Comment by aminaaslam** [comment]
Thanks hai and villu for your guidance. I havenot given enough thought to it. I may or may not publish it depending on how well it goes.

**Comment by aminaaslam** [comment]
Thanks @vruusmann; thats how i am handling categorical features by having NormDiscrete element.
But i  am having trouble providing weights to Con element from Smile's NeuralNetwork.

@haifengl I exposed Layer class in your implementation of Neural Network to get weights and outputs of a layer. But when i debug it; i come across this scenario. 
e.g. in my dataset i have 2 categorical features each has 3 categories and a Numeric attribute.  There are 7 NeuralInput but i get only 3(NeuralInputs) attributes from the net variable of type Layer[] which goes as input to the next layer;How do i work around other NeuralInput. According to one-hot-encoding i will have following NeuralInputs 
<NeuralInput id="0">
        <DerivedField optype="continuous" dataType="double">
          <NormContinuous field="age of car">
            <LinearNorm orig="0.01" norm="0"/>
            <LinearNorm orig="3.07897" norm="0.5"/>
            <LinearNorm orig="11.44" norm="1"/>
          </NormContinuous>
        </DerivedField>
   </NeuralInput>
<NeuralInput id="1">
    <DerivedField name="derivedNI_MaritalWidowed" optype="continuous" dataType="double">
     <NormDiscrete field="Marital" value="Widowed"/>
    </DerivedField>
   </NeuralInput>
   <NeuralInput id="2">
    <DerivedField name="derivedNI_OccupationClerical" optype="continuous" dataType="double">
     <NormDiscrete field="Occupation" value="Clerical"/>
    </DerivedField>
   </NeuralInput>
   <NeuralInput id="3">
    <DerivedField name="derivedNI_OccupationExecutive" optype="continuous" dataType="double">
     <NormDiscrete field="Occupation" value="Executive"/>
    </DerivedField>
   </NeuralInput>
<NeuralInput id="4">
    <DerivedField name="National_EmploymentPrivate" optype="continuous" dataType="double">
     <NormDiscrete field="Employment" value="Private"/>
    </DerivedField>
   </NeuralInput>
   <NeuralInput id="5">
    <DerivedField name="Nationla_EmploymentPSFederal" optype="continuous" dataType="double">
     <NormDiscrete field="Employment" value="PSFederal"/>
    </DerivedField>
   </NeuralInput>
   <NeuralInput id="6">
    <DerivedField name="National_EmploymentPSLocal" optype="continuous" dataType="double">
     <NormDiscrete field="Employment" value="PSLocal"/>
    </DerivedField>
   </NeuralInput>

**Comment by haifengl** [comment]
You probably has 3 neurons in the second layer. The net variable to the next layer is the output of this layer.

**Comment by aminaaslam** [comment]
@haifengl  this is my first layer or the input layer. but the net variable only give me 3 values in the output array where are ther should be 7 values in the output array to go into the next layer??

**Comment by haifengl** [comment]
Each neuron has 7 weights. Logically, there is the first layer of inputs. But programmatically you don't need it.

**Comment by aminaaslam** [comment]
So are you saying if there are 3 features 2 categorical(with 3 categories in each feature) and one 1 Numeric feature even then input layer will have 3 neurons and 3 values in output(which will go as input to the neuron of the next layer) because there is nothing in the weights array. Then the weights in the next layer go as input to the following array??

**Comment by haifengl** [comment]
No. You don't need to store the first/input layer, which is only for people to draw the graph. The first layer in our NeuralNetwork is actually the second layer that you normally see in a text book. If you have 10 neurons in the second layer of logical graph, then you will see 10 neurons in our first layer. In each neuron of our first layer, it takes 7 inputs and also has 7 weights. The output of each neuron is a single value, which is part of that layer's output vector.

**Comment by aminaaslam** [comment]
Hi hai, I am sorry i am bothering you. Your first layer doesnot have the same number of inputs as required by the PMML. I have in total 100 features and some of them are categorical so the total count comes up to 132(in terms of PMML 132 Neural Inputs). I only see 100 inputs in both the hidden layers. I am attaching pictures for your reference. This is from my debugger.
![img_6689](https://cloud.githubusercontent.com/assets/19845672/23805088/8778754e-058a-11e7-9624-fa98f8432d27.JPG)
![img_6690](https://cloud.githubusercontent.com/assets/19845672/23805087/87725182-058a-11e7-9206-db5379a43fe3.JPG)

**Comment by haifengl** [comment]
Can you post your code of training the neural network?

**Comment by aminaaslam** [comment]
Thats how i am training the neural network. These are my input parameters.

 "number.layers": 2,
    "error.function": "least.mean.square",
     "activation.function": "linear",
     "hidden.layer1.size":10,
     "hidden.layer2.size":10,
     "validationMethod": "entire"

`double[][] trainingArray = this.data.toArray(new double[data.size()][]);
int[] y = data.toArray(new int[data.size()]);
	    	NeuralNetwork.Trainer trainer = new NeuralNetwork.Trainer(this.errorFunction, this.activationFunction, trainingArray[0].length, this.units_layer_1,this.units_layer_2, this.output_layer);
	    	model = trainer.train(trainingArray, y);`

**Comment by aminaaslam** [comment]
@haifengl, did u get a chance to look at my code. Is there something that i am missing which is causing the problem.

**Comment by haifengl** [comment]
Can you print out trainingArray[0].length?

**Comment by aminaaslam** [comment]
The length of trainingArray[0] is 100 bc i have hundred features. But some features are categorical and PMML treats every category of a feature as a separate input which  is the problem that  i am facing

**Comment by haifengl** [comment]
If it is 100, the weight should be of 100. You are confused with PMML and implementation.

**Comment by haifengl** [comment]
To use categorical variable in smile, you should do the one hot encoding before feeding the data to neural network. We have classes to do this task, which separated from NeuralNetwork. PMML is just a specification. And most importantly, it is the output of training process. It doesn't mean that an implementation work in the same way.


Are you trying to import an PMML model into smile or export from smile?

**Comment by aminaaslam** [comment]
I used Nominal2Binary class to do One hot encoding and i am using that as a data preprocessing step and feed the processed data to the Neural Network.
But my problem remains that same. If u look at my PMML, there are 131 inputs but i have only 9 connections in my hidden layer. I think i am not calculating the weights properly.
[PMML.txt](https://github.com/haifengl/smile/files/845653/PMML.txt)

I am trying to generate PMML from smile neural network output. 
I am using JPMML evualuator to verify my predictions

**Comment by aminaaslam** [comment]
Problem was at my end and i am able to fix it
