### ISSUE TITLE
Complie error: smile.math.matrix.SparseMatrix cannot be converted to double[][]

### ISSUE THREAD

**Issue by DaveXster** [haifengl/smile#162]
Hi Haifeng Li,

I tried to get started with Smile in Windows 10 based on http://haifengl.github.io/smile/index.html#quickstart

I got the following error message:
```
C:\workspace\GIT\smile>sbt package
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
...
...
[info] Compiling 175 Java sources to C:\workspace\GIT\smile\core\target\classes...
[error] C:\workspace\GIT\smile\core\src\main\java\smile\manifold\LLE.java:204:  smile.math.matrix.SparseMatrix cannot be converted to double[][]
[error]         EigenValueDecomposition eigen = EigenValueDecomposition.decompose(M, n);
[error] C:\workspace\GIT\smile\core\src\main\java\smile\manifold\LaplacianEigenmap.java:200:  **smile.math.matrix.SparseMatrix cannot be converted to double[][]**
[error]         EigenValueDecomposition eigen = EigenValueDecomposition.decompose(L, d + 1);
[info] Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[error] (core/compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 5 s, completed Mar 16, 2017 5:26:08 PM
```

Can you please help me to find out what can be the problem?

Some info that might be useful:
- Windows 10 64 Bit
- java version "1.8.0_121"
- Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
- Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
- Scala code runner version 2.12.1
- SBT 0.13.13.1
- addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0") is added and seems to be applied
- The source code was cloned using GIT. Last commit: a948edcb429d7073c64c85625fb3e4d8586cc50f (Thu Mar 9 17:18:25 2017 -0500)
- I managed to compile smile-1.1.0

Thank you,
David

**Comment by haifengl** [comment]
We are refactoring matrix library. This may be caused by an accidental commit. Please wait a little bit. Our refactor will finish soon. Thanks!

**Comment by haifengl** [comment]
We just push the refactoring to master. Please do "git pull" and build again. Thanks!

**Comment by DaveXster** [comment]
Dear Haifeng,

It works now!

Thank you,
David
