### ISSUE TITLE
classWeight paramater on RandomForest is not clear.

### ISSUE THREAD

**Issue by javierfvargas** [haifengl/smile#163]
As classWeight parameter is not clear I was forced to check into the code to make some sense of it. The code raised a question.  I am far of an expert therefore my question could be foolish. 

It is regarding this line of code:
https://github.com/haifengl/smile/blob/ca15aac9308fde3a62bc0312d1266c2ed4f149af/core/src/main/java/smile/classification/RandomForest.java#L354

If you alter nj that way, aren't you truncating the sampling space? I mean, samples above nj/classWeight are not being used. Is it ok?

int xi = Math.randomInt(nj)
My understanding is that xi will never be greater than nj and if classWeight[l] is greater than 1 you will never use samples above the new value of nj.

Maybe I got it all wrong. In that case could you please explain how classWeight affects sampling.

Thanks.

**Comment by haifengl** [comment]
Thank you very much! It is a bug. The fix is in master now.

**Comment by javierfvargas** [comment]
Thank you. 

Just in case.  Bagging.java includes a very similar portion of code.

Also.  Could you elaborate a little on how classWeight works?  E.g, how I can achieve balanced class weight in unbalanced sets?

**Comment by haifengl** [comment]
Thanks! Updated it.

classWeight is the priors of the classes. The weights of each class is roughly the  ratio of samples in each class. For example, if  there are 400 positive samples and 100 negative samples, the classWeight should be [1, 4]  (assuming label 0 is of negative, label 1 is of positive). If the classWeight is null, we will assume that the data is balanced and assign the weight 1 to each class.

**Comment by nmaisonneuve** [comment]
I had to go to the code too to understand why to handle unbalanced data with random Forest .

i have high unbalanced data with a ratio of 1 / 10 for the classWeight , but the optimal results for the randomForest is to  put everything in false.   

1. any advice to be sure I am doing the right stuff?
 
2. the default value [1, 1] but the default assumption of a balanced data is really unlikely. from a end-user point of view, why is this classWeight parameters not more visible in the public training methods? trainer.train(dataset, prior)  ?

3. should be computed automatically from the training test to set the default classWeight values?

**Comment by haifengl** [comment]
1. For unbalanced data, firstly try to set a proper classWeight. If your ratio is 1: 10 for false : true, start with [1, 10] for classWeight and do some adjustment based on experiment results. Second, use the posterior probability and choose a cutoff by yourself. The default predict() just use 0.5, which may not be proper to you.

2. There is no good theory to find the classWeight for all data. The caller should do some experiments to find the good one for their use cases. If I change the default value to other values, some other people will complain that it is not  good for their data :)
