### ISSUE TITLE
Template issue on smile website

### ISSUE THREAD

**Issue by crockpotveggies** [haifengl/smile#165]
![screen shot 2017-03-28 at 7 07 08 pm](https://cloud.githubusercontent.com/assets/1445295/24435414/ff8ee8d4-13e9-11e7-8339-abfbe7788686.png)

Noticed the smile homepage was acting funny. This only happens when accessing the path root and not http://haifengl.github.io/smile/index.html (note index.html).

I think this commit is somehow affected by using the base `/` path: https://github.com/haifengl/smile/commit/afc866cfdf7a8bd14ce7d81056e8d03c2d3318ce

**Comment by haifengl** [comment]
It is an issue with cache. Clearing your browser cache will fix it. A workaround without clearing cache is to click the mean item (say User Guide -> Statistics). It will look good. Then click the title to go back to home page.

**Comment by haifengl** [comment]
You are right. This is more about the base / path. Our javascript doesn't handle it well. I will fix it. Thanks!

**Comment by haifengl** [comment]
Fixed. Thank you very much!

**Comment by crockpotveggies** [comment]
Glad it's solved!
