### ISSUE TITLE
partion

### ISSUE THREAD

**Issue by 2pol** [haifengl/smile#167]
Hi,

I have a case where the number of the amount of returned clusters of the HierarchicalClustering.partion(int k) function is lower than the given k.
Is this expected behavior?
Would you like to have some demo data?

Best,
p

**Comment by haifengl** [comment]
Yes, please. If you can provide your code snippet, it will be great. Thanks!

**Comment by 2pol** [comment]
Hi,

first, Thank you for creating and sharing this package. I forgot to mention this previously.

I have here a code snippet from a unit Test.
You have to read a txt file and have to change the path to your file location.
Then it should work. Let me know if you have problems or need help.

The [test.txt](https://github.com/haifengl/smile/files/884827/test.txt) with the test data.

Thank you!

Best,
p

` 
@Test
public void testCutTree() throws IOException {

    List<double[]> spectra = new ArrayList();

    BufferedReader br = null;
    //Reading the csv file
    br = new BufferedReader(new FileReader("test.txt"));

    String line = "";

    while ((line = br.readLine()) != null) {
        String[] lineArr = line.split(";");

        double[] vector = new double[lineArr.length];

        for (int i = 0; i < lineArr.length; i++) {
          vector[i] = Double.valueOf(lineArr[i]);
        }

        spectra.add(vector);
    }

    int n = spectra.size();

    double[][] proximity = new double[n][];

    for (int i = 0; i < n; i++) {
      proximity[i] = new double[i + 1];
      for (int j = 0; j < i; j++) {
        proximity[i][j] = Math.distance(spectra.get(i), spectra.get(j));
      }
    }

    /*
    end file read
     */

    HierarchicalClustering hac = new HierarchicalClustering(new SingleLinkage(proximity));

    int[] backArray = hac.partition(97);
    List<Integer> backList = uniqueArray(backArray);
    System.out.println(backList.size());//94

    backArray = hac.partition(89);
    backList = uniqueArray(backArray);
    System.out.println(backList.size());//87

  }


  private static List<Integer> uniqueArray(int[] arr) {

    List<Integer> uniList = new ArrayList();

    for (int i = 0; i < arr.length; i++) {

      int index = uniList.indexOf(arr[i]);

      if (index == -1) {

        uniList.add(arr[i]);
      }

    }

    return uniList;
  }
`

**Comment by haifengl** [comment]
Thanks! I will look into it. BTW, here is the same code in Scala

```
val x = read.table("/Users/lihb/Downloads/test.txt", delimiter=";").unzip
val d = proximity(x)
val hac = hclust(d, "single")
unique(hac.partition(97)).length
unique(hac.partition(89)).length
unique(hac.partition(8)).length
```

Also, you use a very large number of clusters to partition given the size of your data. I suggest to use a smaller number.

**Comment by haifengl** [comment]
I think that it is a design problem with our partition algorithm. Our partition algorithm is simple and efficient for almost all cases except yours. You have  only 131 samples but try to partition them into 97 or 89 clusters. For these settings, only a few clusters contain (a very small number of) multiple instances while all other clusters have only one instance. In practice, I don't really think that these numbers are meaningful.

To keep our algorithm simple and efficient, I would not revise it to pursue the perfectness in these extreme cases. Thanks!
