### ISSUE TITLE
Class RegressionTree.Node is not serializable

### ISSUE THREAD

**Issue by stieglma** [haifengl/smile#168]
In https://github.com/haifengl/smile/issues/79 you did the main work to make all classifiers serializable. I was currently testing with `RegressionTree` and got some errors due to the inner class `Node` of `RegressionTree` which is not serializable.

I propose to add this interface there, too, as it is for e.g. the `DecisionTree` class, where the inner `class Node implements Serializable`.

If you want a pull request for that I can also create it, but as this is only a one-line change I thought that's not necessary.

**Comment by haifengl** [comment]
The fix is in master branch now. Thanks!

**Comment by stieglma** [comment]
wow, that was fast, thanks!
