### ISSUE TITLE
NominalAttribute#valueOf declares to throw ParseException

### ISSUE THREAD

**Issue by stieglma** [haifengl/smile#169]
The method `NominalAttribute#valueOf(String s)` declares to throw `ParseException` which is not correct from my understanding. The method does only lookup strings in a map and if existant return the related double value. If not existant, a new relation between this string and an incremented number is added to the map.

Would be great if you could remove this unnecessarily declared exception. If you want to have a pull-request for that, I can also create one.

**Comment by haifengl** [comment]
The declare of "throw ParseException" comes from the parent class Attribute. Note that what you describe is only true when the attribute is open. If not, we could throw an exception. I just update the code to throw ParseException instead of IllegalArgumentException. Thanks!

**Comment by stieglma** [comment]
That's true, thanks for the fast fix! Do you already have a date in mind for the next release?

**Comment by haifengl** [comment]
v1.3.0 was just released. So we will wait a little bit to cumulate enough fixes for next release. For now, you can clone and build the project by yourself. Thanks!

**Comment by stieglma** [comment]
That's what I thought, we did clone the project already, and I also made some changes to clean up the code a little bit (many easy-to-fix rawtype/generics warnings coming up with eclipse, as well as some unused imports) if you are interested in that I can create a pull request with these fixes.

Exactly for the task of importing this project into eclipse was quite hard as there is no really good sbt-support. Would you mind creating a pom file such that it can be properly imported? This will make it for everyone who wants to contribute much easier to start.

**Comment by haifengl** [comment]
Yes, please. Thank you very much!

We actually had pom files before. But since we switched to IntelliJ, the life is much easier with sbt. Then we removed pom files as they became outdated. It is hard to keep tracking two building system. More importantly, we have the scala module now.

**Comment by haifengl** [comment]
v1.3.1 is released with all the bug fixes. Thanks!
