### ISSUE TITLE
ManiFoldLearning-ISOMap; java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#175]
Hi Hai,
I am running into this issue while running ISOMap
`[main] INFO smile.manifold.IsoMap - IsoMap: 2 connected components, largest one has 986 samples.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10
	at smile.math.matrix.EigenValueDecomposition.tql2(EigenValueDecomposition.java:1404)
	at smile.math.matrix.EigenValueDecomposition.decompose(EigenValueDecomposition.java:629)
	at smile.math.matrix.EigenValueDecomposition.decompose(EigenValueDecomposition.java:422)
	at smile.math.Math.eigen(Math.java:4316)
	at smile.manifold.IsoMap.<init>(IsoMap.java:179)
	at com.smile.dimensionality.reduction.IsoMapLearner.learn(IsoMapLearner.java:80)
	at com.smile.dimensionality.reduction.ManifoldLearningFunction.execute(ManifoldLearningFunction.java:85)
	at com.common.ModelingEngine.main(ModelingEngine.java:81)`

**Comment by haifengl** [comment]
Can you share your data? I will debug it. BTW, did you test this with 1.3.0? Have you tried 1.2.3? I made big changes to matrix computation. Want to make sure if the changes cause this. Thanks!

**Comment by aminaaslam** [comment]
HI Hai,
I am using smile version 1.2.3. Do you think i should try 1.3.0??

**Comment by haifengl** [comment]
I will test it with 1.3.0 (latest version) anyway.

**Comment by aminaaslam** [comment]
ok I will test it with the latest version and let you know. until then i will keep the issue opne.

Thanks

**Comment by haifengl** [comment]
I guest that this is the same data as in ticket 174. Can you first check if you have duplicated samples in your data? Thanks!

**Comment by aminaaslam** [comment]
hi hai,
you guessed it right. there may be duplicate samples in the data. Is duplicate data instances causing the problem? Does this mean i need to remove duplicate data instances from data?? or version 1.3.0 works around this problem.

**Comment by haifengl** [comment]
Duplicated sample will cause the distance matrix singular, which cause the issue in ticket 174 for sure. You should remove duplicated samples. no work around for singular matrix.

This ticket might be cause by the duplicated samples. But I am not sure. Thanks!

**Comment by aminaaslam** [comment]
Let me remove the duplicated samples and see what happens. I will revert back.
Thanks

**Comment by aminaaslam** [comment]
Hi Hai,
I ran some experiments on my data which didnt have duplicate samples and here are the results from my experiments.
I believe ticket 174 are not linked 
ManiFold Learning- LLE
------------------------
Cards data.
none:works fine

Standardize: Gives this error

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 402
	at smile.manifold.LLE.<init>(LLE.java:209)
	at com.smile.dimensionality.reduction.LLELearner.learn(LLELearner.java:67)
	at com.smile.dimensionality.reduction.ManifoldLearningFunction.execute(ManifoldLearningFunction.java:85)
	at com.common.ModelingEngine.main(ModelingEngine.java:81)


Normalize: Gives this error

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 402
	at smile.manifold.LLE.<init>(LLE.java:209)
	at com.smile.dimensionality.reduction.LLELearner.learn(LLELearner.java:67)
	at com.smile.dimensionality.reduction.ManifoldLearningFunction.execute(ManifoldLearningFunction.java:85)
	at com.common.ModelingEngine.main(ModelingEngine.java:81)


ManiFold Learning- ISOMap
--------------------------

"method" : "isomap.learner",
  "parameters" : {
    "d" : 2,
    "k" : 5,
    "normMethod" : "normalize",
   }



  "method" : "isomap.learner",
  "parameters" : {
    "d" : 2,
    "k" : 5,
    "normMethod" : "standardize",
}


  "method" : "isomap.learner",
  "parameters" : {
    "d" : 2,
    "k" : 5,
    "normMethod" : "none",
    }

**Comment by haifengl** [comment]
Does "d" means the dimensionality of input data? If so, k = 5 is probably too big.

**Comment by haifengl** [comment]
Also, normalization and standardization may not be good ideas for manifold learning. They are mostly for classification.

**Comment by aminaaslam** [comment]
yes d means dimensions of data.
i can have only two values in it 2 or 3.
So what would be a good range for k for these dimensions???

**Comment by haifengl** [comment]
In general k should be less than d. The purpose of manifold learning is to find the intrinsic dimensions, which should be smaller.

**Comment by aminaaslam** [comment]
Hi Hai,
Referring to your earlier comment k should be less than d. Then how do i run manifold learning on Mnist dataset and get these results.
http://scikit-learn.org/stable/auto_examples/manifold/plot_lle_digits.html#sphx-glr-auto-examples-manifold-plot-lle-digits-py
Here in the experiment k = 30 and number of dimensions =2 ??

**Comment by haifengl** [comment]
The dimension of MNIST is 28 X 28 = 784. You are confused with the t-SNE plot.

**Comment by aminaaslam** [comment]
This is one of the examples in the link
n_neighbors = 30
 

# Isomap projection of the digits dataset

print("Computing Isomap embedding")

t0 = time()

X_iso = manifold.Isomap(n_neighbors, n_components=2).fit_transform(X)

print("Done.")

plot_embedding(X_iso,

               "Isomap projection of the digits (time %.2fs)" %

               (time() - t0))

**Comment by haifengl** [comment]
Sorry, there were miscommunications. I was asking if d is the input dimension in your settings. You said yes. In our API, d is the output dimension.

**Comment by aminaaslam** [comment]
I am sorry for the miscommunication. This means i can set k greater the output dimensions of the data. So when i do that it gives me this error. Is it because of duplicate data samples? But when i set k <d(output of dimensions) this error disappears? can you please explain what is going on?. 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 402
at smile.manifold.LLE.(LLE.java:209)
at com.smile.dimensionality.reduction.LLELearner.learn(LLELearner.java:67)
at com.smile.dimensionality.reduction.ManifoldLearningFunction.execute(ManifoldLearningFunction.java:85)

**Comment by haifengl** [comment]
Duplicates are more likely the issue.

**Comment by aminaaslam** [comment]
Hi Hai, 
So i made sure there are no duplicates in my data but when i give these parameters it gives me this exception 
d = 2(dimensions of output data )
k =3 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See  for further details.
Exception in thread "main" java.lang.RuntimeException: Matrix is singular.
  at smile.math.matrix.LUDecomposition.solve(LUDecomposition.java:254)
  at smile.manifold.LLE.<init>(LLE.java:178)
   
I have raised a similar ticket https://github.com/haifengl/smile/issues/174
What do you think is the cause of this issue ?

**Comment by haifengl** [comment]
Can you share the data? I will debug it. Sometimes if two samples are too close, the distance matrix might be singular or near singular, which will cause the problem. Thanks!

**Comment by aminaaslam** [comment]
Here is the data that i am using and the data description file.

**Comment by aminaaslam** [comment]
[iso-card.json.txt](https://github.com/haifengl/smile/files/1023382/iso-card.json.txt)

[CardOperations-Training.csv.txt.gz](https://github.com/haifengl/smile/files/1023390/CardOperations-Training.csv.txt.gz)

**Comment by aminaaslam** [comment]
.json is the data descriptor 
the other file is data. 

Thanks,

**Comment by haifengl** [comment]
Thanks! Do you have the code snippet too?

**Comment by aminaaslam** [comment]
For parsing the data ??

**Comment by haifengl** [comment]
For parsing and also the call to LLE. Thanks!

**Comment by aminaaslam** [comment]
Hai, I am using univocity parser for parsing the data. 
import com.univocity.parsers.csv.CsvParser;
import com.univocity.parsers.csv.CsvParserSettings;

I dont know how to share the code with you because its so interdependent that i will have to share the entire project with you and thats a total waste of your time. This is the best i could do 

`      double data[][]; 
       IsoMap isomap = new IsoMap(data, d, k,true);
        this.coordinates = isomap.getCoordinates();
        this.graph = isomap.getNearestNeighborGraph();`

**Comment by aminaaslam** [comment]
this is how i am parsing data. Hope it makes sense.
```
import java.io.*;
import java.net.URI;
import java.nio.charset.StandardCharsets;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.baesystems.ai.analytics.common.FieldConfiguration;
import com.baesystems.ai.analytics.common.FieldFunction;
import com.baesystems.ai.analytics.common.ModelingDataType;
import com.baesystems.ai.analytics.common.input.DatasetConfiguration;

import com.univocity.parsers.csv.CsvParser;
import com.univocity.parsers.csv.CsvParserSettings;



import smile.data.Attribute;
import smile.data.AttributeDataset;
import smile.data.Datum;
import smile.data.NominalAttribute;
import smile.data.NumericAttribute;


public class SmileDataUtils {
	private static final Logger log = LoggerFactory.getLogger(SmileDataUtils.class);
	

	private static AttributeDataset data;

	public static AttributeDataset getData()
	{
     	return data;
	}
	
	/**
     * Parse a data instance from given row.
     */
    public static AttributeDataset parse(final DatasetConfiguration dataInfo, final List<String> attributesList) throws IOException, ParseException
    {
		//cleanseData(dataInfo);
		String[] row;
		int responseIndex=0;
		Attribute response=null;
		int numAttributes=0;
		String target="";
		List<Attribute> attributes = new ArrayList<>();
        Attribute[] attr = new Attribute[attributesList.size()];
        attributes.toArray(attr);
        //attributesList.forEach(attribute-> {
            for(String attribute: attributesList) {
				FieldConfiguration field = dataInfo.getFieldConfiguration(attribute);
				if (field.modelingType().equals(ModelingDataType.categorical) && field.function().equals(FieldFunction.predictor)) {
					attributes.add(createCategoricalAttribute(dataInfo.getFieldConfiguration(attribute)));

				} else if (field.modelingType().equals(ModelingDataType.continuous)) {
					attributes.add(new NumericAttribute(attribute));
					numAttributes++;
				}
				if (field.function().equals(FieldFunction.target)) {
					responseIndex = dataInfo.getFieldPosition(attribute);
					String[] values = new String[2];
					values[0]="0";
					values[1]="1";
					response = new NominalAttribute(field.name(),values);
					target = field.name();
				}
			}
          // });
         
        final CsvParserSettings parserSettings = new CsvParserSettings();
   		//char delimiter = dataInfo.delimiter().charAt(0);
   	    parserSettings.getFormat().setDelimiter(dataInfo.delimiter().charAt(0));
   	    parserSettings.setMaxColumns(10000);
   	    
   	    parserSettings.setLineSeparatorDetectionEnabled(true);
   	    final CsvParser parser = new CsvParser(parserSettings);
   	       
   	    final Path path = Paths.get(URI.create(dataInfo.location()));
       	parser.beginParsing(path.toFile(), StandardCharsets.UTF_8);


		int lineCount=0;
		data = new AttributeDataset("DataSet", attributes.toArray(new Attribute[attributes.size()]), response);

   	    while ((row = parser.parseNext()) != null) {
   	    	if (lineCount++ < dataInfo.skipHeaderLines()) {
                continue;
            }
   	    	else {
   	    	   data.add(getDataInstance(attributes,responseIndex,row,dataInfo,target));
   	    		//data.add(getDataInstanceForNeuralNetwork(attributes,responseIndex,row,dataInfo));
   	    	}
   	      }

   	      return data;

    }

   /* private static void cleanseData(final DatasetConfiguration dataInfo)
	{
		String location = dataInfo.location();
		List<String[]> inputList = new ArrayList<String[]>();

		//final String delimiter = ((String) dataInfo.delimiter().charAt(0));
		try{
			File inputF = new File("/root/bae/datafiles/cards-temp.csv");
			InputStream inputFS = new FileInputStream(inputF);
			BufferedReader br = new BufferedReader(new InputStreamReader(inputFS));
			inputList = br.lines().skip(1).map( line->{
              String []  p = line.split("|");
              return p;
			}).collect(Collectors.toList());
			br.close();
			List<String[]> distinctElements = inputList.stream().distinct().collect(Collectors.toList());
			System.out.println("this is the size"+distinctElements.size());
		} catch (final IOException e) {
			System.out.println(e.getMessage());

		}

		BufferedReader list = null;
		try {
			list = new BufferedReader( new FileReader( "/root/bae/datafiles/cards-temp.csv" ) );
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		String line;
		int count =0;
		TreeMap<String,Integer> map  = new TreeMap<String,Integer>();

		try {
			while ( (line = list.readLine()) != null )
            {
                if (!map.containsKey(line))
                {
                    final Integer put = map.put(line, 0);

                }
                else {
                	count++;
				}


            }

			list.close();
			System.out.println(map.size()+":" + count);
		} catch (IOException e) {
			e.printStackTrace();
		}


	}*/





	private static Datum<double[]> getDataInstance(List<Attribute> attributes,int responseIndex,String[] row,final DatasetConfiguration dataInfo,String target) throws IOException, ParseException
    {
        
    	double[] x =  new double[attributes.size()];
        double y = Double.NaN;
        for (int k=0;k<attributes.size();) {
        	
        	 int index=dataInfo.getFieldPosition(attributes.get(k).getName());
        	 FieldConfiguration field=dataInfo.getFieldConfiguration(attributes.get(k).getName());
        	 if(field.modelingType().equals(ModelingDataType.categorical) && field.function().equals(FieldFunction.predictor)) {
        		  x[k] = (row[index]!=null&&!row[index].equals("NaN")) ? getCategoryValue(field,row[index]):getCategoryValue(field,field.missing());
        		  k++;
        	 }
        	 else if(field.modelingType().equals(ModelingDataType.continuous) && field.function().equals(FieldFunction.predictor)) {
        		  x[k] = (row[index]!=null&&!row[index].equals("NaN"))  ? getDataType(row[index],field):getDataType(field.missing(),field);
        		  k++;
             }
        
        }
        y=getDataType(row[responseIndex],dataInfo.getFieldConfiguration(target));
        return new Datum<>(x, y);
    }

	
	private static NominalAttribute createCategoricalAttribute(FieldConfiguration field)
	{
		int size = field.categories().size();
		String[] values = new String[size];
	    for(int i=0;i<size;i++) {
			values[i] = field.categories().get(i);
		}
		return new NominalAttribute(field.name(),values);
		
	}
	
	public static double getDataType(String data,FieldConfiguration field)
	{
		final NumberFormat numberFormat = NumberFormat.getNumberInstance();
		switch (field.baseType()) {
        case integer:
            try {
               numberFormat.parse(data).intValue();
            } catch (final ParseException e) {
                throw new IllegalArgumentException(String.format("Field '%s' has value '%s' which does not parse as an integer.", field.name(), data));
            }
        case real:
            try {
               return numberFormat.parse(data).doubleValue();
               
            } catch (final ParseException e) {
                throw new IllegalArgumentException(String.format("Field '%s' has value '%s' which does not parse as a real number.", field.name(), data));
            }
        default:
            throw new UnsupportedOperationException(String.format("Unsupported feature base type '%s' for field", field.baseType()));
   
		}
    }
	private static double getCategoryValue(FieldConfiguration field,String data)
	{
        double index = (double)field.getCategoryIndex(data);
		return (double)index;
	}
}
		

```

**Comment by haifengl** [comment]
Thanks! What's your k and d? You already filtered the duplicates in the attached files, right?

**Comment by aminaaslam** [comment]
k = k-neighbor
d= dimensions of output data 
Yes there are no duplicates in the data.
Hai, one more thing i actually ran Iso map on a data set with duplicate samples and it worked fine. Its just that there were only 100 records in there. 
Is size of data with higher number of k the cause of this exception?

**Comment by haifengl** [comment]
Large k is not recommended in general. I know the meaning of k and d :) I was asking their values in your settings that cause the problem.

**Comment by aminaaslam** [comment]
Sorry , This is the value that i used 
 "d" : 2,
 "k" : 3,

**Comment by haifengl** [comment]
Can you serialize the parsed data (the data matrix) into a plain csv file or Java object file? I am afraid that I will load your data incorrectly, which is pretty complicated. BTW, IsoMap/LLE uses Euclidean distance, which seem not appropriate to your data, which is mix of numeric, nominal and string data.

**Comment by haifengl** [comment]
You better first convert nominal values to one-hot encoding.

**Comment by haifengl** [comment]
Also don't include operation id and timestamp in the features. If you have to use timestamp, better convert it to things like day of month, day of weeks, etc. Feature engineering is very important in machine learning.

**Comment by aminaaslam** [comment]
Here is the parsed data with no Strings and nominal features( i have done one-hot encoding). Let me know if this is what u wanted. Please find attached the .csv file and this data goes into the ISO-Map learner.
[outdata.csv.gz.zip](https://github.com/haifengl/smile/files/1025948/outdata.csv.gz.zip)

**Comment by aminaaslam** [comment]
I am not using any String features and i am converting nominal features. Please let me know if this makes sense.

**Comment by haifengl** [comment]
Thanks! Sounds good. I will try it tonight.

**Comment by haifengl** [comment]
I cannot open your file:
```
$ unzip outdata.csv.gz.zip 
Archive:  outdata.csv.gz.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of outdata.csv.gz.zip or
        outdata.csv.gz.zip.zip, and cannot find outdata.csv.gz.zip.ZIP, period.
```

**Comment by aminaaslam** [comment]
[outdata.csv.gz](https://github.com/haifengl/smile/files/1027804/outdata.csv.gz)

**Comment by aminaaslam** [comment]
this is .gz file. You should be able to open this.
THanks!!!

**Comment by aminaaslam** [comment]
Hi Hai,
Did u get a chance to look at the file that i sent you.
Thanks!!!!

**Comment by haifengl** [comment]
Got OOM error on a small machine last night. Will try it on a bigger machine.

**Comment by aminaaslam** [comment]
Hi Hai, 
I have a good news so i have a smaller data set which has 3000 records and ISOMap works on as big a value of k=50. I am not able to test this data set that i attached here because i am running into OOM even on my biggest machine and with k=3. 
However, LLE doesnot work even with k=3 on my smaller data set and throws the exception that i mentioned in ticket: 174 and here is the exception 
Exception in thread "main" java.lang.RuntimeException: Matrix is singular.
at smile.math.matrix.LUDecomposition.solve(LUDecomposition.java:254)
at smile.manifold.LLE.<init>(LLE.java:178)
I hope i am not confusing you any further.
Thanks!!!

**Comment by haifengl** [comment]
I see the exception in IsoMap, which happens during the eigen value decomposition. I will try to figure out what's wrong. It may take some time.

**Comment by aminaaslam** [comment]
Thanks that will be very helpful.
Amina

**Comment by aminaaslam** [comment]
Hi Hai, Did u get a chance to look at what is going one with Eigen Value Decomposition. Please let me know when you get a chance to look at this issue.
Thanks,
Amina

**Comment by haifengl** [comment]
Likely it is a numeric stability issue. It is also why you have fewer problems with smaller data. For long term, we should use something like blas and lapack, which are more numerical stable and also faster. I am looking into how to do it. But it will take a lot of time.
