### ISSUE TITLE
No *.arff files in data/weka/?

### ISSUE THREAD

**Issue by tarlen5** [haifengl/smile#177]
Hello! I am trying out this library to explore switching some Machine Learning work to scala and in going over the `User Guide`, I noticed that there are no *.arff files in the repository in the `data/weka/` directory. For example, in implementing the `iris.sh` script in the `User Guide`/`Shell` section, I had to google around to find the file iris.arff from a random link! Shouldn't these sample data sets in the User Guide be in the repository here? Or am I missing something?

Thanks!

**Comment by haifengl** [comment]
If you download the binary package, the data are in the install direcotry data/weka. If you try to find them in the source code, they are in shell/src/universal/data/weka.

**Comment by tarlen5** [comment]
Ahh, thanks. I installed from source by cloning the repo, so I see them now in my `shell/src/universal/data/weka` directory. Thanks again!

**Comment by haifengl** [comment]
In your clone, run ./smile.sh to build and get into the smile shell. It also set the working directory to the right location so that you load data directly from the data directory such as read.arff("data/weka/cpu.arff"). Cheers!
