### ISSUE TITLE
saving an image

### ISSUE THREAD

**Issue by lolaclinton** [haifengl/smile#179]
When I trigger the save image in the context window it doesn't let me put in a file name. It only works by picking a file it can overwrite.

**Comment by haifengl** [comment]
What's your OS?

**Comment by lolaclinton** [comment]
Mac


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone
-------- Original message --------From: Haifeng Li <notifications@github.com> Date: 5/2/17  6:40 PM  (GMT-05:00) To: haifengl/smile <smile@noreply.github.com> Cc: lolaclinton <oferm@cluemail.com>, Author <author@noreply.github.com> Subject: Re: [haifengl/smile] saving an image (#179) 
What's your OS?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haifengl/smile","title":"haifengl/smile","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/haifengl/smile"}},"updates":{"snippets":[{"icon":"PERSON","message":"@haifengl in #179: What's your OS?"}],"action":{"name":"View Issue","url":"https://github.com/haifengl/smile/issues/179#issuecomment-298781384"}}}

**Comment by haifengl** [comment]
Swing doesn't work well on mac. The image saving facility works well on windows. I will see if there is any work around.

**Comment by lolaclinton** [comment]
It's kind of strange as it is bringing up the open file menu not a save file one. 


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone
-------- Original message --------From: Haifeng Li <notifications@github.com> Date: 5/2/17  7:09 PM  (GMT-05:00) To: haifengl/smile <smile@noreply.github.com> Cc: lolaclinton <oferm@cluemail.com>, Author <author@noreply.github.com> Subject: Re: [haifengl/smile] saving an image (#179) 
Swing doesn't work well on mac. The image saving facility works well on windows. I will see if there is any work around.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haifengl/smile","title":"haifengl/smile","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/haifengl/smile"}},"updates":{"snippets":[{"icon":"PERSON","message":"@haifengl in #179: Swing doesn't work well on mac. The image saving facility works well on windows. I will see if there is any work around."}],"action":{"name":"View Issue","url":"https://github.com/haifengl/smile/issues/179#issuecomment-298786353"}}}

**Comment by haifengl** [comment]
When in the file dialogue, please try CMD + Shift + G to bring up a window to type the path. I find this on internet and have not tried it yet. Thanks!

**Comment by lolaclinton** [comment]
Doesn't seem to work.

**Comment by haifengl** [comment]
I fixed it. Please try v1.3.1. Thanks!
