### ISSUE TITLE
SmileDemo

### ISSUE THREAD

**Issue by andy-goryachev** [haifengl/smile#18]
Can you please provide sources for SmileDemo?
Thanks!
-a

**Comment by haifengl** [comment]
For sure, I can share the source code of SmileDemo. The problems is that it depends on some open datasets that I download from the web. I cannot put these data in Github as they belong to others. You will be able to browse the code but cannot really run it due to the data. Is it okay?

**Comment by andy-goryachev** [comment]
Yes, this should be fine.  It is much easier to evaluate or learn the code if one looks at a working example.
Thank you!

**Comment by haifengl** [comment]
SmileDemo is imported. Please let me know if you have any questions. Thanks!

**Comment by amorroxic** [comment]
I too am a beginner and was sweating with a few books aside trying to grasp the concepts. 
Thank you for sharing your incredible work Professor Haifeng Li!

Adrian.

**Comment by andy-goryachev** [comment]
Thanks!
