### ISSUE TITLE
Math.isZero(double) implementation is incorrect

### ISSUE THREAD

**Issue by AlexDBlack** [haifengl/smile#180]
In short: ```Math.isZero(0.0)``` returns false, which causes (probably amongst other things) the Java Lasso and RidgeRegression implementations to fail when a column contains all of the identical values for all examples.

Math.isZero(double x) calls Math.isZero(x, Double.MIN_VALUE), which does ```abs(x) < 2*epsilon```
https://github.com/haifengl/smile/blob/master/math/src/main/java/smile/math/Math.java#L3453-L3455

However, (presumably because Double.MIN_VALUE is a denormal floating point number) ```2.0*Double.MIN_VALUE``` is 0.0, and consequently ```Math.abs(0.0) < 0.0``` returns false.

I doubt it matters, but I'm running Windows 10, Oracle JDK 1.8.0_91

**Comment by haifengl** [comment]
This is surprising!! I will check it out. Thank you very much!!

**Comment by haifengl** [comment]
I don't observe what you described:

```
smile> Math.isZero(0.0)
res0: Boolean = true
smile> Math.isZero(java.lang.Double.MIN_VALUE)
res1: Boolean = true
smile> Math.isZero(2*java.lang.Double.MIN_VALUE)
res2: Boolean = false
```

**Comment by haifengl** [comment]
But Double.MIN_VALUE is very small (2^-1074). A more practical epsilon value maybe Math.EPSILON (2.220446049250313E-16 on my machine). I will try this value and run unit tests.

**Comment by AlexDBlack** [comment]
Thanks for looking into this. So, the plot thickens...

Here's a stand-alone method that (when run in my project) returns the correct values:
```
    public static void main(String[] args){
        System.out.println("-- Standalone Class ---");
        double d = 2.0;
        System.out.println("2.0 * Double.MIN_VALUE: " + (d * Double.MIN_VALUE));
        System.out.println("Is zero: " + smile.math.Math.isZero(0.0));
    }
```
```
-- Standalone Class ---
2.0 * Double.MIN_VALUE: 1.0E-323
Is zero: true
```

Yet, running the exact same code as part of my training pipeline gives a different result:
```
    public static RidgeRegression ridgeRegression(MultiDataSet trainData, double lambda){
        System.out.println("-- My Code ---");
        double d = 2.0;
        System.out.println("2.0 * Double.MIN_VALUE: " + (d * Double.MIN_VALUE));
        System.out.println("Is zero: " + smile.math.Math.isZero(0.0));

        Pair<double[][], double[]> pair = mdsToDoublesRegression(trainData);
        return new RidgeRegression(pair.getFirst(), pair.getSecond(), lambda);
    }
```

```
-- My Code ---
2.0 * Double.MIN_VALUE: 0.0
Is zero: false
```

I'm not doing anything special in my code - same machine, same environment, standard hardware (Intel i7), not messing with anything unusual like strictfp, reflection or anything. Suffice to say, I'm pretty confused by this result - but it is repeatable.

At any rate, ```2.0*Double.MIN_NORMAL``` gives me a positive number (4.450147717014403E-308) while ```2.0*Double.MIN_VALUE``` does not.

**Comment by haifengl** [comment]
I made a revise yesterday about isZero. The default epsilon is now smile.math.Math.EPSILON. It should be more predictable and small enough for practical purpose.

The problem with Math.MIN_VALUE is that it is so small (as small as a random error in FPU). It maybe the root cause.

Please clone the repo or git pull to test it out. Thanks!
