### ISSUE TITLE
how to running program with SVMdemo

### ISSUE THREAD

**Issue by sitinurdiana** [haifengl/smile#181]
when I running program class main SVM Demo, why I found in here:

java.io.FileNotFoundException: shell\src\universal\bin\..\data\classification\toy\toy-train.txt (The system cannot find the path specified)
Exception in thread "main" java.lang.NullPointerException
	at smile.demo.classification.ClassificationDemo.<init>(ClassificationDemo.java:102)
please help me 
thank you

**Comment by haifengl** [comment]
Do it in the shell. It is easier. If you install the binary package, type bin/smile to run the shell. Then type demo in the shell.

If you clone the repo, type ./smile.sh to build and run shell.

**Comment by sitinurdiana** [comment]
Mr. Haifeng 
can you help to tell me run your program about Support vector machine, because I am newbie and I am very confused to my research.
thank you

**Comment by haifengl** [comment]
Please check the document at

http://haifengl.github.io/smile/classification.html#svm

and

http://haifengl.github.io/smile/api/java/index.html

You should also read http://haifengl.github.io/smile/shell.html about how to use the smile shell and http://haifengl.github.io/smile/data.html to load the data. Thanks!

**Comment by sitinurdiana** [comment]
thank you Mr. you are very helpful

**Comment by haifengl** [comment]
You are welcome!
