### ISSUE TITLE
Errors while executing smile/core/src/main/java/smile/regression/RandomForest.java project

### ISSUE THREAD

**Issue by ANURAGMN** [haifengl/smile#184]
Tried importing the smile-master and executing the project, 
1.No errors in RandomForest.java file still could not able to run/execute.
2.Lots of errors in other packages such as libsvm parser error,org.slf4j cannot be resolved error,.......

**Comment by haifengl** [comment]
Well very likely you didn't follow our building instructions. Are you using JDK8 and SBT?
