### ISSUE TITLE
RandomForest issue with dummy coded y[] values

### ISSUE THREAD

**Issue by smutchler** [haifengl/smile#187]
In RandomForest.java (line 333) you assume that dummy coded values (for y) start at zero.

 public Tree call() {
            int n = x.length;
            int k = smile.math.Math.max(y) + 1;
...

This should be 
           int k = smile.math.Math.unique(y);

You cannot assume the dummy coded values start at zero and are continuous (and don't otherwise).

**Comment by haifengl** [comment]
It is our assumption. And it is consistent in all our classification algorithms. It is the caller's responsibility to make sure the input data follow the requirements.
