### ISSUE TITLE
Case-wise variable importance

### ISSUE THREAD

**Issue by smutchler** [haifengl/smile#188]
It would be great to be able to calculate case-wise variable importance (vs. overall variable importance) in RandomForest.  It's often advantageous to be able to "explain" how RandomForest is making decisions for specific cases.

**Comment by haifengl** [comment]
What do you mean case-wise importance? Thanks!

**Comment by smutchler** [comment]
For example, if you are predicting setosa/virginica/versicolor in classification and ultimately predict setosa (with some posterior probability) for case/row #1... what variables were important in making that prediction.  For case 1, Sepal.Length may be the strongest predictor and for case 2, Sepal.Width may be the strongest predictor.  
In the RandomForest package in R, this is turned on by localImp = TRUE.
I guess you would look at Gini decrease for each variable (turned on) for all trees but just for a single row of data.  I'm just guessing.

**Comment by haifengl** [comment]
Close the ticket as the definition of local importance is not clear and no strong demand.
