### ISSUE TITLE
numUnits for NeuralNetwork classification

### ISSUE THREAD

**Issue by smutchler** [haifengl/smile#189]
If I'm trying to predict 3 possible y values, given 4 different x variables and I want a hidden layer with 5 nodes, should numUnits be 4, 5, 3?  Where 4 is the size of the input layer (4 x values), 5 is the hidden layer size and 3 is the output layer size (because there are 3 possible values)?

What about a bias term?

**Comment by haifengl** [comment]
Your setting is correct. The bias term is implicitly handled by smile.
