### ISSUE TITLE
Online learning for KNN?

### ISSUE THREAD

**Issue by skx300** [haifengl/smile#190]
Hi,

Is there any ONLINE LEARNING for KNN? 

I have checked the source code. It seems like the KNNSearch can't do the online learning.

**Comment by haifengl** [comment]
Nearest neighbor is a lazy learning algorithm, which means no learning :)

I guess what you want is an online algorithm to build a nearest neighbor search data structure. I am not aware of such algorithms.

**Comment by skx300** [comment]
Thank you @haifengl . By the way, is there any demo for storing the trained model?

**Comment by haifengl** [comment]
Check out FAQ on haifengl.github.io. Basically use read(), read.xstream(), write(), and write.xstream() functions

**Comment by lorinying** [comment]
Thanks for the useful information provided by @haifengl and @skx300. But I have another question. Is there any demo or api to store the trained model to buffer in memory or serialized to string and then put the data stream in memory  into mongodb dataset?

**Comment by haifengl** [comment]
First of all I don't recommend to save models to Mongodb as it has hard limit on document size (16mb), which is not sufficient for big models.

To serialize an object in memory with Java, please just google it. There are many examples online and it is very simple.
