### ISSUE TITLE
Some Tokenizer Issues

### ISSUE THREAD

**Issue by hrzafer** [haifengl/smile#191]
Some location names are merged with the period.

`City of Boston. Each party` => `City`, `of`, `Boston.`, `Each`, `party`
`State of New York. Notwithstanding` => `State`, `of`, `New`, `York.`, `Notwithstanding`
`the State of North Carolina. For any` => `the`, `State`, `of`, `North`, `Carolina.`, `For`, `any`
`courts of Illinois. The United Nations` => `courts`, `of`, `Illinois.`, `The`, `United`, `Nations`
`the State of California. Any dispute` => `the`, `State`, `of`, `California.`, `Any`, `dispute`

Actually, there are more but I think this should be enough to address the issue.

**Comment by haifengl** [comment]
the tokenizer is rule based and is not perfect. We were mostly concerned with the cases like "U.S."

"Boston." is not perfect but it seems a bigger issue if we split U.S. to U . S .
