### ISSUE TITLE
NeuralNetwork Classifier not working as expected

### ISSUE THREAD

**Issue by smutchler** [haifengl/smile#192]
I'm trying to use the classic iris data set to predict Species using Sepal Width, Sepal Length, Petal Length and Petal Width (all doubles).  I setup a NN with 4:5:3 layers.  Where the output layer maps to Setosa:0, Virginica:1, and Versicolor:2.  The NN always predicts a single output (no matter what options I chose). 

Please find the code/data/output attached.

[iris_nn_issue_files.zip](https://github.com/haifengl/smile/files/1078066/iris_nn_issue_files.zip)

**Comment by haifengl** [comment]
The data should be normalized first before feeding to neural network. Check our unit tests. We use iris there too.

**Comment by smutchler** [comment]
If you look at my output, I normalize the data upfront and use it both for training and scoring.  Something else I'm doing is wrong.  I'll try look at the unit tests.
One final note... It would be great if I could use MLP for regression also.
Smile is great by the way! Thanks for releasing it.

On Thursday, June 15, 2017, 9:53:06 AM MDT, Haifeng Li <notifications@github.com> wrote:


The data should be normalized first before feeding to neural network. Check our unit tests. We use iris there too.
