### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by defoye** [haifengl/smile#193]
Hi. I wonder if symbolic and numerical differentiation would be relevant/useful for this project or machine learning in general? I have a system that computes derivatives both symbolically and numerically. I would be glad to add it to this project.

**Comment by haifengl** [comment]
Absolutely!! Thank you very much for contributions!!! Can you please provide more information on your system? Would love to learn more and decide how and which module we can integrate your work.

**Comment by defoye** [comment]
That's wonderful!  I asked because it is a project I have not completely finished(doesn't derive and integrate _all_ expressions yet), but would be glad to develop into a finished product if it serves an awesome project like smile.

It is a relatively simple system, and I think my code is fairly understandable and adaptable.  Basically, it parses expressions, converts them into a tree with the shunting yard algorithm and applies differentiation rules at each level.  It can easily be expanded to include integration.

**Comment by defoye** [comment]
It reads a string and outputs a string.  It uses differentiation rules(product rule, quotient rule, chain rule)

**Comment by haifengl** [comment]
Cool. I will create a module and directory structure. You can import your code there.

**Comment by haifengl** [comment]
Beyond strings as input and output, we can create a DSEL in scala, which is more useful in a programmatic way.

**Comment by haifengl** [comment]
I add the 'symbolic' module. Please add your code there. Thanks a lot!
