### ISSUE TITLE
use plots in JavaFx application? 

### ISSUE THREAD

**Issue by lwhite1** [haifengl/smile#197]
Hi,
I've tried to display a SMILE histogram in a JavaFx application, using the Fx SwingNode as a wrapper. It does not seem to render. The SwingNode documentation says: 

> The content to be displayed is specified with the setContent(javax.swing.JComponent) method that accepts an instance of Swing JComponent. The hierarchy of components contained in the JComponent instance should not contain any heavyweight components, otherwise SwingNode may fail to paint it.

I can't find any definition of what a "heavyweight component" might be. Do you know of anyone who has been able to render SMILE plots in Fx successfully? Example code would be very helpful. 

thanks.

**Comment by haifengl** [comment]
I have not experience in this.

**Comment by haifengl** [comment]
Smile uses light weight component JPanel, Canvas, etc. It should not be a problem. Did you try to add a PlotCanvas or PlotPanel to SwingNode? I guess that you should add a PlotCanvas to SwingNode.

**Comment by lwhite1** [comment]
I tried to add a PlotCanvas. It could be I was doing something wrong at the
time.

**Comment by haifengl** [comment]
Does it work now?

**Comment by lwhite1** [comment]
I switched for my current project to a JavaScript plotting library.
