### ISSUE TITLE
Models are not serializable

### ISSUE THREAD

**Issue by nopper** [haifengl/smile#20]
Is there a way to save the trained models? It seems that all of the models do not support serialization at all.

**Comment by haifengl** [comment]
I use XStream (http://xstream.codehaus.org) for serialization of models. Can you have a try? Thanks!

**Comment by haifengl** [comment]
Previously, all models support Serializable interface. However, I remove them due to several concerns. For example, the exact format is hard to keep stable, class changes can easily make your serialized data unreadable, reading/writing the data in non-Java code is almost impossible. I am still looking for a simple and flexible solution. Currently, XStream seems good enough and your classes don't need implement any interfaces. In the future, I would like to support PMML for some models.

I am very open to this question and would like to listen all kinds of suggestions! Thanks!

**Comment by nopper** [comment]
Fair enough. Thanks for the suggestion ;) Really appreciated. I am gonna close the issue.

**Comment by haifengl** [comment]
Can you please reopen this ticket? I would like to listen to different voice. Hope more people will see this ticket. Thanks!

**Comment by haifengl** [comment]
Thanks!

**Comment by kid1412z** [comment]
Protostuff(https://code.google.com/p/protostuff/) or Hessian(http://hessian.caucho.com/doc/hessian-serialization.html)?  I use them to compress the loaded Objects in my LSH of SimHash version. It reduce the memory of old generation of jvm. In my case, the serialized objects of Protostuff are smaller.

**Comment by haifengl** [comment]
Thanks! I will check out them.

**Comment by haifengl** [comment]
Protostuff looks very good. But seems we need create schema for every model. A lof of work.

**Comment by kid1412z** [comment]
I think schema is used to keep compatible if the model has to be changed. 
Otherwise, runtime schema can be used and it doesn't need too much code as shown in the example code.

**Comment by haifengl** [comment]
Sounds great! Will learn more about it. If we choose it, would you like to work together on it? Thanks!

**Comment by kid1412z** [comment]
Of course  :)
2015-03-25 21:52 GMT+08:00 Haifeng Li <notifications@github.com>:

**Comment by haifengl** [comment]
With runtime schema, it seems that the usage of ProtoStuff is similar with XStream. I prefer not to modify the model object for specific serialization library. So it is better for the users to choose whatever they want. If we finally choose some serialization library, I still want to do it in a separate module and leave smile-core unchanged.

**Comment by haifengl** [comment]
A second thought: do we really need backward/forward compatibility? If the model member variables change, it usually means a serious change to the algorithm. It is better to retrain the model rather than importing the old model.

**Comment by haifengl** [comment]
Any comments (or complains) to my second thoughts? Thanks!
