### ISSUE TITLE
KPCA : java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#201]
This is the issue with KPCA.
Kernel Function: Gaussian Kernel 
 Number of Principal Components : 2
 Sigma: 2.5 
Threshold: 0.001

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at smile.math.Math.ax(Math.java:3746)
	at smile.projection.KPCA.<init>(KPCA.java:176)
	at com.baesystems.ai.analytics.smile.dimensionality.reduction.KernelPCA.reduce(KernelPCA.java:107)
	at com.baesystems.ai.analytics.smile.dimensionality.reduction.DimensionReductionFunction.execute(DimensionReductionFunction.java:89)
	at com.baesystems.ai.analytics.common.ModelingEngine.main(ModelingEngine.java:81)

**Comment by aminaaslam** [comment]
There is one comment that i forgot to add 
I have tried PPCA with all of my datasets and  it is working fine and not generating any errors. 
Size of datasetA:25000 instances.
Size of datasetB: 4500 instances.
Size of datasetC: 470000 instances.
I made sure there no duplicates in these datasets.
I am wondering why am i not seeing this issue(numeric instability) in PPCA?

**Comment by haifengl** [comment]
I have add initial support netlib.

Is it possible something wrong with your data? Things like NaN, Inf values?

**Comment by aminaaslam** [comment]
Hi hai, there are no NaN or Inf values in my dataset. I am attaching one of the datasets that i am using for your reference 
[card.csv.gz](https://github.com/haifengl/smile/files/1119790/card.csv.gz)

**Comment by haifengl** [comment]
Maybe you trigger some bug in smile. But you get errors with PCA, KPCA, IsoMap, LLE, etc., which actually uses different matrix decomposition algorithms (eigen value, singular value, and LU). Also no one else has ever met similar issues. I really suspect that there is something wrong in your data or preprocessing steps.

**Comment by haifengl** [comment]
Have you tried other ML software on your data?

**Comment by aminaaslam** [comment]
Hi hai, there are no NaN or Inf values in my dataset. I am attaching one of the datasets that i am using for your reference 
[card.csv.gz](https://github.com/haifengl/smile/files/1119790/card.csv.gz)

**Comment by haifengl** [comment]
Do you have very large values in your data? I have been very busy and don't have time to play with your data.

I am working on integrating netlib blas/lapack. It is a big change to my matrix library design. Need one or two more weeks.

**Comment by aminaaslam** [comment]
Hi Hai,  size of the dataset is 25000 records and it doesn't have large values. There are around 100 features in the dataset. 
Please let me know when you are finished redesigning you matrix library.
