### ISSUE TITLE
ArrayIndexOutOfBounds in DecisionTree.java - disable parallel processing?

### ISSUE THREAD

**Issue by olbapjose** [haifengl/smile#204]
Hi,

@haifengl I am calling method smile.classification.cart from Scala inside a call to Spark's mapPartitions. The method should run sequentially in an executor with a portion ("partition") of the data (no shared memory or anything similar). Do you see any issue with this? I am getting an ArrayIndexOutOfBoundsException in line 599 of DecisionTree.java. It seems that "i" (which are the values of order[j]) gets some value greater than the length of the samples array. All my columns are numeric.

Can you think of any "global state" that could be working bad? I guess there is some sort of multi-core parallel processing under the hood in Smile, maybe I just have to disable that option... Note that if I repeat the experiment without Spark with exactly the same portion of data that caused the exception (just calling Smile from a sequential Scala code) then everything works fine.

Thanks

**Comment by haifengl** [comment]
Smile uses multicores when possible. But Spark does that too. So there is some conflict. You can use the JVM flag -Dsmile.threads=1 to force smile to run in single thread.

**Comment by olbapjose** [comment]
Thanks so much. Tried this before my vacation :-) 
I noticed some change (it is actually faster!) but unfortunately it did not fix the problem. Is there anything else related to the parallel processing that can/should be disabled?
Thanks again

**Comment by haifengl** [comment]
Can you provide more information about the data, code snippets of calling smile, stack trace, etc? Thanks.

**Comment by olbapjose** [comment]
This is my stack trace (Smile version 1.3.1 but I am getting the same error with 1.4.0):

java.lang.ArrayIndexOutOfBoundsException: 4122
	at smile.classification.DecisionTree$TrainNode.findBestSplit(DecisionTree.java:599)
	at smile.classification.DecisionTree$TrainNode.findBestSplit(DecisionTree.java:531)
	at smile.classification.DecisionTree$TrainNode.split(DecisionTree.java:717)
	at smile.classification.DecisionTree.<init>(DecisionTree.java:987)
	at smile.classification.DecisionTree.<init>(DecisionTree.java:845)
	at smile.classification.Operators$$anonfun$cart$1.apply(Operators.scala:585)
	at smile.classification.Operators$$anonfun$cart$1.apply(Operators.scala:585)
	at smile.util.package$time$.apply(package.scala:49)
	at smile.classification.Operators$class.cart(Operators.scala:584)
	at smile.classification.package$.cart(package.scala:130)

I am calling it like this:

smile.classification.cart(fold1selectedFeatures, fold1labels, fold1data.length / 4, selectedAttributes)

where selectedAttributes is an Array[Attribute] in which every element has been created like NumericAttribute(s"v$attIndex") with increasing attIndex numbers (no repeated). The most strange thing, as I said, is that running this outside of Spark does not yield this error. The dataset used (fold1selectedFeatures together with the corresponding element from fold1labels at the end of each line) is attached (gzipped csv,  522 examples, 973 features plus the label column) 

[error_fold_data.txt.gz](https://github.com/haifengl/smile/files/1262839/error_fold_data.txt.gz)

Thanks

**Comment by olbapjose** [comment]
Any suggestion?

**Comment by haifengl** [comment]
Can you please provide complete code for me to reproduce? Thanks!
