### ISSUE TITLE
Platt Scaling class probability and prediction mismatch

### ISSUE THREAD

**Issue by digital-thinking** [haifengl/smile#205]
Hi!
I am using SVM with platt scaling for binary text classification (BagOfWord + HashingTrick) and found some examples, where the prediction is 1 and the probability for this class is ~0.14.

I know that in theory platt scaling can give different results to the SVM prediction, but this seems pretty huge for me. Sadly I can´t share the original code and data, but maybe you have a setup where, you can confirm my observation. 

Using smile-nlp version: 1.4.0

**Comment by haifengl** [comment]
Do you observe this on multiple datasets? Thanks!
