### ISSUE TITLE
SentenceSplitter deletes sentence on short abbreviations

### ISSUE THREAD

**Issue by hguhlich** [haifengl/smile#208]
The SimpleSentenceSplitter seems to delete sentences that end with a short abbreviation. In particular with abbreviations that end in a consonant. 

See example below:
```
import smile.nlp.tokenizer.SimpleSentenceSplitter

val sss = SimpleSentenceSplitter.getInstance()

sss.split("This is an nn. This is the next sentence.") // Array(This is the next sentence.)
sss.split("This is an nn. this is the next sentence.") // Array(This is an nn. this is the next sentence.)
sss.split("This is an na. This is the next sentence.") // Array(This is an na., This is the next sentence.)
```

**Comment by haifengl** [comment]
Thanks for the report. I will debug it.

**Comment by haifengl** [comment]
Case 1 is a bug, which I fixed now. Case 2 is not really a bug as we expect a sentence starting with capital. It is not perfect but a reasonable requirement for a rule-base system. Case 3 works because na is not an abbreviations in our dictionary.

**Comment by hguhlich** [comment]
Thanks! I added Case 2 and 3 just to show that in these cases the first sentence is not deleted.

**Comment by haifengl** [comment]
BTW, after the fix, the first case will still return only one sentence (but the whole string), which is expected by the rules.
