### ISSUE TITLE
clustering optics algorithm

### ISSUE THREAD

**Issue by haluk** [haifengl/smile#21]
Do you have plans to add OPTICS clustering algorithm feature along with its reachability plots?

**Comment by haifengl** [comment]
Do you mean this algorithm http://fogo.dbs.ifi.lmu.de/Publikationen/Papers/OPTICS.pdf? Thanks!

**Comment by haifengl** [comment]
Do you mean this algorithm http://fogo.dbs.ifi.lmu.de/Publikationen/Papers/OPTICS.pdf? Thanks!

**Comment by haifengl** [comment]
Do you mean this algorithm http://fogo.dbs.ifi.lmu.de/Publikationen/Papers/OPTICS.pdf? Thanks!

**Comment by haifengl** [comment]
Do you mean this algorithm http://fogo.dbs.ifi.lmu.de/Publikationen/Papers/OPTICS.pdf

 Thanks!

**Comment by haluk** [comment]
Yes, that one.

**Comment by haifengl** [comment]
I will investigate it. Why would you like it? Would you like to join the effort? Thanks!

**Comment by haluk** [comment]
Yes, I would like to.

**Comment by haifengl** [comment]
Thanks!

**Comment by haifengl** [comment]
Hi Haluk,

I have been too busy to work on this. Would you like to start this effort? Thank you very much in advance!

**Comment by haluk** [comment]
I would like to start. I first need to finalize some other work. I will start the implementation in a month.

--
HD

**Comment by haifengl** [comment]
Great! Thanks a lot!
