### ISSUE TITLE
How interpolate 6x6 cell?

### ISSUE THREAD

**Issue by sss989870** [haifengl/smile#210]
This demo source code is run 4x4 cell.

but i need change another number.

what should i change code?

**Comment by haifengl** [comment]
there is no difference between interpolate 4x4 and 6x6 (or any other data size). What exact problem do you have?

**Comment by sss989870** [comment]
double[] x1 = {0, 1, 2, 3};
        double[] x2 = {0, 1, 2, 3};
        double[][] y = {
                {1, 2, 4, 1},
                {6, 3, 5, 2},
                {4, 2, 1, 5},
                {5, 4, 2, 3}
        };

        PlotCanvas canvas = Heatmap.plot(y, Palette.jet(256));
        canvas.setTitle("Original");
        add(canvas);

        BicubicInterpolation bicubic = new BicubicInterpolation(x1, x2, y);
        double[][] yy = new double[101][101];
        for (int i = 0; i <= 100; i++)
            for (int j = 0; j <= 100; j++)
                yy[i][j] = bicubic.interpolate(i*0.03, j*0.03);

        canvas = Heatmap.plot(yy, Palette.jet(256));
        canvas.setTitle("Bicubic");
        add(canvas);

It's your demo code.
To change a 4x4 cell to a 6x6 cell.

i changed 

double[] x1 = {0, 1, 2, 3, 4, 5};
double[] x2 = {0, 1, 2, 3, 4, 5};
double[][] y = {
                {1, 2, 4, 1, 5, 6},
                {6, 3, 5, 2, 2, 4},
                {4, 2, 1, 5, 1, 1},
                {5, 4, 2, 3, 5, 2},
                {4, 2, 1, 5, 1, 1},
                {1, 2, 4, 1, 5, 6}
        };
but there is no change.

**Comment by sss989870** [comment]
hello?

**Comment by sss989870** [comment]
Oh, i changed 0.03 to 0.06, that's working.

for (int i = 0; i <= 100; i++)
        for (int j = 0; j <= 100; j++)
            yy[i][j] = bicubic.interpolate(i*0.03, j*0.03);

**Comment by haifengl** [comment]
What do you mean "there is no change"? Did you check the content of yy after interpolation? And you should change

```
yy[i][j] = bicubic.interpolate(i*0.03, j*0.03);
```

to 

```
yy[i][j] = bicubic.interpolate(i*0.05, j*0.05);
```

**Comment by haifengl** [comment]
0.03 (or 0.05) is the step of interpolation here? Note that we interpolate for 100 steps, so (5 - 0) / 100 = 0.05 for your new data.

**Comment by sss989870** [comment]
Thank you so much.

**Comment by sss989870** [comment]
if changed y array value changed,
should make new interpolation instance?
its using so much cpu..

**Comment by haifengl** [comment]
If y changes, the interpolation results should change of course. Bicubic interpolation is CPU intensive. If you have constraints on CPU resource, try other interpolation algorithms.

**Comment by sss989870** [comment]
In your experience, what algorithms are good for expressing pressure?

**Comment by haifengl** [comment]
It really depends on your problem/data. But in general, bicubic gives best results on regular grids in terms of quality. Try the demo program (type demo in the shell). There are examples on a variety of interpolation algorithms and see which one may fit your problem.

**Comment by sss989870** [comment]
Thank you so much 👍
