### ISSUE TITLE
Enhancement request: Implement XGBoost classification

### ISSUE THREAD

**Issue by lwhite1** [haifengl/smile#212]
Rumor has it that XGBoost is the new hotness in Kaggle competitions, outperforming the previously favored Random Forests.  I would like to enter some Kaggle competitions using Java, Tablesaw, and Smile and perform competitively.

**Comment by haifengl** [comment]
Xgboost is a library in c++. What do you mean "implement it"?

**Comment by lwhite1** [comment]
Sorry for my ignorance. I assume then that it is doing standard gradient
boosting, and its popularity is a result of good performance?

**Comment by haifengl** [comment]
My understanding is that it's main selling point is the high performance. We support gradient boosting too besides random forest and AdaBoost. And our performance is excellent too.

**Comment by lwhite1** [comment]
Sounds good. Thanks very much Haifeng. Closing
