### ISSUE TITLE
Lack documentation about setting column labels for prediction and training

### ISSUE THREAD

**Issue by arun-taiger** [haifengl/smile#213]
A CSV file consists of the following  format, which updated dynamically 

Vendor,MYCT,MMIN,MMAX,CACH,CHMIN,CHMAX,Performance
amdahl,23,16000,64000,64,16,32,749
amdahl,23,32000,64000,128,32,64,1238
apollo,400,1000,3000,0,1,2,23
apollo,400,512,3500,4,1,6,24
basf,60,2000,8000,65,1,8,70
basf,50,4000,16000,65,1,8,117
bti,350,64,64,0,1,4,15 

We need to train a system that predicts the Vendor. Currently, it is not possible to set the field that we need to predict using  DelimitedTextParser. 

There are two issues one is about reading a dynamically updating CSV file and the second issue is setting the column label that we need to predict. 

There is no Java based example on setting column  like in the case of ArffParser

arffParser.setResponseIndex(4);

We need an example that explains how to use DelimitedTextParser and set column labels for prediction, if the class labels are strings as in the above case.

**Comment by haifengl** [comment]
See an example at line 68 here:

https://github.com/haifengl/smile/blob/master/demo/src/main/java/smile/demo/classification/ClassificationDemo.java

I will update the documents on this. Thanks!

**Comment by haifengl** [comment]
Our README actually have example on this use case in the tutorial part.
