### ISSUE TITLE
Weight-normalized Complement Naive Bayes (WCNB) implementation 

### ISSUE THREAD

**Issue by arun-taiger** [haifengl/smile#214]
For text classification applications, Naive Bayes algorithm produces good results. However, the independence assumption creates problems.   Weight-normalized Complement Naive Bayes provides a clean solution to deal with independence assumption problem.  Using this implementation,  smile could provide a good baseline for text classification problems.  
This is  the relevant paper: 
Rennie, Jason D., et al. "Tackling the poor assumptions of naive Bayes text classifiers." Proceedings of the 20th International Conference on Machine Learning (ICML-03). 2003.

**Comment by haifengl** [comment]
added in v2.
