### ISSUE TITLE
Build failure on systems with SBT 1.0.0

### ISSUE THREAD

**Issue by pfcoperez** [haifengl/smile#216]
The project seems to require SBT 0.13.x, however, that is not set in the project properties file `project/build.properties`.

The problem is that SBT will use the version installed in the system which, for most updated Linux distributions, is already 1.0.0. SBT 1.0.0 is not compatible with the project plugins versions so either these versions get a bump or SBT 0.13.X should be used.

The PR https://github.com/haifengl/smile/pull/215 fixes the SBT version for the project fixing compilation problems in updated systems and allowing future versions upgrades.

**Comment by haifengl** [comment]
Thanks! The plugins are still with 0.13 series.
