### ISSUE TITLE
Allow for arbitrary column to contain row names/IDs

### ISSUE THREAD

**Issue by DewaldDeJager** [haifengl/smile#217]
This is specific to the `DelimitedTextParser` and it's `hasRowNames` attribute. Currently the class accepts a boolean to indicate whether the first column contains row IDs. It may be useful to accept an integer instead and have this indicate the column index of the column containing the row IDs (Similar to response index). This would purely be for convenience and may avoid some preprocessing.

**Comment by haifengl** [comment]
In v2, we support DataFrame, which may include a column as row name. When fitting a model, use Formula to select variables for fitting.
