### ISSUE TITLE
RandomForest ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by erdos** [haifengl/smile#22]
Calling the constructor of `smile.regression.RandomForest` with numeric and nominal attribute types mixed, I get the following exception (randomly).

`ArrayIndexOutOfBoundsException 3 smile.regression.RegressionTree$TrainNode.findBestSplit (RegressionTree.java:484)`

I do not get exception with only numeric attributes.

**Comment by erdos** [comment]
I see that `Attribute.valueOf` must be used to convert string to double. Sorry for bothering you. Also, thank you for your wonderful library.

**Comment by haifengl** [comment]
I will update the wiki for this. Thanks!
