### ISSUE TITLE
Simple method of creating ConfusionMatrix

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#221]
I see that [Smile has a ConfusionMatrix class](https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/validation/ConfusionMatrix.java), but I don't see it used or documented anywhere. It would be nice if there were a method I could call to create a ConfusionMatrix given a model and a test/validation set and an example of using it in the documentation

**Comment by haifengl** [comment]
In the Scala api smile.validation, we have test(), test2(), test2soft(), cv(), loocv(), where I print out confusion matrix. It will be available in the next release.

**Comment by benmccann** [comment]
That's great. Thank you!

Would it be possible to make it available in the Java API as well?

**Comment by haifengl** [comment]
These model validation methods are supposed to be used in the shell and scala is a great language for this purpose. I have no plan to support them in Java.

**Comment by benmccann** [comment]
I actually wanted them to use in the shell in Java. There's a great shell for Java called BeakerX: https://github.com/twosigma/beakerx

**Comment by haifengl** [comment]
As a functional language, scala is way better than Java for scripting. And we make most of our scala API compatible with matlab and R. It is really easy to learn our scala API.

But I will look into the Java shell. The big question is that Java 9 will have built in shell. Is this one compatible with Java 9?

**Comment by benmccann** [comment]
We should wait to test BeakerX until 0.3 is released later this week. I will post an example after the release

**Comment by haifengl** [comment]
Well, it is a notebook, not a shell. It is very interesting though. Surely it is nice to enable smile in Jupyter + BeakerX although I still strongly suggest Scala over Java in a notebook.

**Comment by benmccann** [comment]
I've been playing with BeakerX Java notebooks quite a bit. It's very fun

Here's an example of a Groovy notebook using the tablesaw-smile library: https://github.com/twosigma/beakerx/blob/master/doc/groovy/Tablesaw.ipynb

I would really love it if we were able to use a `ConfusionMatrix` in Java notebooks

**Comment by haifengl** [comment]
Java can call scala methods directly. just google how to do it.
