### ISSUE TITLE
Get current neuron weights from a neural network?

### ISSUE THREAD

**Issue by ejberry** [haifengl/smile#223]
Would it be feasible to add a method to get the current weights for a neuron in the NeuralNetwork class? Such information is required for the implementation of [NNPID algorithms](http://research.ijcaonline.org/iciiioes/number9/iciiioes1651.pdf) and other similar control sytems.

**Comment by haifengl** [comment]
Sure thing.

**Comment by haifengl** [comment]
I add "getWeight(int)" to return the weights of a layer. 0 for input layer.
