### ISSUE TITLE
SVM: IllegalArgumentException when using binary SVM to predict with LinearKernel

### ISSUE THREAD

**Issue by mgiannini** [haifengl/smile#224]
I am getting an IllegalArgumentException when I attempt to train a binary SVM using a LinearKernel. The following test method reproduces the error:

```java
    @Test
    public void testFoo()
    {
        SVM<double[]> svm = new SVM<>(new LinearKernel(), 10.0);
        svm.learn(new double[] { 3, 0, 0, 0,}, 1);
        svm.learn(new double[] { 1, 0, 1, 0,}, 1);
        svm.learn(new double[] { 0, 2, 0, 0,}, 0);
        svm.learn(new double[] { 0, 1, 0, 0,}, 0);
        svm.learn(new double[] { 0, 0, 1, 0,}, 1);
        svm.learn(new double[] { 0, 0, 0, 3,}, 0);
        svm.finish();
        int p = svm.predict(new double[] { 0 ,0, 0, 1}); // This line throws exception
        System.out.println(p);
    }
```

Here is the exception I get:

```
java.lang.IllegalArgumentException: Arrays have different length.

	at smile.math.Math.dot(Math.java:2407)
	at smile.classification.SVM$LASVM.predict(SVM.java:522)
	at smile.classification.SVM.predict(SVM.java:1424)
	at smile.classification.SVMTest.testFoo(SVMTest.java:71)
```

I am using smile 1.4.0

**Comment by haifengl** [comment]
Please do this way:

```
svm.learn(new double[][]{
                {3, 0, 0, 0},
                {1, 0, 1, 0},
                {0, 2, 0, 0},
                {0, 1, 0, 0},
                {0, 0, 1, 0},
                {0, 0, 0, 3}
            },
                new int[] {1, 1, 0, 0, 1, 0}
        );
        svm.finish();
```
Although SVM support online learning, it is recommended that the initial model should be learned in a batch way. You can use online learning to update the model later.

**Comment by mgiannini** [comment]
I submitted a pull request that will fix this #225. I am using the SVM class behind another api which allows users to train models one instance at a time. So it is not practical in my use case to have all the training data available at once to initially learn the model.

**Comment by haifengl** [comment]
I added some safe guard so that your code can run without problems. But it is still recommended to train the initial model with a set of data. There are some extra optimization.

**Comment by haifengl** [comment]
Thanks! Your change is okay but a little bit too much overhead. It is only necessary in the finish() function. See my latest commit.

**Comment by mgiannini** [comment]
Thanks for fixing!
