### ISSUE TITLE
NumericAttributeFeature returning 0 Attribute

### ISSUE THREAD

**Issue by yeahia2508** [haifengl/smile#226]
numericAttributereFeature.attributes() always returning 0;
Here is my Code: 

       DelimitedTextParser parser = new DelimitedTextParser();
        parser.setDelimiter(",");
        parser.setColumnNames(true);

        Attribute[] attributes = new Attribute[2];

        attributes[0] = new NominalAttribute("Postition");
        attributes[1] = new NominalAttribute("Level");

        parser.setResponseIndex(new NumericAttribute("Salary"), 2);

        AttributeDataset usps = parser.parse(attributes, new File("/home/y34h1a/test/Position_Salaries.csv"));
        double[][] x = usps.toArray(new double[usps.size()][]);
        //        double[] y = usps.toArray(new double[usps.size()]);

        NumericAttributeFeature numericAttributeFeature = new NumericAttributeFeature(usps.attributes(),
                NumericAttributeFeature.Scaling.NORMALIZATION,x);

        Attribute[] att = numericAttributeFeature.attributes();

        for (int i = 0; i < x.length; i++) {
            double[] y = new double[att.length];
            for (int j = 0; j < y.length; j++) {
                y[j] = numericAttributeFeature.f(x[i], j);
            }
        }

Dataset :

Position                   level        Salary
Business Analyst       1           45000
Junior Consultant      2           50000
Senior Consultant     3           60000
Manager                    4          80000
Country Manager      5          11000

**Comment by haifengl** [comment]
I don't see the delimiter "," in your data. That is the problem.

**Comment by yeahia2508** [comment]
Its a csv file. if I delete delimiter then ParseException: 1column,eexcepted 3 occurring.  Only NumericAttributeFeature giving 0 attribute. AttributeDataset giving 3 attribute.

**Comment by haifengl** [comment]
So, the parsing is okay but the output of NumericAttributeFeature is wrong?

**Comment by yeahia2508** [comment]
yes. NumericAttributeFeature is wrong. all time giving 0 attribute.

**Comment by yeahia2508** [comment]
I want to do scale dataset to fit in svr

**Comment by haifengl** [comment]
For which column? And it is better to provide a file for us to debug. Thanks!

**Comment by yeahia2508** [comment]
I want to scale all column. Here is my  data file. Thanks.
[Position_Salaries.csv.zip](https://github.com/haifengl/smile/files/1288214/Position_Salaries.csv.zip)

**Comment by haifengl** [comment]
Position and level should NOT be normalized as they are nominal attributes. My question was which column generates all 0 output.

**Comment by yeahia2508** [comment]
numericAttributeFeature.attributes() giving 0, not column. 
this line line causing problem.
`Attribute[] att = numericAttributeFeature.attributes(); //att.length = 0`

**Comment by haifengl** [comment]
Haha, it is clear now. You better say that "numericAttributeFeature.attributes() returns empty array".

And it is not a bug. First of all, you have only three columns and by your configuration, two of them are part of x as nominal attributes, and the third one is numeric as the response variable.

```
 double[][] x = usps.toArray(new double[usps.size()][]);
```
Check the x, it has only two columns. And you should check 
```
usps.attributes()
```
which returns only two attributes too and they are nominal.

As I said before, NumericAttributeFeature is only for numeric attribute (by its name) and ignores the nominal attributes. Of course, att.length is zero.

**Comment by yeahia2508** [comment]
my depedent data is numeric (Salary). How to scale this. it is double[] array. but NumericAttribute only receive double[][] data. please give just a little example. Thank you very much.

**Comment by haifengl** [comment]
smile.math.Math has several functions such as unitize, normalize, standardize.

**Comment by yeahia2508** [comment]
Thank you very much.
