### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by Malkitti** [haifengl/smile#227]
While   running SparseMatrixPlotDemo extends JPanel  class
an error!

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by haifengl** [comment]
It is a warning, not an error. When there is no logger binding, everything is fine. There is no log output. That is it.

How do you run this demo code? Your project misses a slf4j binding dependency.

Btw, try "demo" in the shell. You will have a window for all demos and the logger is bonded too.

**Comment by Malkitti** [comment]
I clone  the library and  executing  the Java code one by one.
