### ISSUE TITLE
Predicting  Class Labels Instead of Numbers.

### ISSUE THREAD

**Issue by Malkitti** [haifengl/smile#228]
I have a  CSV data set  has following form.   
(Name, age, Salary,  class).  I use  SMILE random forest algorithm to  train the system my problem is  in the case of prediction it does´t produce  class labels instead of that  it gives numbers.  Is there any way to map the class labels to the numbers  and vice versa ?

## Code snippet
public void trainExample() {
        System.out.println("Myexample");
        DelimitedTextParser parser = new DelimitedTextParser();
        parser.setResponseIndex(new NominalAttribute("class"), 0);
        try {
            AttributeDataset train = parser.parse("USPS Train", smile.data.parser.IOUtils.getTestDataFile("usps/zip.train"));
            AttributeDataset test = parser.parse("USPS Test", smile.data.parser.IOUtils.getTestDataFile("usps/zip.test"));

            double[][] x = train.toArray(new double[train.size()][]);
            int[] y = train.toArray(new int[train.size()]);
          
            
            RandomForest forest = new RandomForest(x, y, 200);
ObjectOutputStream oos = new ObjectOutputStream( 
                      
                               new FileOutputStream(new File("model.model")));

oos.writeObject( forest );
}

public void  Predict() {
  double[][] testx = test.toArray(new double[test.size()][]);
            int[] testy = test.toArray(new int[test.size()]);
  
            for (int i = 0; i < testx.length; i++) {
                if (forest.predict(testx[i]) != testy[i]) {
                    error++;
                }
}

## Input data

Name, age, Salary,  class
Abc, 12, 300, A
CDE, 12, 499, C
EFG, 12, 456,  D

For instance, a  label indexer that maps a string column of labels to an ML column of label indices. If the input column is numeric,  cast it to string and index the string values. The indices are in [0, numLabels), ordered by label frequencies. So the most frequent label gets index 0. And vice versa.

**Comment by haifengl** [comment]
All class labels are translated into numbers first. The output is a number. You can convert the number to a string by

```
train.response().toString(y)
```

Here `train` is the AttributeDataset returned by the parser. `y` is the predicted value.
