### ISSUE TITLE
How do I use the library in intellij. 

### ISSUE THREAD

**Issue by andrewcz** [haifengl/smile#229]
I am just trying to input the library in intellij and compile some of the classes.what would be the easiest way to do this. Linux mint jdk 1.8 just using the demo classes.
Best,
Andrew

**Comment by haifengl** [comment]
If you want to use the library in your own project, please just add the library as a dependency. The project readme has instructions how to do it with maven or sbt.

If you want build smile in intellij, just install sbt plugin for intellij and then import the project into intellij (File -> Import), which is simple and straightforward.

**Comment by andrewcz** [comment]
Hi!
cheers for the reply.
so i have tried to run SmileDemo.java and got the following in the intellij ide.
Would you be able to advise next steps?
Many thanks for your reply.
Best,
Andrew


Information:Using javac 1.8.0_91 to compile java sources
Information:java: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Information:java: Errors occurred while compiling module 'demo'
Information:9/17/17 9:49 PM - Compilation completed with 100 errors and 0 warnings in 5s 844ms
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/stat/distribution/GeometricDistributionDemo.java
Error:(33, 18) java: package smile.plot does not exist
Error:(34, 18) java: package smile.plot does not exist
Error:(35, 18) java: package smile.plot does not exist
Error:(36, 31) java: package smile.stat.distribution does not exist
Error:(46, 13) java: cannot find symbol
  symbol:   class PlotCanvas
  location: class smile.demo.stat.distribution.GeometricDistributionDemo
Error:(47, 13) java: cannot find symbol
  symbol:   class PlotCanvas
  location: class smile.demo.stat.distribution.GeometricDistributionDemo
Error:(48, 13) java: cannot find symbol
  symbol:   class PlotCanvas
  location: class smile.demo.stat.distribution.GeometricDistributionDemo
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/wavelet/CoifletWaveletDemo.java
Error:(25, 18) java: package smile.plot does not exist
Error:(26, 18) java: package smile.plot does not exist
Error:(27, 21) java: package smile.wavelet does not exist
Error:(28, 21) java: package smile.wavelet does not exist
Error:(29, 21) java: package smile.wavelet does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/wavelet/SymletWaveletDemo.java
Error:(25, 18) java: package smile.plot does not exist
Error:(26, 18) java: package smile.plot does not exist
Error:(27, 21) java: package smile.wavelet does not exist
Error:(28, 21) java: package smile.wavelet does not exist
Error:(29, 21) java: package smile.wavelet does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/classification/RDADemo.java
Error:(26, 28) java: package smile.classification does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/classification/ClassificationDemo.java
Error:(33, 18) java: package smile.data does not exist
Error:(34, 18) java: package smile.data does not exist
Error:(35, 25) java: package smile.data.parser does not exist
Error:(36, 18) java: package smile.plot does not exist
Error:(37, 18) java: package smile.plot does not exist
Error:(38, 18) java: package smile.plot does not exist
Error:(39, 18) java: package smile.plot does not exist
Error:(54, 12) java: cannot find symbol
  symbol:   class AttributeDataset
  location: class smile.demo.classification.ClassificationDemo
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/plot/GridDemo.java
Error:(24, 18) java: package smile.plot does not exist
Error:(25, 18) java: package smile.plot does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/classification/LDADemo.java
Error:(23, 28) java: package smile.classification does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/wavelet/HaarWaveletDemo.java
Error:(25, 18) java: package smile.plot does not exist
Error:(26, 18) java: package smile.plot does not exist
Error:(27, 21) java: package smile.wavelet does not exist
Error:(28, 21) java: package smile.wavelet does not exist
Error:(29, 21) java: package smile.wavelet does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/plot/LinePlotDemo.java
Error:(25, 18) java: package smile.plot does not exist
Error:(26, 18) java: package smile.plot does not exist
Error:(27, 18) java: package smile.plot does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/manifold/ManifoldDemo.java
Error:(32, 18) java: package smile.data does not exist
Error:(33, 25) java: package smile.data.parser does not exist
Error:(49, 12) java: cannot find symbol
  symbol:   class AttributeDataset
  location: class smile.demo.manifold.ManifoldDemo
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/classification/KNNDemo.java
Error:(26, 28) java: package smile.classification does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/plot/StaircasePlotDemo.java
Error:(24, 18) java: package smile.plot does not exist
Error:(25, 18) java: package smile.plot does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/projection/PCADemo.java
Error:(28, 18) java: package smile.plot does not exist
Error:(29, 18) java: package smile.plot does not exist
Error:(30, 24) java: package smile.projection does not exist
Error:(31, 18) java: package smile.math does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/projection/ProjectionDemo.java
Error:(31, 18) java: package smile.data does not exist
Error:(32, 18) java: package smile.data does not exist
Error:(33, 25) java: package smile.data.parser does not exist
Error:(51, 22) java: cannot find symbol
  symbol:   class AttributeDataset
  location: class smile.demo.projection.ProjectionDemo
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/stat/distribution/GaussianMixtureDemo.java
Error:(25, 18) java: package smile.math does not exist
Error:(26, 18) java: package smile.plot does not exist
Error:(27, 18) java: package smile.plot does not exist
Error:(28, 18) java: package smile.plot does not exist
Error:(29, 31) java: package smile.stat.distribution does not exist
Error:(30, 31) java: package smile.stat.distribution does not exist
Error:(31, 31) java: package smile.stat.distribution does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/plot/ScatterPlotDemo.java
Error:(25, 18) java: package smile.plot does not exist
Error:(26, 18) java: package smile.plot does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/interpolation/LaplaceInterpolationDemo.java
Error:(25, 27) java: package smile.interpolation does not exist
Error:(26, 27) java: package smile.interpolation does not exist
Error:(27, 18) java: package smile.plot does not exist
Error:(28, 18) java: package smile.plot does not exist
Error:(29, 18) java: package smile.plot does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/clustering/MECDemo.java
Error:(27, 18) java: package smile.plot does not exist
Error:(28, 18) java: package smile.plot does not exist
Error:(29, 24) java: package smile.clustering does not exist
Error:(30, 27) java: package smile.math.distance does not exist
Error:(31, 18) java: package smile.plot does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/clustering/ClusteringDemo.java
Error:(34, 18) java: package smile.data does not exist
Error:(35, 25) java: package smile.data.parser does not exist
Error:(36, 18) java: package smile.plot does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/stat/distribution/EmpiricalDistributionDemo.java
Error:(25, 18) java: package smile.plot does not exist
Error:(26, 18) java: package smile.plot does not exist
Error:(27, 18) java: package smile.plot does not exist
Error:(28, 31) java: package smile.stat.distribution does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/stat/distribution/MultivariateGaussianDistributionDemo.java
Error:(30, 18) java: package smile.plot does not exist
Error:(31, 18) java: package smile.math does not exist
Error:(32, 18) java: package smile.plot does not exist
Error:(33, 31) java: package smile.stat.distribution does not exist
Error:(42, 13) java: cannot find symbol
  symbol:   class PlotCanvas
  location: class smile.demo.stat.distribution.MultivariateGaussianDistributionDemo
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/stat/distribution/ChiSquareDistributionDemo.java
Error:(33, 18) java: package smile.plot does not exist
Error:(34, 18) java: package smile.plot does not exist
Error:(35, 18) java: package smile.plot does not exist
Error:(36, 18) java: package smile.plot does not exist
Error:(37, 18) java: package smile.plot does not exist
Error:(38, 31) java: package smile.stat.distribution does not exist
Error:(48, 13) java: cannot find symbol
  symbol:   class PlotCanvas
  location: class smile.demo.stat.distribution.ChiSquareDistributionDemo
Error:(49, 13) java: cannot find symbol
  symbol:   class PlotCanvas
  location: class smile.demo.stat.distribution.ChiSquareDistributionDemo
Error:(50, 13) java: cannot find symbol
  symbol:   class PlotCanvas
  location: class smile.demo.stat.distribution.ChiSquareDistributionDemo
Error:(51, 13) java: cannot find symbol
  symbol:   class PlotCanvas
  location: class smile.demo.stat.distribution.ChiSquareDistributionDemo
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/clustering/NeuralGasDemo.java
Error:(24, 16) java: package smile.vq does not exist
Error:(25, 18) java: package smile.plot does not exist
Error:(26, 18) java: package smile.plot does not exist
Error:(27, 18) java: package smile.plot does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/classification/NeuralNetworkDemo.java
Error:(26, 28) java: package smile.classification does not exist
Error:(27, 18) java: package smile.math does not exist
/home/andrewcz/Desktop/Java/smile/demo/src/main/java/smile/demo/projection/PPCADemo.java
Error:(25, 18) java: package smile.plot does not exist
Error:(26, 18) java: package smile.plot does not exist

**Comment by haifengl** [comment]
You miss other modules. You should import the whole smile project into IntelliJ, not just some of its subdirectories. Btw, you can run the demo from the shell if you download the prepackaged binary.
