### ISSUE TITLE
Is there a GridSearch or something to programmatically optimize classifier's parameters?

### ISSUE THREAD

**Issue by owlmsj** [haifengl/smile#23]
I am looking for optimize an online classifier. Is there some example?

Thanks!

**Comment by haifengl** [comment]
Do mean searching the optimal hyper parameter by stepping through an interval? We don't have that.

**Comment by owlmsj** [comment]
Yes. Okay!

**Comment by haifengl** [comment]
With Java 8 or Scala, it should be quite easy to do things like that. Libsvm has a little tool in python for that purpose.

**Comment by owlmsj** [comment]
I know. This is not an issue, just a question! Closing...
