### ISSUE TITLE
Does DBSCAN in SMILE use indexing so is o(nlogn) or does it calculate all the distance naively?

### ISSUE THREAD

**Issue by yxchng** [haifengl/smile#232]
Does DBSCAN in SMILE use indexing so is o(nlogn) or does it calculate all the distance naively?

**Comment by haifengl** [comment]
Our implementation works on the generic data type. Depending on the data type, it may or may not use advanced nearest neighbor search algorithm. And we give the user option of customized nearest neighbor data structure in the constructor. Check out smile.neighbor package for available data structures.

**Comment by harry-2016** [comment]
Does DBSCAN works well for large volume of data. say some 30k rows with 6-8 columns.
How long will it take to complete.?

**Comment by haifengl** [comment]
30k is not big. With 6-8 columns, you can use KDTree for nearest neighbor search.

**Comment by harry-2016** [comment]
nope getting out of memory for even 16gb ..
any help is appreciated..

thanks in advance

**Comment by haifengl** [comment]
How do you call it?

**Comment by harry-2016** [comment]
[image: Screen Shot 2018-03-13 at 10.13.35 AM.png]

**Comment by harry-2016** [comment]
For 20k how much i have to give as heap size. Because 10GB is not enough
for 20k rows.
For 10k rows its working perfectly fine.
PFA..
Look at the old gc

[image: Screen Shot 2018-03-13 at 12.38.04 PM.png]
