### ISSUE TITLE
HierarchicalClustering Exception

### ISSUE THREAD

**Issue by asmirn1** [haifengl/smile#233]
For proximity matrix
> [[0.0, 0.001]]
> [[0.001, 0.0]]

the code `new HierarchicalClustering(new CompleteLinkage(proximity)).partition(1.0)` raises an exception

> The parameter h is too large

Should it just return one cluster without an exception?

**Comment by haifengl** [comment]
There are two partition() methods. paritition(double) cut the tree by the hight. This requires the caller has some knowledge how trees are merged, which you can get some feeling by plotting the tree out.

parition(int) simply cut the tree into n groups. 

This is not a bug. As the exception indicate, it is an invalid parameter.

**Comment by asmirn1** [comment]
I see your point. However, a clustering result with only one cluster isn't invalid in my opinion, while the code is raising an exception in this case and I have to additionally process it.

But I agree in that it's not a bug.

**Comment by haifengl** [comment]
Btw, the height is based on the cluster distance, not the discrete values of layers.

**Comment by asmirn1** [comment]
Not sure, what do you mean by "discrete values of layers." Also, if I use complete linkage, what would be the minimum and maximum valid h-parameter?

**Comment by haifengl** [comment]
The height doesn't mean which layer to cut the tree. The height is about the linkage when merging two sub trees. The value depends on the data and I cannot tell you the min and max. Plot the tree, we drew the tree merge point based on the height.

**Comment by asmirn1** [comment]
Well, I'm trying to cluster hundreds of small datasets, so plotting the tree for each one of them is not an option. Moreover, users that may use my program would have no idea about the hierarchical clustering. 

I understand that it is hard to find min and max since it depends on the linkage and the data. That's why I prefer any value from interval (0, +infinity) to be valid for h-parameter.

But, it's just my opinion. I'm catching the exception now, and it seems to work fine for now.

**Comment by haifengl** [comment]
Why don't you specify an integer k, the number of clusters?

**Comment by asmirn1** [comment]
Because I don't know the number of clusters beforehand. I may have only one cluster or many clusters for different datasets.

**Comment by haifengl** [comment]
If your goal is partition, you can try several methods that automatically discover the number of clusters. For example, x-means, g-means, minimum entropy, dbscan, etc.

**Comment by asmirn1** [comment]
Thank you for the suggestions! I might try them. I chose hierarchical clustering because I can approximately estimate the diameter of each cluster and this diameter stays the same for all datasets. That's why I use the hierarchical clustering with the complete linkage.
