### ISSUE TITLE
Is there a way to plot a model

### ISSUE THREAD

**Issue by medke** [haifengl/smile#234]
I created and trained an SVM model as described in the tutorial. Now I want to plot this model, is there a way to do that in Java.

I saw SVM plot in the Demo library, but there is no example showing how to get there. I saw here in the issues people use plot canvas and send the coordinates, but I was wondering whether we can plot the trained model directly. I would appreciate a code example.

**Comment by haifengl** [comment]
Only if your data is 2 dimensional, you can plot it like the demo.

There is no function to do it directly. Check out smile.demo.classification.ClassifictionDemo for sample code.

**Comment by haifengl** [comment]
If you use Scala, there is a function for this purpose. For example,

```
plot(x, y, knn(x, y, 3))
```

**Comment by medke** [comment]
No unfortunately I am using Java.

**Comment by haifengl** [comment]
See https://github.com/haifengl/smile/blob/master/demo/src/main/java/smile/demo/classification/ClassificationDemo.java#L151

for java example.

But you should be able to call a scala function in Java too. add smile-scala_2.11 to your dependency and give it a try first.
