### ISSUE TITLE
Multi-class classification measures

### ISSUE THREAD

**Issue by vagmcs** [haifengl/smile#235]
## Expected behaviour

Given a vector/array holding the predicted values of a classifier and a vector/array holding the actual truth values, the classification measures, such as precision, recall, f-measure etc., should correctly identify if the problem is binary or multi-class classification and calculate each measure appropriately.

In issue #32 a confusion matrix was merged into the project, but the matrix is currently not used by the classification measures. Is someone working on this? If not I could try and push a fix for all classification measures.  If this feature is not desirable for some reason, I think an appropriate message should be shown to the users notifying them for this behaviour. Another solution is to rename the measures to BinaryPrecision, BinaryRecall, etc.

## Actual behaviour

Given the following input data:

```java
int[] prediction = { 0, 1, 0, 0, 2, 0, 3, 1, 3, 3 };
int[] truth = { 0, 1, 1, 0, 2, 0, 2, 0, 3, 3 };
```
Classification measures consider only label 1 as the positive class.

## Information

- Java 1.8 and Scala 2.11
- Smile version 1.4.0
- Debian 9.1

**Comment by haifengl** [comment]
recall, precision, f-measures should be applied only to binary classification. We may raise exceptions if we see values other than 0 or 1.

**Comment by vagmcs** [comment]
OK, but I think it would be very useful to have some extension for these measures in the multi-class case. Otherwise each user should write its own function for each measure using the confusion matrix.

**Comment by haifengl** [comment]
By definition, they are defined for binary cases. Anyone can create extension but no one with agree with each other.

**Comment by haifengl** [comment]
I add safe guard to these measures. We accept only 0 or 1 now and raise exceptions in case that people misuse them.

In scala api, we have multiple functions test(), test2(), test2soft(), cv(), loocv(), boostrap() that train and test a classifier and reports meaningful measures and confusion matrix.

Thanks!
