### ISSUE TITLE
How to train new data for DecisionTree or LogisticRegression trained models

### ISSUE THREAD

**Issue by SonnyBao** [haifengl/smile#238]
Dear Authors,

Thank you very much for sharing this powerful framework.
I'm studying some classification models, starting with DecisionTree and LogisticRegression.
I'm wondering if those trained models allow to continue train or learn new data?

Lets say we have trained data as below:
@data
sunny,hot,high,FALSE,no
sunny,hot,high,TRUE,no

I trained the model with below code using Java:
Classifier model = new DecisionTree(weather.attributes(), x, y, 5);

Then I save/load the trained model.
How can I continue to train new data after loading?
Example new data: sunny,hot,normal,FALSE,yes

Thanks.
-Sonny

**Comment by haifengl** [comment]
What you look for is called online learning. Not all algorithms support online learning. If a classification class implements OnlineClassifier, it has a method learn(double[]) that takes a new sample. But the two algorithms you mentioned don't support this feature.

**Comment by SonnyBao** [comment]
Thanks for your explanation. Is there any chance to support this feature for those algorithms in near future?
Thanks.

**Comment by haifengl** [comment]
They are batch learning algorithms. I don't think that you can make them online learning.

**Comment by csalperwyck** [comment]
If you are interested in such tools, you can have a look at MOA:
https://moa.cms.waikato.ac.nz/

There is an online tree such as Hoeffding Tree, but it needs lots of data
to have good performances.

2017-10-18 15:07 GMT+02:00 Haifeng Li <notifications@github.com>:

**Comment by haifengl** [comment]
Interesting. Thanks.

**Comment by SonnyBao** [comment]
Thank you all.

**Comment by divyansh1329** [comment]
How to Save/Load trained models as @SonnyBao  mentioned in the question ? I want to train the model once and use it for predicting multiple times later.

**Comment by SonnyBao** [comment]
@divyansh1329: I followed this issue here to save/load the trained model: https://github.com/haifengl/smile/issues/135
Basically, when loading using Java's ObjectInputStream, you can directly cast the loaded object to the model type that you trained before.

**Comment by SaiprasadKrishnamurthy** [comment]
Hi, I'm trying to serialize the RandomForest class and I'm able to do so successfully. I'm intending to use this instance to call predict multiple times. I'd like to understand how can I create the input values for double[] x. Any pointers?

**Comment by haifengl** [comment]
See http://haifengl.github.io/smile/data.html how the data be handled.
