### ISSUE TITLE
DenseMatrix.eigen(k) sometimes returns an eigenvector with n < k

### ISSUE THREAD

**Issue by CBrophy** [haifengl/smile#243]
Apparent violation of the function interface is causing ArrayIndexOutOfBounds exceptions elsewhere, such as MDS() line 187 which assumes that eigen(2) will, in fact, return a vector with 2 elements. See test code and analysis below.

```
 @Test
  public void testSymmetricEigen(){

    DenseMatrix B = DenseMatrix.zeros(5000, 5000);

    for(int rowIndex = 0; rowIndex < 5000; rowIndex++){
      for(int colIndex = 0; colIndex < 5000; colIndex++){
        B.set(rowIndex, colIndex, 0.0071);
      }
    }

    B.setSymmetric(true);

    EVD eigen = B.eigen(2);

    assertEquals(2, eigen.getEigenValues().length); // Fails because length == 1
  }
```
The issue appears to be rooted with line 360 in Lanczos.startv function, which is zeroing out at small numbers. This is resulting in the eigenvector calculation short-circuiting in the first iteration for this test case. Commenting out this code block results in the expected outcome. 
```
            if (t <= Math.EPSILON * rnm) {
                t = 0.0;
            }

```
This is the code that is throwing an AIOB exception from MDS, because it assumes that what it asks for is what it will get.

  ```
      EVD eigen = B.eigen(k);
        
        coordinates = new double[n][k];
        for (int j = 0; j < k; j++) {
            if (eigen.getEigenValues()[j] < 0) {
                throw new IllegalArgumentException(String.format("Some of the first %d eigenvalues are < 0.", k));
            }

            double scale = Math.sqrt(eigen.getEigenValues()[j]);
            for (int i = 0; i < n; i++) {
                coordinates[i][j] = eigen.getEigenVectors().get(i, j) * scale;
            }
        }
```

If this is correct behavior for Lanczos.startv, then it seems like eigen() should throw an illegal argument exception because it cannot meet the expectation of the argument. Returning a partial result seems failure prone.

**Comment by CBrophy** [comment]
Sorry, this should read: "This is the code that is throwing an AIOB exception from MDS, because it assumes that what it asks for is what it will get."

**Comment by haifengl** [comment]
Do you add smile-netllib to dependency? If so, smile will use a native implement ion, which may be more numeric stable. It is a quick way for you to move forward. I will look into this problem anyway but it may take some time. Thanks!

**Comment by CBrophy** [comment]
No I didn't. I will try that, thanks!

**Comment by haifengl** [comment]
I cannot reproduce the problem in the shell

```
smile> val a: DenseMatrix = ones(100, 100) * 0.0071 
a: DenseMatrix =   0.0071    0.0071    0.0071    0.0071    0.0071    0.0071    0.0071  ...
  0.0071    0.0071    0.0071    0.0071    0.0071    0.0071    0.0071  ...
  0.0071    0.0071    0.0071    0.0071    0.0071    0.0071    0.0071  ...
  0.0071    0.0071    0.0071    0.0071    0.0071    0.0071    0.0071  ...
  0.0071    0.0071    0.0071    0.0071    0.0071    0.0071    0.0071  ...
  0.0071    0.0071    0.0071    0.0071    0.0071    0.0071    0.0071  ...
  0.0071    0.0071    0.0071    0.0071    0.0071    0.0071    0.0071  ...
  ...


smile> a.setSymmetric(true) 


smile> val e = eigen(a,2) 
[main] INFO smile.netlib.ARPACK - ARPACK: 6 iterations for Matrix of size 100
[main] INFO smile.netlib.ARPACK - ARPACK computed 2 eigenvalues
e: EVD = smile.math.matrix.EVD@113337a0

smile> e.getEigenValues 
res17: Array[Double] = Array(0.7100000000000003, 2.403532089570415E-19)
```

**Comment by haifengl** [comment]
BTW, how did you pin the issue to the line 360? Thanks!

**Comment by haifengl** [comment]
I tried on 5000 x 5000 matrix too.

**Comment by CBrophy** [comment]
I've confirmed that this issue does not happen with netlib, so pure-java problem only. Line 360: I used a debugger to figure out where the decision to short-circuit k was happening and traced it back to the zero-out logic.

**Comment by CBrophy** [comment]
I'll add that I'm on OpenJDK 1.8.0.151, Fedora 26 64

**Comment by haifengl** [comment]
Thanks! the function startv tries to find initial vectors. If it fails, we will get fewer vectors. But the line 360 is the same logic that you can find in other implementation including native fortran code. Not sure why it happens in our java code.

**Comment by haifengl** [comment]
I think that our eigen decomposition behavior for your matrix is correct. Your matrix is of same values and thus has only one eigen vector. Therefore, our Lanczos implementation converges to 1 eigen vector. The native implementation returns two but the second one is close to zero. Besides, the second returned vector could be random according to mathematical theory.

But I would enhance MDS in case that the user gives a too big k. Thanks!

**Comment by haifengl** [comment]
I actually don't throw exceptions in this case. For MDS and manifold learning (major user of eigen(k)), I will log a warning when getting fewer eigen vectors and returns a fewer-dimensional results. These are still useful in practice as they are mostly for visualization. It is better than an invalid array index exception.

**Comment by CBrophy** [comment]
Ah, ok. Thanks again for your help.
