### ISSUE TITLE
Possible Memory Leak in Smile Shell?

### ISSUE THREAD

**Issue by sudarsun** [haifengl/smile#244]
## Expected behaviour
smile> val a = randn(10000,9000) 
a: DenseMatrix =  -0.2015   -0.1568   -1.2813    0.0905   -1.7807   -0.3035    0.2579  ...
  0.9704    1.1750    1.7820   -0.6855    0.7325    0.2757    0.5772  ...
  2.7269    1.5059   -0.7013    0.4295   -1.0673    0.7825    1.7719  ...
 -0.1460    0.9704   -0.7109   -0.4607   -0.4236   -1.4759    0.5908  ...
  1.8722   -1.2937   -1.6331   -0.1099   -0.4046   -0.9848   -1.5071  ...
  0.4959   -1.0450   -0.5052   -0.2892    1.0435    0.0474   -0.6501  ...
  0.5539    0.6234    0.8357   -0.7341   -1.0011   -0.6974    0.8984  ...
  ...
smile> val b = randn(9000,15000) 
b: DenseMatrix =   1.2864    1.9764   -0.7183    2.4796    1.1056   -2.2591    0.7363  ...
 -0.4342   -1.7522    0.5853    1.3350   -0.5286   -0.1848    0.4102  ...
  0.7502    1.6444   -0.3972   -0.5313    1.4875    0.4529   -1.1809  ...
  0.1860    0.0787   -1.7037   -0.9045    0.2873    0.4760    0.1710  ...
  0.3190    0.3127    0.3486   -1.2244    1.4375   -1.4157   -0.3996  ...
  0.5438    0.2160    0.3346   -0.7319   -0.8930   -0.6308   -0.4984  ...
  0.3858    0.7406    1.7967    0.0190   -1.0619   -0.1146    0.8765  ...
  ...
smile> (a %*% b).toMatrix 
Nov 03, 2017 1:08:41 AM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded /tmp/jniloader5425324786287751594netlib-native_system-linux-x86_64.so
res2: DenseMatrix =  77.0954  -103.4315  -61.7543  -75.2236  -86.8510  -162.1371  -223.6612  ...
 38.6477   54.9267  -65.3077   45.5505  212.8126  -83.0247  141.0495  ...
  9.1660  -83.0286    4.5630  108.6834  -41.8311   -5.0851  185.6353  ...
-75.1136  125.9296  -135.2340   53.3893  -31.8623  -18.8496  172.5966  ...
 39.3162  102.6317  -185.4385  -91.2418   30.8640  -77.2048  -60.2692  ...
-61.6768   75.8956  136.0994   35.3006   86.4011   91.3585   14.1761  ...
-32.0659  -19.0175  -43.9971   79.6401   13.4532   39.2640  -66.5606  ...
  ...
smile> (a %*% b).toMatrix 
java.lang.OutOfMemoryError: Java heap space
  smile.math.matrix.JMatrix.<init>(JMatrix.java:78)
  smile.netlib.NLMatrix.<init>(NLMatrix.java:75)
  smile.netlib.NLMatrix.abmm(NLMatrix.java:150)
  smile.netlib.NLMatrix.abmm(NLMatrix.java:36)
  smile.math.MatrixMultiplicationExpression.toMatrix$lzycompute(Expression.scala:438)
  smile.math.MatrixMultiplicationExpression.toMatrix(Expression.scala:433)
  ammonite.$sess.cmd3$.<init>(cmd3.sc:1)
  ammonite.$sess.cmd3$.<clinit>(cmd3.sc)
## Actual behaviour

Just repeating the same operation again leads to OutOfMemoryError.  Does this mean, there is a memory leak somewhere?

## Code snippet

val a = randn(10000,9000)
val b = randn(9000,15000)
(a %*% b).toMatrix  <-- this works fine
(a %*% b).toMatrix  <-- repeating the command leads to OutOfMemoryError.

## Input data

randn()

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
OpenJDK 1.8.0_131

- Which Smile version
1.5.0 RC2

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Ubuntu 16.04.3 LTS x64 32Gb i7 6700

**Comment by haifengl** [comment]
By default, the shell use only 4GB memory. You are creating three large matrices, which exceeds 4GB. You can change the JVM options in the conf/smile.ini. Or you can pass the option -J-Xmx16GB to command line.
