### ISSUE TITLE
inverse of a densematrix throws segmentation fault

### ISSUE THREAD

**Issue by sudarsun** [haifengl/smile#245]
## Expected behaviour
smile> val a = randn(100,100) 
a: DenseMatrix =  -0.2015    0.0481    0.0432   -0.6100   -1.0286   -0.7054    0.1032  ...
  0.9704    0.3677   -0.0011    1.5735   -0.7982    1.1519   -0.3758  ...
  2.7269   -0.7253   -0.2067   -0.8212    1.8176   -0.7403   -0.1626  ...
 -0.1460   -1.6094    1.0685   -0.7500   -2.9544    0.9874   -0.7922  ...
  1.8722    0.6541   -1.5475    1.7311    1.5635    1.2492   -0.6935  ...
  0.4959    0.6218    1.8119    2.1485    0.0260   -0.2688    0.0886  ...
  0.5539   -1.8473    0.8755   -0.2812    1.3386   -0.3521    0.3232  ...
  ...

The expected output is the matrix inverse of DenseMatrix a.

## Actual behaviour

smile> val b = inv(a) 
Nov 03, 2017 1:13:28 AM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded /tmp/jniloader7844851871842582915netlib-native_system-linux-x86_64.so
Segmentation fault

## Code snippet

val a = randn(100,100)
val b = inv(a)

## Input data

randn(100,100)

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
openjdk 1.8.0_131 

- Which Smile version
1.5.0 RC2

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Ubuntu 16.04.3 LTS x64 32Gb RAM i7 6700

**Comment by haifengl** [comment]
Thanks for reporting this. But I can reproduce it on Mac, Windows, and RHEL. I don't have a native Ubuntu 16.04. But I tried in Windows Linux Subsystem, which is actually Ubuntu 16.04. It doesn't have issue either there. Do you observe this issue every time? Or only for some matrix?

The error seems from the underlying BLAS/Lapack library. I suspect that there is some issue in your environment.

**Comment by sudarsun** [comment]
I am able to consistently reproduce the error every time.  The error is definitely not random.  
What is the recommended BLAS package version number?
Where should I look into to get more useful information for you to debug further?

**Comment by haifengl** [comment]
I just used the default version:

sudo apt-get install libblas-dev liblapack-dev

**Comment by haifengl** [comment]
Since it happens every time, I am more confident that it is an environment issue.

**Comment by sudarsun** [comment]
Hmm.  When checked the version of blas and lapack, I could find that the version is 3.6.0-2ubuntu2

sudar@Imhotep:~$ sudo apt install libblas-dev liblapack-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libblas-dev is already the newest version (3.6.0-2ubuntu2).
liblapack-dev is already the newest version (3.6.0-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

Is there a place where I should check next to resolve the problem?

**Comment by haifengl** [comment]
Do you have another ubuntu machine? First we want to make sure if this issue happens with all ubuntu machines or just your current one. Thanks!

**Comment by sudarsun** [comment]
Yes Sir.  I have tried it already on a different machine.

sudar@optimus:~/smile$ ./smile.sh 
[info] Loading project definition from /home/sudar/smile/project
[info] Set current project to smile (in build file:/home/sudar/smile/)
[info] Wrote /home/sudar/smile/shell/target/scala-2.12/smile-shell_2.12-1.5.0-RC2.pom
[info] Main Scala API documentation to /home/sudar/smile/shell/target/scala-2.12/api...
[info] Compiling 1 Scala source to /home/sudar/smile/shell/target/scala-2.12/classes...
model contains 13 documentable templates
[info] Packaging /home/sudar/smile/shell/target/scala-2.12/smile-shell_2.12-1.5.0-RC2.jar ...
[info] Done packaging.
[info] Main Scala API documentation successful.
[info] Packaging /home/sudar/smile/shell/target/scala-2.12/smile-shell_2.12-1.5.0-RC2-javadoc.jar ...
[info] Done packaging.
[info] Wrote /home/sudar/smile/math/target/smile-math-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/data/target/smile-data-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/graph/target/smile-graph-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/netlib/target/smile-netlib-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/core/target/smile-core-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/interpolation/target/smile-interpolation-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/nlp/target/smile-nlp-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/plot/target/smile-plot-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/scala/target/scala-2.12/smile-scala_2.12-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/benchmark/target/scala-2.12/smile-benchmark_2.12-1.5.0-RC2.pom
[info] Wrote /home/sudar/smile/demo/target/smile-demo-1.5.0-RC2.pom
[success] Total time: 8 s, completed 3 Nov, 2017 8:56:17 PM
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/replBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Compiling (synthetic)/ammonite/predef/CodePredef.sc

                                                       ..::''''::..
                                                     .;''        ``;.
     ....                                           ::    ::  ::    ::
   ,;' .;:                ()  ..:                  ::     ::  ::     ::
   ::.      ..:,:;.,:;.    .   ::   .::::.         :: .:' ::  :: `:. ::
    '''::,   ::  ::  ::  `::   ::  ;:   .::        ::  :          :  ::
  ,:';  ::;  ::  ::  ::   ::   ::  ::,::''.         :: `:.      .:' ::
  `:,,,,;;' ,;; ,;;, ;;, ,;;, ,;;, `:,,,,:'          `;..``::::''..;'
                                                       ``::,,,,::''

  Welcome to Smile Shell; enter 'help<RETURN>' for the list of commands.
  Type "exit<RETURN>" to leave the Smile Shell
  Version 1.5.0-RC2, Scala 2.12.3, SBT 0.13.16, Built at 2017-11-03 15:26:08.605
===============================================================================
     
smile> val a = randn(100,100) 
a: DenseMatrix =  -0.2015    0.0481    0.0432   -0.6100   -1.0286   -0.7054    0.1032  ...
  0.9704    0.3677   -0.0011    1.5735   -0.7982    1.1519   -0.3758  ...
  2.7269   -0.7253   -0.2067   -0.8212    1.8176   -0.7403   -0.1626  ...
 -0.1460   -1.6094    1.0685   -0.7500   -2.9544    0.9874   -0.7922  ...
  1.8722    0.6541   -1.5475    1.7311    1.5635    1.2492   -0.6935  ...
  0.4959    0.6218    1.8119    2.1485    0.0260   -0.2688    0.0886  ...
  0.5539   -1.8473    0.8755   -0.2812    1.3386   -0.3521    0.3232  ...
  ...


smile> inv(a) 
Nov 03, 2017 8:56:47 PM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded /tmp/jniloader308925819341196954netlib-native_system-linux-x86_64.so
./smile.sh: line 11: 29624 Segmentation fault      (core dumped) bin/smile

sudar@optimus:~/smile$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

sudar@optimus:~/smile$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               1200.117
CPU max MHz:           3100.0000
CPU min MHz:           1200.0000
BogoMIPS:              4391.67
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts

**Comment by haifengl** [comment]
Can you try oracle JDK?

**Comment by sudarsun** [comment]
The error is reproducible in JDK 1.9 Oracle, JDK 1.8 Oracle & OpenJDK, JDK 1.7 Oracle.   Is there a way to debug the issue in some form?  You'd mentioned that you could reproduce this in mac, windows, and RHEL.  Is there are solution coming for those in the next versions?

**Comment by haifengl** [comment]
I can NOT reproduce it. To debug, please clone and build smile on your local machine.

**Comment by sudarsun** [comment]
Oh! I will do that then.

By the way, I am not getting the bug if I create a Scala project using the scala_smile jar.  The error was happening only the "smile" shell.

**Comment by haifengl** [comment]
I use jave8 and scala 2.11.8

**Comment by haifengl** [comment]
Scala 1.12 and 2.10 are also supported

**Comment by haifengl** [comment]
Any updates? When you create your scala project, do you also include smile-netlib jar? Smile shell uses it to use native BLAS/LAPACK library. Without it, we will fall back to pure Java implementation by smile. Your segment error seems from BLAS/LAPACK or JNI. Wihout smile-netlib, I guess that we won't get this error.

**Comment by sudarsun** [comment]
Upon analysis, the LAPACK function dgetrf() is throwing SIGSEGV.   dgetrf() is the function called within LAPACK when inv() or lu() methods are called.  

I tried plain qr(a:DenseMatrix), the LAPACK function dgeqrf() seems to work fine.
Likewise for eig(a:DenseMatrix), the LAPACK function dgeev() seems to work fine.

So, I don't think we have a problem with LAPACK integration through smile-netlib & com.github.fommil.netlib.

Please also find the BLAS,LAPACK version from the following "ldd" dump.

sudar@Imhotep:/projects/smile$ ldd  /tmp/jniloader5694017120184178737netlib-native_system-linux-x86_64.so
        linux-vdso.so.1 =>  (0x00007ffdee175000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fdf59ecc000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fdf59c6b000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fdf59488000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdf590be000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fdf58e7f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdf58b76000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdf58960000)
        libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007fdf568cc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdf5a587000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdf566af000)

**Comment by haifengl** [comment]
```
$ ldd /tmp/jniloader3583089873415736808netlib-native_system-linux-x86_64.so
        linux-vdso.so.1 =>  (0x00007fffcb527000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f531fc00000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f531f990000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f531f190000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f531edc0000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f531eb80000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f531e860000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f531e640000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5320400000)
```

**Comment by haifengl** [comment]
You have both `libblas` and `libopenblas`. Maybe it is the problem?

**Comment by sudarsun** [comment]
Oh genius!

After removing libopenblas, inv() works great!  Thanks very much Haifengl.  You made my day.

sudar@Imhotep:~$ ldd /tmp/jniloader3856932465116552375netlib-native_system-linux-x86_64.so 
        linux-vdso.so.1 =>  (0x00007ffde2fcb000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f806feaf000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f806fc71000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f806f48d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f806f0c3000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f806ee84000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f806eb7b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f806e965000)
        libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f806e3c7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f806e1aa000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f807056a000)

smile> val a = randn(5000,5000) 
a: DenseMatrix =  -0.6220   -0.0783   -0.8023   -0.3890   -0.5245    0.2128   -0.5224  ...
 -1.6479   -1.5208   -0.8594    0.3664    0.9871    0.6149   -0.1476  ...
  0.8378   -1.1239   -1.4638    0.3877   -0.2612    1.6644    0.1382  ...
  0.3510    1.3740    0.0927    1.7777    0.3945   -0.9368   -0.7576  ...
 -2.2577   -0.3411    0.4708    0.9353    0.4971   -0.5266   -0.8725  ...
 -1.0600   -0.0399    0.7752   -0.0318   -0.5856    0.0688    0.2655  ...
 -0.6944   -1.8710    0.2559    1.6812   -0.7443   -2.3982   -0.4802  ...
  ...

smile> inv(a) 
res3: DenseMatrix =   0.0045    0.0216    0.2812    0.2703    0.1335   -0.0393   -0.1738  ...
  0.0162   -0.0113   -0.1276   -0.1123   -0.0600    0.0148    0.0721  ...
 -0.0246   -0.0067   -0.1294   -0.1178   -0.0681    0.0025    0.0673  ...
 -0.0030   -0.0208   -0.2531   -0.2495   -0.1152    0.0466    0.1596  ...
 -0.0198   -0.0255   -0.4126   -0.3651   -0.1945    0.0253    0.2417  ...
  0.0144   -0.0246   -0.2498   -0.2304   -0.1156    0.0385    0.1543  ...
 -0.0215    0.0034    0.1684    0.1285    0.0888   -0.0090   -0.1044  ...
  ...

Thanks very much.

**Comment by sudarsun** [comment]
The exact problem is the following:  The OpenBlas 0.2.18 package is broken at dgetrf() LAPACK function when the OPENBLAS_NUM_THREADS > 1.  When the thread count set to 1, openblas works fine for evaluating matrix inverse.   The same LAPACK function from libblas and libatlas are working fine, but painfully slower compared to libopenblas's single thread version.

**Comment by haifengl** [comment]
We actually use OpenBlas on Windows and have no issues. But I use a prebuit version, which I don't know if USE_OPENMP=1.

It is interesting that libblas is much slower than OpenBlas for this use case. How much slower? Thanks!

**Comment by sudarsun** [comment]
The code that are used to benchmark
```
val a = randn(2000,2000)
val b = (a.t %*% a).toMatrix
```
**This operation took ~500mS with openblas single thread mode **

sudar@Imhotep:/tmp $ update-alternatives --config libblas.so.3
There are 3 choices for the alternative libblas.so.3 (providing /usr/lib/libblas.so.3).

Selection    Path                                    Priority   Status
------------------------------------------------------------
* 0            /usr/lib/openblas-base/libblas.so.3      40        auto mode
  1            /usr/lib/atlas-base/atlas/libblas.so.3   35        manual mode
  2            /usr/lib/libblas/libblas.so.3            10        manual mode
  3            /usr/lib/openblas-base/libblas.so.3      40        manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/lib/libblas/libblas.so.3 to provide /usr/lib/libblas.so.3 (libblas.so.3) in manual mode

sudar@Imhotep:/tmp $ update-alternatives --config liblapack.so.3
There are 3 choices for the alternative liblapack.so.3 (providing /usr/lib/liblapack.so.3).

Selection    Path                                      Priority   Status
------------------------------------------------------------
* 0            /usr/lib/openblas-base/liblapack.so.3      40        auto mode
  1            /usr/lib/atlas-base/atlas/liblapack.so.3   35        manual mode
  2            /usr/lib/lapack/liblapack.so.3             10        manual mode
  3            /usr/lib/openblas-base/liblapack.so.3      40        manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/lib/lapack/liblapack.so.3 to provide /usr/lib/liblapack.so.3 (liblapack.so.3) in manual mode

**After changing to libblas, the same operation took ~24986mS **

# The speed up is over 50 times!!

**Comment by haifengl** [comment]
Something is wrong with your libblas. I used libblas on RHEL7 and Windows Linux Subsystem, and it is very fast this operation, definitely subseconds. With even pure Java implementation, it won't take 24 seconds for 2000 x 2000 matrix multiplication.

**Comment by haifengl** [comment]
I know you are benchmarking. But for production, please don't use `a.t %*% a`, we have `a.ata` (and `aat`) for the same purpose, which should be faster in general.
