### ISSUE TITLE
logistic regression with sgd

### ISSUE THREAD

**Issue by mazorigal** [haifengl/smile#247]
it would be nice to have in smile an implementation of online logistic regression using sgd.

**Comment by rayeaster** [comment]
http://www.cs.cmu.edu/~wcohen/10-605/sgd-part2.pdf

I would like give it a try for sgd on LR:)

**Comment by haifengl** [comment]
Sure. Thanks. Several things to note:

- It is very straightforward to support SGD in binary case. But for multiple class, it is quite different especially our implementation trains the model in one optimization.
- Don't touch the existing algorithm. Make the class support OnlineClassifier and just implement the additional method for model update.

**Comment by rayeaster** [comment]
will follow your notes. Thanks.
