### ISSUE TITLE
L1 normalization in regressions

### ISSUE THREAD

**Issue by aelkholy** [haifengl/smile#249]
Can we have the option for L1 normalization in the linear / logistic / maxent algorithms? This would give us a way to zero out the weights, especially when using bag of words with a sparse vector.

**Comment by haifengl** [comment]
I guess that you mean regularization. Check out LASSO, which has L1 regularization for linear regression.

Additional work is needed for logistic/maxent. It is a big work. It is not just an option. It is whole new algorithms :)
