### ISSUE TITLE
different labels in truth and prediction

### ISSUE THREAD

**Issue by avanco** [haifengl/smile#250]
https://github.com/haifengl/smile/blob/af7fadbf44423cd99eb611c6c92be5e3f7c027c0/core/src/main/java/smile/validation/ConfusionMatrix.java#L37

it seems there is a problem in construction of confusion matrix, consider for instance:
int[] truth = 		{0,0,0,3,0,0,0,1,2,3,0,0};
int[] prediction = 	{0,1,2,4,5,2,1,2,4,5,4,1};

it is necessary all possible labels to construct the confusion matrix, right?
maybe a 'for' like this would solve it?

for(int i = 0; i < truth.length; i++){
    ySet.add(truth[i]);
    **ySet.add(prediction[i]);**
}

**Comment by haifengl** [comment]
How do you have more classes with predictions?

**Comment by avanco** [comment]
consider for example, i have a model which could map an instance in three possible values [0, 1, 2]
while testing this model it is possible this scenario:
truth = {1, 0, 1, 0}
prediction = {1, 2, 0, 1}

ySet is used to hold all possible labels, but only values from 'truth' are used
this way it is created a matrix 2x2, but should be 3x3

**Comment by haifengl** [comment]
We will enhance confusion matrix. But seriously why don’t you include all classes in the test data? It doesn’t sound a good way to test the model to me.

**Comment by avanco** [comment]
Exactly haifengl, no doubt a test must always include all classes considering a model construction process.
But sometimes we have new tiny data, and would be nice to get confusion matrix from it.
It would be nice this enhancement :)
thanks, regards

**Comment by haifengl** [comment]
The enhancement is pushed to the master branch. Thanks!
