### ISSUE TITLE
Topic Modeling

### ISSUE THREAD

**Issue by pscholze** [haifengl/smile#253]
Is there any way to do Topic Modeling with smile?

Thanks in advance
Peter

**Comment by haifengl** [comment]
Do you mean topic classification in NLP?

**Comment by pscholze** [comment]
I mean unsupervised topic detection in NLP, commonly done with Latent Dirichlet Allocation etc.

**Comment by haifengl** [comment]
No LDA right now. But we have unsupervised key word extraction, which may be useful to you.
