### ISSUE TITLE
Platt Scaling Application

### ISSUE THREAD

**Issue by scarton** [haifengl/smile#256]
Not a bug or an issue - just trying to understand how your PlattScaling class works. And maybe more importantly, what the code expects for input and what it produces for output.

I've copied the class (retaining your license and attribution of course), and am trying to use it against some output from a Spark SVM classifier.  The data set comprises a subset with scores (from the SVM) and labels assigned by a human; and also a subset of just scores with no labels. I'm using the first subset to train the Platt model and the second subset to test the results. I'm feeding the class an array of scores and labels that have a number of true and false label values. 

How big a set does the model need for best accuracy? And should I try to ensure that there are a roughly equal number of true and false label/score combinations?

Could you tell me what the resulting probability score means? I have been assuming that the resulting probability reflects a scale from 0.0 to 1.0 on which the SVM score falls between "false" and "true". In other words, a probability of 0.001 indicates that this SVM score is close to "false" while a probability of 0.95 indicates that the SVM score is close to "true".

**Comment by haifengl** [comment]
Please see the paper for details.

Platt, John (1999). "Probabilistic outputs for support vector machines and comparisons to regularized likelihood methods". Advances in large margin classifiers. 10 (3): 61–74.

**Comment by scarton** [comment]
Thanks - I had read the paper.
