### ISSUE TITLE
How to use SVM with only 2 classes

### ISSUE THREAD

**Issue by gustavosiqueira94** [haifengl/smile#26]
I'm trying to use SVM algorithm to train a classifier for a dataset with only 2 classes. Java is throwing an illegal argument exception with message "Invalid number of classes: 2".

How can I train a classifier using the algorithm in this specifications?

**Comment by haifengl** [comment]
can you show your code? Thanks!

**Comment by Xyclade** [comment]
Hi @gustavosiqueira94, in my blog about machine learning using smile, I've made a code example on how to use the SVM. In this example there where 2 classes. Note that the code is in Scala, so if you have questions feel free to ask.  You can find the example [here](http://xyclade.github.io/MachineLearning/#using-support-vector-machines-svms)

**Comment by gustavosiqueira94** [comment]
Thank you for helping, now I'm able to train my dataset. The problem was that in your tutorial the examples showed how to train using only Multiclass One vs. One or One vs. All.
