### ISSUE TITLE
Set seed randomForest

### ISSUE THREAD

**Issue by AntonYurchenko** [haifengl/smile#262]
Hello! Tell me please, how can I set seed for random forest?

**Comment by haifengl** [comment]
set -Dsmile.threads=1 for JVM and call smile.math.Math.setSeed before training the model. If you just want repeatable result, the first step should be sufficient.

**Comment by AntonYurchenko** [comment]
Thanks a lot! I have tried the method. It works.

But I need to call smile.math.Math.setSeed before each training of the model

For example:
```scala
smile.math.Math.setSeed(777)

val model1 = regression.randomForest(trainDs.x, trainDs.y)
val trainRMSE1 = rmse(model1.predict(trainDs.x), trainDs.y)

val model2 = regression.randomForest(trainDs.x, trainDs.y)
val trainRMSE2 = rmse(model2.predict(trainDs.x), trainDs.y)

trainRMSE1 == trainRMSE2 // false
```
True way is:
```scala

smile.math.Math.setSeed(777)
val model1 = regression.randomForest(trainDs.x, trainDs.y)
val trainRMSE1 = rmse(model1.predict(trainDs.x), trainDs.y)

smile.math.Math.setSeed(777)
val model2 = regression.randomForest(trainDs.x, trainDs.y)
val trainRMSE2 = rmse(model2.predict(trainDs.x), trainDs.y)

trainRMSE1 == trainRMSE2 // true
```

**Comment by lfoppiano** [comment]
Hi, I have a couple of questions: 
1. the parameter `-Dsmile.threads=1` should be used only for training or everytime we want to set the seed manually? 
2.  once the model is serialised, do we still need to set the seed / set the threads=1 after deserialise it?
Thank you in advance

**Comment by lfoppiano** [comment]
More details in the FAQ: http://haifengl.github.io/smile/faq.html
