### ISSUE TITLE
Smile版本1.4和1.5，本地使用jdk1.7无法调用jar包，出现版本不一致的错误，请教下如何解决啊？

### ISSUE THREAD

**Issue by qianyiwei** [haifengl/smile#264]
## Expected behaviour

E.g. Train a RandomForest on my data which has 10000 samples and 10 attributes, which are ....

## Actual behaviour

E.g. The algorithm throws an exception. Here is the stack trace...

## Code snippet

E.g. The code to parse data and the call of Smile algorithm.

## Input data

E.g. sample data

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
- Which Smile version
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )

**Comment by haifengl** [comment]
Smile is built with Java 8.

**Comment by qianyiwei** [comment]
谢谢！！！
