### ISSUE TITLE
Enhancement: Import pretrained Decision Trees/Random Forests

### ISSUE THREAD

**Issue by mpeychev** [haifengl/smile#265]
Hello, I am exploring the opportunity to use this library for making predictions only. Is it possible to import or create decision tree/random forest objects which implement already trained models? The kind of functionality I am looking for is similar to the ```ML.FOREST.ADD``` operation provided by RedisML.

https://redislabs.com/modules/machine-learning/

Thank you.

**Comment by haifengl** [comment]
No.

**Comment by mpeychev** [comment]
Thank you for your response. I am not asking for support for other systems. Rather than that, I thought it would be useful to provide a way or a method for building and creating decision trees/random forests manually. In this way one can use another tool (e.g. SparkML, scikit-learn) for training, than translate the model to your library and use it for prediction/serving.
