### ISSUE TITLE
Random question (sorry, couldn't find your email address for this)

### ISSUE THREAD

**Issue by crew102** [haifengl/smile#266]
I'm working a PR (https://github.com/jtablesaw/tablesaw/pull/233) for the tablesaw Java library that involves wrapping the hierarchical clustering functionality present in smile. I'd like to know if it's OK with you if I copy some of smile's documentation (e.g., the javadocs for HierarchicalClustering)? I'd be happy to note where I got the documentation from (i.e., that's they're copied from smile’s javadocs).

**Comment by haifengl** [comment]
Okay
