### ISSUE TITLE
agglomerative clustering 5x slower than R implementation, is it expected?

### ISSUE THREAD

**Issue by dariomx** [haifengl/smile#275]
Dear Haifeng,

I am just starting to use your pretty cool library, so far I am quite excited because it almost feels like working on R!

I had a prototype working in R, and calling hclust(.) with a similarity matrix for 14470 vectors, takes around 6secs (all params set to default). When I use equivalent method on smile (with complete linkage, same default is same as R), it takes around 30secs. I have installed the native libraries and all, but I think that this algorithm does not leverage on nd4j/blas. 

I just wanted to confirm if this performance was expected. 

Thanks.

**Comment by haifengl** [comment]
We use one of most advanced algorithm for hclust. In theory, it should be very fast. I guess that the slowness is again because of JVM's memory management. The distance matrix double[][] is really not modern CPU friendly. I will change the underlying data structure to speed it up.

**Comment by dariomx** [comment]
Thanks for the quick reply Haifeng.

Looking forward to it, I am quite interested in this type of optimization. I would like to contribute in the future, but for now probably just watch and learn ;-?

**Comment by haifengl** [comment]
I made some optimization and it takes 9 seconds on my 4 year old laptop for a test data of 14470 samples. Try the master branch and see if it works better now on your data.

BTW, R's hclust is implemented by C underlying. If they use the same algorithm as ours, it will be hard for Java to win in this case. Basically, the array index checking in Java is a performance killer.

**Comment by dariomx** [comment]
Dear Haifeng,

Thanks a lot for your super-fast reply!

I gave it a try right away, and detected an speedup of 10-12secs less with mentioned data. That is, without your optimization it takes around 30s, and with your optimization around 18-20s. 

My laptop is not that old, so I was hoping to achieve something similar or superior than your test. In case you get a chance, please give the file below a try; is the very same data I am trying:

https://drive.google.com/open?id=1sYs70zD8GksHcl909cePS-guRpRFmErf

Thanks.

**Comment by haifengl** [comment]
It takes 8.8s on my laptop (unplugged).

```
smile> val x = read.csv("trainData.csv",header=true).unzip  
x: Array[Array[Double]] = Array(
  Array(0.32919254658385094, 0.16779060123827824),
  Array(0.3105590062111801, 0.19826924340214483),
  Array(0.7018633540372671, 0.33629456734164326),
  Array(0.515527950310559, 0.10448280534069074),
  Array(0.37888198757763975, 0.14139610123006685),
  Array(0.30434782608695654, 0.13457756482895666),
  Array(0.14906832298136646, 0.13143054802844428),
  Array(0.2484472049689441, 0.15725538256885255),
  Array(0.2732919254658385, 0.15380146491271288),
  Array(0.22981366459627328, 0.30400736562053504),
  Array(0.12422360248447205, 0.2641061486919249),
  Array(0.5652173913043478, 0.1875),
  Array(0.3416149068322981, 0.19664749306137197),
  Array(0.32298136645962733, 0.1931935754052323),
  Array(0.2608695652173913, 0.16732152534857367),
  Array(0.2670807453416149, 0.1839978404033437),
  Array(0.36645962732919257, 0.2119586638419471),
  Array(0.5527950310559007, 0.22162347473354027),
  Array(0.4658385093167702, 0.20391560329112676),
  Array(0.5093167701863354, 0.19729106107634956),
  Array(0.6645962732919255, 0.18380589906554334),
  Array(0.2919254658385093, 0.1718193164835526),
  Array(0.6149068322981367, 0.14651898474322972),
  Array(0.5962732919254659, 0.19937059663989753),
...

smile> val d = pdist(x)  
d: Array[Array[Double]] = Array(
  Array(0.0),
  Array(0.03572333208105006, 0.0),
  Array(0.40899525342055637, 0.4149338292742624, 0.0),
  Array(0.1967962390479195, 0.2254066636314669, 0.29741818317645197, 0.0),
  Array(0.05626464411118842, 0.08889647958905339, 0.3772298704672966, 0.1415440233447636, 0.0),
  Array(0.04147729407875742, 0.06399381749830109, 0.4457671410773985, 0.2133137112699339, 0.07484539844086947, 0.0),
  Array(0.1837574199803093, 0.17477600513025338, 0.5895350818816917, 0.3674490975607588, 0.23002963436432003, 0.1553113897930917, 0.0),
  Array(0.08142973059589859, 0.07443126113406716, 0.4874845986490785, 0.2722445030474166, 0.13139539306520776, 0.060325474377111325, 0.10267952212656789, 0.0),
  Array(0.0576244338498421, 0.05801912297738562, 0.46580811695578167, 0.24720562678578542, 0.10631629350608848, 0.03652433843095588, 0.1262218734469703, 0.02508365371599998, 0.0),
  Array(
    0.1686154473465351,
    0.13304270247848707,
    0.4731525892313369,
    0.34848630276682285,
    0.2205987040377702,
    0.18509942902503287,
    0.1905323283926425,
    0.14793023138094952,
    0.1563719021297947,
    0.0
  ),
  Array(
    0.22647064429305172,
    0.19762434257988248,
...

smile> val clusters = hclust(d, "complete")  
[main] INFO smile.util.package$ - runtime: 8880.695798 ms
clusters: HierarchicalClustering = smile.clustering.HierarchicalClustering@7725470b
```

**Comment by haifengl** [comment]
I use oracle jvm with these options

```
-Xmx4096M
-Xms1024M
-server
-XX:+AggressiveOpts
-XX:+UseG1GC
-XX:+UseStringDeduplication
-XX:-PrintGCDetails
```

**Comment by dariomx** [comment]
Thanks Haifeng,

I guess that difference could be the "client" JDK I am using (through Intellij). I set the same options that you shared, but I suspect the "server" feature is not really honored on my client JDK/JRE.

I will give it a try with a Server JRE, either from command line as you did or same Intellij. So far no banana due a couple of issues:

1) Intellij complains about invalid JDK when passing the Server JRE flavor, asked about it on an existing ticket at JetBrains:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000708044-Cannot-use-Server-JRE-The-selected-directory-is-not-a-valid-home-for-JDK

is not totally clear yet if I can use this Server JRE or not from the IDE, awaiting reply.

2) My smile shell does not resolve predefined library names, not even "help" command is available though I can perform basic Scala operations that do not involve the library. I am pasting a sample session below, it relates perhaps with the fact I am using Cygwin and not plain Linux shell nor Windows (I tried from Windows DOS prompt though, but the smile.bat tells error about command too long):

DBAHENA-LAP+dbahena@DBAHENA-LAP /cygdrive/c/Users/dbahena/IdeaProjects/smile
$ ./smile.sh
[info] Loading settings from buildinfo.sbt,plugins.sbt ...
[info] Loading project definition from C:\Users\dbahena\IdeaProjects\smile\project
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Set current project to smile (in build file:/C:/Users/dbahena/IdeaProjects/smile/)
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\shell\target\scala-2.12\smile-shell_2.12-1.5.1.pom
[info] Main Scala API documentation to C:\Users\dbahena\IdeaProjects\smile\shell\target\scala-2.12\api...
[info] Compiling 1 Scala source to C:\Users\dbahena\IdeaProjects\smile\shell\target\scala-2.12\classes ...
[info] Done compiling.
[info] Packaging C:\Users\dbahena\IdeaProjects\smile\shell\target\scala-2.12\smile-shell_2.12-1.5.1.jar ...
[info] Done packaging.
model contains 13 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging C:\Users\dbahena\IdeaProjects\smile\shell\target\scala-2.12\smile-shell_2.12-1.5.1-javadoc.jar ...
[info] Done packaging.
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\math\target\smile-math-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\data\target\smile-data-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\graph\target\smile-graph-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\netlib\target\smile-netlib-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\core\target\smile-core-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\interpolation\target\smile-interpolation-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\nlp\target\smile-nlp-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\plot\target\smile-plot-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\scala\target\scala-2.12\smile-scala_2.12-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\benchmark\target\scala-2.12\smile-benchmark_2.12-1.5.1.pom
[info] Wrote C:\Users\dbahena\IdeaProjects\smile\demo\target\smile-demo-1.5.1.pom
[success] Total time: 17 s, completed 20/02/2018 03:03:35 PM

                                                       ..::''''::..
                                                     .;''        ``;.
     ....                                           ::    ::  ::    ::
   ,;' .;:                ()  ..:                  ::     ::  ::     ::
   ::.      ..:,:;.,:;.    .   ::   .::::.         :: .:' ::  :: `:. ::
    '''::,   ::  ::  ::  `::   ::  ;:   .::        ::  :          :  ::
  ,:';  ::;  ::  ::  ::   ::   ::  ::,::''.         :: `:.      .:' ::
  `:,,,,;;' ,;; ,;;, ;;, ,;;, ,;;, `:,,,,:'          `;..``::::''..;'
                                                       ``::,,,,::''

  Welcome to Smile Shell; enter 'help<RETURN>' for the list of commands.
  Type ":quit<RETURN>" to leave the Smile Shell
  Version 1.5.1, Scala 2.12.4, SBT 1.1.0, Built at 2018-02-20 21:03:19.193
===============================================================================

smile> val x = read.csv("trainData.csv",header=true)
<console>:11: error: not found: value read
       val x = read.csv("trainData.csv",header=true)
               ^
<console>:11: error: not found: value header
       val x = read.csv("trainData.csv",header=true)
                                        ^
smile> pdist
<console>:12: error: not found: value pdist
       pdist
       ^
smile> hclust
<console>:12: error: not found: value hclust
       hclust
       ^
smile> help
<console>:12: error: not found: value help
       help
       ^
smile> print(666)
666smile>
smile> val x = 665
x: Int = 665
smile> x + 1
res4: Int = 666
smile>


I will keep on trying, for me the practical thing would be to be able to use the Server JRE from my IDE (Intellij). Will keep you updated when I achieve that.

Thanks.

**Comment by haifengl** [comment]
Do yo installed jdk in cygwin? If not, it will pick up the one from windows. Things are more complicated then. 

If you have a linux box, it is probably easier way for you to try this out. BTW, I am not sure if -server makes that difference.

**Comment by dariomx** [comment]
I am setting env vars to force cygwin pick the one I wanna, but perhaps have not touched system vars to enforce that. 

I agree that cygwin is becoming a pain, I wish I could freely use Ubuntu at work ;-?

Will keep on trying, thanks for your continuous support.

PS: Perhaps the -server option is not the culprit as you said, but so far is the best I could think of. The experiment will confirm.

**Comment by dariomx** [comment]
I think you were right Haifeng. With help of Intellij I managed to use Server JRE, with all flags you mentioned; but still getting ~ 17secs for same data. I guess the IDE is bringing some extra noise, hence should try to test this in command line as you did.

Will try to fix the cygwin + java thing and report outcome, thanks again.

**Comment by haifengl** [comment]
You can build and run smile without cygwin. In the source dir, run

```
sbt stage
```
the binary will be available in `shell/target/universal/stage/bin`.

I am not sure either that Intellij introduces the noise. Something else probably.

**Comment by haifengl** [comment]
I released v1.5.1, which includes this enhancement. Please make sure to use Oracle JDK. I know that OpenJDK has performance issues with some other algorithms in smile.

**Comment by dariomx** [comment]
Thanks a lot Heifeng.

Even if I do not get yet same performance as you do, I can definitely see an speedup with the changes applied. This is great support, thanks again.

**Comment by haifengl** [comment]
What's your current performance and settings (hardware & software)?
