### ISSUE TITLE
Attribute equals() method requires descriptions

### ISSUE THREAD

**Issue by wmbuchanan** [haifengl/smile#276]
Lines 159-162 of `smile.data.Attribute.equals()` read:
```java
if (description != null && a.description != null && description.equals(a.description)) {
    return true;
} else {
    return false;
```
Meaning that, regardless of the fact that the `Attribute`s I'm trying to compare are equal in every respect, since neither has descriptions `equals()` still returns `false`.

Just wondering what the reason is for this?

**Comment by haifengl** [comment]
Thanks for reporting this. I change the logic to

```
if (description != null && a.description != null) {
    return description.equals(a.description);
} else {
    return description == a.description;
}
```

**Comment by wmbuchanan** [comment]
Thank you!
