### ISSUE TITLE
Consider supporting intercept / bias in logistic regression model

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#278]
## Current behaviour

I was trying to port some code from scikit-learn to Smile and noticed that Smile's `LogisticRegression` class does not support an equivalent of `fit_intercept`

## Desired behaviour

From [sklearn.linear_model.LogisticRegression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html):

fit_intercept : bool, default: True
Specifies if a constant (a.k.a. bias or intercept) should be added to the decision function.

**Comment by haifengl** [comment]
We always include intercept in logistic regression. It is part of weight vector.
