### ISSUE TITLE
loglikelihood is negative?

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#279]
## Actual behaviour

I'm calling `LogisticRegression.loglikelihood` and it is returning negative values

## Expected behaviour

I expected log-likelihoods to generally be positive? Is it actually returning the negative log likelihood? Optimisers typically minimize a function, so I could understand using negative log-likelihood as minimising that is equivalent to maximising the log-likelihood. However, if this is the case, it would be helpful to document

**Comment by haifengl** [comment]
In the log? Yes, it is negative log likelihood. The optimization method is out of logistic regression and it just print out the objective function value. I don't think it says what it is.

**Comment by benmccann** [comment]
There's a method that returns `loglikelihood` which I was referring to: https://github.com/haifengl/smile/blob/205d98db4d8940885d499097987254594303ac0f/core/src/main/java/smile/classification/LogisticRegression.java#L880

I'm wondering if it should be called `negativeloglikelihood` instead or add to the Javadoc comment that it's the negative log likelihood

Also, I was trying to do a grid search on the regularization parameter. The larger the regularization parameter, the smaller the `loglikelihood` value (still negative, but greater in magnitude). I would have expected there to be some optimal value of `lambda`. I can share the code and data for this grid search if you have any ideas

**Comment by haifengl** [comment]
in general likelihood < 1 and thus log likelihood is negative.

**Comment by haifengl** [comment]
You misunderstand the regularization, which penalizes the weights. And in general it does make the loglikelihood smaller.
