### ISSUE TITLE
Which is best way to represent a binary attribute on supervised learning algorithms? NominalAttribute or NumeralAttribute?

### ISSUE THREAD

**Issue by owlmsj** [haifengl/smile#28]
Hi!

I am working on a tutorial about how to use Smile in NLP applications and I have a few questions that I did not find an easy answer inside the javadocs.

Is there a place that I could ask you, @haifengl ? 
Or it is okay to use this issue to talk about...

Btw, the first one: which is the best way to represent a binary attribute on supervised learning algorithms? NominalAttribute or NumeralAttribute?

Thanks a lot!

**Comment by haifengl** [comment]
There are no silly questions. I prefer that people ask questions here so that others can also see them. Just please give it a meaningful title. Thanks!

For binary attributes, please use NominalAttribute.

**Comment by owlmsj** [comment]
Okay, Thanks!

I am going to open another questions in the next days.
