### ISSUE TITLE
Simpler CrossValidation API

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#282]
Right now to call `CrossValidation` is seems that I need to do:
```
CrossValidation cv = new CrossValidation(n, k);
int error = 0;
int total = 0;
for (int i = 0; i < k; i++) {
  double[][] trainx = Math.slice(x, cv.train[i]);
  int[] trainy = Math.slice(y, cv.train[i]);
  NaiveBayes model = new NaiveBayes(NaiveBayes.Model.MULTINOMIAL, 2, feature.length);
 
  model.learn(trainx, trainy);
 
  double[][] testx = Math.slice(x, cv.test[i]);
  int[] testy = Math.slice(y, cv.test[i]);
  for (int j = 0; j < testx.length; j++) {
    int label = model.predict(testx[j]);
    if (label != -1) {
      total++;
      if (testy[j] != label) {
        error++;
      }
    }
  }
}
```

It could be nice if `CrossValidation` took the `x`, `y`, and `model` as inputs and actually ran the k-fold cross validation for you so that less code was required to do a cross-validation

**Comment by haifengl** [comment]
In `smile.validation.Validation` we have several Java helper functions for this purpose. 

With Scala API, it is even more convenient. For example,
```
cv(x, y, 10) { case (x, y) => lda(x, y) }
```
See http://haifengl.github.io/smile/validation.html for more example.

**Comment by benmccann** [comment]
Thank you. That's a super helpful pointer!

Would it be possible to add something about `smile.validation.Validation` to the docs? Perhaps on http://haifengl.github.io/smile/validation.html?
