### ISSUE TITLE
Is it possible with KMeans/XMeans/GMeans to get the input data associated with each centroid in the results?

### ISSUE THREAD

**Issue by rschiavi** [haifengl/smile#284]
## Expected behaviour

E.g. Train a RandomForest on my data which has 10000 samples and 10 attributes, which are ....

## Actual behaviour

E.g. The algorithm throws an exception. Here is the stack trace...

## Code snippet

E.g. The code to parse data and the call of Smile algorithm.

## Input data

E.g. sample data

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
- Which Smile version
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )

**Comment by haifengl** [comment]
`KMeans.centroids()` returns the centroids of each cluster. `PartitionClustering.getClusterLabel()` returns the cluster labels of input data. KMeans is a subclass of `PartitionClustering`.
