### ISSUE TITLE
Is multi-threading a configurable feature in Smile?

### ISSUE THREAD

**Issue by dariomx** [haifengl/smile#285]
Hello Haifeng,

One general question about Smile. 

Initially, I kinda assumed that it was all serial execution; possibly leveraging vectorization in some cases (thanks to nd4j/blas). But a college pointed me out that the code base indeed, seems to have a lot of places that mention multi-threading.

Could you clarify if this multi-threading is something we can easily disable, meaning I do not want to use additional threads? (or at least not to use more than one additional thread).

Thanks.

**Comment by dariomx** [comment]
So far I see all this classes using MulticoreExecutor, so it does not apply to all algorithms; but to several:

./core/src/main/java/smile/association/FPGrowth.java
./core/src/main/java/smile/classification/DecisionTree.java
./core/src/main/java/smile/classification/LogisticRegression.java
./core/src/main/java/smile/classification/Maxent.java
./core/src/main/java/smile/classification/RandomForest.java
./core/src/main/java/smile/classification/SVM.java
./core/src/main/java/smile/clustering/CLARANS.java
./core/src/main/java/smile/clustering/DENCLUE.java
./core/src/main/java/smile/clustering/DeterministicAnnealing.java
./core/src/main/java/smile/clustering/KMeans.java
./core/src/main/java/smile/clustering/MEC.java
./core/src/main/java/smile/clustering/SIB.java
./core/src/main/java/smile/gap/GeneticAlgorithm.java
./core/src/main/java/smile/manifold/TSNE.java
./core/src/main/java/smile/regression/RandomForest.java
./core/src/main/java/smile/regression/RegressionTree.java
./core/src/main/java/smile/regression/SVR.java
./core/src/main/java/smile/sequence/CRF.java

**Comment by dariomx** [comment]
By looking into the code, looks like property smile.threads can control the number of threads I do want to have. Hence, setting that to one should make the trick.

Please just confirm my understanding is correct.

**Comment by haifengl** [comment]
Yes, you are right.

**Comment by dariomx** [comment]
Thanks.
