### ISSUE TITLE
FP-Growth issue

### ISSUE THREAD

**Issue by peter-toth** [haifengl/smile#287]
FP-Growth does not return all frequent itemsets when mines a single path FP-tree. Consider the following itemset:

`{{1, 2, 3, 4}}`

The result should contain these 15 itemsets if minsupport is 1:

```
1 (1)
2 (1)
3 (1)
4 (1)
1 2 (1)
1 3 (1)
1 4 (1)
2 3 (1)
2 4 (1)
3 4 (1)
1 2 3 (1)
1 2 4 (1)
1 3 4 (1)
2 3 4 (1)
1 2 3 4 (1)
```

but `1 3 4 (1)` is missing.

#286 PR fixes the issue.

**Comment by haifengl** [comment]
Thanks for PR!
