### ISSUE TITLE
Help on using SVM for text Classification

### ISSUE THREAD

**Issue by sreendra** [haifengl/smile#289]
Hi Haifeng,
I am ravi and i am trying to use Online SVM for text classification. 
We have some 10k documents and their corresponding labels(10) and what is the best classification technique can i go with to classify data ? 

As of now, 
i am taking the documents and creating a dictionary out of all the available words after tokenizing, pos,lemmatization and then removing the stop words. I am using the output of the preprocessed document as input to SVM(increasing the dimensionality of the feature space to ~ 10k) ? Will SVM work for such cases or it a over kill ? Please share your views.

Thanks,
raveendra

**Comment by haifengl** [comment]
Yes, your approach (SVM with bag of words) is okay as the start point. Depending on your kernel, you may want to normalize the feature vector. Besides, the dimension is a little bit high (what do you mean "increasing the dimensionality of the feature space to ~ 10k"). It might be good to try some feature selection or reduction techniques.

**Comment by sreendra** [comment]
Hi Haifeng,
Thank you for your response. Can i reach out to you on Skype and i would like to take some 30 minutes of your time to better understand on how to implement our problem.

My skype id is : raveendra1232

Thanks,
raveendra

**Comment by sreendra** [comment]
Hi Haifeng Li,
I am trying to understand the SMO algorithm for quick some time but couldn't clearly get the algorithm. Can you please help me to understand it ?

I followed the code & the below paper
Tobias Glasmachers and Christian Igel. Second Order SMO Improves SVM Online and Active Learning.

But unfortunately i couldn't convince there is a 1-1 match. 

Thanks,
raveendra
