### ISSUE TITLE
Dataset custom type  yields NoClassDefFound error - Dataset<T> dataset = new Dataset<T>();

### ISSUE THREAD

**Issue by kalki123123** [haifengl/smile#290]
## Expected behaviour
i am trying to create a dataset of custom objects. However, i end with error
E.g. Train a RandomForest on my data which has 10000 samples and 10 attributes, which are ....

## Information
1.8.0_144 JDK
1.5.1 smile
Windows 10

##Output
java.lang.NoClassDefFoundError: smile/data/Dataset
	de.imc.clix.core.recommender.RecommenderSample.executeQuery(RecommenderSample.java:16)
	org.apache.jsp.test_jsp._jspService(test_jsp.java:96)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	de.imc.clix.servlets.filter.IEFilter.doFilter(IEFilter.java:23)
	de.imc.clix.servlets.filter.EncodingFilter.doFilter(EncodingFilter.java:38)

**Comment by kalki123123** [comment]
I am pretty new to java as well as smile. Excuse me for silly question.

**Comment by haifengl** [comment]
Do you include smile in your project dependency?

**Comment by kalki123123** [comment]
Its a java project. I have added smile/lib folder as library dependency to my project. 
now I get same error for StringAttribute as well. 

Please let me know, in a normal setting, how would you create dataset of custom objects X ? 
X is a separate class defining properties of custom objects.

**Comment by haifengl** [comment]
You should use maven for dependency. If you cannot, I guess that you copy only smile-core to your lib directory, you should at least also include smile-math and smile-data. If you google about this kind of basic java package problems.
