### ISSUE TITLE
How to optimize DBScan for high dimensional and large volume of data 

### ISSUE THREAD

**Issue by harry-2016** [haifengl/smile#291]
I have a data of some 50k(approx) rows with 6-8 columns in it. 

If i try to use dbscan to find outliers using kd trees its running like anything and not even stopping.

Most of the time i am getting no heap space(but i have given some 90GB) and some times cpu is waiting to greater extend.

I have ran this for some 20times and only once algorithm is working. 

Is there any way to optimize my epsilon and min points so that it will work.?

**Comment by haifengl** [comment]
Please provide the details how you call DBScan. Thanks.

**Comment by haifengl** [comment]
In smile shell, type `demo`. In the GUI, choose Clustering/DBScan and choose data `Chameleon/t7.10k`, which has 10k points. Just use the default parameters MinPts = 10 and Range = 10. DBScan can finish in 240 ms on my PC. Your settings on MinPts and Range may not be right.

**Comment by haifengl** [comment]
BTW, DBScan is designed for spatial data (2 or 3 dimensional).

**Comment by harry-2016** [comment]
Yeah i tried for Chameleon/t7.10k data. 

But for my data(which will be around 40k and 5-10 dimension) i cant optimize epsilon and min points. 

Is there any way that i can use smile DBScan for my data.?

**Comment by harry-2016** [comment]
dbscan(data, 300, 1000)

**Comment by harry-2016** [comment]
Or i have to use any other clustering algorithm.? like k-means ..

**Comment by harry-2016** [comment]
Or i have to use any other clustering algorithms like kmeans.?

**Comment by haifengl** [comment]
Please provide detailed information. What's exactly `data`? Is it the raw array or KDTree? You should pass KDTree. Lacking of information, it is really hard to help you. In the future, please follow our ticket template.

MinPoints = 300 is absolutely too big. Range = 1000 seems very large although I have not see your sample data yet.

Also I suggest you read the DBScan paper first.

**Comment by harry-2016** [comment]
Data will be raw array.

yeah i tried with  min ponits to 20 and epsilon from 100 to 1000.

>

**Comment by haifengl** [comment]
Please share some sample data. And pass in KDTree, not the raw array.

**Comment by harry-2016** [comment]
okay thanks..
As of now will pass data as KDTree.
Will share sample data soon.

>
