### ISSUE TITLE
SVM Implementation of evict method

### ISSUE THREAD

**Issue by sreendra** [haifengl/smile#294]
Hi Heifeng Li,
I am looking at the implementation of the code.

Can you look at this method.

void evict() {
            minmax();
            
            for (int i = 0; i < sv.size(); i++) {
                SupportVector v = sv.get(i);
                if (v != null && v.alpha == 0) {
                    if ((v.g >= gmax && 0 >= v.cmax) || (v.g <= gmin && 0 <= v.cmin)) {
                        sv.set(i, null);
                    }
                }
            }
        }

Where as in the paper,

4)i←argmaxs∈Sgs withαs<Bs j ← argmins∈S gs with αs > As
Foralls∈S suchthatαs =0
If ys =−1 and gs ≥gi then S=S−{s} 
If ys =+1 and gs ≤gj then S=S−{s}

Is the statement,0 >= v.cmax equivalent to ys = -1 ? Is it not v.cmax == 0 ?

Thanks,
raveendra

**Comment by haifengl** [comment]
Which paper do you refer to?

**Comment by haifengl** [comment]
Your guess is right. Note the code

```
            if (y > 0) {
                v.cmin = 0;
                v.cmax = weight * Cp;
            } else {
                v.cmin = -weight * Cn;
                v.cmax = 0;
            }
```

Mathematically, it should be `v.cmax == 0`. But for numeric stability with FPU, I use `0 >= c.cmax` instead of `v.cmax == 0`.
