### ISSUE TITLE
SVM predict original probability

### ISSUE THREAD

**Issue by SCpRoION** [haifengl/smile#298]
Is there any way to get SVM classifier original probability before prediction?
I mean, there is a method `int predict(T x)` which calls `double predict(T x)` for two classes case and does this:
`
            if (svm.predict(x) > 0) {
                return 1;
            } else {
                return 0;
            }`

But I want to know that double value from private method.

Thank you for your attention and this great library!

**Comment by haifengl** [comment]
We could make it public for two-class case. But first of all, it is not probability at all.

**Comment by SCpRoION** [comment]
Is it a distance value to the dividing hyperplane according to the chosen kernel?

**Comment by SCpRoION** [comment]
It would be very helpful for me at least. By the way, I can try to write it myself, but first of all I need `public double predict(T x)` method.

**Comment by SCpRoION** [comment]
I've found now, that there is already implemented Platt scaling algorithm with probability method for SVM. It's my oversight, I haven't understood you correct.

I think, the issue may be closed. Thanks once again for this helpful library!

P.S.
For those, who are interested in the answer: to get probabilities from SVM classifier you should call 
`trainPlattScaling()` method after `finish()`-ing SVM training and then you can call `predict(T x, double[] prob)` method instead of `predict(T x)` to get expected probabilities.
