### ISSUE TITLE
Add support for missing values in decision tree

### ISSUE THREAD

**Issue by monapasan** [haifengl/smile#303]
Currently, when having numerical features as input for a decision tree algorithm, there is no way to mark a value of the value as missing. This, however, can happen quite often when working with the real data.

**Comment by haifengl** [comment]
check out smile.imputation package. We provide several ways to impute missing values. This is more generic and work for other classification algorithms.

**Comment by monapasan** [comment]
@haifengl Thank you for the prompt answer!
Imputing the numerical values does not make sense In the case where a missing value actually has a mining, rather than missing at random.
For example, in case of nominal features, it's possible to encode a missing value as a new category.
For numerical features, it would be very helpful to have a similar way of doing that.
For decision tree, it would mean that when splitting on a numerical feature there would be an additional check on equality to the missing value(representation of missing value, e.g. Double.NaN).

**Comment by haifengl** [comment]
This will be a big change. Typically decision trees are binary trees. What you suggest is something like three-value-logic in database domain. Also this logic is different from the standard way to handle missing values in CART. I am afraid that it will introduce confusions to other users. Lastly, this design will be highly unstable given the ratio of missing values.

Therefore, I don't intent to implement it. I suggest that you discretize your numeric variable and encode missing values properly first. This work around is not perfect but should be sufficient in many cases.

**Comment by monapasan** [comment]
@haifengl yeah, that sounds like a good workaround! What is in your opinion would the best way to create range buckets out of the numerical features? One way of doing it can be to choose amount of buckets you want to have and split the value by percentile so every bucket would have the same amount of observations.

**Comment by monapasan** [comment]
Hey @haifengl !
I have created a PR with the support of missing values.
On a split, missing values will be sent to the majority direction. Functionally it's the same as in `rpart` package with `usesurrogate=2`, but with a possible split on a missing value.
Please let me know if it's possible to merge it.

**Comment by monapasan** [comment]
#306
