### ISSUE TITLE
Reduce initial size of order array while building FP Tree in Association Rule Mining

### ISSUE THREAD

**Issue by akshanshjain95** [haifengl/smile#304]
Hi,

I was wondering why the initial size of `order[]` array is equal to the total number of items in the itemset. It can be reduced to just the maximum id of the header table + 1, as it is only used to access the header table item positions.

```Java
public FPTree(int[] frequency, int minSupport) {
        this.itemSupport = frequency;
        this.minSupport = minSupport;

        root = new Node();
        
        numItems = frequency.length;
        for (int f : frequency) {
            if (f >= minSupport) {
                numFreqItems++;
            }
        }
        
        // It greatly improves the performance by making header table of
        // size numFreqItems instead of numItems. The reason is that numFreqItems
        // is usually much smaller than numItems and it is time consuming to
        // sort a large array.
        headerTable = new HeaderTableItem[numFreqItems];
        for (int i = 0, j = 0; i < numItems; i++) {
            if (frequency[i] >= minSupport) {
                HeaderTableItem header = new HeaderTableItem(i);
                header.count = frequency[i];                        
                headerTable[j++] = header;
            }
        }
        
        Arrays.sort(headerTable);
        order = new int[numItems];
        Arrays.fill(order, numItems);
        for (int i = 0; i < numFreqItems; i++) {
            order[headerTable[i].id] = i;
        }
    }
```

Furthermore, array `o[]` in the below code snippet can also be initialized to the number of frequent items in the passed itemset instead of the whole itemset's length and can be made to hold only the frequent items in the itemset, and another array can be created which consists of the frequent items in the given itemset and can be used with the new `o[]` for further quick sorting.

```Java
public void add(int[] itemset) {
        numTransactions++;
        
        int m = 0;
        int t = itemset.length;
        int[] o = new int[t];
        for (int i = 0; i < t; i++) {
            int item = itemset[i];
            o[i] = order[item];
            if (itemSupport[item] >= minSupport) {
                m++;
            }
        }

        if (m > 0) {
            // Order all items in itemset in frequency descending order
            // Note that some items may have same frequency. We have to make
            // sure that items are in the same order of header table.
            QuickSort.sort(o, itemset, t);
            
            // Note that itemset may contain duplicated items. We should keep
            // only one in case of getting incorrect support value.
            for (int i = 1; i < m; i++) {
                if (itemset[i] == itemset[i-1]) {
                    m--;
                    for (int j = i; j < m; j++) {
                        itemset[j] = itemset[j+1];
                    }
                }
            }
            
            root.add(0, m, itemset, 1);
        }
    }
```

This will help in increasing the memory efficiency and working on smaller arrays will certainly help in making the algorithm a little faster.

**Comment by haifengl** [comment]
We expect the item IDs are compact, that is in the range of [0, numItems). For any meaningful data, the header table size is about numItems. BTW, numItems is typically a small number. I don't see that such a change will change the footprint of program notably.

**Comment by haifengl** [comment]
Thanks for you effort. But I prefer simple code than a change that has very minimal impact on the performance. Actually, I don't expect any benchmark difference for this change. Have you run the unit tests to check the run time?

**Comment by akshanshjain95** [comment]
Hello @haifengl 
Yes, I ran all the test cases. For small data like the hardcoded one and the Pima file, there wasn't any significant improvement, but for a little larger data, i.e., Kosarak file, there was a significant improvement. I have attached the screenshots of the results of Kosarak test case generated from both the current and proposed implementation.

Current implementation(Kosarak) -
![old_implementation](https://user-images.githubusercontent.com/29911091/39226374-bffc6212-486f-11e8-884a-05b5b68b0fd1.png)

Proposed implementation(Kosarak) -
![new_implementation](https://user-images.githubusercontent.com/29911091/39226384-cc105ea0-486f-11e8-997b-035b7f6380c7.png)

This kind of improvement suggests that for actual data the algorithm would turn out to be much faster than the current version. Plus, the implementation hasn't changed a lot, and as far as I can tell, the implementation is still simple. I think keeping the code almost the same with very few changes and getting a good amount of improvement in terms of performance would be a good enhancement for the algorithm.

Please ping back with your thoughts on this, and any improvement that could be done.

Thank you!

**Comment by haifengl** [comment]
BTW, in the future, please don't create both a ticket and PR for the same thing. We can exchange comments in the PR too. Thanks.

**Comment by haifengl** [comment]
Your change is about building FT-Tree. I don't see there is real difference for that part. The time difference in the frequent item set mining should be caused by other reasons.

**Comment by akshanshjain95** [comment]
Hello @haifengl 
Can you please tell me how many threads are spawning for you? My machine is spawning 4 threads, so maybe there is a difference between the number of threads between our machines.

Considering there is a difference in the number of threads, wouldn't it be better for the algorithm to be implemented while keeping in mind machines with low thread-pool, as in my case the performance difference is huge.

> BTW, in the future, please don't create both a ticket and PR for the same thing. We can exchange comments in the PR too. Thanks.

I'm sorry about this. I will keep this in mind.

> Your change is about building FT-Tree. I don't see there is real difference for that part. The time difference in the frequent item set mining should be caused by other reasons.

In the FP-Growth algorithm, various **conditional FP-Trees** are being built when mining the frequent itemsets. In FPGrowth.java, in the grow() method at line 324, the else case spawns an FP-Tree at line
385. So, a change in the building of FP-Tree would also matter on the performance of the mining algorithm.

Please ping back with your thoughts on this, and any improvement that could be done.

Thank you!
