### ISSUE TITLE
Neural Gas In Scala

### ISSUE THREAD

**Issue by AT-Mohamed** [haifengl/smile#307]
Hello, 
I'm  working on a new approach for clustering datastream using neural gas in Scala language, i recoded the smile neural gas in Scala but the problem is that i don't get the same centroids in output, here's my scala code and the output compared to the java code output .

Scala Code:
for (t <- 0 until steps) {

          val tf = (t / steps).toDouble
          val lambda = lambda_i * Math.pow(lambda_f / lambda_i, tf)
          val eps = eps_i * Math.pow(eps_f / eps_i, tf)
          for (j <- 0 until n) {
            var signal= data(j)
            for (l <- 0 until k) {
              nodes(l).dist = euclidian(nodes(l).w, signal)
            }

            //
            nodes.sortWith(_.dist < _.dist)
            for (i <- 0 until k) {

              val delta: Double = eps * Math.exp(-(i) / lambda)
              if (delta > 0) {
                for (m <- 0 until d) {
                  nodes(i).w(m) += delta * (signal(m) - nodes(i).w(m))
                  println(signal(m) - nodes(i).w(m))

                }
              }
            }

          }
      }

JAVA
3.7911102514135093  0.9994011843199987   
7.54548170323517  2.085250219578483   
1.9719372013411223  4.88880114371598   
-0.005374434336144141  -0.003986091101522487   
5.108612573275283  7.972694630422137   
8.546589251170682  6.128490755437161

SCALA
9.00393086512124  6.858672693796663   
9.039059915577358  6.6543733359569694   
8.967302788037278  6.485539949609361   
8.862522534679464  6.371978138261647   
8.760161241402418  6.3032538365366575   
8.677095960267335  6.258864107961748  
Thank you,

**Comment by haifengl** [comment]
Thanks for using smile. Due to limited time and resource, we are not able to debug other's code.
