### ISSUE TITLE
Error calculation typo in LogisticRegression demo?

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#311]
In **smile.demo.classification.LogisticRegressionDemo**, do we need to use a new array to store the prediction result and use that for comparison instead of using same label array? I could help to submit a PR to fix this if it is a typo @haifengl 

![image](https://user-images.githubusercontent.com/1487283/40157407-66f57618-59d1-11e8-8bb3-d724f5ae141f.png)

**Comment by haifengl** [comment]
It should be a bug. Let me fix it. Thanks.

**Comment by rayeaster** [comment]
multiple demo files might have same issue

**Comment by haifengl** [comment]
I fixed all of them. Thanks.
