### ISSUE TITLE
Fix spelling of DBSCAN

### ISSUE THREAD

**Issue by kno10** [haifengl/smile#313]
The DBSCAN algorithm is incorrectly spelled "DBScan" throughout smile.

**Comment by haifengl** [comment]
Since you care about it, can you fix and make a pull request? Thanks.

**Comment by kno10** [comment]
I don't actually use Smile.

As this will break APIs when renaming the class, it is probably something you should decide how you want to handle a transition. E.g. by renaming the class to DBSCAN but adding a DBScan legacy subclass instead. Or just postpone this to the next major release.

Just the documentation change is of course an easy s/DBScan/DBSCAN/ - except for class names...
