### ISSUE TITLE
integration with apache spark

### ISSUE THREAD

**Issue by Ranganaths** [haifengl/smile#319]
## Expected behaviour
Use SMILE library with Apache spark

## Actual behaviour
I dont see the support for the Apache Spark Dataset, like how we can work in R programming

**Comment by haifengl** [comment]
Why Spark for only 10000 samples? You can train it with smile directly on a single machine. Smile take simple `double[][]` as input for most algorithm. If you have to use spark, extract data from your RDD or DataFrame to `double[][]`.

**Comment by Ranganaths** [comment]
well its not abiout 10k samples.. basically i was looking for seemless integration with Spark DataSet like how we do with the R.

**Comment by haifengl** [comment]
If you have to use Spark, I assume that the data is too big to be trained by smile. You can still use smile with Spark for prediction though.

**Comment by rayeaster** [comment]
@haifengl  just curious how to use smile with Spark for prediction if the model is not trained within smile? smile support model import from Spark?

**Comment by haifengl** [comment]
@rayeaster no.
