### ISSUE TITLE
Is there an easy way to calculate multiclass precision, recall and F-Measure validation?

### ISSUE THREAD

**Issue by owlmsj** [haifengl/smile#32]
Given two vectors, the predicted and the truth, filled with multi class numbers is there an easy way to computate precision, recall and f-measure?

Example:

predicted = [0,2,1,3]
truth         = [0,1,2,3]

**Comment by haifengl** [comment]
Check out the package smile.validation. We have all of them (and something else) there.

**Comment by owlmsj** [comment]
Sure, but in Precision, Recall and FMeasure implementation is only for one-class validation, right? It test 0 (false) and 1 (true), not the class-number. Or what am I doing wrong?

**Comment by owlmsj** [comment]
This question is like in this link : http://stats.stackexchange.com/questions/51296/how-to-calculate-precision-and-recall-for-multiclass-classification-using-confus

**Comment by haifengl** [comment]
Ok. Let's create a class to calculate confusion matrix and then update these measure classes for multi-class.

**Comment by owlmsj** [comment]
Hi, I did that in meantime. Any suggestions about this new class name?

**Comment by haifengl** [comment]
ConfusionMatrix should be fine. You can make a pull request and we can start from there. Thanks!

**Comment by owlmsj** [comment]
Okay! Just a little con: Project 'Smile' is missing required Java project: 'SmileTestData'	. Where can I find this project?

**Comment by haifengl** [comment]
SmileTestData contains various datasets that I download from internet. As I am not the owner of these datasets, I cannot include them in github.

**Comment by owlmsj** [comment]
Ah, no problem. I just remove the dependency and it was OK!

**Comment by haifengl** [comment]
The maven .pom files have no such dependency. Only for eclipse project files. BTW, SmileTestData is only for unit tests. You don't need them to compile the packages. Thanks!

**Comment by haifengl** [comment]
Thanks for the great work! The ConfusionMatrix is merged into master.
