### ISSUE TITLE
LDA, FLD, QDA algorithm implementation references

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#320]
@haifengl could please shed some light on following questions? Really appreciate your time.

1) in smile.classification.LDA, following code snippet calculate the cross variance matrix, is there any reason or reference about the usage of **_n-k_** at line 287?

![image](https://user-images.githubusercontent.com/1487283/41228964-d9b008fa-6dac-11e8-9a8c-ae52ac839b72.png)

and there exist some magic number for prediction, again, any reference would be great to understand.
![image](https://user-images.githubusercontent.com/1487283/41231296-37e86752-6db5-11e8-8199-958e301f343c.png)

2) in smile.classification.FLD, following code snippet calculate the desirable projection matrix, is there any reason or reference about the usage of code between line 289 and line 297? 

And It seems that the testing result on demo even better with those codes removed. Current version of code would result in a projection matrix directly from between class scatter matrix...

From smile documentation, the implementation seems not correct. But I tried `U.inverse().abmm(B)` which give worse result on demo data set than current implementation
![image](https://user-images.githubusercontent.com/1487283/41345842-54b63bba-6f37-11e8-889f-2eaac52fd021.png)

![image](https://user-images.githubusercontent.com/1487283/41229426-8c21801c-6dae-11e8-9f30-17219197920d.png)

3) in smile.classification.QDA, following code snippet calculate the discriminant function for classes(which is quite different from LDA), is there any reason or reference about the calculation?
![image](https://user-images.githubusercontent.com/1487283/41232115-daff1fce-6db7-11e8-8605-6ac143d67082.png)

**Comment by haifengl** [comment]
Check this paper https://ieeexplore.ieee.org/abstract/document/1498032/

**Comment by rayeaster** [comment]
@haifengl 
that is great reference and Thanks. Thought we could add the reference in the code for clarity. 
BTW, I checked the paper and submit a PR [here ](https://github.com/haifengl/smile/pull/322) you want to have a look at. 
Really appreciate your time.

**Comment by rayeaster** [comment]
another minor issue is about the prediction formula `f = ct[i] - 0.5 * f;` in LDA and QDA which I failed to find reference in the paper. Could you please mind to point it out? 
@haifengl

**Comment by haifengl** [comment]
LDA takes class labels when calculating `C`. PCA doesn't.

**Comment by haifengl** [comment]
For more details, check the book `Pattern Classification` by Duda, Hart, & Stork.
