### ISSUE TITLE
Bug in XMeans line 116-121

### ISSUE THREAD

**Issue by rbouadjenek** [haifengl/smile#321]
# Problem
@haifengl could you please check the following code in **lines 116-121** in:
https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/clustering/XMeans.java

![screenshot from 2018-06-13 14-20-13](https://user-images.githubusercontent.com/7735263/41370531-e4fe7434-6f15-11e8-8211-4d5cb1d9e4fc.png)

- In **line 116**, you are ordering the **score** array. However, according to the documentation of this function, it orders the array given in parameter, and returns **the original index** of elements after sorting.

![screenshot from 2018-06-13 14-32-01](https://user-images.githubusercontent.com/7735263/41370815-9a278da0-6f16-11e8-8074-2110ea26f3fc.png)

- The problem is that in **line 118**, you use the index obtained in **line 116** to access elements in the **ordred array and not the original array**. We have observed (with @Suri-Xiang, @Nhrishti, @ssanner) abnormal behavior of the XMeans algorithm.

# Solution

- The solution we propose is to copy the array **score** and sort that new copied array. Then, you can use the index obtained on the **score** array.
`double[] score_sorted = score.clone();`
`int[] index = QuickSort.sort(score_sorted);`
           ` for (int i = 0; i < k; i++) {`
                `if (score[index[i]] <= 0.0) {`
                    `centers.add(centroids[index[i]]);`
               `}`
            `}`

**Comment by haifengl** [comment]
What abnormal behavior do you observe? Thanks.

**Comment by rbouadjenek** [comment]
If the minimum number of clusters is set to kmin=10 **(we modified a little bit the original algorithm)**, the algorithm may return a lower number of clusters. This is due to this sorting bug.

**Comment by haifengl** [comment]
I think that we just change line 118 to

```
if (score[i] <= 0.0)
```

The lines 116 - 121 are to keep old clusters without split.

**Comment by rbouadjenek** [comment]
yes, you can also change line 118 to 
`if (score[i] <= 0.0)`

thanks.

**Comment by haifengl** [comment]
I fixed the bug in X-Means and G-Means. The fix is available in master branch now.

**Comment by rbouadjenek** [comment]
Thank you very much :)
On behalf of: @Suri-Xiang, @Nhrishti, @ssanner 

best,
reda
