### ISSUE TITLE
Incremental Learning using SVM

### ISSUE THREAD

**Issue by vamsigp** [haifengl/smile#326]
@haifengl could please help us with the following questions?

I have a huge dataset.
I am using SVM with Linear Kernel.

We trained 2 models on same data, 
1. Using complete data at once
2. Divided the complete dataset into multiple parts and trained the model incrementally, by calling SVM::train() followed by SVM::finish() in a loop for all the parts.

I tested both model-1 and model-2 on same test data, observation is as below - 
 - complete batch training, the testing accuracy comes upto ~87%
 - Incremental training with multiple parts, the final testing accuracy comes to ~82%. If I increase the number of parts, the final accuracy decreases further.
 eg - with 100 parts, accuracy = 82%
	 with 200 parts, accuracy = 80%

Model accuracy decreases with Incremental Training, Is this the expected behaviour?
Am I following correct approach for Incremental Training?

one more query, Is there a way to set the Initial Learning Rate as we do in SGD?

**Comment by haifengl** [comment]
The overall process is okay. In fact, our SVM implementation is incremental by natural. The SVM::finish() is to refine learned support vectors. However, it is several things that you may try to improve the results:

1. Make sure your data is randomized. Note that you have 100 or 200 parts. So each part may not contain sufficient samples in each class.
2. How many sample do you have? If not too many, 100 or 200 parts are too many. Try smaller number of parts if so.
