### ISSUE TITLE
ARM returns millions of results

### ISSUE THREAD

**Issue by kalki123123** [haifengl/smile#327]
I am trying to elucidate association rules between different items from a shopping cart. I input around 1000x200 matrix to ARM. On some datasets, ARM generates millions of association rules. Even using Print stream, memory overflows in java.

I am sure number of association rules can be dictated by support and confidence. Is there any other way to restrict the number of association rules so that I dont run out of memory. 
Please let me know.

Regards
Prashant

**Comment by haifengl** [comment]
It is very common to generate millions association rules, which I didn't have memory issues if printing the results to a file. How much memory did you allocate to JVM? Try giving it more with -Xmx option.

**Comment by kalki123123** [comment]
Sure, It works fine when I try to give more memory with -Xmx option. I am wondering if there is a way to restrict the number of association rules generated. This would actually save time writing to file and reading a rule at a time.  Currently, I restrict results by way of setting high support and confidence.
Thank you for the quick reply.

**Comment by haifengl** [comment]
High support and confidence is the way to go. Not only reduce the number of generated rules, they also give you most important ones.
