### ISSUE TITLE
Smile Decision Tree gives less accuracy compared to scikit and H2O.ai

### ISSUE THREAD

**Issue by shikharsharma23** [haifengl/smile#328]
On the attached train and test files, scikit and h2o both give 99.6% (get 13 samples incorrect) accuracy and exact same results.  Both use maxDepth = 10 and decision tree as algorithms. 
But when using smile i get 26 examples incorrect 

     AttributeDataset train = parser.parse(" Train", new  FileInputStream("features_train.csv"));
     AttributeDataset test = parser.parse("Test", new FileInputStream("features_test.csv"));
    Attribute[] atr = train.attributes();
    double[][] x = train.toArray(new double[train.size()][]);
    int[] y = train.toArray(new int[train.size()]);
    double[][] testx = test.toArray(new double[test.size()][]);
    int[] testy = test.toArray(new int[test.size()]);
    DecisionTree tree = new DecisionTree(x, y, 1024);

Consider for example file smilepred.csv where line 669 prediction is wrong. 

Features_train.txt : Training file 
Features_test.txt : Test File 
Scikitpred.txt : Scikit predictions (Column 1 is prediction and Column 2 is actual tagged value)
h2opred.txt : H2O predictions (Column 1 is prediction and Column 2 is actual tagged value)
smilepred.txt : Smile predictions (Column 1 is prediction and Column 2 is actual tagged value)

Model used is Decision tree with max depth 10 

[smilepred.txt](https://github.com/haifengl/smile/files/2163340/smilepred.txt)
[h2opred.txt](https://github.com/haifengl/smile/files/2163319/h2opred.txt)
[scikit_preds.txt](https://github.com/haifengl/smile/files/2163320/scikit_preds.txt)
[features_train.txt](https://github.com/haifengl/smile/files/2163313/features_train.txt)
[features_test.txt](https://github.com/haifengl/smile/files/2163312/features_test.txt)

Why does smile get few predictions wrong always . Is there some parameter i am missing ?

**Comment by rayeaster** [comment]
@shikharsharma23  did you compare the implementation? there should be some uncertainty or choice needed to make in decision tree building process even with same depth, especially with numeric features. Just my two cents.

**Comment by shikharsharma23** [comment]
Yes. I couldnt find any difference. All parameters appear to be same

**Comment by haifengl** [comment]
The max depth 10 doesn't mean 1024 leaf nodes in smile. These are two different regularization approaches. In general, 1024 is too big for many small/medium data size. You have only 2208 samples, 1024 leaf nodes are way too many.

**Comment by shikharsharma23** [comment]
Okay. Makes sense. Could you advise on what to do in order to attain the same accuracy as h2o and scikit ?

**Comment by haifengl** [comment]
Some hyperparameter tuning is needed. But for your case, some quick trail-n-fail should be sufficient to get similar results.
