### ISSUE TITLE
Add a testimonial page or link for smile users

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#329]
Thought testimonials from all kinds of areas and users across the world would give community more hint how smile actually used in various scenarios where machine learning is required. Also beneficial to attract more developers to contribute:)

Just a suggestion.

**Comment by JoshCason** [comment]
Fantastic, thanks!

**Comment by haifengl** [comment]
Add some testimonials to the project [homepage](http://haifengl.github.io/smile/). More will come.

**Comment by rayeaster** [comment]
testimonials added:
https://github.com/haifengl/smile/commit/314977c862906093af7148ccc12b7d449f964d2e
