### ISSUE TITLE
Boxplot: unable to create correct plot when series are different lengths

### ISSUE THREAD

**Issue by lwhite1** [haifengl/smile#33]
Hi, and thank you for this awesome library.

I'm unable to create a correct multi-box boxplot when the number of observations differs between the boxes.  

For example, I want to create a plot on a dataset where the data of interest is a person's age, and there is one "box" displayed for males and a second for females.  If there are more males, the box for females depicts observations at 0.0 for each observation that has no value.  This throws off the distribution.  

In the attached plot image, the dataset has no actual 0.0 values, but some are depicted.

I tried initializing my dataset to Double.NaN before filling it, but this caused problems with rendering the graph. 

Thank you again for SMILE. 

![boxplot](https://cloud.githubusercontent.com/assets/3430274/7616715/e9b25af0-f9a6-11e4-9089-4a996ce24017.jpg)

**Comment by haifengl** [comment]
Can you please share your code and samples for debugging? Thanks!

It should be fine for groups with different size. Please note that for input matrix, each row is a group. In your case, the input 2-d array should have two rows and each row is for male or female data, respectively. Do you input data with 2 columns?

**Comment by lwhite1** [comment]
Sorry, I was under the impression that a 2D array in java needed to have
the same length for all rows.  Let me see if I can fix my code and I will
update the issue.

thanks

**Comment by haifengl** [comment]
If you do

new int[2][10]

yes, it has the same length for all rows. but you can do

new int[2][]

and then allocate each row separately with different size.

**Comment by lwhite1** [comment]
The problem was in my code. Sorry to trouble you.
