### ISSUE TITLE
Gaussian Mixture Model implementation

### ISSUE THREAD

**Issue by josiasjr** [haifengl/smile#331]
I am porting a scikit-learn GMM code for Scala in my local repository. Do it have to do in Java to be submitted?
[http://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html](url)

**Comment by haifengl** [comment]
We have Gaussian Mixture Model implementations. They are in the class of MultivariateGaussianMixture. We actually support more advanced mixture model in MultivariateExponentialFamilyMixture. Thanks.
