### ISSUE TITLE
Mention how to use in Jupyter notebooks in docs?

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#333]
Smile can be used in Jupyter notebooks, which I've found to be a really great experience. Screenshot below

![screenshot from 2018-07-12 23-07-56](https://user-images.githubusercontent.com/322311/42675470-1cbdd41c-8629-11e8-852a-5d91f1d4628d.png)

Details which could be included in the documentation are:

Smile can be used in [Jupyter](http://jupyter.org) notebooks by installing the [BeakerX](http://beakerx.com) extension, which provides JVM support. After you've installed Jupyter and BeakerX, [check out this example notebook using Smile](https://github.com/twosigma/beakerx/blob/master/doc/groovy/Tablesaw.ipynb)

**Comment by rayeaster** [comment]
This is great and attractive feature for pythoners :)

**Comment by haifengl** [comment]
Add a jupyter-beaker example page on the project website. Thanks.
