### ISSUE TITLE
Return fitted values for OLS

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#334]
Smile's OLS model lacks a function to return the fitted values for each input. The relationship of fitted values to residuals is used to identify regions in the input data where the model doesn't fit well. This is something that many other statistics packages provide

**Comment by haifengl** [comment]
We can add that function. Currently you work around with the function `residuals`. It is easy to calculate the fitted values from it.

**Comment by haifengl** [comment]
Add `getFittedValues()` method.

**Comment by benmccann** [comment]
Thanks!!

**Comment by lwhite1** [comment]
Thanks very much for adding this. 

Do you have any idea when we'll see a release in maven central with this change?
