### ISSUE TITLE
KModes.scala

### ISSUE THREAD

**Issue by henryhyu** [haifengl/smile#339]
What format is the input dataset being read as? I see that it is an Array[Array[Int]] but is the input the one hot encoded feature vectors or what? In you code it seems you do val modes = Array.fill(k) {
    Array.fill(p) { Random.nextInt(2) }
  } where you only use binary numbers. Examples on how to use your algorithm would be nice. Thanks

**Comment by haifengl** [comment]
On the right, click the package `smile` and it will show the classes. It used to work. Not sure if a change in scaladoc format. Will investigate. Thanks.

**Comment by haifengl** [comment]
K-modes supposes working on binary data therefore the input should be either 0 or 1. It is a new added algorithm. We will add more documents and examples.
