### ISSUE TITLE
## RBFNetwork

### ISSUE THREAD

**Issue by yzhang672** [haifengl/smile#344]
## Expected behaviour

E.g. Train a RandomForest on my data which has 10000 samples and 10 attributes, which are ....

## Actual behaviour

E.g. The algorithm throws an exception. Here is the stack trace...

## Code snippet

E.g. The code to parse data and the call of Smile algorithm.

## Input data

E.g. sample data

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
- Which Smile version
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )

**Comment by yzhang672** [comment]
How to save the trained RBFNetwork or NeuralNetwork for future usage?  How to set parameters (distance, rbf, centers) for RBFNetwork?  Any example codes in Java?  Thank you very much!

**Comment by haifengl** [comment]
See [the project website](http://haifengl.github.io/smile/classification.html) how to train a model.

```
    val centers = new Array[Array[Double]](50)
    val basis = gaussrbf(x, centers)
    val classifier = rbfnet(x, y, new EuclideanDistance, basis, centers)
    plot(x, y, classifier)
```

You can save a model as shown in [FAQ](http://haifengl.github.io/smile/faq.html).

**Comment by yzhang672** [comment]
Thank you very much for your reply!! I really appreciate it!


Have a great rest of your summer!


Best,

Yilin

________________________________
