### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by digital-thinking** [haifengl/smile#346]
I noticed that its very easy to reach the memory limit, when training an SVM in NLP context. I have used [this](https://www.kaggle.com/c/twitter-sentiment-analysis2/data) data with a simple bag of words approach (dictionary with 100k features).

Using 30k training samples already exceeds 16 GB of memory. This is happening even if I use batched training, calling train + finish on batches. Seems like the SVM is using a lot of support vectors. 

Is there any way how to overcome this issue?

**Comment by haifengl** [comment]
30k x 100k of course takes a lot of space. But your data should be highly sparse. I suggest that you use a sparse encoding of your data and create a customized kernel that recognizes your data format. In fact, some of our kernels take sparse encoding. Check out `BinarySparse*Kernel` classes in the package `smile.math.kernel`.

**Comment by digital-thinking** [comment]
Thanks for your quick response. I am currently using SVM<SparseArray> and the SparseLinearKernel, so it should be ok, right?

**Comment by haifengl** [comment]
Yes.
