### ISSUE TITLE
fastICA implementation

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#347]
typical use case is 'cocktail party problem' where to identify original speakers from mixed audio recordings:

https://www.cs.helsinki.fi/u/ahyvarin/papers/TNN99new.pdf
https://en.wikipedia.org/wiki/FastICA

**Comment by haifengl** [comment]
They are not really machine learning algorithm. But if you want, you may implement it in the `math` module.

**Comment by rayeaster** [comment]
glad to help:) But why not add it to projection package in core like PCA?

**Comment by haifengl** [comment]
Maybe. Can it support the methods of `Projection` interface?

**Comment by rayeaster** [comment]
of course:)

**Comment by haifengl** [comment]
ICA is not a projection. It is wrong to use the final result as a projection matrix. Besides, there are several mathematical mistakes in your implementation (maybe confused by the signal/source, i.e. row/column). Thanks

**Comment by haifengl** [comment]
BTW, you should avoid matrix multiplication route (N^3) when one matrix is diagonal. It can be done in O(N^2).
