### ISSUE TITLE
Gaussian process question

### ISSUE THREAD

**Issue by chdamianos** [haifengl/smile#348]
Just a quick question. Does smile optimize the kernel parameters and lambda when performing Gaussian process regression? 

For example if I initialize the Gaussian kernel with a gamma of 0.8 and a lambda of 0.01, will the regression try to find an optimal gamma and lambda based on a loss like the loglikelihood?
```Java
GaussianKernel gpKernel = new GaussianKernel(0.8);
GaussianProcessRegression<double[]> gp = new GaussianProcessRegression<double[]>(x, y, x, gpKernel, 0.01);
```
I just started with Java a couple of days ago but looking through the code it looks like the code solves for `y` based on the Cholesky decomposition without any optimisation on the kernel parameters (e.g. gamma) and lambda.

**Comment by haifengl** [comment]
No. They are hyper-parameters.
