### ISSUE TITLE
SmileTestData is missing?

### ISSUE THREAD

**Issue by gohawks3** [haifengl/smile#35]
I downloaded the code but it doesnt load in Eclipse complaining smiletestdata is missing?

**Comment by haifengl** [comment]
Hi SmileTestData contains the datasets that I download from internet. As I don't own them, I cannot publish it in github. They are only used for unit tests. You can remove the dependency in eclipse or create a dummy project there. Thanks!

**Comment by ashrafs** [comment]
please  send us  link for download dataset used in regression part or name of dataset

thanks

**Comment by haifengl** [comment]
1. weka
2. usps ocr
3. uci machine learning repo
4. chameleon
5. many others

**Comment by ashrafs** [comment]
please I  my project indoor location and I use  SVR Regression
I need train svr offline using x,y location and received signal strength wifi  in my location and build model after that predict new location for  new signal strength will come online phase
in SVR Code published  Predict function in SVR takes an array of numbers as input and returns ONE numeric value as output. but I have two instances, for X and Y.
 public double predict(T x);{
}
the question :
I can train two dimensional x,y together or each coordinate is considered as one output of SVR and trained independently ?
thanks

**Comment by haifengl** [comment]
Are you predicting signal strength based on location? If so, it is doable with SVR.

But if you predict location based on signal strength, it is impossible.

**Comment by ashrafs** [comment]
I need predict location based signsl strength. 
I Must train all diminsion for  all coordinate xy independent. 
train x
train y
for solve this problem?
or whats your suggested solution
many thanks

**Comment by haifengl** [comment]
In general, many locations have same signal strength. It is a one-to-many mapping (from signal strength to locations). It is not a function at all. Note that supervised learning is just to fit a function.

**Comment by ashrafs** [comment]
Let consider the location doesn't have same signal strength from all access point in same time must be different values .
we will consider it  fingerprint .
I can train all diminsion for xy and use svr
I read some paper use svr indoor wlan localization its doable? Because I have real
Value data and I must use regression.

**Comment by haifengl** [comment]
It is impossible for a mapping from low-dimensional to higher-dimension to be one-to-one mapping. In case of wlan localization, the intrinsic dimension is one if the signal is restricted to a very narrow area. That is what you want to fit. Then with some other information (e.g. your signal source location and direction), you map decouple it to (x, y). BTW, SVR has no advantage for this low dimensional problem.

**Comment by ashrafs** [comment]
Yes I use orientation when record signal strength as measure value and I do 4 cluster for all orientation measured and I will train all cluster for all orientation (north south east wast) using svr.
I must do train for x and another train for y for all 4 cluster stored? In this case it douable?
 Thanks alot for your support

**Comment by haifengl** [comment]
As I said, you should fit with something like distance instead of (x, y). then you reconstruct (x, y) with additional information.

**Comment by ashrafs** [comment]
lAverage": -93,
      "levelVariance": 0,
      "levels": [
        -93,
        -93,
        -93,
        -93
      ],
      "ssid": "MCIT_SV"
    },
    {
      "bssid": "00:21:d8:d6:5d:60",
      "frequency": 2437,
      "levelAverage": -81,
      "levelVariance": 9,
      "levels": [
        -82,
        -86,
        -79,
        -77,
        -82
      ],
      "ssid": "MCIT_SV"
    },
    {
      "bssid": "00:21:d8:d6:5c:f0",
      "frequency": 2462,
      "levelAverage": -50,
      "levelVariance": 1,
      "levels": [
        -51,
        -51,
        -48,
        -51,
        -50
      ],
      "ssid": "MCIT_SV"
    },
    {
      "bssid": "00:21:d8:d6:6f:a0",
      "frequency": 2412,
      "levelAverage": -81,
      "levelVariance": 1,
      "levels": [
        -82,
        -82,
        -82,
        -80,
        -80
      ],
      "ssid": ""
    },
    {
      "bssid": "00:21:d8:d6:02:90",
      "frequency": 2437,
      "levelAverage": -86,
      "levelVariance": 20,
      "levels": [
        -91,
        -82
      ],
      "ssid": "MCIT_SV"
    },
    {
      "bssid": "00:22:55:73:bc:20",
      "frequency": 2412,
      "levelAverage": -89,
      "levelVariance": 0,
      "levels": [
        -89,
        -89
      ],
      "ssid": ""
    },
    {
      "bssid": "00:21:d8:d6:5c:50",
      "frequency": 2437,
      "levelAverage": -92,
      "levelVariance": 0,
      "levels": [
        -92,
        -92
      ],
      "ssid": ""
    },
    {
      "bssid": "00:21:d8:d6:a2:ba",
      "frequency": 2412,
      "levelAverage": -92,
      "levelVariance": 0,
      "levels": [
        -92
      ],
      "ssid": ""
    },
    {
      "bssid": "00:21:d8:4a:02:83",
      "frequency": 2462,
      "levelAverage": -93,
      "levelVariance": 0,
      "levels": [
        -93
      ],
      "ssid": ""
    }
  ],
  "sampleCount": 5,
  "time": "2015-03-25 10:47:47.027"



data have noise and I record alot of features for location in offline phase
how I can measure distance?
Sample from data stored for one location xy as below

**Comment by ashrafs** [comment]
I take 5 sample scanning measure rssi offline for same xy and take average of measure and variance.
data have noise because wlan with temperature and attunation and other factor.
For that I will use gauss kernel transformation nonlinear data I have.
