### ISSUE TITLE
In-Consistent decision tree when order of features is shuffled

### ISSUE THREAD

**Issue by ishaan007** [haifengl/smile#353]
Hi ,
When I train the a decision tree model using SMILE module, I get different results on different runs. The only difference between various runs is the order of the features. The features are exactly similar (just the order is different). Is this the expected behaviour ? If yes, is there any parameter in the api call which I can tweak to get consistent results ir-respective of the order of features (maybe some sorting of features) . I am using the following code. @haifengl  any help is appreciated.

```
String[] featureNames = new String[featureHeaders.size()];
featureNames = featureHeaders.toArray(featureNames);
Attribute[] attributes = new Attribute[featureNames.length];
for (int i = 0; i < featureNames.length; ++i)
{
  attributes[i] = new NumericAttribute(featureNames[i]);
}
this.tree = new DecisionTree(attributes, featureMap, tags, TREE_NODES);

```

**Comment by ishaan007** [comment]
The order of features is static, what I meant to convey was that the order of training examples is shuffled so features say F1,F2,F3 are still in same order just that rows/training examples R1,R2,R3.... are now in a shuffled order say R1,R3,R2. And I am getting different decision trees in those two cases. Is this the expected behaviour ?

**Comment by haifengl** [comment]
In general, they should not. But maybe you have samples with same values. We sort samples for each numeric features first. If you shuffle the samples, the order may be different for samples with same values, then the results may be slightly different.

**Comment by ishaan007** [comment]
Yes you are spot on, I am guessing the sorting is an internal mechanism . As far as I know, decision tree should not be affected by  the order of training examples when it tries to find the feature and associated splitValue with maximum information gain. It should be same in both the cases (irresepective of the order) because it is computed on a global set of combination of attribute and its value.

**Comment by myui** [comment]
Smile's [DecisionTree](https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/classification/DecisionTree.java#L495) uses [Math.permutate](https://github.com/haifengl/smile/blob/master/math/src/main/java/smile/math/Math.java#L882) using a thread local random number generator without random seed.

It's used for feature sampling. Better to have a way to fix the random seed.

**Comment by haifengl** [comment]
Each thread has a deterministic seed in v2.
