### ISSUE TITLE
add Isotonic Regression scaling for classification posteriori propability

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#354]
> An alternative approach to probability calibration is to fit an isotonic regression model to an ill-calibrated probability model. This has been shown to work better than Platt scaling, in particular when enough training data is available --- from Platt Scaling wiki page

https://www.cs.cornell.edu/~alexn/papers/calibration.icml05.crc.rev3.pdf

**Comment by rayeaster** [comment]
PR is here : https://github.com/haifengl/smile/pull/356

**Comment by rayeaster** [comment]
@haifengl and would you mind to share the reference for static method of `PlattScaling#multiclass()` which looks quite amazing?

**Comment by haifengl** [comment]
Probabilistic Outputs for Support Vector Machines and Comparisons to
Regularized Likelihood Methods

https://www.researchgate.net/profile/John_Platt/publication/2594015_Probabilistic_Outputs_for_Support_Vector_Machines_and_Comparisons_to_Regularized_Likelihood_Methods/links/004635154cff5262d6000000.pdf

**Comment by rayeaster** [comment]
Really appreciate!
