### ISSUE TITLE
does smile have dependency parsing like stanford nlp

### ISSUE THREAD

**Issue by yantraguru** [haifengl/smile#36]
http://nlp.stanford.edu/software/dependencies_manual.pdf

I would like to get subject from sentence. Example "Filters are not working properly in dashboard", I am looking to extract 
<Filters> - Subject 
<not working> - negative verb

I know stanford NLP dependency parser can extract this kind of information. Wondering if SMILE has similar capability.

**Comment by haifengl** [comment]
Unfortunately, we don't support it currently. Let me check if we can add this feature quickly. Thanks!
