### ISSUE TITLE
Error while training LogisticRegression on specific dataset

### ISSUE THREAD

**Issue by luffy2095** [haifengl/smile#361]
Hey,
I am training a logistic regression model on some sample dataset. 

I came across a specific data which gives error while training.
X = {{1,1},{1,1},{1,1},{1,1},{1,0},{1,0},{1,0},{1,0},{1,0},{1,0},{1,0},{1,0}};
Y = {0,1,2,3,0,0,1,1,2,2,3,3};
This gives error "Line Search: the search direction is not a descent direction, which may be caused by roundoff problem."

I was expecting output where each class has equal probability, which is however true in a similar dataset

X = {{1,1},{1,1},{1,1},{1,0},{1,0},{1,0},{1,0},{1,0},{1,0}};
Y = {0,1,2,0,0,1,1,2,2};

The only difference is that class '3' is removed.
Is this an expected behaviour?

**Comment by haifengl** [comment]
We don't support such kind of artificial data. You basically have only two unique data points (1, 1) and (1, 0) but assign them random labels. The objective function may not make sense at all and thus line search fails.
