### ISSUE TITLE
how to dump Logistic Regression model

### ISSUE THREAD

**Issue by joyang1** [haifengl/smile#362]
## Expected behaviour

I want to dump model.

## Actual behaviour

I don't find method to dump model.

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
jdk1.8
- Which Smile version 
1.5.1
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Ubuntu

**Comment by haifengl** [comment]
See FAQ http://haifengl.github.io/smile/faq.html
