### ISSUE TITLE
 java.lang.IllegalStateException: BFGS: Too many iterations.

### ISSUE THREAD

**Issue by joyang1** [haifengl/smile#364]
## Expected behaviour
No IllegalStateException

## Actual behaviour
Have  java.lang.IllegalStateException: BFGS: Too many iterations.

## Code snippet
Exception in thread "main" java.lang.IllegalStateException: BFGS: Too many iterations.
at smile.math.Math.min(Math.java:4679)
at smile.classification.LogisticRegression.<init>(LogisticRegression.java:261)
at smile.classification.LogisticRegression$Trainer.train(LogisticRegression.java:176)

## Input data
data is 5000000

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
1.8
- Which Smile version
1.5.1
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Ubuntu

**Comment by rayeaster** [comment]
> data is 5000000
is your memory large enough to hold that data?

**Comment by joyang1** [comment]
memory is enough, I use 80G memory.

**Comment by joyang1** [comment]
yes,it's ok when I using 10% of the data set.
I also have a question to ask you, How to use OneHot to train LR model?

**Comment by haifengl** [comment]
BFGS issues may be resolved by tuning hyper-parameters. Besides, if you are familiar with Java, please set a breakpoint to check the objective function values in the loop. Just to ensure we don't get `NaN` during the iteration.

**Comment by haifengl** [comment]
For sparse data (OneHot), you better use Maxent. Mathematically, it is same as LogisticRegression. But it is more efficient with sparse encoded data.
