### ISSUE TITLE
OOM when train LogisticRegression on big dataset

### ISSUE THREAD

**Issue by holysoros** [haifengl/smile#367]
## Expected behaviour

Train a LogisticRegression on my data which has 2 million samples and 10k attributes, which are OneHot encoded and very sparse.

LogisticRegression trainer accept `double[][]` and `int[]` as parameters, which assume the features is dense. A double type consume 8 bytes in JVM, so my dataset will consume 2m x 10k x 8 bytes = 160g 
 memory at least in concept. The fact that LogisticRegression trainer accepts feature parameter of `double[][]` type determines the upper bound of data size.

Any plan on LogisticRegression supporting Sparse Matrix?

## Actual behaviour

OOM when I prepare data of `double[][]` type to feed LogisticRegression trainer, because I just have 90G available memory.

**Comment by haifengl** [comment]
Use `Maxent`.

**Comment by holysoros** [comment]
Alright.
