### ISSUE TITLE
NLP initialisation breaks  on new SimpleCorpus

### ISSUE THREAD

**Issue by Xyclade** [haifengl/smile#37]
When I start a new project, and include smile (including NLP) from Maven.

Simply running the following code gives an initialization exception:

new SimpleCorpus();

The library seems to be missing the dictionary files.

Stacktrace: 

caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at smile.nlp.dictionary.EnglishStopWords.<init>(EnglishStopWords.java:59)
	at smile.nlp.dictionary.EnglishStopWords.<clinit>(EnglishStopWords.java:34)
	... 17 more

**Comment by haifengl** [comment]
Sorry for the issue. I have published SmileNLP 1.0.4 with resource files included. It works with my test app. Please have a try. Thanks!

**Comment by Xyclade** [comment]
@haifengl  no problem, I can't seem to find the SmileNLP 1.0.4 on Maven, do you have a download link for me?

**Comment by haifengl** [comment]
My test app uses sbt:

libraryDependencies += "com.github.haifengl" % "smile-nlp" % "1.0.4"

Can you try it later? Maybe the central repo takes some time to publish it. Thanks!

**Comment by Xyclade** [comment]
I've updated it now and it works, thank you!
