### ISSUE TITLE
Allow NumericAttribute to be used as labels

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#371]
## Expected behaviour

I have a dataset where the response variable is an integer (`1` or `0`). It seems most natural for this type of variable to be loaded into a `NumericAttribute`

However, `AttributeDataset` only allows for `labels`, to work on a `NominalAttribute`. I believe that `NominalAttribute` is meant to hold categorical variables. It's not clear to me why `NumericAttribute` cannot also be used as labels. I would like to submit a PR to remove this restriction if you agree

## Actual behaviour

I'm forced to convert my `NumericAttribute` to a `NominalAttribute` only for it to immediately be [converted back to an `int[]`](https://github.com/haifengl/smile/blob/master/data/src/main/java/smile/data/Dataset.java#L282). Otherwise, an exception is thrown stating "The response variable is not nominal." This is awkward, because it looks to me like [`NominalAttribute`](https://haifengl.github.io/smile/api/java/smile/data/NominalAttribute.html) accepts only `String[]`. I would rather not convert my `int` variables to `String` and then back again unless there's a compelling reason

## Input data

https://datahub.io/machine-learning/spambase

## Information

- Smile 1.5.2

**Comment by haifengl** [comment]
NominalAttribute is not Strings. Internally they are integers. NumericAttribute are double values and thus can be used as response in regression, not labels in classification.

**Comment by benmccann** [comment]
Ok. I understand better now the intended usage. Thank you

I've updated Tablesaw, so that the next version has improved Smile support based on this feedback. There are a couple examples of using them together here: https://github.com/jtablesaw/tablesaw/blob/06db8082afe113a091a1891682c9258e773f5cb9/core/src/test/java/tech/tablesaw/conversion/SmileConverterTest.java
