### ISSUE TITLE
SMILE LASSO vs R, Python

### ISSUE THREAD

**Issue by shanlodh** [haifengl/smile#373]
## Expected behaviour

SMILE LASSO output similar to normalize = True in sklearn or standardize = TRUE in glmnet

## Actual behaviour

Actual output seems to be more in line with normalize = False in sklearn or standardize = FALSE in glmnet

## Code snippet

```
        Reader in = new FileReader(filePath);
        Iterable<CSVRecord> records = CSVFormat.EXCEL.withHeader().parse(in);
        double[] yInputArray = new double[20];
        double[][] xInputArray = new double[20][4];
        int i = 0;
        for (CSVRecord record : records) {
            yInputArray[i] = Double.parseDouble(record.get("consump"));
            xInputArray[i][0] = Double.parseDouble(record.get("price"));
            xInputArray[i][1] = Double.parseDouble(record.get("income"));
            xInputArray[i][2] = Double.parseDouble(record.get("farmPrice"));
            xInputArray[i][3] = Double.parseDouble(record.get("trend"));
            i++;

       }
      LASSO smileLASSO = new LASSO(xInputArray, yInputArray, 0.03);

        double[] weights = smileLASSO.coefficients();

```

## Input data

Kmenta dataset from systemfit package in R, the consump variable is regressed on the remaining 

## Information

- JDK8
- SMILE 1.5.2
- Ubuntu16.04

**Comment by haifengl** [comment]
Smile doesn't have normalization in LASSO. Normalization/standardization can be done before the training with algorithms in `smile.feature`.
