### ISSUE TITLE
## Expected when I use  var c = Matrix.zeros(214952,214952),I  got an execption,java.lang.NegativeArraySizeException,but the Int range is beyond the number,How to solve this problem?

### ISSUE THREAD

**Issue by qingfengcss** [haifengl/smile#379]
## Expected behaviour

E.g. Train a RandomForest on my data which has 10000 samples and 10 attributes, which are ....

## Actual behaviour

E.g. The algorithm throws an exception. Here is the stack trace...

## Code snippet

E.g. The code to parse data and the call of Smile algorithm.

## Input data

E.g. sample data

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
- Which Smile version
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )

**Comment by haifengl** [comment]
It is beyond the java array index range. It is a limitation of JVM.

**Comment by qingfengcss** [comment]
> It is beyond the java array index range. It is a limitation of JVM.

Thank you so much, I have changed the size of matrix,it works
