### ISSUE TITLE
[Issue] Non-typical missing value imputation

### ISSUE THREAD

**Issue by inejc** [haifengl/smile#381]
I see that `AverageImputation` estimates row-wise means which are then used to fill the missing values. I believe this is non-typical (e.g. scikit-learn's [implementation](https://github.com/scikit-learn/scikit-learn/blob/bac89c2/sklearn/impute.py#L93) computes column-wise statistics instead). Are there any specific reasons for that implementation?

**Comment by haifengl** [comment]
row-wise means is very typical for sensor and biological data. All other algorithms in `smile.imputation` are essentially of column-wise. The difference is how to find the local scope, which is in general much better than the average of whole column.

Note that the whole column average doesn't make sense in machine learning. That means that we assume that all samples follow the same distribution for that attribute.

**Comment by inejc** [comment]
Can you please elaborate on the following:
_Note that the whole column average doesn't make sense in machine learning. That means that we assume that all samples follow the same distribution for that attribute._

We may be talking about two different things but I can't agree with your comment if I understand it correctly. If we don't assume that the distribution of inputs is fixed than learning itself isn't possible. We expect the future data to be distributed identically like the past. See [this](https://stats.stackexchange.com/a/214277/186222) comment from StackExchange.

I agree that the mean imputation technique where all missing data is replaced by a single value has its own problems though (e.g. reduces variance in the dataset).

Do you have any references for using row-wise means in the above-mentioned domains?

**Comment by haifengl** [comment]
I mean that each class has its own distribution (e.g. different means in case of Gaussian distribution). Calculating the mean of the mixture of all classes doesn't make much sense. All other algorithms in smile calculates the mean in a small neighborhood of the sample. The difference is how to find the neighbors.

**Comment by haifengl** [comment]
For reference, google some papers on microarray (gene expression). Each row is the expressions of a gene in different tissues/environments/patients/...

Row means is more meaningful because it is about the same gene. The column mean over all genes has no meaning.
