### ISSUE TITLE
Vulnerabilities detected in dependencies.

### ISSUE THREAD

**Issue by michellemay** [haifengl/smile#382]
We found that smile depends on a xstream version that have reported vulnerabilities:

https://snyk.io/vuln/search?type=maven&q=com.thoughtworks.xstream:xstream

Maybe this is only a matter of bumping up the version of xstream to 1.4.10 or more recent.

**Comment by michellemay** [comment]
According to the change logs of xstream (http://x-stream.github.io/changes.html)
All known vulnerabilities has been patched in 1.4.11.1

**Comment by haifengl** [comment]
It is upgraded to 1.4.11.1 now. Thanks.

BTW, only the scala module has this dependency. If you just use the core java smile libraries, you are fine.

**Comment by michellemay** [comment]
That was quick!   thanks!
