### ISSUE TITLE
Get/Set LogisticRegression weights

### ISSUE THREAD

**Issue by stathischaritos** [haifengl/smile#383]
Hello there,
I would like to be able to get/set the weights for the LogisticRegression classifier. 
They are private at the moment, is there a way to at least look at them?
Would a PR with getters/setters be welcome? Is there a good reason they are private?
Thank you for all your hard work!

**Comment by haifengl** [comment]
Models are immutable. Why do you want tot set weights? I may add a method to get the weights though.

**Comment by stathischaritos** [comment]
This is very specific to my use case. 
I have some historical values for weights that I wanted to use and compare with newly trained models. 
I found an alternative way to achieve this, by using the xml serialisation of the models.
i.e. use **write.xstream** instead of **write** in scala 
so now I can see everything inside and create custom models as xml.
