### ISSUE TITLE
Any way to achieve consistent results for Random Forests

### ISSUE THREAD

**Issue by ishaan007** [haifengl/smile#384]
I used SMILE's RandomForest for training on a dataset. I get inconsistent results. By inconsistent, I mean results change when a new model is trained on the same dataset on multiple runs. Is there a way to make these results consistent? I understand we will have to set the seed as a constant and the all decision trees(ntrees) will have to be run on a single thread for that. Are there any parameters exposed to do this?

**Comment by haifengl** [comment]
add `-Dsmile.threads=1` to jvm options.

**Comment by serickso** [comment]
If you want repeatable results, try calling `smile.math.Math.setSeed` before training your model. See https://haifengl.github.io/smile/faq.html#seed for more details.

**Comment by serickso** [comment]
Try calling `System.setProperty("smile.threads", 1)` before you train your random forest.
