### ISSUE TITLE
Ammonite REPL - loading predef + :help command

### ISSUE THREAD

**Issue by manlioGit** [haifengl/smile#385]
I don't know if this is an ammonite problem or not,  but I try to load predef import and functions  using  std location (i.e. $HOME/.ammonite/predef.sc) and --predef cli parameter, but It doesn't load anything..

From repl session, :help or :quit throws 

```
SyntaxError: found ":help", expected Import | Prelude ~ BlockDef | Expr | "{" | End at index 0
:help
^
```
## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

- Which Smile version

```
Version 1.5.2, Scala 2.12.6, SBT 1.2.4, Built at 2018-10-15 19:45:32.021
```

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )

```
(X)Ubuntu 18.04.1 LTS \n \l
Linux Gemini-X 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you

**Comment by haifengl** [comment]
It is in `~/.smile`.

**Comment by manlioGit** [comment]
Using $HOME/.smile/predef.sc works.. thank you
