### ISSUE TITLE
SammonMapping unexpected escape condition

### ISSUE THREAD

**Issue by folterj** [haifengl/smile#386]
The SammonMapping has an unexpected escape condition:

	if (lambda < 1E-3) {
		logger.info(String.format("Sammon's Mapping stress after %3d iterations: %.5f", iter-1, stress));
		break;
	}

The SammonMapping correctly converges / escapes on: 1. stress, 2. number of iterations
This additional escape condition makes the function terminate at unexpected intervals, where lambda does not converge but just varies. Removing this condition resolved my issue, which is the only solution as this does not appear to be parameterised.

Smile version: 1.5.2

**Comment by haifengl** [comment]
`lambda` is the step size in diagonal Newton method. The above condition is for early stop as the step is so small that the search won't progress much in general. In your case, the objective function is probably very flat given your data. So we may want no early stop as long as you don't care the time. How many iterations it keeps going after `lambda` is smaller than 0.001?

We may remove the early stop behavior or add an additional parameter to enable/disable early stop.

**Comment by folterj** [comment]
Thank you for responding - sorry for the slow response, just recently got back to this. As originally mentioned the lamda does not converge, our data does not have an optimal solution. Below is an example of a smaller data set (with larger initial lamdas) - note that the stress level does converge, while the lamda fluctuates and in this case actually increases.

Sammon's Mapping initial stress: 0.48861
Sammon's Mapping stress after  10 iterations: 0.39193, magic = 0.018
Sammon's Mapping stress after  20 iterations: 0.21394, magic = 0.009
Sammon's Mapping stress after  30 iterations: 0.19811, magic = 0.020
Sammon's Mapping stress after  40 iterations: 0.15827, magic = 0.226
Sammon's Mapping stress after  50 iterations: 0.14010, magic = 0.500
Sammon's Mapping stress after  60 iterations: 0.13570, magic = 0.500
Sammon's Mapping stress after  70 iterations: 0.13502, magic = 0.500
Sammon's Mapping stress after  80 iterations: 0.13474, magic = 0.500
Sammon's Mapping stress after  90 iterations: 0.13457, magic = 0.500
Sammon's Mapping stress after 100 iterations: 0.13444, magic = 0.500
Sammon's Mapping stress after 110 iterations: 0.13442, magic = 0.500

**Comment by haifengl** [comment]
We support a customized parameter to control the early stop behavior in v2.
