### ISSUE TITLE
SVM - different results

### ISSUE THREAD

**Issue by Algo90GT** [haifengl/smile#387]
## Expected behaviour

Always Same Results of SVM Classification

## Actual behaviour

Using the SVM in a Test and repeat the same classification test in a loop it returns different results
(one Test: f.e. training 1000 times a testset of 50 samples)
These multiple test are the same, if they are started again via main(args[])

Its like that the output is changing at runtime because something is saved, but i cant see whats the
reason in the project because i use every Training time a new Instance of the class

## Code snippet

I use:
        SVM = new SVM<>(new LinearKernel(), 10.0);
        SVM.learn(X, y);       
        SVM.finish();

## Input data

E.g. sample data

## Information

- NetBeans with Java 8
- Actual Github
- Windows

**Comment by haifengl** [comment]
We use a stochastic algorithm to train SVM. Thus, the model may be slightly different each time. You may run `SVM.learn(X, y)` multiple times (typically twice is sufficient), the difference should be very small.

**Comment by Algo90GT** [comment]
Thanks for the information, the results are now better with 2 times Training.
But I think my problem was'nt explained enough:

![desktop](https://user-images.githubusercontent.com/45149960/48977526-418b1b00-f09c-11e8-80ad-75c02d7350d9.jpg)

These Tests are made in a loop at runtime with the SVM for OHLC-Data Prediction.
If i run this test again, i get the same results (exactly). Using other Libs doesnt produce different
results. So my assumption is, that this has something to do with Smile at runtime. Its like a
cache is used and the last test affects the new one (always in the same way), but i couldnt figure out whats the cause in the code.
A solution would be very usefull.

regards

**Comment by haifengl** [comment]
I don't get your problem. Can you explain? Do you make the prediction during the training? Do you use SVM or SVR?

**Comment by Algo90GT** [comment]
I use the SVM.java in the classification package.
Its very strange, i extracted the SVM and the used classes into a new project, removed all "implements Serializable" and now i get always different results via the stochastic algorithm (Isn't there a parameter to make the SVM predict uniform repeatable? The differences aren't really maintainable respectively to large (like in the image)).

My original problem:
I tried it again with the Smile Project and there is the fault again.
I think the problem is, that if a new instance of the SVM-class is created, the previous instance (and their training knowledge) affects the actual one. Here it is strange that all tests give the output of the image,
at first always the blue curve and then the others.
The Test of one equity is always made with the exactly same Data Input at every point of time.
That means f.e. at date 2010.01.01 the SVM is trained always with the previous dates.

But i don't want to study all the code at the moment, rather i use a other lib for SVMs.

**Comment by Algo90GT** [comment]
Here is a code snippet which explains my problem perfectly:

` @Test
    public void Test_Repeatable() {
        int tests = 1;//1 Test no fault, if greater than 1 test failed
        double[][] X = new double[][]{{1.0010988645066765, 0.9952449135892911, 1.0015117711697912},
        {0.9976716338477913, 0.9969132517296433, 1.00189595529537},
        {0.9918917116756685, 0.9898579715943189, 1.004407548176302},
        {0.9951060139559271, 0.9929548112991919, 1.0034957043171948},
        {0.9933795414319108, 0.9924405172064369, 1.0026008944374638},
        {1.0078886878935842, 0.9985514736885055, 1.0104729132380343},
        {0.99271284563378, 0.992645371982241, 1.002557251393331},
        {1.0042072781153568, 0.9981444476163288, 1.0090126830064028},
        {0.996405969745169, 0.9899895089512336, 1.0024637043554774},
        {1.0093944869373837, 0.9987229475457496, 1.0127365603814855},
        {1.0005922057645849, 0.9967630571276674, 1.0039166335794127},
        {0.9984665568147425, 0.9963076302249723, 1.0030937888825369},
        {1.0101510875202921, 1.0, 1.0117475093798205},
        {0.9997266010509189, 0.9961124003094076, 1.001600384092182},
        {0.9996131347425011, 0.9974186749197921, 1.0037285806714114},
        {0.9908918026223602, 0.9889834184099022, 1.0019751109331732},
        {1.0047946127946126, 0.9982895622895623, 1.00593265993266},
        {1.003216899445085, 0.9973058467147415, 1.006319867034823},
        {0.9937404804531972, 0.9892312214413596, 1.001997434732651},
        {1.005808208127458, 0.9988975160498808, 1.0077509999663876},
        {0.9974201137556059, 0.9920932501888129, 1.000240611152327},
        {0.9958655257215228, 0.9917913598198791, 1.0008242144833919},
        {1.0066009043440816, 0.9979073585616623, 1.0092654895838942},
        {1.0004478699439159, 0.9952472308936677, 1.0019184876702072},
        {1.0111115565533462, 0.9992783835792175, 1.0118799444088091},
        {0.9924071712252275, 0.9885347624680328, 1.0005815221341863},
        {0.9966439824741308, 0.9873816404533289, 1.0},
        {1.0025321699159506, 0.999732752515467, 1.0077635394256852},
        {1.004931590837904, 0.9977208053154553, 1.007457365064344},
        {0.9976590425284994, 0.9968765128354764, 1.0020027454855331},
        {1.000465301781441, 0.9998737038021803, 1.006461047593725},
        {0.986419507009501, 0.9847917081921467, 1.0026642747990167},
        {0.9985787991863456, 0.99391779936147, 1.0039537671924883},
        {0.991696738727193, 0.9902600249569997, 1.0028127213247446},
        {1.0014351398411143, 0.9977010556099685, 1.005407280444009},
        {1.000441471117601, 0.997290046524264, 1.0024858219852617},
        {0.9930889341479973, 0.9902308214528173, 1.0031296673455532},
        {1.001804733323307, 0.9978329527898169, 1.003917091644905},
        {0.9919342731974944, 0.9896960681287787, 1.0005868464509438},
        {0.9995253295176246, 0.9978811810351944, 1.0037354503178229},
        {0.9866891496610345, 0.9844867338862314, 1.000447365704257},
        {0.999888393635647, 0.9947893778642727, 1.0053222285000802},
        {0.9959189368307232, 0.9952980571348844, 1.0026997802504447},
        {0.9978215186326702, 0.9958952087419446, 1.0039226674138415},
        {1.0062197698825543, 0.9992488539758088, 1.0085153282929329},
        {1.0021139289078034, 0.9992883803676703, 1.0058883036243764},
        {1.0009607485484342, 0.9992829195616758, 1.003453125217561},
        {0.9981846761629201, 0.9968005786779435, 1.0056059425773427},
        {0.9989966205623106, 0.9945580601330872, 1.000675887537888},
        {0.9996721791715201, 0.9978587022480138, 1.0071981084040704}};

        double[] y = new double[]{1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0,
            -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0,
            -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0,
            1.0, 1.0, -1.0, -1.0, -1.0};

        for (int i = 0; i < tests; i++) {
            int[] arr = new int[y.length];
            for (int j = 0; j < arr.length; j++) {
                arr[j] = (int) Math.max(0, y[j]);//just change input label -1 to 0
            }
            smile.classification.SVM<double[]> SVMS = new smile.classification.SVM<>(new LinearKernel(), 10.0);
            SVMS.learn(X, arr);
            SVMS.finish();

            for (int k = 0; k < X.length; k++) {
                int p = SVMS.predict(X[i]);
                assertTrue(y[i] == p);
            }
        }
    }`

If **int tests=1** there is no mistake. But if tests = 2 for example the weight vector isn't the same any more. If the JUnit-Test is started again, the weight vectors are always in the same order (i have created a function in the Lib for the weight vector).
w(tests=1): [0.13172843168889337, 0.07509274485847683, -0.018891116784615747]
w(tests=2): [0.14497829883409175, 0.05154082889292155, -0.031091794359431546]
w(tests=3): [0.13172843168890402, 0.0750927448584715, -0.018891116784617523]
w(tests=4): [0.25036854617134363, 0.09089504791907377, 0.05318142326254427]
...

A solution would be very useful because Smiles seems to be a useful lib. I use the SVM-class (beside other libs) for my bachelor thesis.

**Comment by Algo90GT** [comment]
Ok thanks, that means i would have to change the random number generator. 
yes, in a mathematically viewpoint. I suppose with better inputs the tests are more equivalent.

**Comment by haifengl** [comment]
use `smile.math.Math.setSeed()` to set the seed before the training.
