### ISSUE TITLE
issue running K-nearest neighbor demo in NetBeans 

### ISSUE THREAD

**Issue by OsamaFadel** [haifengl/smile#388]
## Expected behaviour

i have successfully imported smile in netbeans, and tried to run the K-nearest neighbor demo. The issue is that i can't load the training data (toy-train.txt).
## Actual behaviour

I get the following exception when running the program:

java.io.FileNotFoundException: shell\src\universal\data\classification\toy\toy-train.txt (The system cannot find the path specified)
Exception in thread "main" java.lang.NullPointerException

## Code snippet

The example i am trying to run can be found here: 

https://www.programcreek.com/java-api-examples/?code=takun2s/smile_1.5.0_java7/smile_1.5.0_java7-master/demo/src/main/java/smile/demo/classification/KNNDemo.java# 

## Input data

E.g. sample data

## Information

- I'm using Java oracle v.8
- Smile version 1.5.2
- I'm using Windows, and NetBeans.

**Comment by haifengl** [comment]
Set the workspace to be the home directory of smile.

**Comment by rayeaster** [comment]
add `-Dsmile.home=<pathToSmile>\shell\src\universal` to your demo/test running setting

**Comment by OsamaFadel** [comment]
> @OsamaFadel please try to add `-Dsmile.home=<pathToSmile>\shell\src\universal` to your demo/test running setting

how to include this path in netbeans, please.

**Comment by OsamaFadel** [comment]
> Set the workspace to be the home directory of smile.

sorry for not responding early, i have tried to move the project directory to SMILE home directory, but the issue remains.
