### ISSUE TITLE
the smile ols is very slow than apache math3 ols

### ISSUE THREAD

**Issue by yelangchs** [haifengl/smile#390]
this is a simple test code. but the result is very different.

```
public static void main(String[] args) throws Exception {
        double[][] x = new double[36][];
        for (int i = 0; i < 36; i++) {
            x[i] = Math.random(3000);
        }
        double[] y = Math.random(3000);
        Stopwatch stopwatch = Stopwatch.createStarted();
        for (int i = 0; i < 300; i++) {
            OLS ols = new OLS(Math.transpose(x), y, true);
            double[] coefs = ols.coefficients();
        }
        System.out.println("smile ols 100 times cost " + stopwatch.elapsed(TimeUnit.SECONDS) + "s");

        Stopwatch stopwatch1 = Stopwatch.createStarted();

        for (int i = 0; i < 300; i++) {
            OLSMultipleLinearRegression regression = new OLSMultipleLinearRegression();
            regression.setNoIntercept(false);

            regression.newSampleData(y, Math.transpose(x));
            double[] coefs2 = regression.estimateRegressionParameters();
            regression.calculateAdjustedRSquared();
            regression.calculateRSquared();
            regression.estimateErrorVariance();
        }
        System.out.println("smile apache 100 times cost " + stopwatch1.elapsed(TimeUnit.SECONDS) + "s");

    }
```

- JDK8
- SMILE 1.5.2
- MacOS

> smile ols 100 times cost 12s
> apache 100 times cost 2s

**Comment by rayeaster** [comment]
maybe you could use some real dataset like classic boston house price instead of random fake data. that would be more persuasive for your statement.

**Comment by haifengl** [comment]
- make sure add smile-netlib to your project.
- you may compare apple to orange. Smile doesn't just fit a linear model but also do goodness-of-fit test, variable significance test, etc. A lot of extra computation are involved to ensure the fitting quality. It is beyond the computation of R squared.
- although not critical, you better do Math.transpose(x) out of the loop.  It is interesting that you generate a 36 x 3000 array and then transpose it. It doesn't make sense to me.

**Comment by haifengl** [comment]
@yelangchs Any updates of new running time? Is smile still slower? Thanks.

**Comment by yelangchs** [comment]
@haifengl yes, I have try again. I add smile-netlib, it improve the better. 

- smile netlike cost about 7s when run 1000 times.
- apache cost about 4s when run 1000 times.

but smile ols is just QR, and the apache ols is the same. why the performance is different. so I try to trace the time.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/3895987/49920081-e81c4c00-fee3-11e8-806b-7e358b666b2c.png">

**Comment by yelangchs** [comment]
> * make sure add smile-netlib to your project.
> * you may compare apple to orange. Smile doesn't just fit a linear model but also do goodness-of-fit test, variable significance test, etc. A lot of extra computation are involved to ensure the fitting quality. It is beyond the computation of R squared.
> * although not critical, you better do Math.transpose(x) out of the loop.  It is interesting that you generate a 36 x 3000 array and then transpose it. Why?

this why the 3000 is the stock number, and the 36 is the 31 industry plus 5 risk.

**Comment by haifengl** [comment]
Thanks for updates.

- 90% time are used for hypot and max, which are called by Beta function. We use the Beta function to calculate the p-value of goodness-of-fit and significance of variables.
- So the fitting part (SVD in your case) is only about 10%, which means smile is faster than Apache in plain OLS fitting.
- In your profiling screenshot, I can see that still the pure Java implementation is used. Is the screenshot was before smile-netlib added to the project? If it is after, it means that there is some configuration wrong so that smile didn't pick up the native library. With native matrix computation library, smile should be faster.

Special function like Beta is computation intensive. I will see if we can leverage a native implementation to speed it up.

**Comment by haifengl** [comment]
For the training data matrix, I mean why don't you generate a 3000x36 matrix directly. I don't see the benefits of creating 36x3000 and then transpose it. In fact, it may have negative effective depending on the random number generator. It is possible that you introduce unnecessary correlations in math.rand(3000) across all your stocks.

**Comment by michellemay** [comment]
There have been a few comments about the test code not being optimal.
It’s only test code meant to help reproduce a problem.  So please be
indulgent, it’s not production stuff where you codereview thoroughly every
suboptimal lines of code.

Btw, I’m not part of that jira but am interested in the results.

**Comment by haifengl** [comment]
Smile uses QR for OLS by default. If it fails (e.g. collinear), smile will switch to SVD. The screenshot shows that SVD is used, which indicates the data generation part is problematic.

I am not ask that the test code to be optimal. But bad settings often draw wrong conclusions.

**Comment by yelangchs** [comment]
@haifengl @michellemay ok, first, I agree with your point. I will test use the true stock data to fit.

**Comment by haifengl** [comment]
@yelangchs please pay attention to my comments on p-value computation, which is the real difference. Apache Commons doesn't do it. You are comparing apple to oranges.

**Comment by yelangchs** [comment]
> @yelangchs please pay attention to my comments on p-value computation, which is the real difference. Apache Commons doesn't do it. You are comparing apple to oranges.

yes, you are right , that is my fault.

**Comment by haifengl** [comment]
@yelangchs This is not about whose fault but to find out the root cause. We all want better performance. But in machine learning, the model quality matters more than performance in most cases. In the case of OLS, we always want to calculate the p-values to check the goodness-of-fit even though it is of high cost. Otherwise, we will blindly apply an ill-trained model as in this example where Apache Commons silently ignores the failure of QR due to the collinearity of variables.

Thanks for submitting this ticket.

**Comment by yelangchs** [comment]
> @yelangchs This is not about whose fault but to find out the root cause. We all want better performance. But in machine learning, the model quality matters more than performance in most cases. In the case of OLS, we always want to calculate the p-values to check the goodness-of-fit even though it is of high cost. Otherwise, we will blindly apply an ill-trained model as in this example where Apache Commons silently ignores the failure of QR due to the collinearity of variables.
> 
> Thanks for submitting this ticket.

yes, I agree with you. your team do well.
