### ISSUE TITLE
Some function like sklearn LabelEncoder or Spark StringIndexer

### ISSUE THREAD

**Issue by LukeWang163** [haifengl/smile#391]
Are there some function like sklearn LabelEncoder or Spark StringIndexer? Thanks~

**Comment by haifengl** [comment]
What do these function do?

**Comment by LukeWang163** [comment]
> What do these functions do?

It can convert a column of strings to indices ranging from [0, classes-1], where 'classes' means how many different strings are there in that column

**Comment by haifengl** [comment]
You may use NominalAttribute to do that.

**Comment by LukeWang163** [comment]
I guess I get your point. But is it possible that I change the attribute from StringAttribute to NominalAttribute?

**Comment by haifengl** [comment]
If you specify a NominalAttribute to read a file, it will transfer the strings to int directly. There is no directly function to convert StringAttribute to NominalAttribute currently. In 2.0, we will have an advanced data frame to support all kinds of mappings.

**Comment by LukeWang163** [comment]
> If you specify a NominalAttribute to read a file, it will automatically build the unique word list and map the strings to int directly. There is no directly function to convert StringAttribute to NominalAttribute currently. In 2.0, we will have an advanced data frame to support all kinds of mappings.

Thanks for the reply. What is in branch v2 seems great. I guess I`ll try for that.
