### ISSUE TITLE
TSNE needs a predict() 

### ISSUE THREAD

**Issue by MartinSchmitzDo** [haifengl/smile#394]
## Expected behaviour
If you learn TSNE on one data set, you want to be able to apply it on others (e.g. for scoring)

## Actual behaviour
There is no scoring function.

**Comment by haifengl** [comment]
t-SNE is not a predictive method. It is for visualization.

**Comment by MartinSchmitzDo** [comment]
Well,
t-SNE is a dimensionality reduction method which is primarily used to visualize. Yes. But there is no reason not to use it the same way than PCA, as dimensionality reduction in front of a learner.

But in my case it's for visualization. I want to project a second data set into the same 2D-Space to see how clusters move in this space.

**Comment by haifengl** [comment]
PCA is a projection but t-SNE is not.

**Comment by MartinSchmitzDo** [comment]
Ehm, can you explain why? Why can't i use the same transformation into a lower dimensional vector space on a different data set?

**Comment by haifengl** [comment]
t-SNE doesn't have an explicit mapping. It simply just wants to mimic the distance distribution.

**Comment by Wang-Yu-Qing** [comment]
you can train a DNN for that: https://datascience.stackexchange.com/questions/22441/tsne-for-prediction
