### ISSUE TITLE
Math.pdist ignores squared and half flags if less than 100 points

### ISSUE THREAD

**Issue by stephenjelfs-gd** [haifengl/smile#396]
Math.pdist method ignores squared and half flags if less than 100 points:

![image](https://user-images.githubusercontent.com/19291351/50633012-12dd4b80-0f4a-11e9-95e6-2b4f961bcb40.png)

**Comment by haifengl** [comment]
It is to keep code simple. `half=true` is only meaningful when sample size is very large and the algorithm uses only the lower half of distance matrix. When sample size is less than 100, it doesn't really matter. Thanks.
