### ISSUE TITLE
Cannot call toString on AttributeDataset with open nominal response

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#397]
In `AttributeDataset.toString` it does:
```
sb.append(response.toString(y));
```

`response.toString` throws an exception if it is a `NominalAttribute` where `open = true` because `values` may not have been populated yet. You must call the constructor for `NominalAttribute` which contains the list of all possible values for the toString to work. Is it possible to remove this restriction which makes it more difficult to instantiate an `AttributeDataset`?

Perhaps `NominalAttribute.toString` could be changed to check if it's an open attribute:
```
    @Override
    public String toString(double x) {
        if (Double.isNaN(x)) {
            return null;
        }
        
        if (Math.floor(x) != x) {
            throw new IllegalArgumentException("The input nominal value is not an integer: " + x);
        }

        if (x < 0) {
            throw new IllegalArgumentException("Invalid nominal value: " + x);
        }

        if (open) {
            return valueOf(Double.toString(x));
        }

        if (x >= values.size()) {
            throw new IllegalArgumentException("Invalid nominal value: " + x);
        }

        return values.get((int) x);
    }
```

**Comment by haifengl** [comment]
It will cause different behavior. In Smile, labels must be in [0, k). But many data doesn't follow this pattern. It is why we do the mapping in this class. Your change is hacking and will cause confusion when others use it on their data. I would like to keep the current behavior. Thanks.
