### ISSUE TITLE
Enhancement request: window.canvas.save(file) with image resolution.

### ISSUE THREAD

**Issue by rumeshkrish** [haifengl/smile#398]
## Existing code:
```
 // function for extract the line 
 def extractXAndY(line: String) =
      line.split(',') match {
        case Array(_, x, y) => Some(Array(x.toDouble, y.toDouble))
        case _ => None
      }

 // read the data points
 val bufferedSource: BufferedSource = io.Source.fromResource(fileName)
 val data: Array[Array[Double]] = bufferedSource.getLines.toStream.tail.flatMap(extractXAndY).toArray

 // create window and display
 val window: Window = plot(data, '.')
 window.canvas.setAxisLabels(List("X", "Y"): _*)

 // store the image
 window.canvas.save(file)
```

## Input data has been attached
https://github.com/rumeshkrish/rumeshkrish.github.io/blob/master/cities.csv

## Output image also attached.
![1546716053986](https://user-images.githubusercontent.com/5201760/50728306-ff87d700-1127-11e9-8051-bb4bd9a8fd30.png)

## Expected output: 
Image output expected in details view, which has plot length 1 -> 150 pixels or user given resolution.

**Comment by haifengl** [comment]
You can set the window size as a workaround.

**Comment by rumeshkrish** [comment]
> You can set the window size as a workaround.

yes, you mean using zoom option I can set window and get full details for specific region.

The image I provided is just point plots. Let say, if I am computing the TSP for this points, all the points are connected in single loop. If I want to analyse more details where I am doing wrong, than I can zoom and find from window, if I want to find the cross join in the graph using some image analysis for large interested area then I want to save this graph image. This has only limited information. So if I can set resolution and see in depth that, I can do what ever the analysis.

**Comment by haifengl** [comment]
What does the "image resolution" means here? Image size? PPI?

Besides, this will be a low priority to us. Would you like to take on it? Thanks.

**Comment by rumeshkrish** [comment]
> What does the "image resolution" means here? Image size? PPI?
> 
> Besides, this will be a low priority to us. Would you like to take on it? Thanks.

I mean PPI, if there is an option to define the window size and PPI. I will check the code and fix the way to improve.

**Comment by haifengl** [comment]
smile-plot was not designed images. As the name implies, it is for mathematical plot. And I have to focus on the core algorithms. Can you please implement this by yourself. Thanks.
