### ISSUE TITLE
FeatureTransform `transform(double[][] x)` avoid a copy and do inplace transformation instead.

### ISSUE THREAD

**Issue by kuzeko** [haifengl/smile#400]
https://github.com/haifengl/smile/blob/03fc394fd5f2cb6b4dc5abe202e7016f34dd8777/core/src/main/java/smile/feature/FeatureTransform.java#L80-L94

Should line 87 check for the value of `copy` and avoid instantiating a new array if `copy=False`?

**Comment by haifengl** [comment]
Yes, it should. Thanks.

**Comment by haifengl** [comment]
The fix is in master branch. Thanks.
