### ISSUE TITLE
LAPACK DGESDD error code: 1

### ISSUE THREAD

**Issue by sssingh21** [haifengl/smile#401]
I am using smile 1.5.2. 
In line 
`this.model` =  new OLS(xTrain, yTrain, true);
I am getting the following error:

> Jan 10, 2019 4:31:01 PM com.github.fommil.netlib.LAPACK <clinit>
> WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
> Jan 10, 2019 4:31:01 PM com.github.fommil.jni.JniLoader liberalLoad
> INFO: successfully loaded C:\Users\IBM_AD~1\AppData\Local\Temp\jniloader422834344316138440netlib-native_ref-win-x86_64.dll
> [main] ERROR smile.netlib.NLMatrix - LAPACK DGESDD error code: 1
> java.lang.IllegalArgumentException: LAPACK DGESDD error code: 1

Any idea why this happens?

**Comment by haifengl** [comment]
The error code indicates that there was a convergence failure inside the SVD code. Your input data is probably problematic (e.g. singular matrix).
