### ISSUE TITLE
Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded

### ISSUE THREAD

**Issue by rahabwairimu05** [haifengl/smile#402]
## Expected behaviour

E.g. Train a Regression using OLS on 1022 records which contain 20 attributes each...

## Actual behaviour
It should be able to train the model

E.g. The algorithm throws an exception. Here is the stack trace...

Jan 20, 2019 12:18:52 AM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
Jan 20, 2019 12:18:53 AM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded C:\Users\rwangari\AppData\Local\Temp\jniloader9128222539364714454netlib-native_ref-win-x86_64.dll
Jan 20, 2019 12:18:54 AM com.github.fommil.netlib.BLAS <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
Jan 20, 2019 12:18:54 AM com.github.fommil.jni.JniLoader load
INFO: already loaded netlib-native_ref-win-x86_64.dll
2377 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2380 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2381 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2382 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2382 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2383 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2383 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2384 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2384 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2384 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2385 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2385 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2385 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded
2386 [main] ERROR smile.math.special.Beta - Beta.incompleteFractionSummation: Maximum number of iterations wes exceeded

## Code snippet
E.g. The code to parse data and the call of Smile algorithm.
`OLS myHousePriceTrainer = new OLS(HouseTrainIndependentArr,dependentPriceArr);`
 Passing the independent variables and the dependent variable

## Input data
E.g. sample data
Attached

## Information
- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
Using  JDK 10 and Java version 10, running the project on Eclipse IDE
- Which Smile version - Using Version 1.5.2
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Using windows

[independentDataSample.zip](https://github.com/haifengl/smile/files/2776070/independentDataSample.zip)

**Comment by haifengl** [comment]
The beta function is used to calculate p-value. It fails very likely because the fitting is failed due to invalid data (e.g. collinearity) and produces NaN values.

**Comment by rahabwairimu05** [comment]
Sorted it out.
