### ISSUE TITLE
DecisionTree interprets nominal '?' incorrectly

### ISSUE THREAD

**Issue by jsatxi** [haifengl/smile#407]
## Expected behaviour

Train a DecisionTree with '?' values for nominal attributes; '?' should be treated as a distinct implicitly-defined attribute value.

## Actual behaviour

The DecisionTree algorithm does not distinguish between '?' and the 0th nominal.

## Code snippet

https://github.com/haifengl/smile/blob/03fc394fd5f2cb6b4dc5abe202e7016f34dd8777/core/src/main/java/smile/classification/DecisionTree.java#L559

If `x[i][j]` is `NaN`, then `(int)x[i][j]` evaluates to `0` and the `0th` nominal is over-counted.

## Input data

https://github.com/haifengl/smile/blob/03fc394fd5f2cb6b4dc5abe202e7016f34dd8777/shell/src/universal/data/weka/soybean.arff

## Information

Version: 
https://github.com/haifengl/smile/tree/03fc394fd5f2cb6b4dc5abe202e7016f34dd8777

Note: A naive fix for this led to significantly improved DecisionTree results.

**Comment by haifengl** [comment]
Missing value should be imputed first. Check out `smile.imputation` package.
