### ISSUE TITLE
Categorical features for CRF

### ISSUE THREAD

**Issue by dkulagin** [haifengl/smile#408]
Am I right that the following syntax of CRF:

`public int[] predict(double[][] x)`

expects a sequence of **dense (!)** feature vectors? So the only way to encode _a categorical feature f_ having values in range _[1..m]_ would be to reserve an _m-sized_ subvector and use the one-hot encoding scheme?

**Comment by bratao** [comment]
@haifengl How could we use categorical features in Smile?

Thank you for this awesome lib!!!

**Comment by haifengl** [comment]
CRF works with categorical features. See the unit test for an example: https://github.com/haifengl/smile/blob/master/core/src/test/java/smile/sequence/CRFTest.java
