### ISSUE TITLE
LLE python to java

### ISSUE THREAD

**Issue by hlbkin** [haifengl/smile#413]
Can this package be used for LLE in the following way:

1) Take dataset in Python
2) Learn embedding via https://scikit-learn.org/stable/modules/generated/sklearn.manifold.LocallyLinearEmbedding.html#sklearn.manifold.LocallyLinearEmbedding
3) Load this embedding in Java library and use live for prediction on each new vector

**Comment by haifengl** [comment]
Smile can learn LLE directly.
