### ISSUE TITLE
How to get coefficients for Wavelet constructor?

### ISSUE THREAD

**Issue by aspecialkey** [haifengl/smile#415]
Hello,

I have some signal data and want to transform it with discrete wavelet transformation. Therfore I have found your `wavelet.java` and want to use it, but I don`t know which coefficients I have to pass to the constructor or how to calculate them.

It would be great if you can give me a hint!

Best regards

```
public Wavelet(double[] coefficients) {
        ncof = coefficients.length;

        ioff = joff = -(ncof >> 1);

        cc = coefficients;

        double sig = -1.0;
        cr = new double[ncof];
        for (int i = 0; i < ncof; i++) {
            cr[ncof - 1 - i] = sig * cc[i];
            sig = -sig;
        }
}
```

**Comment by haifengl** [comment]
Wavelet is a parent class. You should use one of child classes such as DaubechiesWavelet, SymletWavelet, etc. You may also want to check out WaveletShrinkage, which denoise a signal with wavelet.
