### ISSUE TITLE
DecisionTree fails to detect contiguous, but offset, label set

### ISSUE THREAD

**Issue by twotabbies** [haifengl/smile#416]
If the set of labels passed to DecisionTree cover a contiguous range of non-negative values, and the smallest value is not zero, then the DecisionTree constructor does not detect this and throws ArrayOutOfBoundsException.

## Expected behaviour

This should be detected and rejected (via IllegalArgumentException)

## Actual behaviour

The constructor throws an ArrayOutOfBoundsException.
```
java.lang.ArrayIndexOutOfBoundsException: 3
        at smile.classification.DecisionTree.<init>(DecisionTree.java:956)
        at smile.classification.DecisionTree.<init>(DecisionTree.java:858)
        at smile.classification.DecisionTree.<init>(DecisionTree.java:802)
```
## Code snippet
```java
      int[] labels = new int[]{1, 2, 3};
      double[][] features = new double[][]{{0},{0},{0}};
      new DecisionTree(features, labels, 100, DecisionTree.SplitRule.GINI);
```
The fix should be pretty easy: replace the loop at https://github.com/haifengl/smile/blob/259ddcb02691d92df6b2466402d49f174dd5d732/core/src/main/java/smile/classification/DecisionTree.java#L896 with
```java
        for (int i = 0; i < labels.length; i++) {
            if (labels[i] < 0) {
                throw new IllegalArgumentException("Negative class label: " + labels[i]); 
            }
            
            if (labels[i] != i) {
                throw new IllegalArgumentException("Missing class: " + i);
            }
        }
```

## Information

- Which Smile version: 1.5.2

**Comment by haifengl** [comment]
It is caller's responsibility to ensure all labels are in [0, k). All classifiers in smile has this contract declaration in the document. Thanks.

**Comment by twotabbies** [comment]
The caller is certainly in the wrong in this case - but the DecisionTree classifier (and possibly other ones; I didn't look) is doing some input validation to ensure that the callers are abiding by this contract. The logic of this input validation is incomplete; it detects some violations but not others. My suggested change makes it cover all violations, and is simpler than the existing logic.

**Comment by haifengl** [comment]
I add your logic. Thanks.

**Comment by twotabbies** [comment]
Thanks!
