### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by cranst0n** [haifengl/smile#42]
Trying to  build using `mvn package -Dmaven.test.skip=true`:

I get the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project smile-data: Compilation failure: Compilation failure:
[ERROR] /home/brandy/Software/smile/SmileData/src/main/java/smile/data/parser/BinarySparseDatasetParser.java:[116,13] try-with-resources is not supported in -source 1.5
[ERROR] (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/brandy/Software/smile/SmileData/src/main/java/smile/data/parser/DelimitedTextParser.java:[223,13] try-with-resources is not supported in -source 1.5
[ERROR] (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/brandy/Software/smile/SmileData/src/main/java/smile/data/parser/SparseMatrixParser.java:[95,13] try-with-resources is not supported in -source 1.5
[ERROR] (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/brandy/Software/smile/SmileData/src/main/java/smile/data/parser/ArffParser.java:[395,13] try-with-resources is not supported in -source 1.5
[ERROR] (use -source 7 or higher to enable try-with-resources)
```

I'm not a maven user so maybe I have an error in my setup but I was able to correct this by making a few changes:

1. In `pom.xml`, changing the `source` and `target` __maven-compiler-plugin__ values to `1.7`
2. Adding the following to `SmileData/pom.xml` and `SmileNLP/pom.xml`
```xml
    <parent>
        <groupId>com.github.haifengl</groupId>
        <artifactId>smile-all</artifactId>
        <version>1.0.3</version>
    </parent>
```

From my limited understanding it seems like the __maven-compiler-plugin__ configuration isn't picked up in the submodules without the submodule referencing the parent module (and the source/target setting is currently set to 1.6).

If this is a proper fix, I can formulate a PR if you like.

**Comment by haifengl** [comment]
Yes, please. Thank you very much! I recently updated some code with 1.7 features but forgot to update pm.xml.

**Comment by haifengl** [comment]
Oh, please don't include the parent part to subproject pom.xml. This parent project is only for building purpose. Add it to subproject will create dependency problems in maven repo.

**Comment by cranst0n** [comment]
Understood. If I don't add the `<parent>` reference, the build fails even after changing the source/target level to 1.7. The only other way I can get it to work without adding the `<parent>` reference is to add the __maven-compiler-plugin__ entry to each submodule's POM.

**Comment by haifengl** [comment]
I already update all pom.xml files. Will push it to github soon.

**Comment by haifengl** [comment]
it is in master now. I tested it. Thanks!

**Comment by cranst0n** [comment]
Thanks!
