### ISSUE TITLE
[Question] Heatmap logscale axes?

### ISSUE THREAD

**Issue by alexblickenstaff** [haifengl/smile#422]
Is there a way to make the axes in the `Heatmap` use a log scale? I see that there is an option for that in the [`Contour`](https://github.com/haifengl/smile/blob/05a93e7951f93f9370b16cf0461aaab4a1e77c84/plot/src/main/java/smile/plot/Contour.java#L60), but I don't see a way in the `Heatmap`. I've looked around in the `PlotCanvas` and `Axis` classes as well. If there is no way, I think it would be a useful feature.

**Comment by haifengl** [comment]
It doesn't make sense to use log scale for heatmap axes in most cases (just integer of cell index). If you have to use log scale, you can transfer your data first.

**Comment by alexblickenstaff** [comment]
In my case, the x axis has data at 1, 2, 4, 8, 16, etc. I could transform the data before passing it to the heatmap, but then the labels are be incorrect (it will show 0, 1, 2, 3, etc. instead of 1, 2, 4, 8, etc.).

**Comment by haifengl** [comment]
You can set the axes labels by a set of strings.
