### ISSUE TITLE
HDBScan

### ISSUE THREAD

**Issue by SomeUserName1** [haifengl/smile#423]
## Feature Contribution: HDBScan

Hi,

I'd like to implement [HDBScan](https://link.springer.com/chapter/10.1007/978-3-642-37456-2_14) as part of my bachelor's project in Java using & extending SMILE.  

As mentioned in the Contribution.md I am opening an issue.

My approach would be to port the [Python lib](https://github.com/scikit-learn-contrib/hdbscan) as close as possible to achieve comparable performance. This includes other algorithms e.g. Dual Tree Boruvka Minimimum Spanning Tree.   
Some guidance where to put the classes (besides HDBScan, obviously core/clustering) and whether certain components are already there 1:1 (e.g. the metrics from [here](https://github.com/scikit-learn-contrib/hdbscan/blob/master/hdbscan/dist_metrics.pyx) would be very helpful.

Best,
Fabian

**Comment by haifengl** [comment]
It would be wonderful. Thanks!

Clearly, HDBScan would be in core's smile.clustering. There are many distance/metric classes in math module (`smile.math.distance`). Check out DBScan class. The user can pass a distance metric or a neareast neighbor search data structure (e.g. KDTree). Check out `smile.neighbor` package (in core module).

**Comment by SomeUserName1** [comment]
I was told to popen the jar instead of implementing it and to focus on a survey of related work rather than implementing sth. that is state of the art :( sorry for the false alarm
