### ISSUE TITLE
-NEED HELP- Lasso Regression

### ISSUE THREAD

**Issue by sriharsha-indukuri** [haifengl/smile#424]
I am using the smile package for LASSO regression. The requirement is that we need to use 3 fold cross validation to find hyper-parameter lambda. How to find lambda with the methods provided under CrossValidation.java and LASSO.java?
Thanks.

**Comment by haifengl** [comment]
People usually use grid search to tuning the hyper-parameter. CrossValidation is used for checking which hyper-parameter value is better.
