### ISSUE TITLE
How can I use a custom distance matrix to cluster?

### ISSUE THREAD

**Issue by narzero** [haifengl/smile#428]
I want to cluster a large dataset. This dataset contains latitude and longitude values. To make sure that the clustering is more realistic I want to cluster based on a real distance matrix instead of the Euclidean distance.

I know that the k-medoids/CLARANS algorithm allows this but I can't seem to find any documentation on how to accomplish this with smile.

So my question is if it's possible at all using (any algorithm except DBScan because the results are poor for our dataset) with smile? If so, can you please point me into the right direction.

Thank you.

**Comment by haifengl** [comment]
You can pass a distance class to CLARANS.
