### ISSUE TITLE
Axis Scale

### ISSUE THREAD

**Issue by cranst0n** [haifengl/smile#43]
Is it possible to change the axis labeling to a custom range? I've created a heatmap from spectral data:

![heatmap](https://cloud.githubusercontent.com/assets/1173143/10495847/fb942ad8-728b-11e5-998c-a34042bae5aa.jpg)

Currently the y-axis labels the pixels (bin numbers in my case) but it would be nice if I could modify the plot to label a range of values that I provide (i.e. frequency range).

I've done a good amount of digging and messing around with the ```smile.plot.Base``` class but I get the sense I'm barking up the wrong tree.

**Comment by haifengl** [comment]
After plotting your graph, try

Plot.getAxis(1).addLabels

Your need to provide the labels and locations.

**Comment by cranst0n** [comment]
Thanks you. That was exactly what I was looking for.
