### ISSUE TITLE
Why doesn't this return 1? RandomForest classification

### ISSUE THREAD

**Issue by camdenorrb** [haifengl/smile#430]
## Expected behaviour.
Trained a RandomForest on values 0.0 --> 0.5 and 0.6 --> 1.0, when testing on 0.6 --> 1.0 should return 1 (Orange)

## Actual behaviour
Returns 0 (Apple)

E.g. The algorithm throws an exception. Here is the stack trace...

For some reason it spams 
`[Thread-5] ERROR smile.classification.RandomForest - Random forest has a tree trained without OOB samples.`
per ntrees, due to my lack of ML knowledge I don't really know what I should do to fix this, even after comparing to examples.

## Code snippet
```Kotlin
package me.camdenorrb.generaltesting.machinelearning

import smile.classification.RandomForest
import smile.data.NumericAttribute

object SmileTest {

    @JvmStatic
    fun main(args: Array<String>) {

        //SVM<DoubleArray>

        val attributes = arrayOf(
            NumericAttribute("Thing1", 0.4),
            NumericAttribute("Thing2", 0.5)
        )

        val trainingData = arrayOf(
            doubleArrayOf(0.0, 0.5),
            doubleArrayOf(0.6, 1.0)
        )

        val classifiers = intArrayOf(
            Fruit.APPLE.ordinal,
            Fruit.ORANGE.ordinal
        )

        val forest = RandomForest(attributes, trainingData, classifiers, 500)

        // Both of these print 0
        println(forest.error())
        println(forest.predict(doubleArrayOf(0.6, 1.0)))
    }


    enum class Fruit {
        APPLE, // 0
        ORANGE // 1
    }
}
```

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
OpenJDK 12.0.1

- Which Smile version
1.5.3

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Ubuntu

**Comment by camdenorrb** [comment]
Update: It appears to work if I use a RandomForest.Trainer....?

```Kotlin
        val trainer = RandomForest.Trainer(attributes, 500)//(attributes, trainingData, classifiers, 500)
        val forest = trainer.train(trainingData, classifiers)

        println(forest.error())
        println(forest.predict(doubleArrayOf(0.6, 1.0)))
```

**Comment by haifengl** [comment]
It is meaningless to train a random forest of 500 trees with 2 samples.

**Comment by camdenorrb** [comment]
You didn’t answer the OOB issue @haifengl

**Comment by haifengl** [comment]
You have only 2 samples. It is impossible to have OOB samples.
