### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by hmf** [haifengl/smile#431]
Would like to request an update of `smile-scala` to support Scala 2.13. 
I think you only have this dependency:  

https://github.com/haifengl/smile/blob/master/scala/build.sbt#L21

But according to:

https://github.com/lightbend/scala-logging/pull/171

this may not be an issue (tags are missing but it should work). So I think it is just a matter of bumping the Scala version. 

TIA.

**Comment by haifengl** [comment]
It will be supported in v2

**Comment by haifengl** [comment]
This is more complicated than we thought. Scala 2.13 introduces many changes/breaks to the library. We will have to maintain two branches for 2.13 and 2.12/2.11, respectively. We will drop the support to 2.10.

**Comment by haifengl** [comment]
We are running v2 with Scala 2.13.1 now. Thanks
