### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid x: Infinity

### ISSUE THREAD

**Issue by zorel** [haifengl/smile#432]
Hello.
I'm trying to use ols in Spark but I have this exception (demo with spark2 shell): 

```
spark2-shell --packages com.github.haifengl:smile-core:1.5.3 --packages com.github.haifengl:smile-scala_2.11:1.5.3 
scala> import smile.regression._
import smile.regression._

scala> 

scala> val x = (1 to 5).map(x => Array(x.toDouble)).toArray
x: Array[Array[Double]] = Array(Array(1.0), Array(2.0), Array(3.0), Array(4.0), Array(5.0))

scala> val y = val y = Array(41.0, 41.0,41.0,41.0,41.0)
y: Array[Double] = Array(41.0, 41.0, 41.0, 41.0, 41.0)

scala> val res = ols(x,y,"svd")
java.lang.IllegalArgumentException: Invalid x: Infinity
  at smile.math.special.Beta.regularizedIncompleteBetaFunction(Beta.java:58)
  at smile.regression.OLS.<init>(OLS.java:279)
  at smile.regression.OLS.<init>(OLS.java:187)
  at smile.regression.Operators$$anonfun$ols$1.apply(Operators.scala:81)
  at smile.regression.Operators$$anonfun$ols$1.apply(Operators.scala:79)
  at smile.util.package$time$.apply(package.scala:50)
  at smile.regression.Operators$class.ols(Operators.scala:78)
  at smile.regression.package$.ols(package.scala:30)
  ... 50 elided

scala> 
```

It happens when all the values of the y parameter are the same.

**Comment by zorel** [comment]
Tested without svd with the same result

**Comment by haifengl** [comment]
You have only one variable and the y are all the same.

**Comment by zorel** [comment]
Thanks for the answer, but i'm no data scientist and don't understand what it implies.

**Comment by haifengl** [comment]
Basically, your data doesn't make sense for least squares. Smile ships a lot of test data. Why not use them?

**Comment by zorel** [comment]
Thanks. I don't use sample data, the case above occurs with data production. I understand now, I have to get back to our datascientist. Thanks again.

**Comment by jansiroky** [comment]
The optimization problem posted by @zorel does have a solution (tested in Matlab). There is no reason why such optimization cannot be solved by least squares.  If needed I can provide more details on the solution of this particular example posted by @zorel 

I am facing the same error with different input, however my input also has all y values the same. I suggest that there is a bug in a code.

**Comment by haifengl** [comment]
@jansiroky it is not about OLS optimization. The error was from variable significance test, which is after the OLS fitting. In v2, we have the option to turn off the significance test.

**Comment by jansiroky** [comment]
@haifengl thank you for this explanation.
