### ISSUE TITLE
OLS could cause a wrong result when QR falls back to SVD

### ISSUE THREAD

**Issue by daigo** [haifengl/smile#433]
Thank you for the good library.

OLS allows QR to fall back to SVD when QR fails, say, due to deficient rank, where the implementation would have a problem.

The point is `X` is mutable on `X.qr()`. The minimal solution would be `X.qr(false)`. To optimize performance, alternatively, X can be recreated before falling back to `X.svd()`.

OLS.java:

```java 
       QR qr = null;
        SVD svd = null;
        if (SVD) {
            svd = X.svd();
            svd.solve(y, w1);
        } else {
            try {
                qr = X.qr(); // X will be changed
                qr.solve(y, w1);
            } catch (RuntimeException e) {
                logger.warn("Matrix is not of full rank, try SVD instead");
                SVD = true;
                svd = X.svd();
                Arrays.fill(w1, 0.0);//re-init w1 with zero after exception caught
                svd.solve(y, w1);
            }
        }
```

In my case, I noticed this issue as a subsequent

```
 pvalue = Beta.regularizedIncompleteBetaFunction(0.5 * df2, 0.5 * df1, df2 / (df2 + df1 * F));
```

threw an error for an invalid range of x.

**Comment by haifengl** [comment]
Thanks. This issue has been fixed in v2.
