### ISSUE TITLE
[Feature Proposal] DelimitedTextParser can split string, except if between quotes

### ISSUE THREAD

**Issue by riiswa** [haifengl/smile#436]
Hello,

Today I was working with the titanic dataset which has for 2 first lines:

```
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3, "Braund, Mr. Owen Harris",male,22,1,1,0,A/5 21171,7.25,,S
```

So I received an error message that there are 13 columns but 12 are expected. It's because of the data in the name column: "Braund, Mr. Owen Harris". This character string contains a comma that should normally be escaped because of quotation marks. I would like to implement in the class `DelimitedTextParser` a new attribute: hasQuotationMarks which will allow to manage the case seen above by processing it in the `parse()` method.
With `hasQuotationMarks == false` (default) we get: `[1, 0, 3, "Braund, Mr. Owen Harris", male, 22, 1, 1, 0, A/5 21171, 7.25, , S]` size (13).
With `hasQuotationMarks == true` we will obtain: `[1, 0, 3, Braund, Mr. Owen Harris, male, 22, 1, 0, A/5 21171, 7.25, , S]` size (12).

I think that this minor feature that will be used in my project will be useful to others. Moreover, it is a feature that most modern parsers include. While waiting to implement it, I thank you for considering my message.

Waris RADJI.

**Comment by riiswa** [comment]
Here is the code an example of the function I would like to implement and which could solve this problem.

```java
class Example {

    public static void main(String[] args) {
        String str = "1,0,3,\"Braund, Mr. Owen Harris\",male,22,1,0,A/5 21171,7.25,,S";
        String sep = ",";
        String regex = "\\Q" + sep + "\\E" + "(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)";
        String[] arr = str.split(regex);
        for (int i = 0; i < arr.length; i++) {
            arr[i] = arr[i].replaceAll("^\"|\"$", "");
            System.out.println(arr[i]);
        }

    }
}
```

**Comment by haifengl** [comment]
Thanks. Quote and escape are already supported in v2.

**Comment by cf212** [comment]
> Thanks. Quote and escape are already supported in v2.

Could you expand on this?
I am trying to parse a csv file where each field of each row is enclosed in double quotes. The `DelimitedTextParser` keeps the double quotes as part of the data, so for example, it can't read "17" as an Int and keeps unwanted " in the String values.

The documentation of the `DelimitedTextParser` class doesn't indicate it's possible to fix this or how.
