### ISSUE TITLE
Implementation of UMAP (manifold learning)

### ISSUE THREAD

**Issue by hageldave** [haifengl/smile#437]
Currently, smile supports the following 4 manifold learning techniques which can be found in the [manifold package](https://github.com/haifengl/smile/tree/master/core/src/main/java/smile/manifold):
* LLE
* ISOMAP
* Laplacian Eigenmaps
* t-SNE

A novel (February 2018) dimensionality reduction technique called _Uniform Manifold Aproximation and Projection_ aka **UMAP** (see [paper](https://arxiv.org/abs/1802.03426) and [python docs](https://umap-learn.readthedocs.io/en/latest/) ) also falls into the category of manifold learning.

Is it possible to include this algorithm into the smile library?

**Comment by haifengl** [comment]
You are welcome to implement it. Thanks

**Comment by haifengl** [comment]
@rayeaster would you like to implement this one? Thanks

**Comment by rayeaster** [comment]
@haifengl It would require a lot work. I need to read the 50-pages paper first:)

**Comment by haifengl** [comment]
@rayeaster Here is easy to understand introduction:

https://umap-learn.readthedocs.io/en/latest/how_umap_works.html

**Comment by haifengl** [comment]
The feature branch `umap` is created.

**Comment by rayeaster** [comment]
@haifengl 
do we have handy function to do a non-linear function fit (a power function) in smile like following scipy method
https://github.com/lmcinnes/umap/blob/master/umap/umap_.py#L1156-L1163
`1.0 / (1.0 + a * x ** (2 * b))`

**Comment by haifengl** [comment]
I will implement the Levenberg-Marquardt algorithm.

**Comment by haifengl** [comment]
The Levenberg-Marquardt algorithm is available in smile.math package. Check out the unit test for usage.

**Comment by rayeaster** [comment]
> The Levenberg-Marquardt algorithm is available in smile.math package. Check out the unit test for usage.

Thanks, will take a look there

**Comment by haifengl** [comment]
Released in 2.4.0.

**Comment by rayeaster** [comment]
> Released in 2.4.0.

Thank you.

@hageldave you may wanna try it in master branch. cheers.

**Comment by hageldave** [comment]
I'm looking forward to use it in my future projects/research.

Thank you!
