### ISSUE TITLE
Reduce memory consumption of DBSCAN

### ISSUE THREAD

**Issue by vlieven** [haifengl/smile#438]
Hi,

First of all, thank you for the work on this library. While using the DBSCAN algorithm, I noticed that the memory consumption is rather high. After looking at the source code, I believe this can be mitigated by expanding the neighbors in a depth-first way, instead of breadth-first.

If you are open to it, I can make a pull request with the proposed changes?

**Comment by haifengl** [comment]
It is very easy to hit stack issue with DFS in DBScan. The memory consumption depends on the nearest neighbor search data structure, and DBScan parameters. If it consumes too much memory, it might be caused by large radius parameter.

**Comment by maciejbrzeski-compactsolutions** [comment]
I have a similar problem, but there is another, in my opinion, more seriously, problem. There is no checking that some point is in the queue, what causes memory is quadratic of the currently processed cluster.

**Comment by haifengl** [comment]
@maciejbrzeski-compactsolutions it may be a cause of high memory usage. I will look into it. Thanks.

**Comment by vlieven** [comment]
I've created a pull request with the changes I made to solve the memory issue I encountered when processing my dataset. It should also solve the issue of @maciejbrzeski-compactsolutions I believe. Feel free to have a look and let me know if any changes are required.

**Comment by haifengl** [comment]
The improvement is v2 branch now.
