### ISSUE TITLE
Math.spearman() returns wrong value.

### ISSUE THREAD

**Issue by slodko** [haifengl/smile#444]
Math.spearman() gives 2.02 for these arrays:
https://pastebin.com/6nq1s0CW

**Comment by haifengl** [comment]
What system did you compare to?

**Comment by slodko** [comment]
I'm not comparing it to anything, it's just outside of [-1,1] range. (https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.spearmanr.html gives -0.016222)

**Comment by haifengl** [comment]
This implementation assumes no ties while your second array has a lot of identical values. I will implement a new algorithm to handle ties, which may be slower though.

**Comment by slodko** [comment]
Ok. Thanks for clarification.

**Comment by haifengl** [comment]
I fix it. It is in v2 branch now. Thanks.
