### ISSUE TITLE
Feature request: R-style text representation of decision trees

### ISSUE THREAD

**Issue by twotabbies** [haifengl/smile#455]
Background: I work on [Google Earth Engine](https://earthengine.google.com) which is a large-scale cloud-based geospatial computation system that allows users (mostly scientists, outside Google) to write scripts that are run in Google's cloud. We have a substantial data catalog (over 25PB) and provide many algorithms that users can run over the catalog (or their own data). Many users want to use satellite observations for things like land cover classification, so we provide machine learning algorithms. I'm in the process of replacing the implementations of some of these algorithms, and I'm very interested in using Smile as that replacement - if we can get to feature parity with our current implementation. (Continuing to use the current implementation isn't an option, for internal reasons.)

One of the ways in which our users communicate with each other is via exchanging trained classifiers - for example, the [Hansen forest change model](https://earthenginepartners.appspot.com/science-2013-global-forest), which has been very influential, is distributed in this way. This means that we need some way to produce a parseable text representation of a trained DecisionTree. For better or worse, the text format that's commonly used is that which is generated by R's `rpart` package.

This feature request is to add `DecisionTree.toString()` which will produce a string in that format containing a representation of the decision tree.

As it happens, I have implemented this already and am happy to submit a pull request with that implementation, but I'm opening an issue first (as is recommended in the guidelines) to discuss the feature request.

**Comment by haifengl** [comment]
Thanks a lot for contribution. Please open a PR. We can discuss the details in the PR.
