### ISSUE TITLE
If you can add java code for CNN deep learning and LSTM recurrent neural  used for regression

### ISSUE THREAD

**Issue by ashrafs** [haifengl/smile#456]
## Expected behaviour

E.g. Train a RandomForest on my data which has 10000 samples and 10 attributes, which are ....

## Actual behaviour

E.g. The algorithm throws an exception. Here is the stack trace...

## Code snippet

E.g. The code to parse data and the call of Smile algorithm.

## Input data

E.g. sample data

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
- Which Smile version
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )

**Comment by ashrafs** [comment]
If you can add java code for CNN deep learning and LSTM recurrent neural used for regression

**Comment by haifengl** [comment]
Not in near future.
