### ISSUE TITLE
Manifold Learning - Laplacian Eigenmap - Inverted Values

### ISSUE THREAD

**Issue by sechaparroc** [haifengl/smile#46]
Hi,

I'm new in this topic of non linear dimension reduction and essentially, what I'm trying to do is taking advantage of the locally preservation of the Laplacian Eigenmap algorithm to find common features in an image, or get a structural representation of the image

It works as expected except for the issue that the output image has sometimes inverted values.

I've seen the manifold demo that you give and in the case of the example with the Swissroll data, it seems that sometimes the sign of the coordinates also changes.

Attached you could find a detailed description

https://docs.google.com/document/d/1YTY9rGkUJR5_Qfh9YM3pQmhVoSMj3OJIx8KOampk_aI/edit?usp=sharing

Thanks and looking forward your comments.

**Comment by haifengl** [comment]
As you know, eigen vectors don't care about the sign. Mathematically, nothing is wrong about that. But for visualization, it maybe a problem to you. I don't have a general fix for that. You may have to check it case by case.

**Comment by sechaparroc** [comment]
Ok, thanks for your quick response.
