### ISSUE TITLE
Error in CSV parsing when missingValue equals empty string

### ISSUE THREAD

**Issue by mwess** [haifengl/smile#467]
## Expected behaviour

Reading a csv file with DelimitedTextParser in Java with the missing attribute set to an empty string (i.e. "") should return an AttributeDataset.
The AttributeDataset should be read correctly and return an instance of AttributeDataset.

## Actual behaviour

The parser method returns null.

We strongly suspect the issue to be in DelimitedTextParser.class in the line.split method (the last invocation of line.split() in the parse method).
When the missingValuePlaceholder is the empty string and the last value in the string is a missing value, the line.split() methods does not recognize the last value as missing.

Example:

```
String line = "1,1,1,,text,text,222,3,";
line.split(",");
```
returns `[1,1,1, "", "text", "text", 222,3]`, but should return `[1,1,1, "", "text", "text", 222,3, ""]`.

## Code snippet

```
new DelimitedTextParser().setDelimiter(",").setMissingValuePlaceholder("").parse(csvfile);
```

where csvfile contains a line such as :

`1,1,1,,2,2,1,`

## Input data

A csv file containing a line like this:

```
0,0,0,text,text,0,
```

## Information

- Java 1.8 OpenJdk.
- Smile version 1.5.3
- Windows.

## Comment

As a temporary solution, we are going to denote missing values as '?' for the time being, but having a missing value represented by an empty string is sometimes inevitable.

Thank you.

**Comment by haifengl** [comment]
this should be fixed in v2 as we move to apache csv parser library.
