### ISSUE TITLE
Values of probability are sorted for SVM.Multiclass.ONE_VS_ONE

### ISSUE THREAD

**Issue by DarrMirr** [haifengl/smile#469]
## Expected behaviour

- values of probability for SVM.Multiclass.ONE_VS_ONE have the same index as label 

## Actual behaviour

- values of probability are sorted for SVM.Multiclass.ONE_VS_ONE. Max value have last index in array. There is correct order for SVM.Multiclass.ONE_VS_ALL 

## Code snippet

I try to use SVM such as:

```
public class Application {

    public static void main(String[] args) throws IOException {
        var trainDataSet = ... // implementation of retrieving trainDataSet is not important here
        var trainLabels = ...  // implementation of retrieving trainLabels is not important here
        var uniqueLabels = ... // implementation of retrieving uniqueLabels is not important here

        var svm = new SVM<double[]>(new GaussianKernel(0.1D), 1.0D, uniqueLabels, SVM.Multiclass.ONE_VS_ONE);
        svm.learn(trainDataSet, trainLabels);
        svm.finish();
        svm.trainPlattScaling(trainDataSet, trainLabels);

        var testImageEmbeddings = ... // implementation of retrieving testImageEmbeddings is not important here
        var probability = new double[uniqueLabels];
        int prediction = svm.predict(testImageEmbeddings, probability);

        System.out.println("prediction   : " + prediction);
        System.out.println("probability  : " + probability[prediction]);
        System.out.println("max probability  : " + Nd4j.createFromArray(probability).maxNumber());
    }
}
```

## Information

- Openjdk 11
- Smile-core 1.5.3
- Windows 8.1

**Comment by haifengl** [comment]
Thanks. Will look into it.

**Comment by haifengl** [comment]
I don't see any where we sort the probability array. Do you see this behavior on all the test datasets? Is the predicted label correct but the probability array doesn't match?

**Comment by haifengl** [comment]
I don't see this behavior with v2. Close it as we will release v2 soon.

**Comment by DarrMirr** [comment]
@haifengl, thanks for response. I will try to reproduce my issue after v2 is released.

I have strange results in v1.5.3. Max probability is third label, but result is fisrt one. See screenshot
![screenshot](https://user-images.githubusercontent.com/17032652/68747600-eedba380-060b-11ea-918f-b5a0071eda3a.jpg)

**Comment by haifengl** [comment]
The RC of v2 is available to download. Can you please test your code with it? I would like to fix it if this is a real issue. Thanks.

**Comment by DarrMirr** [comment]
@haifengl, I tried to reproduce the issue at smile-2.0.0-RC2 and I faced to error:
```stacktrace
java.lang.UnsupportedOperationException: null
	at smile.classification.Classifier.f(Classifier.java:56) ~[smile-core-2.0.0-RC2.jar:2.0.0-RC2]
	at smile.classification.PlattScaling.fit(PlattScaling.java:213) ~[smile-core-2.0.0-RC2.jar:2.0.0-RC2]
	at smile.classification.OneVersusOne.fit(OneVersusOne.java:136) ~[smile-core-2.0.0-RC2.jar:2.0.0-RC2]
	at smile.classification.OneVersusOne.fit(OneVersusOne.java:84) ~[smile-core-2.0.0-RC2.jar:2.0.0-RC2]
```

Method f() have not implementation. Please, check my code snippet. Is it correct?

There is my code:
```java
  var svm = OneVersusOne.fit(dataSetMatrix, dataSetLabels, (x,y) -> SVM.fit(x, y, 1.0D, 0.001D));
  var probability = new double[uniqueLabels];
  int prediction = svm.predict(test.toDoubleVector(), probability);
```

**Comment by haifengl** [comment]
You fit a linear SVM, which eventually returns a LinearModel and thus doesn't support PlattScaling. Please fit a nonlinear model.

**Comment by DarrMirr** [comment]
Probability values have correct index order at 2.0.0-RC. Thanks for help!

![screenshot](https://user-images.githubusercontent.com/17032652/69013027-9817f600-098c-11ea-8e46-8cf1ee3e3b14.jpg)
