### ISSUE TITLE
Visualize multidimensional result of knn

### ISSUE THREAD

**Issue by peterwilli** [haifengl/smile#470]
Hi there! At first sorry for posting a question here... I checked other places but I found no other place where I could ask this.

I have the result of a knn-function. It's very similar to the KNN-call on this example: https://haifengl.github.io/smile/jupyter-notebook.html

As you can tell, the example uses multi-dimensional data (>2 dimensions). How would I go and visualize this? I have looked at the visualization guide (https://haifengl.github.io/smile/visualization.html) and the closest to what I could find what would be useful is this: https://haifengl.github.io/smile/images/iris.png

But I have no idea how to use that in a classification algorithm. I couldn't find an example of it also. Thanks a lot!

**Comment by haifengl** [comment]
check out manifold module how to visualize high dimension data. note that it is only for map data to low dimensional space, not suitable for classifiers.
