### ISSUE TITLE
Can not run script from command line

### ISSUE THREAD

**Issue by stdavy** [haifengl/smile#471]
## Expected behaviour

I'm trying to run a basic smile script using the smile REPL: smile --watch myscript.smile

## Actual behaviour

I get the following error:
```
CodePredef.sc:29: object prompt is not a member of package ammonite.repl
val res_27 = repl.prompt() = "smile> "
```

## Here is the basic script I'm trying to run (from SMILE doc)
```
val iris = read.arff("/opt/smile/data/weka/iris.arff", 4)

// Get the feature vectors.
val x = iris.unzip
// Get the feature vectors and labels.

val (x, y) = iris.unzipInt
iris.head(10)
```

## Information
Java:
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

Smile:
```
  Welcome to Smile Shell; enter 'help<RETURN>' for the list of commands.
  Type "exit<RETURN>" to leave the Smile Shell
  Version 1.5.3, Scala 2.12.8, SBT 1.2.8, Built at 2019-06-02 03:33:37.531
===============================================================================
```
Operating system: Redhat 7

**Comment by haifengl** [comment]
The doc is based on the old design, which uses Scala REPL and it is still available on windows. On Linux, we switch to ammonite and thus this feature is broken. I will look into it in v2.

**Comment by haifengl** [comment]
Cool. Can you share how to do it? We would like incorporate it in next release. Thanks!

**Comment by stdavy** [comment]
Well, it's really basic, I add this at the top of my script:

```
import $ivy.`com.github.haifengl:smile-scala_2.11:1.5.3`
```
and then I can start my script with the other imports like this:
```
import smile.regression.RidgeRegression
import smile.feature.OneHotEncoder
```
and then use ammonite like this:
```
amm -w script.sc
```
This allows me to edit my script in another editor, and when saving it is ran automatically without all the initial compilation time

Now, I think a more clever way to do this would be to add the import $ivy statement in .ammonite/predef.sc. I think that one probably need to add more $ivy stuff like smile-core? Actually if you can summarize what are all the needed stuff to have a fully working  environment it would be nice.

One concern anyway: as we works with, it implies that we have an internet connection, which can sometime be an issue. I don't have yet enough knownledge to setup something offline, using import $file ammonite statement. It could be nice to incorporate all the jars in the smile lib directory in the predef.sc definition, and have a fully offline working environment.

**Comment by stdavy** [comment]
OK, so I went a little bit further with ammonite. Here is my prefef.sc:
```
import java.io.File
import ammonite.ops._

/*
val path = java.nio.file.FileSystems.getDefault().getPath("/path/to/jar")
val x = ammonite.ops.Path(path)
interp.load.cp(x)

*/

val smileLibPath = "/opt/smile/lib"

def getJarList (dir:String, extensions: List[String], blacklist: List[String]) : List[File] = {
        val d = new File(dir)
        if (d.exists && d.isDirectory){
                d.listFiles
                 .filter(_.isFile)
                 .toList
                 .filter(file => extensions.exists(file.getName.endsWith(_)))
                 .filter(file => !(blacklist.exists(file.getName.startsWith(_))))
        } else {
                List[File]()

        }
}

val jarList = getJarList(smileLibPath, List("jar"), List("com.github.fommil.jniloader"))

for (jarPath <- jarList){
        println(s"Loading  $jarPath")
       val x = ammonite.ops.Path(jarPath)
        interp.load.cp(x)
}

```
So, this script list all the jars from /opt/smile/lib and load them in the environment. I had to blacklist  jniloader as it doesn't work with blas.

Then, I start ammonite like this:
amm -p /path/to/predef.sc -w myScript.sc and it seems to work :-)

I don't why I need to specify predef.sc when calling with a script as argument.

I'm not a Scala killer, I'm sure that this can be improved, but at least I can now edit my script in my favorite editor and have it running quicky after each save with full recompile

**Comment by haifengl** [comment]
Thanks. I will try to incorporate this into v2.

**Comment by haifengl** [comment]
So you use amm to run the script, instead of smile.sh? It requires the user to install ammonite.

**Comment by haifengl** [comment]
We are able to run the script with smile shell command now in v2. Thanks

**Comment by stdavy** [comment]
Sorry for this long delay, I've been off for two weeks. Thanks for your feedback, and yes, I use directly ammonite which implies that the user must install it before.

**Comment by haifengl** [comment]
With v2, you don't need to install ammonite. Check out RC1 release, you can just do

```
bin/smile examples/usps.sc
```
