### ISSUE TITLE
smile.math.Math.mad() mutates input array

### ISSUE THREAD

**Issue by genmeblog** [haifengl/smile#472]
## Expected behaviour

Input array for mad() function shouldn't be changed.

## Actual behaviour

Implementation reuses input array to keep temporary values. This destroys original data which cannot be reused to calculate other statistics.

## Code snippet

In Clojure:

```clojure
(let [arr (double-array [1 2 3 4 5 6])]
  (smile.math.Math/mad arr)
  (seq arr))
;; => (1.0 0.0 1.0 2.0 2.0 3.0)
```

## Input data

As above.

## Information

- What Java: OpenJDK 64-Bit Server VM 11.0.4+11-post-Ubuntu-1ubuntu218.04.3
- Which Smile version: 1.5.3
- What is your build system: Ubuntu 18.04.3 LTS via WSL

**Comment by haifengl** [comment]
It is expected behavior, which is stated in the javadoc of the function. In wavelet, we leverage this design to avoid extra working space.
