### ISSUE TITLE
MulticoreExecutor does not use all the CPU cores

### ISSUE THREAD

**Issue by sudarsun** [haifengl/smile#474]
## Expected behaviour
I am building a Decision Tree with -Dsmile.threads=8.  I have 16 logical CPUs, so was expecting to see upto 800% cpu utilization.

## Actual behaviour
But, I see that the CPU utilisation is not going more than 100%.  I am seeing that there are 8 worker threads spawned and each one is using upto 12.5% of CPU.

## Code snippet

I am using smile REPL.

## Input data

Using a SATIMAGE data from UCI site.

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
OpenJDK 1.8.0_222

- Which Smile version
Smile 1.5.1
Scala 2.12.4

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Ubuntu 18.04.3

**Comment by haifengl** [comment]
MulticoreExecutor will retire in v2.
