### ISSUE TITLE
Native eigen threading issue

### ISSUE THREAD

**Issue by piotrmwojcik** [haifengl/smile#480]
While computing eigenvalues for 3 x 3 matrix on three threads, fatal error occurs. 
```
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007fd2b256b23f, pid=27689, tid=27772
```
Please take a look at the code below:

```scala
val a = Seq.fill(3)(Future {
    val m = matrix.matrix(3, 3, 1.0)
    m.setSymmetric(true)
    m.eigen(2)
})
Await.result(Future.sequence(a), scala.concurrent.duration.Duration.Inf)
```
This is 100% reproducible on both Windows/Linux environment. When switching to generic Java BLAS/LAPACK implementation, no error is visible.

- OpenJDK 11.0.3
- Smile 1.5.3
- Ubuntu/Windows
- libblas-dev (0.2.18-1ubuntu1)/binaries distributed in Smile package on Windows

**Comment by haifengl** [comment]
The native lapack library will be loaded when it is used for the first time. When you get three threads do that at the same time, they all try to load the library and thus crash. It is beyond our control how to detect the race condition of .dll/.so loading.

To avoid the crash, please create a matrix before the multi-threading part (e.g. at the main entry of your program).

**Comment by piotrmwojcik** [comment]
Hi!
Thanks for your comment. However, this is not the issue. I can force preloading of LAPACK before threads start by calling some computations (d.eigen(2)). 

```scala
  val a = matrix.matrix(3, 3, 1.0)
  val b = matrix.matrix(3, 3, 1.0)
  val c = matrix.matrix(3, 3, 1.0)
  val d = matrix.matrix(3, 3, 1.0)
  a.setSymmetric(true)
  b.setSymmetric(true)
  c.setSymmetric(true)
  d.setSymmetric(true)
  d.eigen(2)

  val t1 = Future (a.eigen(2))
  val t2 = Future (b.eigen(2))
  val t3 = Future (c.eigen(2))
  Await.result(Future.sequence(Seq(t1, t2, t3)), scala.concurrent.duration.Duration.Inf)
```
This reduces frequency of crash-ending runs but SIGSEGV is still reproducible in the environments mentioned above.

**Comment by piotrmwojcik** [comment]
Let me share some debugging results: the segmentation fault error is a result of memory corruption by `dsaupd` ARPACK method. After `rawEigen` is called from many threads, `workd` array may be of random length (even negative).  Smile glue code crashes when trying to copy result from `workd` array.

The following code snippet is a stripped down version of Smile wrapper for `eigen`.
```scala
def rawEigen(A: Matrix, k: Int, which: String, kappa: Double, maxIter: Int): Unit = {
    val n = A.nrows
    val nev = new intW(k)
    val ncv = Math.min(3 * k, n)
    val tol = new doubleW(kappa)
    val info = new intW(0)
    val iparam = new Array[Int](11)
    iparam(0) = 1
    iparam(2) = 300
    iparam(6) = 1
    val ipntr = new Array[Int](11)
    val resid = new Array[Double](n)
    val ido = new intW(0)
    val v = new Array[Double](n * ncv)
    val workd = new Array[Double](3 * n)
    val workl = new Array[Double](ncv * (ncv + 8))

    for (_ <- 1 until maxIter) {
      println(s"workd.length(a) == ${workd.length}")
      com.github.fommil.netlib.ARPACK.getInstance().dsaupd(ido,
        "I",
        n,
        which,
        nev.`val`,
        tol,
        resid,
        ncv,
        v,
        n,
        iparam,
        ipntr,
        workd,
        workl,
        workl.length,
        info)
      // after calling native `dsaupd` method, `workd` array may have bizarre length (e.g. it may be negative)
      println(s"workd.length(b) == ${workd.length}")
    }
  }

  val a = matrix.matrix(3, 3, 1.0)
  val b = matrix.matrix(3, 3, 1.0)
  val c = matrix.matrix(3, 3, 1.0)
  val d = matrix.matrix(3, 3, 1.0)
  a.setSymmetric(true)
  b.setSymmetric(true)
  c.setSymmetric(true)
  d.setSymmetric(true)
  d.eigen(2)

  val t1 = Future(rawEigen(a, 2, "LA", 1.0E-8, 10 * a.nrows))
  val t2 = Future(rawEigen(b, 2, "LA", 1.0E-8, 10 * b.nrows))
  val t3 = Future(rawEigen(c, 2, "LA", 1.0E-8, 10 * c.nrows))
  Await.result(Future.sequence(Seq(t1, t2, t3)), scala.concurrent.duration.Duration.Inf)
```

**Comment by haifengl** [comment]
Thanks for pining down the root cause. In fact, ARPACk is not multithread safe.

https://stackoverflow.com/questions/3889222/is-arpack-thread-safe
