### ISSUE TITLE
Request: Add standard deviation method to GaussianProcessRegression class

### ISSUE THREAD

**Issue by lwinch** [haifengl/smile#481]
## Expected behaviour

I am trying to Implement Bayesian Optimization functionality in my own repository using the GaussianProcessRegression class. Bayesian Optimization uses predicted values and their uncertainties as calculated by a GPR to find the most likely location of the function optimum.

## Actual behaviour

Currently the GaussianProcessRegression class contains a predict() method but not a standard-deviation method.  

There is more than one way to solve this issue. If anyone knows a lot about GPR then the addition of a StdDev implementation would be much appreciated. Alternatively I could make a sub class of GPR and attempt to add the StdDev method in my own Repository. However, the StdDev method requires access to the kernel variable which is private and has no getter in the GPR class. I could Also make a fork of Smile and implement it myself the the GPR class but I am not very knowledgeable about GPR currently.  

Is it possible to implement this feature?

**Comment by lwinch** [comment]
I see this issue was discussed in issue #473 
I think a StdDev calculation might be possible without a costly MCMC calculation according to this Stack Exchange post: [https://stats.stackexchange.com/questions/330185/how-to-calculate-the-standard-deviation-for-a-gaussian-process](url)

**Comment by haifengl** [comment]
What you refer is applicable to 2-dimensional data. It is okay for a toy demo but not for real high-dimensional data.

**Comment by lwinch** [comment]
Thank you for the response. So the method described does not generalize?
Do you know if a Bayesian Optimizer is possible at all for an n dimensional parameter space if a GPR cannot produce the StdDev of the prediction? Like maybe and approximation of the StdDev of some other method of guessing the function optimum.
