### ISSUE TITLE
quick question about 2.0 RC2 release note

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#482]
> RandomForest is 8X faster than XGBoost on large benchmark data (10MM samples).

@haifengl is 10MM means 10 Million (thought a typo..) or 10 Billion?  If possible, would you please share the benchmark data source? Thanks

**Comment by haifengl** [comment]
It is 10 million (not a typo though). 100k and 1M data are included in RC2. The 10M data was (accidentally) included RC1. Check examples/airline.sc.
