### ISSUE TITLE
plot package is not getting imported

### ISSUE THREAD

**Issue by Apurv3377** [haifengl/smile#484]
## Expected behaviour
Class should be imported with below statement.
import smile.plot.ScatterPlot;
import smile.plot.Plot;

## Actual behaviour
Not able to import plot, other classes like PCA is getting imported as expected!

I have tried both 1.5.3 and 1.5.1 versions of the library in gradle. using below to add dependancy.

implementation 'com.github.haifengl:smile-core:1.5.1'
implementation 'com.github.haifengl:smile-core:1.5.3'

## Code snippet
//Works
import smile.projection.PCA;
//Does not work
import smile.plot.ScatterPlot;
import smile.plot.Plot;

## Input data

E.g. sample data

## Information

- Android Studio --> 3.5.2
- OpenJDK --> 64bit
- JRE --> 1.8
- Which Smile version -> 1.5.1 and 1.5.3 both tried
- What is your build system -> Ubuntu 16.04

Is this specifically because of the Android Studio? or this is generic issue with plot package??

Thanks for the solutions already !

**Comment by haifengl** [comment]
it is in smile-plot. And it is swing based and thus won't work on android.
