### ISSUE TITLE
PatternSyntaxException in SimpleTokenizer

### ISSUE THREAD

**Issue by goldthorp** [haifengl/smile#486]
## Expected behaviour

Should be able to instantiate SimpleTokenizer

## Actual behaviour

java.util.regex.PatternSyntaxException thrown on line 89

## Code snippet

new SimpleTokenizer(false);

## Input data

n/a

## Information

- Android sdk - java version 1.8.0_25
- 2.0.0
- MacOS

**Comment by goldthorp** [comment]
Is the library compatible with android?

**Comment by haifengl** [comment]
It is android java's issue. We have not tested the library on android.

**Comment by goldthorp** [comment]
OK - thanks for your reply
