### ISSUE TITLE
What is the correct usage of add() in FPGrowth?

### ISSUE THREAD

**Issue by tqhoc** [haifengl/smile#489]
Can you please explain how to properly use the add() function in FPGrowth? Perhaps I am misunderstanding how to use add(), or maybe how to properly set up the itemsets in the first place.

Consider the example below: 

* There are two itemsets: t1 = {a,b} and t2 = {a,c}
* We then map the variables to integers where a=0, b=1 and c=2
* We get the itemsets:
  * t1 = {0,1}
  * t2 = {0,2} 

After running learn() with minsup = 2

* Our output as expected is "0 (2)"
* Running size() we also get a size of 2 which is expected

Now, using add(), we add the itemset t3 = {b} and after mapping b=1 we get t3 = {1}.

There are now three itemsets:
* t1 = {0,1}
* t2 = {0,2}
* t3 = {1}.

Running learn() with minsup = 2, after having now added itemset t3

* We expect our output to be "0 (2)" and "1 (2)", but the output is instead only "0 (2)"
* Running size() we get a size of 3

I have included a code snippet below.

```
int[][] itemsets =
  {
    {0,1},
    {0,2}
  };

int[] itemset2 = {1};

int minSupport = 2;

FPGrowth growth = new FPGrowth(itemsets, minSupport);
//growth.add(itemset2);

System.out.println("Size is: " + growth.size());
System.out.println(growth.learn());

```

**Comment by haifengl** [comment]
The API had been simplified in v2. See the unit tests how to use it.
