### ISSUE TITLE
Latest news "Smile 2.0.0 released" on https://haifengl.github.io/ pointed to release v1.5.3

### ISSUE THREAD

**Issue by happy15** [haifengl/smile#490]
## Expected behaviour

pointed to https://github.com/haifengl/smile/releases/tag/v2.0.0

## Actual behaviour

pointed to https://github.com/haifengl/smile/releases/tag/v1.5.3

## Code snippet

n/a

## Input data

n/a

## Information

n/a

**Comment by haifengl** [comment]
Fixed.
