### ISSUE TITLE
KDTree should use distance squared, not distance

### ISSUE THREAD

**Issue by lukehutch** [haifengl/smile#491]
`KDTree.java` currently uses distance, not distance squared. This wastes work, since the `sqrt` is not necessary.

https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/neighbor/KDTree.java#L238
https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/neighbor/KDTree.java#L280
https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/neighbor/KDTree.java#L324

**Comment by haifengl** [comment]
I used to use MathEx.squaredDistance and do `sqrt` on the final result. In v2, neighbor fields become `public final` so that we have to calculate the distance in the first place. For real life data, we should not have notable performance difference for this small change.

**Comment by lukehutch** [comment]
Well, for my real world use case, I need to create hundreds of thousands of k-d trees, and perform trends of thousands of tests on each one... So every wasted cycle does matter!

**Comment by haifengl** [comment]
How about you do performance comparison with your real case and let's know the difference between distance and squaredDistance?

**Comment by lukehutch** [comment]
Sorry for the delay in benchmarking this. I finally got around to doing a distance comparison.

I made a copy of the `KDTree` class, and switched the code to used `MathEx.squaredDistance` rather than `MathEx.distance`.

Results for 1.2M queries of a three-dimensional `KDTree` containing 40000 points, running on a single core of a Ryzen-1800X CPU, on JDK 1.8:

* `distance`: 17738.37 queries/sec (67.65 sec total)
* `squaredDistance`: 139448.25 queries/sec (8.61 sec total)
* Speedup: 7.86x

Your assumption that `For real life data, we should not have notable performance difference for this small change` is incorrect.

Can you please reopen this bug?

**Comment by haifengl** [comment]
Thanks. Have you run your changes with unit tests?

**Comment by lukehutch** [comment]
I have unit tests for my own project, and those tests pass identically for the squared distance version. I didn't create a PR against the git latest version, because of your comment about fields being made `public static`. The changes are very straightforward, but I don't know what you want to do about the fact that you already publicly exposed the `distance` field in the class. Please advise.

**Comment by haifengl** [comment]
skipping sqrt cannot make 7.8x difference. I think that you miss the change to KD-Tree branch logic. The unit tests has a case on it. Please try it.

**Comment by lukehutch** [comment]
Please see #571. All SMILE unit tests pass with these changes. And the benchmark code I posted in that PR shows not a 7.8x speedup, but a 124x speedup.

**Comment by lukehutch** [comment]
Sumbitted a PR to fix the absolute value problem. (#572)
