### ISSUE TITLE
Classifier return Array of class confidences

### ISSUE THREAD

**Issue by mwelt** [haifengl/smile#498]
Add a function to classifier which does not predict a concrete class but rather return an array of class confidences i.e. softmax normalized classifier results as Array[Double] with Array[n] denoting confidence ([0, 1]) for class n .

**Comment by haifengl** [comment]
It is in `SoftClassifier`.

**Comment by mwelt** [comment]
Thanks a lot. Method signature wasn‘t that obvious to me :)
