### ISSUE TITLE
Question about predict of RegressionTree

### ISSUE THREAD

**Issue by myui** [haifengl/smile#50]
I have a question about the implementation of RegressionTree.

Why [`if (Math.equals(x[splitFeature], splitValue))`](https://github.com/haifengl/smile/blob/master/Smile/src/main/java/smile/regression/RegressionTree.java#L273) is used, instead of `if (x[splitFeature] == splitValue)`, while it is comparison for NOMINAL attribute?

[`Math.equals`](https://github.com/haifengl/smile/blob/master/SmileMath/src/main/java/smile/math/Math.java#L3151) is not exact equal. 

I assume a NOMINAL variable is a categorical variable.

**Comment by haifengl** [comment]
the data type is double. just in case of small random errors. it is most of a safe guard.

**Comment by myui** [comment]
Got it. 

BTW, `int to double` conversion does not  lose information. 
http://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1.2

And, assignment of `splitValue` is int to double conversion.
https://github.com/haifengl/smile/blob/master/Smile/src/main/java/smile/regression/RegressionTree.java#L516 

I'm not sure about `x` assignment though.

Thanks.

**Comment by haifengl** [comment]
input data is parsed as double. And I found some data files encode data always as doubles. It better be careful here. Thanks for investigation!
