### ISSUE TITLE
jackson-databind compatibility issues

### ISSUE THREAD

**Issue by nishant-ai** [haifengl/smile#500]
Does smile 2.0.0 have a dependency on some version of jackson-databind ?
Because as soon as I updated my project from smile 1.5.3 to smile 2.0.0, I am facing jackson-databind compatibility issues.  

Please help, thanks.

**Comment by nishant-ai** [comment]
Smile 2.0.0 apparently has a dependency on jackson-databind 2.9.8 but this version is not compatible with Apache Spark. Apache Spark 2.4.4 has a dependency on jackson-databind 2.6.7.
So, now I'm not able run my code where I'm using Spark and Smile together, which was running fine with Smile 1.5.3.
Can you suggest a fix for the same, @haifengl ?
Thanks.

**Comment by haifengl** [comment]
Smile doesn't use jackson directly. The dependency on jackson-databind 2.6.7 comes from `arrow` library, which is used by smile-io module. I guess that you don't really need smile-io when working on spark. If you use smile-scala module, you can use `exclude` to remove the dependency to jackson in your sbt build script.

**Comment by nishant-ai** [comment]
Got it, thanks !
