### ISSUE TITLE
ArrayIndexOutOfBoundsException in KDTree

### ISSUE THREAD

**Issue by lukehutch** [haifengl/smile#501]
Sometimes I get an ArrayIndexOutOfBoundsException at the line marked `(*)` in KDTree:

```java
    @Override
    public Neighbor<double[], E> nearest(double[] q) {
        NeighborBuilder<double[], E> neighbor = new NeighborBuilder<>();
        search(q, root, neighbor);
        neighbor.key = keys[neighbor.index];     // (*)
        neighbor.value = data[neighbor.index];
        return neighbor.toNeighbor();
    }
```

Here `neighbor.index == -1`. I am guessing that this should never happen.

Probably this is for a malformed kd-tree (maybe it is empty? I'm not sure, I generate a lot of kd-trees). 

Unfortunately I can't share the data that causes this issue.

**Comment by lukehutch** [comment]
Actually the tree is not empty, but the query contained `NaN`.

**Comment by lukehutch** [comment]
Hi, I ran into this again. Would it be possible to please change the `KDTree` constructor so that it throws `IllegalArgumentException` if `Math.isFinite` returns `false` for any of the key values that are passed in? The algorithm breaks with `NaN`/`infinity` values. Being notified of this when the `KDTree` is constructed would make debugging significantly simpler than trying to debug it downstream when you get a strange `ArrayOutOfBoundsException` in the middle of SMILE's code.

**Comment by haifengl** [comment]
How about does the user code do the check? The cost is the same no matter where is the check (in Smile or the user code). Other users seem not have data with NaN or Inf frequently. They don't need to pay the price.
