### ISSUE TITLE
Support reading CSV from other locations

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#502]
## Expected behaviour

I'd like to be able to read a CSV from over the network, from a `String`, etc. A method that takes an `InputStream` or `Reader` would be great

## Actual behaviour

Only accepts `Path`

## Information

- Smile 2.0

**Comment by haifengl** [comment]
We support reading data from HDFS/S3/HTTP etc. Checkout master. It is not CSV but all other file types.
