### ISSUE TITLE
Additional Feature : Create DataFrame directly from Scala training and label data

### ISSUE THREAD

**Issue by intelligentnet** [haifengl/smile#506]
## Would like

Create DataFrame directly from Scala training (Array of Arrays of values appropriate form the target algorithm) and label data

## Situation now in 2.0.0

Can only create a DataFrame from IO. Manipulation of dataframes is poor, much better done functionally in Scala then either put into a DataFrame when in the right 'shape' or alternatively the algorithm should use the 'raw' data (rather than DataFrame and formula).

## Would like to use Smile 2.0.0 with versions of Java > 1.8

**Comment by haifengl** [comment]
Checkout `DataFrame.of` methods, which can create data frame from an array/list/stream of objects, tuples, matrix or 2-dimensional arrays.

BTW, can you elaborate "Manipulation of dataframes is poor"?

**Comment by intelligentnet** [comment]
Thanks for the reply. I could not find anything in the docs. Though they are Java and Scala. I've just looked in the source and I think I have the method I need (static DataFrame of(double[][] data, String... names) I found Smile a couple of years ago, but was using Spark then, so did not look at in anger until a couple of days ago after having manipulated my IOT/Digital signage data into a form I expected to work. Old tutorials on previous versions of Smile lead me to believe it would be easy. 

I decided to try Smile as I wanted something lighter and leaner that Spark, but did not want to roll my own regression algorithms (and you have several, so I can experiment [regression with neural nets would be nice too]). 

I like what you have done, find the doc/tutorials out of date/confusing. I appreciate it's version 2.0.0 and will mature. As for DataFrame manipulation, I am a great Scala fan, it seems silly to me to re-implement what works well (and with 2.13 groupMapReduce etc are very useful too). So I find Spark bloated, slow and irritating (I suppose they need to work for the python crowd too). Again, possibly due to finding may way around, Dataframes looked limited and why re-implement something that works well in the base language. 

Thanks for your time, great work. There is functionality I like to see (a lot could be done with neural nets), and a course and turtorial would be good, perhaps I could help with them when I have some more experience. My email by the way is chris@dipple.org (amongst many).

**Comment by haifengl** [comment]
2.0 is a fully rewritten so that the doc is lagged. I am working on updating the doc and tutorial.

Although Scala is good but DataFrame is firstly designed for Java users. And Scala collection is row wise while DataFrame is column wise. If you try large data (10M records), you will see that our implementation is much more efficient. Besides, we have a thin layer in Scala on DataFrame so that you can apply Scala built-in functions on it.
