### ISSUE TITLE
Why would visualization randomly produce corrupted images?

### ISSUE THREAD

**Issue by robertvazan** [haifengl/smile#507]
## Expected behaviour

I am exporting visualizations to PNG image per FAQ. See snippet below. The plot being rendered comes from `Histogram.plot(double[])`. I think RNG is not used anywhere, because two executions of the code _usually_ produce identical results. I would expect the code to reliably produce identical visualization all the time.

## Actual behaviour

The visualization is however occasionally corrupted. When it is corrupted, everything is crammed into top left corner. I have similar export functionality for SVG using [Batik](https://xmlgraphics.apache.org/batik/) and when I diff good and corrupted SVG output, it seems to be identical except numeric constants that are close to zero in the corrupted image. I would guess the corrupted image is rendered with 0x0 size.

Image corruption is more probable shortly after the process starts, which suggests there is a race rule somewhere that is more pronounced when the code runs slowly.

## Code snippet

```java
@SneakyThrows public static byte[] toPng(int width, int height, PlotCanvas plot) {
	/*
	 * Smile's PlotCanvas sets its preferred size to 1600x1200 in the constructor.
	 * We have to override it here to get it sized properly.
	 */
	plot.setPreferredSize(new Dimension(width, height));
	/*
	 * The Headless code was taken straight from Smile FAQ.
	 */
	Headless headless = new Headless(plot);
	headless.pack();
	headless.setVisible(true);
	/*
	 * Here the Smile FAQ would make us call plot.save(File), but we don't want to create temporary files.
	 * The code below was pulled from plot.save(File) and modified to write to in-memory buffer instead.
	 */
	BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
	Graphics2D graphics = image.createGraphics();
	plot.print(graphics);
	ByteArrayOutputStream buffer = new ByteArrayOutputStream();
	ImageIO.write(image, "PNG", buffer);
	return buffer.toByteArray();
}
```

## Input data

I couldn't get it to reproduce reliably, but it helps to generate lots of different charts, each with different and sufficiently large dataset. The example below uses random data, but in my case I use only a few fixed datasets and I get random corruption on all of them.

```java
Random random = ThreadLocalRandom.current();
int count = 1000 + random.nextInt(10_000);
int range = 100 + random.nextInt(300);
PlotCanvas plot = Histogram.plot(IntStream.range(0, count).mapToDouble(n -> range * random.nextDouble()).toArray());
return toPng(800, 600, plot); // see toPng() in the code snippet above
```

## Information

- OpenJDK 11
- Smile 2.0.0
- Linux, inside flatpak container
- Wayland (no X Window, not even XWayland), so effectively headless from Java's point of view

I am also converting JFreeChart charts to PNG and SVG using nearly identical code and I never get corruption with JFreeChart images.

**Comment by haifengl** [comment]
Can you upload a picture of corrupted plot? Does this happen only with headless or also in interactive mode? Thanks

**Comment by robertvazan** [comment]
I found a likely cause and a workaround. You might wish to update the FAQ as follows (Java code, needs to be modified for Scala):

```java
Headless headless = new Headless(canvas);
headless.pack();
headless.setVisible(true);
SwingUtilities.invokeAndWait(() -> {
});
```

Posting an empty event via `SwingUtilities.invokeAndWait()` flushes the event queue, making sure that layout events scheduled by `headless.setVisible(true)` run to completion before the plot is painted into image.

This works, but it is still a dirty workaround. Theoretically, all Swing code should run only on the event dispatcher thread. If that is done, then the image is _always_ corrupted, because the layout events are then reliably processed _after_ the image is rendered. To fix that, the `Headless` object setup above has to be followed by event loop "yield", i.e. processing of all events in a secondary event loop created via `EventQueue.createSecondaryLoop()`. Only then the code is guaranteed to be correct.

I am nevertheless happy with the workaround alone. The really correct solution cannot be nicely encapsulated and thus complicates all application code, so I gave up on it. I don't know whether there is a way to expose nice image saving API without having some sort of direct support for multi-threaded off-screen rendering in Swing.

**Comment by haifengl** [comment]
Thanks. It seems an issue with Swing rather than Smile. Wonder how does JFreeCharts manage it.

**Comment by robertvazan** [comment]
`JFreeChart.draw()` takes an explicit size parameter as it doesn't rely on Swing layout. The only downside is that `JFreeChart` object must be wrapped in `ChartPanel` before it can be added to Swing UI, because it is not a Swing component on its own.

**Comment by haifengl** [comment]
I see. So JFreeChart doesn't Swing's Graphics and other drawing capability, I guess. BTW, we will support plots with Vega in next release, which doesn't rely on Swing.

**Comment by robertvazan** [comment]
Actually, `JFreeChart.draw()` does render into Swing's `Graphics2d`. This is useful when redirecting output to SVG via Batik.

Vega would be nice and it would be even nicer if it could produce static SVG server-side.

**Comment by haifengl** [comment]
I add this into `PlotCanvas.save()` function. Thanks
