### ISSUE TITLE
How to pass KDTree to DBSCAN

### ISSUE THREAD

**Issue by cyclic-1** [haifengl/smile#508]
I'm working with ~100k data points with 8 dimensions and performance is extremely slow. I've seen it suggested to pass a KDTree structure to the DBSCAN fit method but no examples are given and it's not clear in the docs either so I'm struggling to understand how to apply it. Are there any examples?

**Comment by haifengl** [comment]
```
double[][] x = ...
KDTree<double[]> kdtree = new KDTree<>(x, x);
DBScan<double[]> dbscan = DBSCAN.fit(x, kdtree, minPts, radius);
```

**Comment by simonshiwt** [comment]
can you give an example, how to use  KDTree in scala? thank you

**Comment by haifengl** [comment]
```
val kdtree = new KDTree(x, x)
val dbscan = DBSCAN.fit(x, kdtree, minPts, radius)
```

**Comment by simonshiwt** [comment]
> ```
> val kdtree = new KDTree(x, x)
> val dbscan = DBSCAN.fit(x, kdtree, minPts, radius)
> ```

thanks you.
