### ISSUE TITLE
能问下，你这些资料可以给我一些吗？不胜感激

### ISSUE THREAD

**Issue by intohole** [haifengl/smile#51]

**Comment by haifengl** [comment]
what materials?

**Comment by intohole** [comment]
ml and nlp materials , papers or books?

2015-12-07 23:12 GMT+08:00 Haifeng Li <notifications@github.com>:

**Comment by haifengl** [comment]
In the code, I list a couple of references in each algorithm's class documents. Check the java doc, which you can find the link in read me. For general introduction, the book "the elements of statistical learning" is pretty good.

**Comment by intohole** [comment]
thx !

2015-12-08 11:48 GMT+08:00 Haifeng Li <notifications@github.com>:
