### ISSUE TITLE
compilation error for JsonSerializer

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#510]
```
[error] C:\ray\code\smile\json\src\main\scala\smile\json\JsonSerializer.scala:302:24: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]     val start = buffer.position
[error]                        ^
[error] C:\ray\code\smile\json\src\main\scala\smile\json\JsonSerializer.scala:310:33: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]     buffer.putInt(start, buffer.position - start) // update document size
[error]                                 ^
[error] C:\ray\code\smile\json\src\main\scala\smile\json\JsonSerializer.scala:317:24: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]     val start = buffer.position
[error]                        ^
[error] C:\ray\code\smile\json\src\main\scala\smile\json\JsonSerializer.scala:325:33: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]     buffer.putInt(start, buffer.position - start) // update document size
[error]                                 ^
[error] C:\ray\code\smile\json\src\main\scala\smile\json\JsonSerializer.scala:352:24: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]     val start = buffer.position
[error]                        ^
[error] C:\ray\code\smile\json\src\main\scala\smile\json\JsonSerializer.scala:389:16: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]     if (buffer.position - start != size)
[error]                ^
[error] C:\ray\code\smile\json\src\main\scala\smile\json\JsonSerializer.scala:390:74: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type Any
[error]       logger.warn(s"BSON size $size but deserialize finishes at ${buffer.position}, starts at $start")
[error]                                                                          ^
[error] 7 errors found

```

**Comment by haifengl** [comment]
in master branch? I don't see these errors. what scala version do you use in build.sbt?

**Comment by rayeaster** [comment]
> in master branch? I don't see these errors. what scala version do you use in build.sbt?

yes, in master branch, I do not modify anything in build.sbt file
`$ sbt version
[info] Loading settings for project smile-build from plugins.sbt ...
[info] Loading project definition from C:\ray\code\smile\project
[info] Loading settings for project root from build.sbt ...
[info] Loading settings for project shell from build.sbt ...
[info] Loading settings for project scala from build.sbt ...
[info] Loading settings for project vega from build.sbt ...
[info] Loading settings for project json from build.sbt ...
[info] Loading settings for project benchmark from build.sbt ...
[info] Loading settings for project demo from build.sbt ...
[info] Loading settings for project plot from build.sbt ...
[info] Loading settings for project nlp from build.sbt ...
[info] Loading settings for project core from build.sbt ...
[info] Loading settings for project interpolation from build.sbt ...
[info] Loading settings for project graph from build.sbt ...
[info] Loading settings for project io from build.sbt ...
[info] Loading settings for project data from build.sbt ...
[info] Loading settings for project netlib from build.sbt ...
[info] Loading settings for project nd4j from build.sbt ...
[info] Loading settings for project math from build.sbt ...
[info] Set current project to smile (in build file:/C:/ray/code/smile/)
[info] io / version
[info]  2.1.0
[info] plot / version
[info]  2.1.0
[info] graph / version
[info]  2.1.0
[info] interpolation / version
[info]  2.1.0
[info] nd4j / version
[info]  2.1.0
[info] math / version
[info]  2.1.0
[info] netlib / version
[info]  2.1.0
[info] demo / version
[info]  2.1.0
[info] nlp / version
[info]  2.1.0
[info] data / version
[info]  2.1.0
[info] core / version
[info]  2.1.0
[info] json / version
[info]  2.1.0
[info] shell / version
[info]  2.1.0
[info] benchmark / version
[info]  2.1.0
[info] vega / version
[info]  2.1.0
[info] scala / version
[info]  2.1.0
[info] version
[info]  2.1.0
`

**Comment by haifengl** [comment]
Are you using Java 11 (or anything above 8)?

**Comment by rayeaster** [comment]
> Are you using Java 11 (or anything above 8)?

I guess yes, Java12, so do we need Java8 for smile compilation?

**Comment by haifengl** [comment]
Yes, JDK8 is required.

**Comment by rayeaster** [comment]
> Yes, JDK8 is required.

Ok, let me try with JDK8 then. Thanks

**Comment by rayeaster** [comment]
` sbt -java-home "/C/Program Files/Java/jdk1.8.0_221" clean compile` will do the magic
