### ISSUE TITLE
Confusing error message when null data in response variable

### ISSUE THREAD

**Issue by benmccann** [haifengl/smile#512]
## Expected behaviour

I would expect the exception to be something more like "IllegalArgumentException: null data is not allowed in response variable"

## Actual behaviour

```
java.lang.UnsupportedOperationException: y:Double
	at smile.data.vector.BaseVector.toDoubleArray(BaseVector.java:75)
	at smile.data.vector.BaseVector.toDoubleArray(BaseVector.java:67)
	at smile.regression.OLS.fit(OLS.java:122)
	at smile.regression.OLS.fit(OLS.java:108)
	at smile.regression.OLS.fit(OLS.java:88)
```

## Code snippet

```
Table data = Table.read().csv("regression.csv");
DataFrame dataframe = data.smile().toDataFrame();
LinearModel model = OLS.fit(Formula.lhs("y"), dataframe);
```

## Input data

It's a CSV with some empty cells including for the response variable

## Information

- Java 8
- Smile 2.0.0
- Ubuntu

**Comment by haifengl** [comment]
`toDoubleArray` is a general function for any vectors, not just response variable.

**Comment by benmccann** [comment]
It looks like `schema.boxed` returns `ObjectType(Double)` for a double column with a missing value. Then because the type is `ObjectType(Double)` we get just a plain `VectorImpl` instead of `DoubleVectorImpl`, so `toDoubleArray` fails. I'm assuming it's intended that `ObjectType(Double)` can't be converted to a `double[]`?

`BaseVector` does not need the methods `toDoubleArray` and `toIntArray` since they're not implemented. Instead there could be a `NumericVector extends BaseVector` which contains them. Then you could better handle unexpected conditions because you could check the type:
```
BaseVector vector = formula.y(data);
if (!vector instanceof NumericVector) {
  throw new IllegalArgumentException("Expected response variable " + vector.name() + " to be numeric");
}
```

**Comment by haifengl** [comment]
`DataType` has needed information. We don't really need `NumericVector`. I will check if we can support these methods for `Vector`. Anyway, we cannot support response variables with missing values.

**Comment by haifengl** [comment]
I add the implementation to VectorImpl. Missing values will be NaN for Double and Integer.MIN_VALUE for Integer.

**Comment by benmccann** [comment]
Cool!

I haven't tested with the new implementation, but it'd be interesting to see what the output is if there's a missing value. If there's no output, then ideally it'd throw some kind of exception explaining the issue
