### ISSUE TITLE
Null handling when reading arrow data looks incorrect

### ISSUE THREAD

**Issue by jhorstmann** [haifengl/smile#514]
I was looking at the data import functionality, especially the support for apache arrow and noticed something suspicious. In [smile.io.Arrow](https://github.com/haifengl/smile/blob/master/io/src/main/java/smile/io/Arrow.java#L408) the following pattern is used multiple times:

        if (fieldVector.getField().isNullable()) {
            // copies data without null checks
        } else {
            ...
            for (int i = 0; i < count; i++) {
                if (vector.isNull(i))
                    a[i] = null;
                else
                    a[i] = ...
            }

Unless the `isNullable` method has a completely misleading name this looks like a bug.

This seems to have been [introduced during a refactoring that incorrectly replaced `fieldVector.getNullCount() == 0` with `fieldVector.getField().isNullable()`](https://github.com/haifengl/smile/commit/63cc7a33fea247ed3d6fda5955a5ad767d35e0a2#diff-28f3a8cfa33ecb28f66842a2959743b9L280)

**Comment by haifengl** [comment]
Thanks for the report. The fix is in master branch now.

**Comment by jhorstmann** [comment]
Thanks, looks good to me. And that was an impressively fast time for a fix.
