### ISSUE TITLE
Set x- and y-axis limit

### ISSUE THREAD

**Issue by toomasliiv** [haifengl/smile#516]
I am trying to create a histogram in SMILE and then setting the y- and x-axis limits. However, I only seem to find the function extendBounds(double[], double[]), which can extend the bounds, but not shrink them. 

Is this functionality hidden elsewhere, or is there a design reason it is not included? 

For reference, setting the limits is a very common part of standard workflow in R/Python/Matlab, needed to get plots that are comparable to eachother.

**Comment by haifengl** [comment]
Right click on the plot, Properties, then change axis range.

If you want to do it by code, use `Axis.setBase()`

**Comment by toomasliiv** [comment]
Thank you for your answer.

I want to do it by code. It is intended to be used in headless mode, producing hundreds of plots for later review. 

However, I am still having problems. First, I create a PlotCanvas object by 		
```
		double[] lowerBound = new double[] {-10, 0.0};
		double[] upperBound = new double[] {10, 0.5};
		PlotCanvas canvas = new PlotCanvas(lowerBound, upperBound, false);
```
and then add a histogram to it by 

`canvas.histogram(data, new Color(1));`

Now, the x-axis bounds are extended further than I specified, -10 to 10. Note that there is data outside this range, but for better viewing and comparability purposes, I want to hide it.

So I want to try your suggestion of using Axis.setBase(), but how do I access the PlotCanvas Axis-object? It only has a getter method, but I need to set it.

**Comment by haifengl** [comment]
The below is hacking and I don't suggest the usage in normal case.

You can directly modify the returned array of `Base.getLowerBounds()` and `Base.getUpperBounds()`.  Then call `Base.initBaseCoord()`.

**Comment by haifengl** [comment]
BTW, since you create histogram, why don't you filter out outliers from your data first. It is much easier and more robust than changing the plot range.

**Comment by toomasliiv** [comment]
Base.initBaseCoords() is not a public method, so unfortunately I cannot access it. 

I do not want to filter out the data first, since that would give incorrect probability densities. 

Also, this is not just intended to be used in the case of a histogram, but for all kinds of plots, to easily programmatically generate them with the same axis, so they later can be compared to each other fairly. Without this functionality, I will need to continue exporting to .csv files and then plotting in R/Python/Matlab, but it would be so much more convenient if everything could be done directly from Java,

**Comment by haifengl** [comment]
I add the method `Base.setBound()`.
