### ISSUE TITLE
Publish smile-vega for Scala 2.12

### ISSUE THREAD

**Issue by darrenjw** [haifengl/smile#517]
## Expected behaviour

I am attempting to use Smile as a Scala library. I add a dependency on "smile-scala" in SBT.

```scala
libraryDependencies  += "com.github.haifengl" %% "smile-scala" % "2.1.1"
```

## Actual behaviour

This works for Scala 2.13, but fails (for me) for Scala 2.12 (and Scala 2.11), as "smile-scala" has a dependency on the "smile-vega" artifact, but this appears only to be published to Maven Central for Scala 2.13.

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version

OpenJdk 1.8, SBT 1.3.3

- Which Smile version

2.1.1

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )

Ubuntu 18.04

**Comment by haifengl** [comment]
Both 2.12 and 2.11 are published now.

**Comment by darrenjw** [comment]
Many thanks for your prompt response. These artefacts are now on Maven Central. Unfortunately I still can't use this on 2.11 or 2.12 as something seems to be wrong with the cross-build configuration.

If I run sbt from an empty directory, then at the sbt prompt enter:
```scala
set scalaVersion := "2.12.10"
set libraryDependencies  += "com.github.haifengl" %% "smile-scala" % "2.1.1"
console
```
The console fails to start, giving error:
```scala
[error]    com.github.haifengl:smile-json _2.12, _2.13
[error]    com.typesafe.scala-logging:scala-logging _2.13, _2.12
[error] stack trace is suppressed; run last update for the full output
[error] (update) Conflicting cross-version suffixes in: com.github.haifengl:smile-json, com.typesafe.scala-logging:scala-logging
```
Similarly if I set the scalaVersion to a 2.11 release. If I set to 2.13.1, everything works fine.

**Comment by haifengl** [comment]
Not sure what's the root cause. I will make a new release (2.2) soon. Hope it will have no issues with cross-build.

**Comment by haifengl** [comment]
2.2.0 is release. please have a try. thanks

**Comment by darrenjw** [comment]
Thanks, but unfortunately this still doesn't work (for me, at least). To reproduce, run a (recent) version of SBT from an _empty_ directory, and then enter the following at the SBT prompt:
```scala
set scalaVersion := "2.12.10"
set libraryDependencies  += "com.github.haifengl" %% "smile-scala" % "2.2.0"
console
```
This _should_ give a Scala REPL with a dependency on Smile, but instead gives an error (for me):
```scala
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/tmp/test/"), "test"):
[error]    com.github.haifengl:smile-json _2.13, _2.12
[error]    com.typesafe.scala-logging:scala-logging _2.13, _2.12
```

**Comment by haifengl** [comment]
#522 is the root cause. I tested that it works once I remove data module's dependency of json (an accident). Will make a 2.2.1 release shortly.

**Comment by haifengl** [comment]
2.2.1 is published.

**Comment by darrenjw** [comment]
Brilliant! This works for me now as a Scala library across 2.11, 2.12 and 2.13. Many thanks for your efforts.
