### ISSUE TITLE
Java api documentation page not found

### ISSUE THREAD

**Issue by Adriankhl** [haifengl/smile#520]
http://haifengl.github.io/api/java/index.html shows nothing. Is this equivalent to http://haifengl.github.io/api/?

**Comment by haifengl** [comment]
Try http://haifengl.github.io/api/index.html for now. I will fix it. Thanks

**Comment by haifengl** [comment]
Fixed. If it still doesn't work you by refreshing, try https.

**Comment by Adriankhl** [comment]
It works, thanks!
