### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by TIBCOeddie** [haifengl/smile#521]
## Expected behaviour

Apache or MIT

## Actual behaviour

Changed to LGPL

## Code snippet

n/a

## Input data

n/a

## Information

Hello! My team and I at TIBCO have been playing around with Smile integrations... but the recent change to LGPL becomes problematic in a commercial context. Is there a reason for the LGPL switch? Could this be reviewed?

**Comment by TIBCOeddie** [comment]
Ah. I just noticed #439 . Sadly I have to disagree with the final conclusion, LGPL can be problematic. Curious if there is some openness here to review, re-discuss or if there's some open spirit to other alternatives.

**Comment by haifengl** [comment]
Thanks for interesting in Smile. What're the issues with LGPL in commercial context? You can also contact me in LinkedIn in case of business sensitivity.

**Comment by TIBCOeddie** [comment]
While in theory LGPL licensed libraries should be acceptable for commercial use - many of our customers and partners are concerned about their potential exposure and  ask us for special handling when LGPL libraries are included in our commercial offerings, which adds cost to us.   Under your previous license agreement - and this was pointed out by several other comments in the initial issue - we would be inclined to contribute our changes back to the project so it's easier for us to consume upgrades.   In our case the change to LGPL will mean we look for alternatives.  Would be great if you would reconsider.

**Comment by haifengl** [comment]
If a business user has concerns with L-GPL, they may acquire a commercial license from us.

**Comment by TIBCOeddie** [comment]
I will find you on LinkedIn and we'll follow up that way. This issue can close if you prefer.

**Comment by gforman44** [comment]
I'm sorry to see the change to LGPL.  My company lets us use Apache/MIT/Berkeley/BSD 2/3 clause, and many others, but LGPL is problematic.  The legal dept. understands it, I guess. 

Anyway, for greater adoption of SMILE, I would urge you to go back to Apache or one of the others.
