### ISSUE TITLE
smile-data has hard-coded dependency on Scala 2.13 (smile-json_2.13)

### ISSUE THREAD

**Issue by kamilkloch** [haifengl/smile#522]
https://mvnrepository.com/artifact/com.github.haifengl/smile-data/2.2.0

**Comment by haifengl** [comment]
Thanks a lot! This is actually the root cause of #517. Will publish a new release shortly.

**Comment by haifengl** [comment]
2.2.1 is published.

**Comment by kamilkloch** [comment]
Thanks! Not there yuet, though ;) https://mvnrepository.com/artifact/com.github.haifengl/smile-data
