### ISSUE TITLE
EDT violation in Window.apply

### ISSUE THREAD

**Issue by mchmaj** [haifengl/smile#523]
It is actually impossible to properly call Window.apply. The creation of a new frame should happen in EDT, but then it is modified using SwingUtilities.invokeAndWait - which throws an exception when called from EDT. Thus, Window.apply cannot be called from EDT and should nor be called outside it.
A workaround might be to check if we are in EDT and only do the repaints and toFronts inside invokeAndWait if we are not.

**Comment by haifengl** [comment]
Are you building a rich desktop app? `Window` was designed for the shell usage. It is why we have to call `invokeAndWait`. `Window` class is a very thin layer of the real implementation of plot functionality. You can create your own version in rich desktop app.
