### ISSUE TITLE
Create DataFrame will null value in tuple field causes NPE

### ISSUE THREAD

**Issue by swarwick** [haifengl/smile#535]
**Describe the bug**
When you use DataFrame.of() and pass in List<smile.data.Tuple> dataTuples with a correct StructType for the tuples but a single field in any of the tuples passed in has a null value a NPE is thrown

**Expected behavior**
A DataFrame is still created with the data given

**Actual behavior**
java.lang.NullPointerException

**Code snippet**
`    @Test
    public void testDataFrameWithNull() throws Exception {
        StructType internalStructType = new StructType(Arrays.asList(new StructField [] { 
                new StructField("field1", smile.data.type.DataTypes.IntegerType) }));

        StructType structType = new StructType(new StructField("data", smile.data.type.DataTypes.object(smile.data.DataFrame.class)));
        logger.info("Struct:\r\n{}",structType.toString());
        
        Object [] internalTupleData = new Object[internalStructType.fields().length];
        internalTupleData[0] = 1;
        smile.data.Tuple internalSmileTuple = smile.data.Tuple.of(internalTupleData, internalStructType);
        logger.info("Tuple1:\r\n{}",internalSmileTuple.toString());
        
        Object [] internalTupleData2 = new Object[internalStructType.fields().length];
        internalTupleData2[0] = null;
        smile.data.Tuple internalSmileTuple2 = smile.data.Tuple.of(internalTupleData2, internalStructType);
        logger.info("Tuple2:\r\n{}",internalSmileTuple2.toString());
        
        List<smile.data.Tuple> dataTuples = new ArrayList<>();
        dataTuples.add(internalSmileTuple);
        dataTuples.add(internalSmileTuple2);
        
        Object [] tupleData = new Object[structType.fields().length];
        tupleData[0] = DataFrame.of(dataTuples, internalStructType);
        smile.data.Tuple smileTuple = smile.data.Tuple.of(tupleData, structType);
        logger.info("Smile Tuple:\r\n{}", smileTuple.toString());
    }`

**Additional context**
- Java 8
- Master Branch
- MacOs

If appears as though inside of the public DataFrameImpl(List<Tuple> data, StructType schema) constructor it is checking the data type but not checking for nulls while iterating over the items in the frame.

**Comment by swarwick** [comment]
It seems odd to me how half the code seems to use Integer while the other half uses int. So for instance the 
`public DataFrameImpl(List<Tuple> data, StructType schema) {`

takes in a tuple and say the field is an Integer, then its converted to an int[] vs Integer[] and then passed into an IntVector which has a declaration of
`BaseVector<Integer, Integer, IntStream>`
But takes in int[] vs Integer[] which would match is declaration and allow for null values.

**Comment by haifengl** [comment]
The rule is that if you have no missing values, use `DataTypes.IntegerType`, `DataTypes.DoubleType`, etc. This provides best performance and low memory usage. If you have missing values, use `DataTypes.IntegerObjectType`, `DataTypes.DoubleObjectType`, respectively.
