### ISSUE TITLE
Error with cumulative t distribution function 

### ISSUE THREAD

**Issue by tibcodscott** [haifengl/smile#536]
The cumulative t distribution function returns an incorrect value.  

Specifically, I am trying to compute Pr( t < 0.003396331870946646) where t is distributed according to a t distribution with df = 119398.  The value according to R is about 0.501354935, however, using smile I get a value of 0.5.

See java code below to reproduce: 
TDistribution t = new TDistribution(119398);
double pval = t.cdf(0.003396331870946646);

**Comment by haifengl** [comment]
For very large `df`, R uses a normal distribution approximation int the tails. The below is from R's documentation.

```
For the central case of pt, a normal approximation in the tails, otherwise via pbeta.
```

**Comment by tibcodscott** [comment]
I also see the same problem with the following code when I change df = 19.  In smile I get 0.5 as the result whereas in R and in apache commons math I get about 0.5001034.  

TDistribution t = new TDistribution(19);
double pval = t.cdf(0.00026267743669450283);

**Comment by haifengl** [comment]
You are using a very small `x=0.00026267743669450283`. Therefore, `1 - df/(df+0.00026267743669450283*0.00026267743669450283)` is about 3E-9. For such small values (< 1E-8), we approximate the beta function as 1, therefore cdf as 0.5.

**Comment by haifengl** [comment]
If I lower the guard to `1E-10`, we will go through the normal beta function, and get the `t.cdf(0.00026267743669450283) = 0.5001034239359441`.

BTW, here is why we add this guard.
```
This function is often used to calculate p-value of model fitting.
Due to floating error, the model may provide a x that could be slightly
greater than 1 or less than 0. We allow tiny slack here to avoid brute exception.
```

**Comment by haifengl** [comment]
I revise the beta function guard so that we will get the same values. Try it from maser branch.

**Comment by tibcodscott** [comment]
Thanks for addressing this.
