### ISSUE TITLE
do we have code example about how to use smile.nlp.embedding.Word2Vec

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#538]
The `smile.nlp.embedding.Word2Vec` class seems not re-implementing the alogrithm but provide methods to load trained models instead. Do we have examples or test data to showcase the usage of the intended functionality? e.g., what type of model files are supported to be loaded?

**Comment by haifengl** [comment]
[Word2Vec](https://code.google.com/archive/p/word2vec/) models can be loaded by the method `Word2Vec.of()`.  [GloVe](https://nlp.stanford.edu/projects/glove/) models can be loaded by `Word2Vec.text()`.

**Comment by rayeaster** [comment]
> loaded

Thanks for the Word2Vec and GloVe reference links. 

I am wondering using some graph algorithms like [random deep walk] which use `Skip-Gram` from `Word2Vec` (http://www.perozzi.net/publications/14_kdd_deepwalk.pdf)

Do we have plan to add graph representation/network embedding in smile? which might quite useful in nowadays for financial service, e-commerce, recommendation system and anormaly detection

**Comment by rayeaster** [comment]
> [Word2Vec](https://code.google.com/archive/p/word2vec/) models can be loaded by the method `Word2Vec.of()`. [GloVe](https://nlp.stanford.edu/projects/glove/) models can be loaded by `Word2Vec.text()`.

Thanks for the Word2Vec and GloVe reference links.

I am wondering using some graph algorithms like [random deep walk] which use `Skip-Gram` from `Word2Vec` (http://www.perozzi.net/publications/14_kdd_deepwalk.pdf)

Do we have plan to add graph representation/network embedding in smile? which might quite useful in nowadays for financial service, e-commerce, recommendation system and anormaly detection

**Comment by haifengl** [comment]
I have no plan. But you surly can make a PR. Thanks.

**Comment by rayeaster** [comment]
> I have no plan. But you surly can make a PR. Thanks.

will investigate after umap work
