### ISSUE TITLE
Denclue does not work on medium-sized datasets [Recursion problem (Kd-tree)]

### ISSUE THREAD

**Issue by nabilEM** [haifengl/smile#539]
The version of Denclue under Java runs on small data sets, for example six.txt (data set provided in smile) and other personal ones about the same size.  But it does not work on medium-sized datasets, for example a two-dimensional dataset containing 5000 points. The cause is due to the Kd-tree used in DBSCAN. Here is the information about the error:

"""
Exception in thread "main" java.lang.StackOverflowError
        at smile.neighbor.KDTree.buildNode(KDTree.java:223)
        at smile.neighbor.KDTree.buildNode(KDTree.java:223)
        at smile.neighbor.KDTree.buildNode(KDTree.java:223)
......
 at smile.neighbor.KDTree.buildNode(KDTree.java:223)Traceback (most recent call last)
"""

I would like to know how I could solve this recursion problem so that I could run Denclue on medium to large datasets.

Thank you in advance.

Technical information:
- java version: 14
- operating system: Windows and Linux
- smile version: 2.3.0

**Comment by haifengl** [comment]
- DENCLUE doen't use KDTree
- Are you really talking about DBScan? If so, it use LinearSearch by default. You don't have to use KDTree
- KDTree should not use up stack normally. Generally, it use only log(n) stack. Very likely, your data is ill-posed.

**Comment by nabilEM** [comment]
Thank you for your response. I saw in the code that Denclue uses Dbscan in the fit function. And in turn Dbscan calls Kd-tree. Maybe in my version of smile (2.3.0) it doesn't use LinearSearch by default. I tested it on several different data sets, on small Denclue works but on large (several thousand two-dimensional points) it falls on the recursion problem caused by Kd-tree.

**Comment by haifengl** [comment]
No.

**Comment by haifengl** [comment]
In general, KDTree should not use up stack. What's the dimension of your data? Please note that DBSCAN and DENCLUE are designed for low dimensional data.

**Comment by haifengl** [comment]
I also enhanced KDTree to handle data points that are extremely close to each other. You can try the master branch. I have tested it on a variety data without issues.

**Comment by nabilEM** [comment]
> I also enhanced KDTree to handle data points that are extremely close to each other. You can try the master branch. I have tested it on a variety data without issues.

Thank you for your response and the additions you have made to your solution. So I'm downloading the new version.
