### ISSUE TITLE
Question about categorical/nominal predictors in Smile

### ISSUE THREAD

**Issue by tibcodscott** [haifengl/smile#543]
What is best practice within smile to inform a predictive modeling algorithm, e.g. logistic regression, linear regression, random forest, etc., that a predictor is categorical in nature?  Do I need to explicitly perform the coding myself, e.g. "one-hot encoding", or is there a mechanism that I can use where smile internally codes the factors for me and/or handles this for me?  This is especially relevant for those algorithms like linear/logistic regression which operate on a design matrix.  Thank you.

**Comment by haifengl** [comment]
In the DataFrame, set the measure of nominal variables to NominalScale. Normally, you don't have to do it manually as the data loader of DataFrame usually figures it out automatically.

**Comment by tibcodscott** [comment]
Thank you for your response.  How would I do this for logistic regression?  

Here is a simple example, 
public static class Datum 
{
        String StringCol;
        int IntCol;
        
        Datum(String StringCol, int IntCol) 
        {
            this.StringCol = StringCol;
            this.IntCol    = IntCol;
        }
        public String getStringCol() {return StringCol;}
        public int getIntCol() {return IntCol;}
}
ArrayList<Datum> datum = new ArrayList<Datum>();
for(int i=0; i<3; i++) {
	datum.add(new Datum("a",0));
	datum.add(new Datum("b",0));
	datum.add(new Datum("b",1));
	datum.add(new Datum("c",1));
	datum.add(new Datum("d",0));
	datum.add(new Datum("d",1));
	datum.add(new Datum("e",1));
}
		
DataFrame df = DataFrame.of(datum, Datum.class).factorize();
Formula formula = Formula.of("intCol", $("stringCol"));
smile.classification.LogisticRegression lr = smile.classification.LogisticRegression.fit(formula, df);

When I fit this with logistic regression, I would like StringCol to be treated as categorical in the sense that additional dummy columns are created in the design matrix, that is, instead of one column I would like StringCol_a, StringCol_b, etc.  How do I inform logistic regression (and linear regression too) that StringCol should be treated as categorical?

**Comment by haifengl** [comment]
logistic regression cannot handle categorical variables directly. one-hot encoding need to be applied first.

**Comment by tibcodscott** [comment]
Thank you.  If I have previously trained a model, for example on the above dataset, and I now want to apply the trained model to new data, is there a mechanism to insure that the one hot encoding is performed in the same manner as on the training dataset?  I am assuming this is my responsibility,  and not Smile's, correct?

**Comment by haifengl** [comment]
yes

**Comment by tibcodscott** [comment]
Thank you
