### ISSUE TITLE
Problem building SMILE locally on machine

### ISSUE THREAD

**Issue by tibcodscott** [haifengl/smile#544]
I am trying to build SMILE locally on my machine. I am using OpenJDK 11 & OpenJFX. I am getting the following issues (see attached log) when trying to build the project using SBT. Would you please advise me on what I might be doing wrong?
[log.txt](https://github.com/haifengl/smile/files/4559917/log.txt)

**Comment by rayeaster** [comment]
try with JDK8?
also check https://github.com/haifengl/smile/issues/510

**Comment by tibcodscott** [comment]
Thank you
