### ISSUE TITLE
Broken link for Neural Networks classifier

### ISSUE THREAD

**Issue by cowwoc** [haifengl/smile#546]
**Describe the bug**
If you click on "Neural Networks" on https://haifengl.github.io/ you will get an HTTP 404.

**Comment by rayeaster** [comment]
https://haifengl.github.io/api/java/smile/classification/MLP.html

**Comment by haifengl** [comment]
Thanks for reporting. I have updated the links.

**Comment by cowwoc** [comment]
Thank you.
