### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path

### ISSUE THREAD

**Issue by fcyu** [haifengl/smile#548]
**Describe the bug**
When calling this library in my program, throwing an exception: Exception in thread "main" java.lang.UnsatisfiedLinkError: no mkl_rt in java.library.path.
I am using maven.

**Expected behavior**
Shipping an open source BLAS library and use that if users don't have MKL.

**Additional context**
- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
Oracle JDK 1.8
- Which Smile version
2.4.0
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Windows 10
- Add any other context about the problem here.
Smile 2.2.0 works well without MKL.

**Comment by haifengl** [comment]
MKL is free. If you use the prebuilt smile package, mkl dll are available in smile/bin directory. Make sure it is in PATH. In next major release, native libraries will be included in the package.

**Comment by fcyu** [comment]
Sounds great! I will wait for the next release. Thanks.
