### ISSUE TITLE
Multiplication of transposed non-square NLMatrix

### ISSUE THREAD

**Issue by albertmolinermrf** [haifengl/smile#549]
**Describe the bug**
The `atbtmm` method of `NLMatrix` returns wrong results if one of the matrices is not squared.

**Expected behavior**
`b.atbtmm(a)` should be equal to `a.abmm(b).transpose()` if `a` and `b` are instances of `NLMatrix` with compatible dimensions.
If for some reason this method is restricted to square matrices, then an `IllegalArgumentException` would be preferrable to a wrong result.

**Actual behavior**
Results are different if for example `a` is not square.
The result is correct if the matrices are instances of `JMatrix`.

**Code snippet**
```
    @Test
    public void atbtmm() {
        double[][] A = {
                {2, 3}
        };
        double[][] B = {
                {-1, 1},
                {0, 1}
        };

        double[][] C = {
                {-2, 5}
        };

        NLMatrix a = new NLMatrix(A);
        NLMatrix b = new NLMatrix(B);
        double[][] D = new NLMatrix(C).transpose().toArray();

        assertTrue(MathEx.equals(a.abmm(b).toArray(), C, 1E-7));
        assertTrue(MathEx.equals(b.atbtmm(a).toArray(), D, 1E-7));
    }
```

**Additional context**
- Smile version: 2.4.0
- OS: Mac OS

**Comment by haifengl** [comment]
`atbt = A' * B'` by definition.  `ab.transpose = B' * A'`. They should not be same.

**Comment by albertmolinermrf** [comment]
Please notice that I am comparing `A * B` with `(B' * A')' = A'' * B'' = A * B`. And that the results match if `JMatrix` is used instead of `NLMatrix`. Shouldn't the results be consistent regarless of the matrix implementation?

**Comment by haifengl** [comment]
NLMatrix leverages the native library for matrix multiplication. I don't see any issues with the call to native library. It is weird.

**Comment by albertmolinermrf** [comment]
From http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaeda3cbd99c8fb834a60a6412878226e1.html (I guess any other BLAS documentation will do), the tenth parameter of `dgemm` has to be at least `n` when transposing.

However, apparently it is receiving `k` in `atbtmm`:
https://github.com/haifengl/smile/blob/4fa102fa1fbf8d99b6b1aeee255c8ee885c97e66/netlib/src/main/java/smile/netlib/NLMatrix.java#L208

**Comment by haifengl** [comment]
Thanks. But both n and k are 2 in your test case. Something else is still wrong.

**Comment by haifengl** [comment]
Thanks! The fix is in master branch.
