### ISSUE TITLE
Can not read ‘.csv’ file on windows

### ISSUE THREAD

**Issue by Mng12345** [haifengl/smile#551]
**Describe the bug**
An Exception was throwed when I use Read.csv to read windows file.
I got this below by usring Read.csv("file:/E:/mypath...")
`Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/E:/IdeaProjects/stockexchange/data.csv
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at smile.io.Input.stream(Input.java:50)
	at smile.io.Input.reader(Input.java:40)
	at smile.io.CSV.read(CSV.java:108)
	at smile.io.CSV.read(CSV.java:97)
	at smile.io.Read.csv(Read.java:56)
	at smile.io.Read.csv(Read.java:49)`
then, i got this below by using Read.csv("E:/mypath...")
`Exception in thread "main" java.net.MalformedURLException: unknown protocol: e
	at java.net.URL.<init>(URL.java:607)
	at java.net.URL.<init>(URL.java:497)
	at java.net.URL.<init>(URL.java:446)
	at java.net.URI.toURL(URI.java:1089)
	at smile.io.Input.stream(Input.java:53)
	at smile.io.Input.reader(Input.java:40)
	at smile.io.CSV.read(CSV.java:108)
	at smile.io.CSV.read(CSV.java:97)
	at smile.io.Read.csv(Read.java:56)
	at smile.io.Read.csv(Read.java:49)
`
So, i read the stacktrace{Input.class):
`static InputStream stream(String path) throws IOException, URISyntaxException {
        URI uri = new URI(path);
        if (uri.getScheme() == null) {
            return Files.newInputStream(Paths.get(path));
        } else {
            String var2 = uri.getScheme().toLowerCase();
            byte var3 = -1;
            switch(var2.hashCode()) {
            case 3143036:
                if (var2.equals("file")) {
                    var3 = 0;
                }
            default:
                switch(var3) {
                case 0:
                    return Files.newInputStream(Paths.get(path));
                default:
                    return uri.toURL().openStream();
                }
            }
        }
    }`
if i put "file:/" before my path, the variable var3 will be 0, and then, the code Files.newInputStream(Paths.get(path)) will be execued, finally got  java.nio.file.InvalidPathException,
if just use normal path, the code uri.toURL().openStream() will be executed, finally got java.net.MalformedURLException.
So, using new URI(path) to read file may not be an appropriate way

**Comment by haifengl** [comment]
Try

```
Read.csv("file:///E:/mypath...")
```

`file://` indicates the protocol. Then `/E:/mypath...` is the file path. `file:/` is wrong.

**Comment by Mng12345** [comment]
Actually i haved tryed both file:/// and file:/, it just throwed the same Exception

> Try
> 
> ```
> Read.csv("file:///E:/mypath...")
> ```
> 
> `file://` indicates the protocol. Then `/E:/mypath...` is the file path. `file:/` is wrong.

**Comment by haifengl** [comment]
The fix is in master branch now. You can do
```
Read.csv("E:/mypath...")
```
or
```
Read.csv("file://E:/mypath...")
```
Note that only two slashes in the second case.

**Comment by Mng12345** [comment]
Thank you! How much time will the package be updated in maven?

> The fix is in master branch now. You can do
> 
> ```
> Read.csv("E:/mypath...")
> ```
> 
> or
> 
> ```
> Read.csv("file://E:/mypath...")
> ```
> 
> Note that only two slashes in the second case.

**Comment by haifengl** [comment]
We don't make a release based on a single ticket. We are working on some major improvements. So it will take some time.

It is easy to build and publish smile locally. If you don't want to do that, you can change your working directory to E: and then use relative path to read data.
