### ISSUE TITLE
`HyperGeometricDistribution`: incorrect `randi()` result

### ISSUE THREAD

**Issue by PoslavskySV** [haifengl/smile#552]
**Describe the bug**
`rand()` in `HyperGeometricDistribution` does not account for (N-m) constraint.

**Expected behavior**
`rand()` must return value >= 5 (see test case below)

**Actual behavior**
`rand()` returns wrong value (< 5 in test case below)

**Code snippet**
```java
int N = 44 + 13;
int m = 44;
int n = 18;

HyperGeometricDistribution dist = new HyperGeometricDistribution(N, m, n);
for (int i = 0; i < 100; ++i) {
    int w = dist.randi();
    System.out.println(w);
    Assert.assertTrue(n - w <= N - m);
}
```

**Additional context**
- OpenJDK 14
- 2.4.0
- OS X

**Comment by haifengl** [comment]
Thanks for reporting. The fix is in master branch now.

**Comment by PoslavskySV** [comment]
Thanks!
