### ISSUE TITLE
Could you provide a detailed documentation or examples of how to use `Read.json` 

### ISSUE THREAD

**Issue by Mng12345** [haifengl/smile#553]
**Is your feature request related to a problem? Please describe.**
I want to read json string from some of my backend api into a DataFrame. There are two problems now: 1. the api Read.json(String jsonStr) is not supported. 2.I don't know how to use Read.json(Path path) to read a json file which contians an JSONArray like object, and i could not find some detailed documention about how to use the api, even though after reading the smile.io.JSON.java code.

**Comment by haifengl** [comment]
1. If you want to parse a JSON string directly, wrap it into a `BufferedReader` and use `smile.io.JSON.read()` method parse.

2. See the unit test. For your case, your should use `MULTI_LINE` mode. See the test case with book2.json. The json. file is in `shell/src/universal/data/json`.

**Comment by Mng12345** [comment]
> 1. If you want to parse a JSON string directly, wrap it into a `BufferedReader` and use `smile.io.JSON.read()` method parse.
> 2. See the unit test. For your case, your should use `MULTI_LINE` mode. See the test case with book2.json. The json. file is in `shell/src/universal/data/json`.

Thank you! I have read the json file successfully!
