### ISSUE TITLE
Prediction with new single-row DataFrame fails

### ISSUE THREAD

**Issue by ddennyd** [haifengl/smile#555]
Hello all,

I couldn´t find anything relatable in the documentation regarding this topic. Can you please help me out?
I got following problem:
I create a DataFrame from a collection with Java objects. After that I factorize the DataFrame.
I train a model with this DataFrame and serialized the trained model.
Then I create again a new DataFrame from a collection of Java objects but with only **one** new object in it. This new DataFrame also gets factorized. I load the serialized model in my programm and use it to predict the new DataFrame with the predict() method.
The model now classifies this new DataFrame always with the same (wrong) label.
(I tried this with serval different objects in the DataFrame and the model always predicts the same wrong label.)

I thought the mistake is because of the different schemas. (The train DataFrame has a different schema as the new DataFrame which is used for the prediction.)
So I copy the previous DataFrame, which was used for the training, and add the new object into this DataFrame and factorize it. After that the labeling of the new row is working fine.

How can I avoid it to use the "old, previous" DataFrame? Shouldn´t the model also work with only a new one-row DataFrame?

**Comment by haifengl** [comment]
The `factorize` operation use all the rows of `DataFrame` to figure out the level of categorical variables. Apparently, it won't work with the second `DataFrame`, which doesn't have all the information.

I suggest that you use the `Measure` of categorical variables in the schema of first DataFrame to transfer strings in the new data.

**Comment by ddennyd** [comment]
Thanks for your fast answer.
How is it possible to transfer the Measure from one DataFrame to another? 
The problem is that I make the predicition not in the same process in which the training happens (that´s also the reason why I serialize the model), so I need to make the DataFrame Measure persistent if there is no other possibility....

If the new DataFrame contains some categorical attributes, which the old DataFrame hasn´t, is it still possible to correctly predict the label by using the GradientBoostedTree?

**Comment by haifengl** [comment]
`factorize` is for String with limited range of values. That is, it is really for Enum in Java. This method is useful when you parse data from csv/json. But since you convert Java object to DataFrame, I suggest that you revisit your class design. If the string field is categorical indeed, you should change it to Enum. If not, generic String fields should not be used in model.

**Comment by ddennyd** [comment]
Okay, thanks a lot!
