### ISSUE TITLE
Isolation Forest for anomaly detection

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#557]
`Isolation Forest` is useful algorithm in anomaly detection, low processing time and low memory footprint:

paper: [https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/icdm08b.pdf](https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/icdm08b.pdf)

reference implementation in Matlab by paper author: https://github.com/zhuye88/iForest

**Comment by conquer66666** [comment]
please add the new feature

**Comment by haifengl** [comment]
added
