### ISSUE TITLE
Scala smile REPL doesn't load help etc 

### ISSUE THREAD

**Issue by implisci** [haifengl/smile#559]
Downloaded latest releases zip file 2.4.0 and ran bin/smile from install folder. The Scala REPL comes up but help("svm")  and exit do not work (not found value help). The lib folder is in the classpath (all jars).  Wondering what the issue could be.

Ubuntu 18.04 LTS
Java(TM) SE Runtime Environment (build 1.8.0_191-b12) 
Smile does seem to load the jars as if I do a :reset all the cleared values are shown

Appreciate any feedback

**Comment by haifengl** [comment]
`help` had been removed as it is outdated. Please refer javadoc/scaladoc. To exit, use `:quit`.

**Comment by implisci** [comment]
Thanks very much. Using Almond with Jupyter now.
