### ISSUE TITLE
Calculate posterior for svm

### ISSUE THREAD

**Issue by haifengl** [haifengl/smile#56]
Estimate probabilistic outputs for support vector machines.

https://en.wikipedia.org/wiki/Platt_scaling
http://citeseer.ist.psu.edu/viewdoc/download;jsessionid=03EE5E2B31E7C95AF3707C7FB007FA34?doi=10.1.1.41.1639&rep=rep1&type=pdf
https://www.csie.ntu.edu.tw/~cjlin/papers/plattprob.pdf
http://machinelearning.wustl.edu/mlpapers/paper_files/icml2005_Niculescu-MizilC05.pdf

**Comment by brsmlnlp** [comment]
Do you have an estimate for this task? Thanks for this great job.

**Comment by haifengl** [comment]
If you strongly need it, we can start to work on it.

**Comment by brsmlnlp** [comment]
It would be great, because probabilistic outputs helps to evaluate the errors. Can I help?

**Comment by haifengl** [comment]
Sure. You are very welcome to contribute!! Thank you!

**Comment by owlmsj** [comment]
Any progress in this thread? Just to know...

**Comment by haifengl** [comment]
not yet. i am busy with other issues. are there great needs of this feature?

**Comment by owlmsj** [comment]
Thanks! I was looking to compare the NN vs SVM results in an article.

**Comment by haifengl** [comment]
I am not sure if it is a good idea to compare NN and SVM by posteriori probabilities. With right choice of active functions in NN, it calculate posterior probabilities. But it is just an estimation in SVM with Platt's trick.

**Comment by owlmsj** [comment]
I agree with you. The idea is not to benchmark each other probabilities, but to show use cases of classifiers that have probabilistic outputs (even if its only an estimation).

**Comment by haifengl** [comment]
Ok, it is there. I just push PlattScaling to master. To use it, please call

svm.trainPlattScaling(x, y);

after training a SVM (i.e. after call finish()). Then use

svm.predict(x, prob)

to get the posteriori probabilities.

**Comment by owlmsj** [comment]
Wonderful! I am going to play with PlattScaling this weekend and try to share some results in an article!
