### ISSUE TITLE
is there any dedicated algorithm in smile for time-series analysis?

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#561]
any plan to add dedicated time-series analysis algorithms like `ARIMA` or [Prophet ](https://peerj.com/preprints/3190.pdf)

**Comment by haifengl** [comment]
We don't have time-series analysis yet. ARIMA and Prophet sound good start points. Feel free to make a PR. Thanks!

**Comment by rayeaster** [comment]
ARIMA reference:

https://www.jstor.org/stable/2335856?seq=1
https://github.com/Workday/timeseries-forecast

**Comment by rayeaster** [comment]
@haifengl would you please create a branch `arima` so I could PR to? Thanks

**Comment by haifengl** [comment]
Done. Thanks!

**Comment by rayeaster** [comment]
https://github.com/haifengl/smile/pull/568

**Comment by rayeaster** [comment]
I will close this issue since `arima` algorithm already in `master` branch.
