### ISSUE TITLE
Applying a RF model

### ISSUE THREAD

**Issue by j3r3m1** [haifengl/smile#564]
Hi, we are working on climate issue (https://github.com/orbisgis/geoclimate) and we are willing to use the smile library in order to use the random forest model.

However, we are currently facing an issue: we have fitted a RF model (classification problem) according to a dataset stored in a dataframe 'df'. Now we would like to apply the model to an other dataset stored in a dataframe 'df1'. df1 does not contain the column to be model ('col2model') while it seems necessary to have it. Is there a simple way to add a column with the right name ('col2model') to df1 ?

**Comment by haifengl** [comment]
You can merge a DataFrame with Vectors or other DataFrames.
```
IntVector y = IntVector.of("col2model", labels);
df.merge(y)
```

Sorry for inconvenience. The next release will fix this issue.

**Comment by j3r3m1** [comment]
OK tanks a lot for answering that fast and accurately. Everything is set in our code now.

**Comment by ebocher** [comment]
This PR has been closed but I'm not able to find in the last release a method to add a new column to an existing dataframe.
Please, can you point me to an example?
I'm looking to do something like in Pandas

```
df = .DataFrame.of(data)   
df.insert(2, "Age", [21, 23, 24, 21], true) 
```
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.insert.html

Thanks

**Comment by haifengl** [comment]
```
df.merge(IntVector.of("Age", [21, 23, 24, 21]))
```

**Comment by ebocher** [comment]
Thanks
