### ISSUE TITLE
CrossValidation Wrong in GradientTreeBoostTest.java 

### ISSUE THREAD

**Issue by ddennyd** [haifengl/smile#565]
Hello,
I have a question about the the GradientTreeBoostTest.java  class (smile/core/src/test/java/smile/classification/GradientTreeBoostTest.java ):
The question refers specifically to the testWeather() method. From a DataScience point of view, isn't it wrong to train the model using all test data and then serialize it, but the error rate is determined by using a gradiented boosted tree which has been trained and tested with CrossValidation. Shouldn't we first train and test the model by using CrossValidation, and then serialize the model that performs best? And for this modell we can give the error rate

Thanks a lot for your reply.

**Comment by haifengl** [comment]
The weather data is extremely small (only a few samples). It is used as a kick-tire test. The other tests do cross validation or bootstrap testing.

**Comment by ddennyd** [comment]
Thanks for your reply.
Would that be the an appropriate way:

        GradientTreeBoost model = null;     
        int[] prediction = LOOCV.classification(WeatherNominal.formula, WeatherNominal.data, (f, x) -> model.fit(f, x, 100, 20, 6, 5, 0.05, 0.7));
        int error = Error.of(WeatherNominal.y, prediction);
        java.nio.file.Path temp = smile.data.Serialize.write(model);
        smile.data.Serialize.read(temp);

**Comment by haifengl** [comment]
Yes
