### ISSUE TITLE
Lemmatization

### ISSUE THREAD

**Issue by stenpiren** [haifengl/smile#566]
I see that seldom there is a java library that provides a clear and simple lemmatization for words. NLTK has a lemmatization module that is able to take just one string say "covers" and return "cover" or multiple strings "he said it covered" to return "he say it cover" by just passing these strings and nothing else.

OpenNLP and CoreNLP are weird as they require parts of speech tagging. Is there a way to add lemmatization into SMILE such that we can achieve the above-said goals?

**Comment by haifengl** [comment]
Lemmatization is a lot complicated what it appears. PoS is an essential step indeed. It is a different question if it should be exposed in API. For efficiency and reusability, it should be. For cleanness, it might be hidden.
