### ISSUE TITLE
KDTree leaf search is inefficient

### ISSUE THREAD

**Issue by lukehutch** [haifengl/smile#569]
The following code is used in `KDTree.java` to determine leaves:

https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/neighbor/KDTree.java#L190

```java
        // If the max spread is 0, make this a leaf node
        if (MathEx.isZero(maxRadius, 1E-8)) {
            node.lower = node.upper = null;
            return node;
        }
```

Therefore, if `node.count > 1`, all points in a leaf node must have equal coordinates.

However then when a nearest neighbor search is performed, all leaf nodes are iterated through:

https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/neighbor/KDTree.java#L244

```java
        if (node.isLeaf()) {
            // look at all the instances in this leaf
            for (int idx = node.index; idx < node.index + node.count; idx++) {
                int i = index[idx];
                if (q != keys[i]) {
                    double distance = MathEx.distance(q, keys[i]);
                    if (distance < neighbor.distance) {
                        neighbor.index = i;
                        neighbor.distance = distance;
                    }
                }
            }
        } else ...
```

(+ two other methods contain similar logic).

This is unnecessary -- it suffices to simply take the node at `node.index` as the nearest neighbor, since all nodes between `node.index` and `node.index + node.count` will have equal coordinates for all leaves.

**Comment by haifengl** [comment]
It is only one case of leaf nodes. See another case at line 222.

**Comment by lukehutch** [comment]
Ah, OK. Thanks.
