### ISSUE TITLE
NullPointerException in KNN

### ISSUE THREAD

**Issue by jef5ez** [haifengl/smile#573]
**Describe the bug**
Certain data seems to cause an NPE when the cover tree does not find enough neighbors.

2020-07-06 23:16:20 WARN  CoverTree:562 - CoverTree.knn(5) returns only 1 neighbors
2020-07-06 23:16:20 WARN  LoopsBenchmarks_jmhType:85 - bork
java.lang.NullPointerException
        at smile.classification.KNN.predict(KNN.java:182)

In KNN.predict L182 it looks like you could take the max of k and size of neighbors when iterating through this loop to stop it
```
        for (int i = 0; i < k; i++) {
            count[labels.indexOf(y[neighbors[i].index])]++;
        }
```

Sorry I can't share data and haven't found a minimal example.

**Additional context**
- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
Java 8
- Which Smile version
2.4.0
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Ubuntu

**Comment by haifengl** [comment]
The fix is in master branch now.
