### ISSUE TITLE
Problems with mlTrain

### ISSUE THREAD

**Issue by Mzazvor** [haifengl/smile#574]
**Describe the bug**
Smile library returns an error in mlTrain. 

**Expected behavior**
We are computing coefficients using least squares. 
**Actual behavior**
Error: The matrix is not positive definite.
This error is quite strange, because Matrices in least squares does not have to be square. 

When reproducing in Matlab we had no issues to use least squares. 
Input matrices are in files  :  x.csv and y.csv 

[InputData.zip](https://github.com/haifengl/smile/files/4891339/InputData.zip)

Best regards 
Martin Zázvorka

**Comment by haifengl** [comment]
we don't have `mlTrain`. Hard to help given little information.

**Comment by Mzazvor** [comment]
Thanx for the reply.
Sorry for my mistake, we are using the OLS method from your package.  mlTrain is just a wrapper.

**Comment by haifengl** [comment]
try `stderr = false`

**Comment by Mzazvor** [comment]
Hello sorry for the long reply. I have to dive into java to use your library directly instead of that wrapper, because I was not able to use your advice. I have managed to do it and stderr does not help. 

sys::ArgErr: java.lang.IllegalArgumentException: The matrix is not positive definite.
  smile.math.matrix.JMatrix.cholesky (JMatrix.java:952)
  smile.regression.OLS.fit (OLS.java:168)

**Comment by haifengl** [comment]
Your data is collinear.

**Comment by haifengl** [comment]
Try set both `stderr = false` and `recursive = false`.

**Comment by haifengl** [comment]
And you better use 2.5.0 now.

**Comment by Mzazvor** [comment]
I tried to set both false and it did not work. We will try new version next
week hope it helps. Thanx for your recommendations.

Martin

Dne čt 30. 7. 2020 16:09 uživatel Haifeng Li <notifications@github.com>
napsal:
