### ISSUE TITLE
Line based dataframe

### ISSUE THREAD

**Issue by JD557** [haifengl/smile#575]
**Is your feature request related to a problem? Please describe.**

With the new smile 2.0 came a new `DataFrame` whose default implementation (`DataFrameImpl`) is column-based.

While this sounds like a good idea in theory, I'm hitting some performance problems in practice (e.g. a workload that took 5s to train now takes 4min to convert the data into a `DataFrame` and 1s to train).

**Describe the solution you'd like**

I think this could be solved by having a line-based implementation of a dataframe. While training models might be slower, this could be a nice tradeoff in some cases.

**Describe alternatives you've considered**

I tried to implement this myself by attempting to implement something like a `MyBaseVector(columnIdx: Int)` that would work as a view over the line-based structure.
I think there are only two problematic methods here:

* `Object array();` - There's not an actual array backing the `BaseVector`. This could be implemented by copying everything to an array when this is called, but that could have some weird performance implications.
* `BaseVector<T, TS, S> get(int... index)`/`BaseVector<T, TS, S> get(int... index)` - This would require storing the filtered indices as well (like `MyBaseVector(columnIdx: Int, filteredEntries: Option[Set[Int]])` or with an extra `FilteredVector(innerVector: BaseVector, filteredEntries: Set[Int])`). I guess it's possible, assuming that the list of indices is small.

None of those methods seems to be used in the DataFrame, so that should be OK.

**Comment by haifengl** [comment]
How do you convert data to DataFrame?

**Comment by JD557** [comment]
I'm currently doing something like `DataFrame.of(trainingFeatures.asJava)`, where `trainingFeatures` is a scala `List[Tuple]` that was read via `akka-streams` from a `gRPC` endpoint (so I think that I can't use anything from `smile.io` to help me here).

**Comment by haifengl** [comment]
`akka-stream` is lazy. `DataFrame.of(trainingFeatures.asJava)` in fact includes the stream processing. Why don't you measure the time in two steps:
```
val data = trainingFeatures.asJava
time {
  DataFrame.of(data)
}
```
`DataFrame.of()` shouldn't use 4 minutes.

**Comment by JD557** [comment]
OK, I think that I found the problem:

The `DataFrameImpl` constructor receives a `List`, which it then uses on a lot of lines like `for (int i = 0; i < size; i++) values[i] = (int) read.invoke(data.get(i));`.

I was using a `LinkedList`, so that `data.get(i)` was really expensive. Converting everything to a vector beforehand fixed the problem.

I think iterating over the list using an iterator or a `for(int value: data)` loop would fix this.
