### ISSUE TITLE
Training multiclass Logistic Regression in Smile 2.4.0 taking a lot of time

### ISSUE THREAD

**Issue by stenpiren** [haifengl/smile#578]
I am experimenting the different versions of Smile for training a multiclass logistic regression. Now trying the 2.4.0 after I got stuck on 1.5.3 with ArrayOutBoundError. 
I notice in 2.4.0 that it takes a lot of time to do predictions on sparse data. I have for instance 15000 columns and 21101 rows of feature data. In python's sklearn this would take about 1 minute to train. In Smile, I left overnight with increased heap memory of 8GB, and didn't work till this morning. 

I simply pass double[][] X and int[] y to ```Logisticegression.fit``` and CPU usage shoots to 100% and memory about 6 GB. 

Any way to improve multiclass classification models on sparse data with more than 30 classes?

**Comment by haifengl** [comment]
use `Maxent` for sparse data.

**Comment by stenpiren** [comment]
> use `Maxent` for sparse data.

Thanks. But looks like ```Maxent``` classifier requires categorical features data. I have a requirement to use double[][], not int [][] that ```Maxent``` requires for ```X```, since I am using tfidf vectors. Any way around this? It's extremely slow to try with Logisticregression on sparse data. Almost hopeless. Thanks again.

**Comment by rayeaster** [comment]
@stenpiren just curious, why do some feature engineering first before applying LR models? like dimension reduction or vectorization.

**Comment by stenpiren** [comment]
> @stenpiren just curious, why not do some feature engineering first before applying LR models? like dimension reduction or vectorization.

@rayeaster it's an NLP task and there is already feature engineering, did tokenization, built vocabulary, did the vectorization. I don't think dimension reduction is necessary. In python's sklearn the same steps I am taking in java takes less than 30 seconds to train. But in Java using smile is just taking forever or falling in heap memory. As I am building a classifier, I would avoid extra pre-processing like dimension reduction.

**Comment by haifengl** [comment]
We will add support to sparse array.

**Comment by haifengl** [comment]
We add `SparseLogisticRegression` in 2.5.0. Please have a try.
