### ISSUE TITLE
Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS

### ISSUE THREAD

**Issue by moberc** [haifengl/smile#579]
Hi,

I am using SMILE 2.4.0 on Windows and on Linux.
On Windows I have installed Intel mkl.
On Linux - not yet.

In both cases I am getting:
17:33:10.203 [main] INFO  smile.math.matrix.Factory : smile-netlib module is available.
Jul 09, 2020 5:33:10 PM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
Jul 09, 2020 5:33:10 PM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeRefLAPACK
Jul 09, 2020 5:33:10 PM com.github.fommil.netlib.BLAS <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
Jul 09, 2020 5:33:10 PM com.github.fommil.netlib.BLAS <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
I am getting results, but I suspect setup issues.

**Expected behavior**
Could you please describe correct setup for math libraries for Windows and Linux?
Thanks!

A clear and concise description of what you expected to happen.**Actual behavior**
For example, the algorithm throws an exception. Here is the stack trace...

**Code snippet**
The code to reproduce the behavior.

**Input data**
The sample data

**Additional context**
- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
- Which Smile version
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
- Add any other context about the problem here.

**Comment by haifengl** [comment]
download the prebuilt package and add its bin to LIBRARY_PATH.

**Comment by moberc** [comment]
Hi,

I’ve got SMILE to work on linux by creating symbolic links from libblas.so.3 and liblapack.so.3 to libmkl_rt.so and adding 2 libraries to the loader path, one for libmkl_rt.so and one for libiomp.so.
export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/:/opt/intel/compilers_and_libraries_2020.1.217/linux/compiler/lib/intel64_lin/:$LD_LIBRARY_PATH

Thanks,
  Margaret
