### ISSUE TITLE
support t-SNE

### ISSUE THREAD

**Issue by haifengl** [haifengl/smile#58]
https://lvdmaaten.github.io/tsne/

**Comment by leo-xin** [comment]
hi,Li.
I have an intention to implement t-sne in smile framework. Is there any requirement or advise? Can I import  other depandency like jblas?

**Comment by haifengl** [comment]
Thank you very much first of all!! Please check out our manifold learning algorithms and follow their API. For JBlas, what functions will you use? We have a lot of matrix algorithms in smile.math.matrix package. BTW, I am planing to include JBlas or ND4j into smile for native matrix computation. I hope that they will be in separate packages so that the most algorithm packages can be platform independent. Thanks!

**Comment by haifengl** [comment]
added t-SNE to manifold module.
