### ISSUE TITLE
Add netlib as optional dep

### ISSUE THREAD

**Issue by ebocher** [haifengl/smile#580]
**Is your feature request related to a problem? Please describe.**

Hi, we are working on climate issue (https://github.com/orbisgis/geoclimate) and we are using the smile library in order to use the random forest model. see https://github.com/haifengl/smile/issues/564
We'd like to use a pure java implementation of Smile but smile-core as a dependency to NetLib.
Is there a way to remove the NetLIb dep.
 

**Describe the solution you'd like**
smile-core and other libs without NetLIb dep

Thanks

**Comment by haifengl** [comment]
You can exclude a dependency in your build system. For example, you do it in SBT with exclude clause 
```
libraryDependencies += "com.github.haifengl" % "smile-core" % "2.4.0" exclude("com.github.haifengl", "smile-netlib")
```

**Comment by ebocher** [comment]
Fixed thanks
