### ISSUE TITLE
JavaFX version of plotting

### ISSUE THREAD

**Issue by brucejohnson** [haifengl/smile#583]
I've built a test version of the SMILE plot code that works in JavaFX. It's not fully ready, but most plotting (Line, Scatter, Scatter3D, HeatMap, Contour, Surface) is working.  I'm quite interested in having this so I can use SMILE based analysis and plotting in my own JavaFX based software, but before I do anything more I wanted to check to see if this would be of interest as a contribution to SMILE.  Most of the code is a duplicate of the SMILE plot.swing code with small changes mostly to change java.awt features (Color and Font for example) to javafx versions.  Some features have more substantial changes to take advantage of JavaFX code.  There might be alternative ways to do this without the code duplication, but this was the quickest way to prototype.

Here's a little screenshot of code in action.
![image](https://user-images.githubusercontent.com/5931606/88221547-a52f6800-cc32-11ea-821b-2ce3989fb8ba.png)

**Comment by haifengl** [comment]
Thanks. It is nice to support JavaFX. Smile Plot is mostly a JPanel. My understanding is that Swing components can be added into JavaFX containers. Are there problems to do that way?

Besides, if we move to JavaFX, it would be nice to redesign the library to get ride of technical debts and add more features. Any suggestions on that?

**Comment by brucejohnson** [comment]
I'd (at least for my uses) rather not embed the Swing component into JavaFX.  There are a few issues.  For example, JavaFX supports gestures (on trackpad etc) and these don't necessarily get passed into the Swing component.  So more modern input styles are precluded.  Also, it would be easier to embed the charts into some GUI features if done with native JavaFX.  For example, I draw some of my data on a JavaFx canvas.  The way I have implemented this code you could add a SMILE chart right on top of the canvas with other types of renderings.  That would be tricky if the SMILE plot was in a JPanel.

The one key feature I'm missing in the current design is that the plot margins are uniform on all sides.  If one could specify a margin on each side you could have more control of where the plot was located.  Then a grid of plots could be done on a single JavaFX canvas, instead of arranging them with a layout container.  

I'm sure there are lots of design changes that could be made to enhance the plotting (though it is already quite useful).  But at this point I'd be happy to use my current (with some minor improvements) version.  It would already be useful to me.

Would it be useful if I posted my current implementation on github?

**Comment by haifengl** [comment]
Cool. May you please make a PR? Thanks.

**Comment by haifengl** [comment]
Would you like to contribute your work back to smile? Thanks.

**Comment by brucejohnson** [comment]
Yes, I was getting organized to do that when I noticed the new Smile license (hence my other issue post).  
I was wondering though if it would be better to do this as a separate project.  Starting with Java 11, JavaFX is no longer bundled with theJDK.  That seems like it could be a problem for building Smile if this JavaFx based SmilePlot code was bundled in.
I can post the current state of the JavaFx plotting code as a project under my own github id so you can look at it (but, wasn't sure what license to put on it).

**Comment by haifengl** [comment]
We will have a parallel v3 release that targets Java 11+. Both v2 and v3 will be maintained.

**Comment by brucejohnson** [comment]
I've put a copy of my version of the plotting code (using JavaFX) at: https://github.com/onemoonsci/smileplot

This is not a full fork of smile.  Just the plot code updated to work with JavaFX.  I'm not a big sbt user so this just builds with maven.  I think (because of issues with JavaFX being removed with JDK 11) it makes sense to have this as a standalone project, but I'd also be fine if you want (assuming you like the code/feature) moving it into the main project until v3.

Also, if you'd rather not have this partial project up, I can remove it.  But this seemed the simplest way to give you a look at it.

**Comment by haifengl** [comment]
Thanks!
