### ISSUE TITLE
Fitting RandomForest model without column names

### ISSUE THREAD

**Issue by Brandonage** [haifengl/smile#586]
**Describe the bug**
I'm trying to fit one RandomForest model with a 2 dimensional vector of doubles for which I don't have the name of the columns. I use the Smile2Utils functions to easily assign the columns. However, when the fitting process is finished the RandomForest object does not have any x, xschema, yx or yxschema assigned. Since those attributes are not assigned. the **predict** method fails with a NullPointerExcepction when given an input vector

**Expected behavior**

A RandomForest model object with all its attributes assigned and a working predict function

**Actual behavior**

```
StructType.fieldIndex(String) line: 81	
Variable$1.<init>(Variable, StructType) line: 80	
Variable.bind(StructType) line: 78	
Formula.lambda$bind$12(StructType, Term) line: 253	
1135970187.apply(Object) line: not available	
ReferencePipeline$7$1.accept(P_OUT) line: 267	
ReferencePipeline$2$1.accept(P_OUT) line: 175	
Spliterators$ArraySpliterator<T>.forEachRemaining(Consumer<? super T>) line: 948	
ReferencePipeline$7(AbstractPipeline<E_IN,E_OUT,S>).copyInto(Sink<P_IN>, Spliterator<P_IN>) line: 482	
ReferencePipeline$7(AbstractPipeline<E_IN,E_OUT,S>).wrapAndCopyInto(S, Spliterator<P_IN>) line: 472	
ReduceOps$3(ReduceOps$ReduceOp<T,R,S>).evaluateSequential(PipelineHelper<T>, Spliterator<P_IN>) line: 708	
ReferencePipeline$7(AbstractPipeline<E_IN,E_OUT,S>).evaluate(TerminalOp<E_OUT,R>) line: 234	
ReferencePipeline$7(ReferencePipeline<P_IN,P_OUT>).collect(Collector<? super P_OUT,A,R>) line: 499	
Formula.bind(StructType) line: 254	
RandomForest(DataFrameRegression).predict(DataFrame) line: 47	
```

**Code snippet**

```
// prepare data for Smile2.0 DataFrame Class
final double[][] trainDataConcat = Smile2Utils.concatArrays(trainx, trainy);
final String[] trainDataColNames = Smile2Utils.getDataFrameColumnNames(trainx[0].length, true);
final String[] XColNames = Smile2Utils.getDataFrameColumnNames(trainx[0].length, false);
final DataFrame trainDataFrame = DataFrame.of(trainDataConcat, trainDataColNames);

LOGGER.info("Building the random forest model with smile");
Properties bestProperties = Smile2Utils.settingsToProperties(bestNumTrees, bestNodeSize, bestMaxNodes, bestSubsample, trainx[0].length * bestMtryRatio);
RandomForest rfModel = RandomForest.fit(Formula.of("y", XColNames), trainDataFrame, bestProperties);
LOGGER.info("Fitted random forest with smile. Formula: " + rfModel.formula());
```

**Input data**
The sample data

**Additional context**
- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version: JRE8
- Which Smile version: 2.5.0
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ): Windows

I think it's just a problem of the way I build the dataframe. I haven't found documentation on how to build the DataFrame object. I used the code attached with version 2.2.2 and it worked fine. However, with 2.2.2 I had a problem with the serialization of the RandomForest object. I saw in #554  that version 2.5.0 could solve the serialisation issue but updating got me to this point.

**Comment by uriloya** [comment]
A possible workaround (until it is fixed) is to convert the DataFrame into a Tuple and you it with predict()

**Comment by Brandonage** [comment]
Not really sure on how can I do that. I have been checking the API docs but I can't find an easy way of translating my 2d array into Tuples. From what I understand in the docs a row in the Dataframe is one Tuple or am I wrong?

**Comment by uriloya** [comment]
This is the code of DataFrameRegression.predict()
`default double[] predict(DataFrame data) {
        // Binds the formula to the data frame's schema in case that
        // it is different from that of training data.
        formula().bind(data.schema());
        int n = data.size();
        double[] y = new double[n];
        for (int i = 0; i < n; i++) {
            y[i] = predict(data.get(i)); // This is actually predict(tuple)
        }
        return y;
    }`

Copy the code without the "formula().bind(data.schema());" and use it

**Comment by Brandonage** [comment]
Can you reopen the issue? I couldn't solve this yet. I followed your instructions but I still get the same NullPointerException. As I said the Binding attribute of the Formula has empty attributes for the model after fitting it.

**Comment by haifengl** [comment]
No idea what's Smile2Utils. `DataFrame` provides many static method to create instances.

**Comment by homeworkprod** [comment]
I've encountered a similar behavior today with Scala, Smile 2.52, and `smile.classification.RandomForest`.

Passing a `DataFrame` to `RandomForest#predict(DataFrame)` (which is actually implemented in `DataFrameClassifier`) resulted in an NPE with the same cause as the stacktrace above.

In my case it happened because `formula()` is called in [`DataFrameClassifier.predict(DataFrame)`](https://github.com/haifengl/smile/blob/v2.5.2/core/src/main/java/smile/classification/DataFrameClassifier.java#L45), but the relevant implementation, [`DecisionTree#formula`](https://github.com/haifengl/smile/blob/v2.5.2/core/src/main/java/smile/classification/DecisionTree.java#L369), returned `null`.

However, its docstring states:
> Returns null if the tree is part of ensemble algorithm.

So maybe this isn't intended to work in the first place, or I'm just passing a wildly inappropriate data frame. Or maybe it is something that could be handled? I'm not sure how important the `Formula#bind` call is in that situation.

**Comment by haifengl** [comment]
@homeworkprod Can you share the code and stack trace?

**Comment by homeworkprod** [comment]
Hi @haifengl, I can't get the details together anymore, sorry about that.

I think I might have been calling `predict` directly on the decision tree (and not on the forest) for some reason, which then triggered the NPE. Maybe that circumvented some checks or is not the intended way to use it.

Sorry for the noise. Feel free to not further investigate this.
