### ISSUE TITLE
UMAP input data.length is greater than umap.coordinates.length and umap.index.length

### ISSUE THREAD

**Issue by rgwood-github2018dec31** [haifengl/smile#587]
**Describe the bug**
I modified UMAPDemo to do:

System.out.format("data.len=%d \n", data.length);
...
UMAP umap = UMAP.of(data, neighbors);
...
System.out.format("umap.coordinates.length=%s \n", umap.coordinates.length);
System.out.format("umap.index.length=%s \n", umap.index.length);

**Expected behavior**
We expect data.length==umap.coordinates.length==umap.index.length

**Actual behavior**
Using the demo modified as above we get:
...
data.len=2500 
19:09:07.285 Thread-0 NearestNeighborGraph.largest: 26 connected components, largest one has 2474 samples.
...
Learn UMAP from 2500 samples in 4580ms
umap.coordinates.length=2474 
umap.index.length=2474 

**Code snippet**
UMAPDemo...

**Input data**
UMAPDemo...

**Additional context**
- Adopt OpenJDK 11, latest)
- Smile 2.5.0 and 2.4.0
- Windows 10 latest

**Comment by haifengl** [comment]
Same as other manifold learning algorithms, we apply UMAP on largest connected component of nearest neighbor graph.

**Comment by rgwood-github2018dec31** [comment]
Taking the reference UMAP python impl we have:

######################
mnist = fetch_openml("mnist_784", version=1, as_frame=True)
print(f"mnist.shape={mnist.frame.shape}")
######################
mnist.shape=(70000, 785)
######################
print("umap...")
reducer = umap.UMAP(random_state=42)
print(f"reducer={reducer}, fit_transform...")
embedding = reducer.fit_transform(mnist.data)
print(f"embedding={embedding}")
######################
umap...
reducer=UMAP(random_state=42), fit_transform...
######################
print(f"embedding={embedding.shape}")
print(f"mnist.desc={mnist.frame.shape}")
######################
embedding=(70000, 2)
mnist.desc=(70000, 785)

So for the ref impl input row count==output row count

**Comment by haifengl** [comment]
The reference implementation works on connected components too. When multiple connected components are identified, each connected component is initialized separately and the results are merged.

However, we don't take that approach because the existence of multiple connected components implies that a global view of the data cannot be attained. Besides, the result is not reliable at all on very small components. As you can see from the log, there are 26 components. Besides the largest one, the rest 25 components have only 26 data points. It is not worth of cramping these outliers into the mapping.

**Comment by rgwood-github2018dec31** [comment]
In my simplistic view, (and I think others make look at it this way) I would like to use this to visualize AND project data down to a lower dimension for user interaction/training. One of the functions that I'd also be interested in would be taking a NEW point (in this case image) and projecting it down to 2 or 3 dims. Again the python impl has this function. I'm up to adding these 2 features (ensuring all training points are mapped and impl a projection function for new points) if you'll maybe guide me on where to start.

See here:
https://umap-learn.readthedocs.io/en/latest/basic_usage.html

reducer = umap.UMAP(random_state=42)
reducer.fit(digits.data)
# reducer.embedding_ should have same shape as digits.data
embeddingNew = reducer.transform(digitsNew)

So in smile it would be something like:

var umap=UMAP.of(data);
double[] projection=umap.transform(pointNew);

**Comment by rayeaster** [comment]
@rgwood-github2018dec31 you could use `UMAP#coordinates` as the low dimension projection for training data.

**Comment by haifengl** [comment]
I wouldn't use manifold mapping coordinates for training. It is meant for visualization.

**Comment by rgwood-github2018dec31** [comment]
Is there a way to 'cram' all the points into the mapping? Seems like computeFuzzySimplicialSet has a bunch of params one could tune.
