### ISSUE TITLE
Pipelines

### ISSUE THREAD

**Issue by IggyBlob** [haifengl/smile#590]
**Is your feature request related to a problem? Please describe.**
In scikits-learn, pipelines can be used to combine several transformers and a final estimator to a combined estimator. A similar concept in Smile would be interesting. Moreover, what's the Smile way of transforming targets in regression (i.e. transforming the targets `y` before fitting a regression model) and how can one build composite feature spaces (feature union, combining several transformers to a new new transformer that combines their output)?

**Describe the solution you'd like**
For instance, I'd like to combine Smile's `RobustStandardizer` with a `SVM` classifier in Java.

**Describe alternatives you've considered**
Using `RobustStandardizer` and `SVM` separately, i.e. scaling the training `DataFrame` first using `RobustStandardizer` and then passing on the scaled `DataFrame` to the classifier.

**Comment by haifengl** [comment]
To transform the response variable, you can do it with formula. for example
```
log(y) ~ .
```

For pipeline, not much code is needed for you to call `RobustStandardizer` and then `SVM`.

**Comment by IggyBlob** [comment]
@haifengl thanks for your response!

So to achieve the behavior of sklearn's [TransformedTargetRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.compose.TransformedTargetRegressor.html#sklearn.compose.TransformedTargetRegressor) (a construct that transforms targets before fitting a regression model and maps back to the predictions to the original space) in Smile, the following steps are necessary:

1. transform the target `y` using the `Formula` parameter of the regressor's `fit` method
2. manually map back the resulting predictions to the original space via an inverse transform function?

This translates to the following Java code:

```java
DataFrame data = Read.read("some-exponential-data-set.arff");

// fit the model 
// the original, exponential targets are linearized
// assuming "y" is the target column in the data set
LinearRegression r = RidgeRegression.fit(Formula.lhs("log(y)", data); 

double[] y_pred = r.predict(data);

// map back the predictions to the original, non-linear (exponential) space
double[] y_pred_orig = Arrays.stream(y_pred).map(Math::exp).toArray(double[]::new);
```

Is that correct?

**Comment by haifengl** [comment]
```
LinearRegression r = RidgeRegression.fit(Formula.lhs(Terms.log("y"), data); 
```
