### ISSUE TITLE
Build dataframe from array

### ISSUE THREAD

**Issue by ebocher** [haifengl/smile#592]
**Is your feature request related to a problem? .**
We are using Smile from Groovy. 
I'd like to create a dataframe from a nested array like this 
```
def data = [
                [100, 5, 20],
                [50, 2, 10],
                [110, 6, 22],
        ]
  def df = DataFrame.of(data, "name", "age", "size")
```
Similar to pandas

So I have implemented the method  of(@NotNull ArrayList data, String... columnNames) 
You can check the code here https://github.com/ebocher/orbisdata/blob/dataFrameMethods/data-manager/dataframe/src/main/java/org/orbisgis/orbisdata/datamanager/dataframe/DataFrame.java#L1150

It works but I'm not confident in the approach with mixed data types in the array.

e.g
Here the second row contains a decimal value 2.5
```
def data = [
                [100, 5, 20],
                [50, 2.5, 10],
                [110, 6, 22],
        ]
  def df = DataFrame.of(data, "name", "age", "size")
```
Indeed, the StructField of the second row contains the good type (Decimal) but a println on the df shows

```
[name: Integer, age: Integer, size: Integer]
+----+---+----+
|name|age|size|
+----+---+----+
| 100|  5|  20|
|  50|2.5|  10|
| 110|  6|  22|
+----+---+----+
```

**Describe the solution you'd like**

I'd be happy to have the same behaviour as in Pandas
So in the example, it must return [name: Integer, age: Decimal, size: Integer]
and if the data array contains  more mixed value as
def data = [
                [100, 5, 20],
                [50, "Smile please", 10],
                [110, 6, 22],
        ]

it must print
 [name: Integer, age: Object, size: Integer]

**Comment by haifengl** [comment]
It is your code. Why do you open the ticket to us?

**Comment by ebocher** [comment]
I open this issue here :  firstly because  I think it's a feature that could be useful to the community, secondly because I'm wondering if the behavior I want to get is not related to the Smile implementation.

**Comment by haifengl** [comment]
We have `DataFrame.of(double[][])` and `DataFrame.of(List<Tuple>)`. I don't know Groovy. No idea what's the type of 
```
def data = [
                [100, 5, 20],
                [50, 2.5, 10],
                [110, 6, 22],
        ]
```

**Comment by ebocher** [comment]
I'm sorry, but I didn't want to pollute...

**Comment by haifengl** [comment]
No worries. Hope you can resolve it soon.
