### ISSUE TITLE
`IMatrix.colName(int)` overflows the stack when `RidgeRegression` is given too many features?

### ISSUE THREAD

**Issue by joshhansen** [haifengl/smile#593]
**Describe the bug**
I'm using `RidgeRegression` on a dataset with 976 instances. When I increase the number of features to 820 or more, I get this:

```
Exception in thread "main" java.lang.StackOverflowError
	at smile.math.matrix.IMatrix.colName(IMatrix.java:122)
	at smile.math.matrix.IMatrix.colName(IMatrix.java:122)
	at smile.math.matrix.IMatrix.colName(IMatrix.java:122)
	at smile.math.matrix.IMatrix.colName(IMatrix.java:122)
	at smile.math.matrix.IMatrix.colName(IMatrix.java:122)
	at smile.math.matrix.IMatrix.colName(IMatrix.java:122)
        ...
```

I've tried to follow the call stack up but by the time it crashes, it's very large, and crashes the debugger itself.

The code of `IMatrix.colName(int)` is:

```
    /** Returns the name of i-th column. */
    public String colName(int i) {
        return colName(i);
    }
```
Any call to this function would seem doomed to overflow the stack since it does nothing but call itself with its original argument.

**Expected behavior**
The `RidgeRegression.fit` call completes successfully.

**Actual behavior**
See above.

**Code snippet**
I reduced the original code to this, which produces the same error:

```
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import smile.data.DataFrame;
import smile.data.formula.Formula;
import smile.data.type.DataTypes;
import smile.data.type.StructField;
import smile.data.type.StructType;
import smile.regression.RidgeRegression;

public class Train {
	private static final int NUM_FEATURES = 820;
	private static final int NUM_INSTANCES = 976;
	
	
	private static DataFrame loadRatings() {
		final List<Map<String,Double>> ratingFeatures = new ArrayList<>();
		
		Set<String> allFeatures = new HashSet<>();
		
		for(int j = 0; j < NUM_INSTANCES; j++) {
			Map<String,Double> features = new HashMap<>();
			for(int i = 0; i < NUM_FEATURES; i++) {
				features.put(String.valueOf(i), Double.valueOf(0.1 * i));
			}
			
			features.put("rating", 20.0);
			
			
			ratingFeatures.add(features);
			
			allFeatures.addAll(features.keySet());
			
		}
		
		List<StructField> fields = new ArrayList<>();
		for(String feature : allFeatures) {
			fields.add(new StructField(feature, DataTypes.DoubleType));
		}
		
		StructType schema = new StructType(fields);
		
		System.out.println("Ratings loaded: " + ratingFeatures.size());
		System.out.println("Number of features: " + allFeatures.size());
		
		return DataFrame.of(ratingFeatures, schema);
		
	}
	
	public static void main(String[] args) {
		DataFrame data = loadRatings();
		RidgeRegression.fit(Formula.lhs("rating"), data);
	}
}
```

**Input data**
N/A, the above code generates a dataset that yields the error.

**Additional context**
* Java 11
* Smile 2.5.0 from Maven

**Comment by haifengl** [comment]
Sorry, it should be `colNames[i]`.

BTW, you data is bad. All the columns are constant.

**Comment by haifengl** [comment]
To try out algorithms, we provide a lot of open data. Just download the prebuilt package. The data are in `data` directory. Or you can use the notebook (click `Try it Online` on the project website) or run your local one with `bin/jupyterlab.sh`

**Comment by joshhansen** [comment]
Thanks for the quick response.

It was just a fake dataset I used to demonstrate the bug.

Do you think you'll be making a 2.5.1 soon that includes this?

**Comment by haifengl** [comment]
2.5.1 was released. this will be in 2.5.2 soon. This bug is only triggered when the data is bad (constant columns) for model fittings. It won't be a road blocker for normal data.

**Comment by joshhansen** [comment]
Got it, thank you
