### ISSUE TITLE
Fisher's Linear Disiminant classification result is strange for Big Toy data

### ISSUE THREAD

**Issue by Yaqiang** [haifengl/smile#596]
**Describe the bug**
In Smile 2.4.0 demo, the FLD classification result for Big Toy data is:
![image](https://user-images.githubusercontent.com/4408029/94502795-87384200-0237-11eb-92d9-e4d12118de3c.png)

In Smile 2.5.3 demo, the result is:
![image](https://user-images.githubusercontent.com/4408029/94502837-9c14d580-0237-11eb-9c77-e529f9319bf4.png)

**Comment by haifengl** [comment]
Fixed. Thanks.

**Comment by Yaqiang** [comment]
Thanks for your quickly response!
