### ISSUE TITLE
Unexpected residuals with less than full rank linear model

### ISSUE THREAD

**Issue by tibcodscott** [haifengl/smile#598]
**Problem** If I have a less than full rank linear model, Smile does not provide residual values consistent with R.  

Here is R Code for this simple example.
xcov  = c(1,2,3,4,5,6,7,8,9,10)
xcat1 = c(1,1,1,0,0,0,0,0,0,0)
xcat2 = c(0,0,0,1,1,1,0,0,0,0)
xcat3 = c(0,0,0,0,0,0,1,1,1,1)
y     = c(8,9,7,10,11,14,8,19,20,22)
options(digits = 15)
lmObj=lm(y~xcov+xcat1+xcat2+xcat3)
lmObj$residuals

The residuals for the R code is given as follows: 
2.722222222222220,1.000000000000000,-3.722222222222220,1.055555555555557,-0.666666666666667,-0.388888888888890, 
-5.166666666666663,3.111111111111111,1.388888888888888, 0.666666666666665 

**Actual behavior**
The residuals for SMILE 2.5.0 are as follows:
6.256723198570374, 3.513446397140749,-2.229830404288876, 3.0, 0.0, 0.0, -2.0, 5.0, 2.0, 1.0

**Code snippet**
**Java code**
double xcov[]  = {1,2,3,4,5,6,7,8,9,10};
double xcat1[] = {1,1,1,0,0,0,0,0,0,0};
double xcat2[] = {0,0,0,1,1,1,0,0,0,0};
double xcat3[] = {0,0,0,0,0,0,1,1,1,1};
double y[]    =  {8,9,7,10,11,14,8,19,20,22};	
	
Properties prop = new Properties();		
prop.setProperty("smile.ols.method", "qr");
prop.setProperty("smile.ols.standard.error", "true");
prop.setProperty("smile.ols.recursive", "false");
		
ArrayList<Data> DataList = new ArrayList<Data>();
for(int i=0; i<10; i++) {
	DataList.add(new Data(y[i],xcov[i],xcat1[i],xcat2[i],xcat3[i]));
}
		
DataFrame df = DataFrame.of(DataList, Data.class);
System.out.println(df.toString());
Formula formula = Formula.of("y" , "xcov", "xcat1", "xcat2", "xcat3");
LinearModel lm = smile.regression.OLS.fit(formula,  df, prop);
System.out.println(lm.toString());
for(int i=0; i<10; i++) {
  System.out.println(lm.residuals()[i]);			
}

**Comment by haifengl** [comment]
The fitting method should be "svd" when the data is not of full rank.

**Comment by tibcodscott** [comment]
In this case its obvious that the design matrix is not full rank.  What if the data and design are more complex and I don't know whether or not the design matrix is full rank?  Do you suggest that I check rank of model prior to running OLS?

**Comment by haifengl** [comment]
just always use "svd".

**Comment by tibcodscott** [comment]
Thank you!
