### ISSUE TITLE
Predict function for linear models has changed

### ISSUE THREAD

**Issue by tibcodscott** [haifengl/smile#599]
In version 2.4 of Smile, I could run the following Java code:
 
		double xcov[]  = {1,2,3,4,5,6,7,8,9,10};
		double xcat1[] = {1,1,1,0,0,0,0,0,0,0};
		double xcat2[] = {0,0,0,1,1,1,0,0,0,0};
		//double xcat3[] = {0,0,0,0,0,0,1,1,1,1};
		double y[]    =  {8,9,7,10,11,14,8,19,20,22};	
		//System.load("C:/Users/dscott/Desktop/SMILE/shell/src/universal/bin/mkl_rt.dll");
		
		Properties prop = new Properties();		
		prop.setProperty("smile.ols.method", "qr");
		prop.setProperty("smile.ols.standard.error", "true");
		prop.setProperty("smile.ols.recursive", "false");
		
		ArrayList<Data> DataList = new ArrayList<Data>();
		for(int i=0; i<10; i++) {
			DataList.add(new Data(y[i],xcov[i],xcat1[i],xcat2[i]));
		}
		
		DataFrame df = DataFrame.of(DataList, Data.class);
		System.out.println(df.toString());
		Formula formula = Formula.of("y" , "xcov", "xcat1", "xcat2");
		
		LinearModel lm = smile.regression.OLS.fit(formula,  df, prop);
		System.out.println(lm.toString());
		
		
		double[] x = new double[3];
		x[0]=1;
		x[1]=2;
		x[2]=3;
		
		System.out.println( lm.predict(x) );

and get a prediction of 25.55555555555556.  However, in Smile 2.5, I get the following error message: "Invalid input vector size: 3, expected: 4".  Am I expected to code the intercept term as well in version 2.5?

**Comment by haifengl** [comment]
Make it double[4] and insert 1 at the beginning (bias). Or  you can use Tuple, it will get the data transformation and bias automatically.

**Comment by tibcodscott** [comment]
Thank you!
