### ISSUE TITLE
Implementation of bag  (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by Xyclade** [haifengl/smile#6]
In the implementation of [Bag.java](https://github.com/haifengl/smile/blob/3e34c767011ce385649b016bc72627e5ff71b6ec/Smile/src/smile/feature/Bag.java) An ArrayIndexOutOfBoundsException will be created in case you do the following:

1. Create a new bag with an array of any type, which has duplicate entries, whichoff some are at the end of the array, for example:
["test","is","a","feature","test"]

2. call the feature method on a sequence of words that contains "test"

The reason this happens is because the this.features hashmap sets the index for test to 0, but later to 4, which is outside the bounds, because the features hashmap contains only 4 elements.

Possible fixes are:
a. Before putting a entry with index in the hashmap, check if it not already is contained in there.

b. Insert the entries backwards in the hashmap, such that the lowest index will lead.

c. Update the documentation to specify that only arrays with unique data can be used in training bags

d. alternative?

I'd be happy to implement any of these fixes, so please let me know which one you prefer, such that I can do a PR with the fix.

Kind regards,

Mike

**Comment by haifengl** [comment]
Hi Mike,

Thanks for the bug report! I would like to do c and a. The "training bag" is actually not for training. It is the feature list, and thus should be a set of unique words. But for sanity check, we should check the duplicates in the constructor. I will do these right now. Can you please add a unit test (in the smile.feature.BagTest of test directory) with your test case? Thanks!

Haifeng

**Comment by haifengl** [comment]
Hi Mike,

The fix is in the master now. Thanks!

**Comment by Xyclade** [comment]
Thanks! I'll add a unit test and PR it to this issue later today, as I'm in a meeting right now.

**Comment by Xyclade** [comment]
PS. the reason I found this was by extracting a feature array for 1 category, then for a second one and combining the two feature arrays into 1 new one, causing duplicates to occur as some terms where in both categories. I should probably remove the intersecting features to make the algorithm predictions better, or does the implementation take these into account?

**Comment by haifengl** [comment]
Yes, you better use Set class to get the union of the features rather than just concat in general. But the constructor now handles the duplicates. So it should be fine for you to use the feature list in your example.

The main problem is the documentation of Bag. It is not for training purpose. It just assumes that you have a set of unique features and uses them to calculate the double valued feature vectors of some text for you.
