### ISSUE TITLE
SMILE License

### ISSUE THREAD

**Issue by brucejohnson** [haifengl/smile#601]
I just noticed that though SMILE is released (I thought) under the LGPL, there is an additional LICENSE file that says that the LPGL only applies if you are not using it commercially (and don't release your code under the LPGL).  I was unaware that you could restrict the use of the LPGL in that way.  It seems it's not really the LGPL.

It also seems inconsistent with the statements in #439 
    
    We use LGPL to encourage the users to contribute back to the project. It is a commercial friendly license.

    As the debates show that LGPL is business friendly. As far as I know, business is not shy away from using LGPL libraries.

**Comment by haifengl** [comment]
Some companies have concerns with LGPL. So we make it dual license such that their layers are happy.

**Comment by brucejohnson** [comment]
But you could make it truly LPGL without additional restriction and still be able to dual license it with a commercial license.  As it is now it doesn't seem to really be available under the LPGL.  You don't have to add this additional restriction on top of it in order to dual license it.  This just makes it messy and I think will limit people from using it rather than encourage them.

**Comment by haifengl** [comment]
It is pretty much same as MySQL's dual license. I don't think it is messy.

**Comment by brucejohnson** [comment]
The difference with MySQL is that MySQL is licensed under the GPL and a commercial license, whereas you're licensing Smile under the LPGL and a commercial license, with a statement that you can only use LPGL for open source projects.  The LPGL is generally considered (see your own statements in #439 ) as allowing use in proprietary commercial software, but you've now prohibited that, so it isn't really the LPGL anymore.

You're, of course, free to license things anyway you want.  It just seems misleading to say its LPGL (implying the ability to use in commercial software without additional licenses) when it's not.

I assume you've changed the licensing (from Apache to LPGL to SMILE License) to increase you're ability to monetize the software.  I completely understand that.  It just is a little frustrating to see the switch to more and more restrictive licensing.  I think Smile is an amazing library, and I feel that this licensing will limit its use.  The Java world seems to specialize in producing multiple different numerical libraries, none of which are as complete as numpy/scipy or R or Julia (will become).

**Comment by haifengl** [comment]
Smile libraries are in LGPL. The shell module is in GPL. I have never hidden any details about the license, which has been timely updated in LICENSE file. Github declares the project as LGPL based on their logic. Maybe your complain is about that.

**Comment by brucejohnson** [comment]
I'm sorry if I have misunderstood the licensing, though the site is not clear.  The main LICENSE file (and what you see if you click "View License" contains the Smile license that is more restrictive than the LPGL.  There's nothing to indicate that the library itself is under LPGL and something else (the shell I guess) is under the more restrictive Smile license).  It would be nice if the page clarified that the library itself is under LPGL.

So my understanding is that I can use  the smile .jar files that contain the Java-based library (and not extra code such as the shell) under the LPGL regardless of whether my project is open source or proprietary (though in fact, at present, all my code is GPL).
