### ISSUE TITLE
UnsupportedOperationException in BaseVector while running quickstart example

### ISSUE THREAD

**Issue by kirkbaker** [haifengl/smile#602]
From https://haifengl.github.io/quickstart.html "A Gentle Example"

var forest = RandomForest.fit(formula, zipTrain, prop);

java.lang.UnsupportedOperationException
	at smile.data.vector.BaseVector.toIntArray(BaseVector.java:90)
	at smile.data.vector.BaseVector.toIntArray(BaseVector.java:82)
	at smile.classification.ClassLabels.fit(ClassLabels.java:106)
	at smile.classification.RandomForest.fit(RandomForest.java:294)
	at smile.classification.RandomForest.fit(RandomForest.java:191)

com.github.haifengl:smile-core:2.5.3

**Comment by kirkbaker** [comment]
As a note this line from the same example doesn't compile. 

var svm = OneVersusOne.fit(x, y, (x,y) -> SVM.fit(x, y, kernel, 5, 1E-3));

**Comment by haifengl** [comment]
I don't have any issues when running these in smile's jshell.sh. What's your environment?

**Comment by kirkbaker** [comment]
jdk-14.0.2

**Comment by haifengl** [comment]
This doesn't help much to debug the issue. Did you try the code in jshell? Or a standalone project with what settings?

**Comment by kirkbaker** [comment]
Sorry about that. I'm trying the following as a main method from Eclipse 2020-09 with JRE set to jdk-14.0.2.

```
import org.apache.commons.csv.CSVFormat;

import smile.classification.OneVersusOne;
import smile.classification.SVM;
import smile.data.formula.Formula;
import smile.io.Read;
import smile.math.kernel.GaussianKernel;

public static void main(String[] args) {
		var format = CSVFormat.DEFAULT.withDelimiter(' ');
		var zipTrain = Read.csv("zip.train", format);
		var zipTest = Read.csv("zip.test", format);
		var formula = Formula.lhs("V1");
		var x = formula.x(zipTrain).toArray();
		var y = formula.y(zipTrain).toIntArray();
		var testx = formula.x(zipTest).toArray();
		var testy = formula.y(zipTest).toIntArray();
		var kernel = new GaussianKernel(8.0);
		var svm = OneVersusOne.fit(x, y, (x, y) -> SVM.fit(x, y, kernel, 5, 1E-3));
	}
```

The last line is the one that doesn't compile for me (Lambda expression's parameter x cannot redeclare another local variable defined in an enclosing scope. ). When I change it to

var svm = OneVersusOne.fit(x, y, (k,v) -> SVM.fit(x, y, kernel, 5, 1E-3));

it compiles and runs but produces the follow error:

Exception in thread "main" java.lang.IllegalArgumentException: Invalid label: 5
	at smile.base.svm.LASVM.process(LASVM.java:357)
	at smile.base.svm.LASVM.fit(LASVM.java:145)
	at smile.base.svm.LASVM.fit(LASVM.java:125)
	at smile.classification.SVM.fit(SVM.java:178)
	at smile.classification.OneVersusOne.fit(OneVersusOne.java:138)
	at smile.classification.OneVersusOne.fit(OneVersusOne.java:87)

I believe the original exception (and the title of this ticket) was coming from labels formatted as floats in the version of "zip.train". that I found. I fixed the file and that is no longer an issue.

**Comment by haifengl** [comment]
For "doesn't compile", I guess that you include smile-scale or smile-kotlin as dependency. As you use Java, don't include those library. 

The second error is likely related that you use `(x, y) -> SVM.fit(x, y)`. Change x, y to some names that are not defined in your method.

**Comment by kirkbaker** [comment]
Thank you for your help and for making this library available. The issues were related to me trying to piece together the examples and errors loading the USPS data. `(x, y) -> SVM.fit(x, y)` is from the example, but I worked it out from the unittest Java code.
