### ISSUE TITLE
Incompatibility of One Versus Rest and Random Forest

### ISSUE THREAD

**Issue by damienlancry** [haifengl/smile#607]
**Is your feature request related to a problem? Please describe.**
the current code for OneVersusRest seems to be incompatible with Random Forest. Indeed all [fit methods](https://github.com/haifengl/smile/blob/a1720b837e2e00b1cb1122b1e0882ef78e81bd92/core/src/main/java/smile/classification/RandomForest.java#L273) of the class Random Forest take a Formula and a DataFrame as inputs. 
In contrast the OneVersusRest Classifier [fit method](https://github.com/haifengl/smile/blob/a1720b837e2e00b1cb1122b1e0882ef78e81bd92/core/src/main/java/smile/classification/OneVersusRest.java#L89) takes features x: Array[T], labels y: Array[Int] and a BiFunction trainer as input. As illustrated in the documentation:
```
    val zip = read.csv("data/usps/zip.train", delimiter = ' ' , header = false)
    val x = zip.drop(0).toArray
    val y = zip.column(0).toIntArray
    val kernel = new GaussianKernel(8.0)
    val model = ovr(x, y) { (x, y) => SVM.fit(x, y, kernel, 5, 1E-3) }
```

**Describe the solution you'd like**
A solution that would be nice would be to have a fit method for the Random Forest that takes features x: Array[T], and labels y: Array[Int] so that we could train a one versus rest random forest like that:
```
    val model = ovr(x, y) { (x, y) => RandomForest.fit(x, y) }
```

**Describe alternatives you've considered** 
Another solution that could work would be to have a fit method for the OneVersusRest class that takes a Formula and a DataFrame as input so that we could train a one versus rest random forest like that:
```
    val model = ovr(formula, data) { (formula, data) => RandomForest.fit(formula, data) }
```

**Additional context**
There could have been a work around to that by doing something like :
```
val model = ovr(x, y) { (x, y) => RandomForest.fit("class" ~, DataFrame.of(x).merge(DataFrame.of(y.map(Array(_)), "class")))}
```
But this gives the error:
```
<console>:46: error: type mismatch;
 found   : smile.classification.RandomForest
 required: smile.classification.Classifier[Array[Double]]
```
Another challenge that will arise is that by default the one versus rest performs platt scaling on the output of the f method of its base estimator and the f method is only implemented for some classifiers (svms, logistic regressions, max entropy...).
Therefore, one would need to make platt scaling an option, and use the predict method of the classifiers instead of f.

I am more than willing to contribute.

**Comment by haifengl** [comment]
RandomForest handles multiclass directly. OneVersusRest and OneVersusOne for binary classifiers.

**Comment by damienlancry** [comment]
Thank you for your answer.

Yes I am aware that Random Forest can handle multi class directly. However, in principle the one versus rest strategy can be used with any base estimator, as it is the case in other frameworks such as scikit-learn, and OVR Random Forest often gives better performance than the multi class Random Forest as reported here:

https://stats.stackexchange.com/questions/260754/better-performance-using-random-forest-one-vs-all-than-random-forest-multiclass
https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2015-5.pdf 

It is also the case in my experience and in my current use case. That is why I would love it if smile supported that.

**Comment by haifengl** [comment]
Make sure that `x` be of `Tuple` with your workaround.

**Comment by damienlancry** [comment]
Thanks for this suggestion.

I tried it and indeed it solves the type error. But as I mentioned above, the [f method](https://github.com/haifengl/smile/blob/14edba58e07f18c47d60b98536c074854fc94fbf/core/src/main/java/smile/classification/Classifier.java#L57) is not implemented for the Random Forest Classifier, so it crashes there:
```
val xt = x.map(arr => Tuple.of(arr, zip.drop(0).schema()))
val model = ovr(xt, y) { (xt, y) => RandomForest.fit("class" ~, DataFrame.of(xt.map(_.toArray)).merge(DataFrame.of(y.map(Array(_)), "class")))}
```
gives the error:
```
java.lang.UnsupportedOperationException
  at smile.classification.Classifier.f(Classifier.java:58)
  at smile.classification.PlattScaling.fit(PlattScaling.java:213)
  at smile.classification.OneVersusRest.fit(OneVersusRest.java:125)
  at smile.classification.OneVersusRest.fit(OneVersusRest.java:90)
  at smile.classification.package$.$anonfun$ovr$1(package.scala:981)
  at smile.util.package$time$.apply(package.scala:57)
  at smile.classification.package$.ovr(package.scala:981)
  ... 48 elided
```

**Comment by haifengl** [comment]
I add a new fit method that takes DataFrame and returns DataFrameClassifier.
