### ISSUE TITLE
Spark and SMILE integration

### ISSUE THREAD

**Issue by pierrenodet** [haifengl/smile#608]
Hi, I have made a package called [spark-smile](https://github.com/pierrenodet/spark-smile) that provides utilities to work with SMILE in Spark environnement.

I see that you have started recently a spark-smile subproject that implement some features of this package. Are you interested in having the whole package upstream to smile ?

**Comment by haifengl** [comment]
Yes. Thanks!

**Comment by haifengl** [comment]
Thanks for the contribution. Grid search fails on my machine. Can you please check if the master branch works on your machine?

**Comment by pierrenodet** [comment]
Yes my bad, actually i misunderstood the cv API, i thought it would return an array of double, of size k (number of folds) but it return an array of size n (number of measures). So in the tests instead of res(0).length == 5 it sould be res(0).length == 1. Do you need a pull request for that ?

Btw if you try to run the test of spark-smile with scala 2.12 but the rest of smile with scala 2.13 it fails.

**Comment by haifengl** [comment]
Thanks for the fix. smile-spark depends on smile-core, which is pure Java. So it is fine.

BTW, I will refactor grid search in the way here http://haifengl.github.io/validation.html#hyperparameter-tuning

**Comment by pierrenodet** [comment]
http://haifengl.github.io/validation.html#hyperparameter-tuning : that's neat, it's going to be a cleaner API. Thank you again to take time for the reviewing process !

**Comment by haifengl** [comment]
Can you refactor `SmileClassifier` and `SmileRegression` to be generic? They are fixed to take `Array[Array[Double]]`.

**Comment by pierrenodet** [comment]
It's kind of unusual for MLLib Estimators to be generic. What's the use case ?

**Comment by haifengl** [comment]
Many Smile algorithms don't take double[][]. So the integration is of limited use. But if MLLib just take double[][], it is fine.

**Comment by pierrenodet** [comment]
Yep they usually (it might even be all of them) take a Vector per row so double[][] as a whole.

**Comment by haifengl** [comment]
Okay. I already refactored the grid search. It is generic and can be use for random search too. Have a look.

If there are no additional changes, I will close this ticket. Thanks!
