### ISSUE TITLE
HiddenLayerBuilder inaccessible in this context

### ISSUE THREAD

**Issue by Gab601** [haifengl/smile#612]
**Describe the bug**
I tried creating a new array of Layers for an mlp classifier, but get the following error message:

`Type HiddenLayerBuilder! is inaccessible in this context due to: public/*package*/ open class HiddenLayerBuilder : LayerBuilder defined in smile.base.mlp in file HiddenLayerBuilder.class`

**Expected behavior**
The code was copied directly from the Kotlin SMILE documentation, so I expected it to compile and create a Layer object.

**Actual behavior**

`Type HiddenLayerBuilder! is inaccessible in this context due to: public/*package*/ open class HiddenLayerBuilder : LayerBuilder defined in smile.base.mlp in file HiddenLayerBuilder.class`

**Code snippet**

`import smile.base.mlp.*
arrayOf(Layer.sigmoid(10), Layer.mle(1, OutputFunction.SIGMOID))`

**Input data**

**Additional context**
- Running Java version 14.0.2, working in Kotlin
- Smile version 2.5.3
- Ubuntu 18.04

**Comment by haifengl** [comment]
`Layer` class provides factory methods to create hidden layers, e.g. `Layer.rectifier()`.
