### ISSUE TITLE
Example of semi-supervised?

### ISSUE THREAD

**Issue by gsaxena888** [haifengl/smile#617]
I've been recently using Smile -- and GradientBoostedTrees (GBT) in particular -- for regression analysis. I'd like to use GBT for classification, but I'm confused as to how to use it for the case of *semi* supervised learning. Specifically, I have two possible class outcomes "True" or "False", but I only ever know the "False" scenario; for the "True" class, my training data does not know which ones are true. I *thought* I read months ago somewhere (but I can no longer find the reference, despite hours of Googling) that I should set the outcome double variable to "NaN" and that smile would then do GBT for a *semi* supervised scenario. Is this the "right way" to set up a semi-supervised GBT classifier? (If there are any examples that you could point me too, please feel free to do so.) Alternatively, could I set the output variable to "NULL"? Thanks in advance.

**Comment by haifengl** [comment]
It is not semi-supervised learning as I know. It is one-class classification and GBT doesn't support it.
