### ISSUE TITLE
Return Interface Instead of Non-Public Subclass in Layer

### ISSUE THREAD

**Issue by ccjernigan** [haifengl/smile#618]
**Describe the bug**
I'm making a call to `Layer.sigmoid`, which has method signature returning a type of `HiddenLayerBuilder`.  `HiddenLayerBuilder` is declared with default class visibility, so effectively `Layer.sigmoid` is returning a private API.  This occurs for several other methods in the Layer class.

**Expected behavior**
Either: 1. `Layer`'s methods signatures return `LayerBuilder` or 2. `HiddenLayerBuilder` becomes declared public.

**Actual behavior**
The Kotlin compiler is giving this warning:
`Type HiddenLayerBuilder! is inaccessible in this context due to: public/*package*/ open class HiddenLayerBuilder : LayerBuilder defined in smile.base.mlp in file HiddenLayerBuilder.class`

**Additional context**
- Kotlin 1.4.10, Java 14
- Smile 2.5.3
- macOS

** Workaround ** 
Create a new class in the Smile package namespace and force downcasting the return type.
```
package smile.base.mlp

object LayerHelper {
    fun safeSigmoid(n: Int): LayerBuilder = Layer.sigmoid(n)
}
```

**Comment by haifengl** [comment]
I make `HiddenLayouerBuilder` public.
