### ISSUE TITLE
add sentiment analysis model

### ISSUE THREAD

**Issue by haifengl** [haifengl/smile#62]
what training data should we use? semi-supervised tweets?

**Comment by haifengl** [comment]
An interesting benchmark:

https://blog.monkeylearn.com/sentiment-analysis-apis-benchmark/

**Comment by rayeaster** [comment]
http://help.sentiment140.com/for-students
Sentiment140 was created by Alec Go, Richa Bhayani, and Lei Huang, who were Computer Science graduate students at Stanford University, allowing you to discover the sentiment of a brand, product, or topic on Twitter.

**Comment by digital-thinking** [comment]
Just found this issue and I recently found this data set.
https://www.kaggle.com/c/twitter-sentiment-analysis2

**Comment by santhoshTpixler** [comment]
Any plans for implementing this feature? @haifengl

**Comment by haifengl** [comment]
You can easily implement a sentiment model with our algorithms and any training data that is suitable to your problem. Feel free to contribute. Thanks!

**Comment by haifengl** [comment]
Sentiment analysis is data dependent while smile focus on fundamental algorithms. We may implement it in a higher level library in the future.
