### ISSUE TITLE
RidgeRegression on Windows 10

### ISSUE THREAD

**Issue by TanyRay** [haifengl/smile#624]
**Describe the bug**
I try to use **RidgeRegression**. I imported only smile-core initially.

```
<dependency>
            <groupId>com.github.haifengl</groupId>
            <artifactId>smile-core</artifactId>
            <version>2.5.3</version>
 </dependency> 
```

I got some unexpected program behavior without any warning. After debug session I realized that I need to add BLAS. I read advice in README of smile and add 3 additional libs to pom.xml

```
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.5.4</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>openblas</artifactId>
            <version>0.3.10-1.5.4</version>
            <classifier>windows-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>arpack-ng</artifactId>
            <version>3.7.0-1.5.4</version>
            <classifier>windows-x86_64</classifier>
        </dependency>  
```

**Expected behavior**
I think the README is missing something or such exceptions should not be occur

**Actual behavior**
Now I get warning in console:
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Warning: Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path

**Code snippet**
LinearModel linearModel = RidgeRegression.fit(Formula.lhs("class"), data, weights, LAMBDA, DELTA0);

**Input data**
The sample data

**Additional context**
My build system is Windows 10. My java info is the following:
OpenJDK Runtime Environment (build 1.8.0_252-b09)

**Comment by haifengl** [comment]
Try not including `classifier`.

**Comment by TanyRay** [comment]
Actually, not adding classifier corrupts it at all. I added classifiers to all of them and warnings were disappeared. `javacpp` didn't have classifier initially.

**Comment by haifengl** [comment]
Without classifier, it should pick up all native libraries. It takes more disk space but is a quick way to get all dependency. I don't know why it fails on your machine. It works on my windows. If you have to use classifier, don't forget a special empty one. Here is my settings for shell module:
```
libraryDependencies ++= Seq(                                                    
    "org.scala-lang" % "scala-compiler" % "2.13.4",                               
    "org.slf4j" % "slf4j-simple" % "1.7.30",                                      
    "org.bytedeco" % "arpack-ng" % "3.7.0-1.5.4"  classifier "macosx-x86_64" classifier "windows-x86_64" classifier "linux-x86_64" classifier "",
    "org.bytedeco" % "openblas"  % "0.3.10-1.5.4" classifier "macosx-x86_64" classifier "windows-x86_64" classifier "linux-x86_64",
    "org.bytedeco" % "javacpp"   % "1.5.4"        classifier "macosx-x86_64" classifier "windows-x86_64" classifier "linux-x86_64"
  )    
```

Note `classifier ""` for arpack-ng.
