### ISSUE TITLE
RidgeRegression has extra validation on X matrix size that can be avoided

### ISSUE THREAD

**Issue by TanyRay** [haifengl/smile#625]
**Is your feature request related to a problem? Please describe.**
I've been working on LIME explainer that's why I would like to use Ridge. But I have a significant limitation: X matrix validation on having column count less than row count. It's ok for small matrices but I reviewed several ridge implementations and I don't see any reason to include such limitation. I have 12k*1k matrix and generating instead of 1k 12k samples to correspond features count makes this task to heavy. 

```
if (n <= p) {
            throw new IllegalArgumentException(String.format("The input matrix is not over determined: %d rows, %d columns", n, p));
        }
```

**Describe the solution you'd like**
Remove this validation from RidgeRegression or clearly explain why it's required as javadoc.

**Comment by haifengl** [comment]
I remove this check.
