### ISSUE TITLE
Per-tree statistics in RF (OOB / Accuracy)

### ISSUE THREAD

**Issue by weinino** [haifengl/smile#627]
We're integrating several Smile algorithms into a ML software. The algorithms will have an UI containing the configuration, statistics and evaluation.

For the RandomForest, I would like to add some statistics about OOB and accuracy of the decision trees. The problem is, that even it is logged out, I have no direct access via the RandomForest. Those metrics are calculated but not sotred on the decision trees.
```
double accuracy = 1.0;
if (oob != 0) {
       accuracy = (double) correct / oob;
       logger.info("Random forest tree OOB size: {}, accuracy: {}", oob, String.format("%.2f%%", 100 * accuracy));
} else {
       logger.error("Random forest has a tree trained without OOB samples.");
}
```

Also the calculated weight of each tree is not accessible from the outside, since it is stripped of the wrapped trees in the getter.
``` 
public DecisionTree[] trees() {
        return trees.stream().map(t -> t.tree).toArray(DecisionTree[]::new);
}
```

Would it be possible to expose this as a ready-only statistic?

**Comment by haifengl** [comment]
Okay.

**Comment by haifengl** [comment]
It is in master now. Try `models()`.

**Comment by weinino** [comment]
> It is in master now. Try `models()`.

Perfect, thank you.
