### ISSUE TITLE
RidgeRegression for SparseMatrix

### ISSUE THREAD

**Issue by TanyRay** [haifengl/smile#628]
Hi. It would be great to have an opportunity to perform RidgeRegression on SparseMatrix. Currently, RidgeRegression is restricted X dense matrix with row size is less than sqrt(Integer.MAX_VALUE). The problem is occurred in line `Matrix XtW = new Matrix(p, n);` of class RidgeRegression because it's impossible to allocate space for [ld * n] array (greater than max int). 
Unfortunately, I cannot provide any other idea (I mean other approach) to make it work. Cholesky isn't implemented for SparseMatrix as well.

**Comment by haifengl** [comment]
`XtW` (transposed) is same size as `X`. If you cannot create `XtW`, how do you create `X`? Besides, `p` is usually small. So the number of rows of matrix can be much larger than `sqrt(MAX_VALUE)`.

**Comment by TanyRay** [comment]
My mistake. The issue occurred in `Matrix XtX = XtW.mm(scaledX); ` 
The issue is following:
```
Matrix XtX = XtW.mm(scaledX); 

where XtW
m = 59718
n = 1001

where scaledX
m = 1001
n = 59718

where new Matrix has m=59718 and n=59718 and ld=59792
double[] array = new double[ld * n]; 
```
New array side exceeds max integer value. It means that RidgeRegression with non sparse matrix approach is restricted sqrt(Integer.MAX_VALUE) feature count.

**Comment by haifengl** [comment]
You have only 1001 samples but 59718 features? Are you sure it is not the other way around?

If it is the case, the fitting results won't be good anyway even if we can support larger matrix (it is a Java limitation anyway). This is underdetermined. ML is mostly for overdetermined. Even though ridge regression works around matrix singularity. But it is to handle collinearity, not underdetermined.

**Comment by TanyRay** [comment]
I'm implementing LIME in Java from https://github.com/marcotcr/lime. In LIME repo they decided to use ridge for feature selection process. They use it for feature selection as optional step and also as regressor model with different regularization. I don't think about ridge as a perfect model. I can try to implement it on sparse matrices and contribute to SMILE but I'm not sure about correctness. I can see the way of usage ridge with relatively small number of samples and large feature space.

**Comment by haifengl** [comment]
`SparseMatrix` is not a solution. First of all, `SparseMatrix` saves memory only if the matrix is sparse indeed. Otherwise, it will use more memory. Maybe your `X` is sparse. But the decomposition matrix is usually not. So you will hit the same matrix size limit issue soon or late.

Besides, I guess that you have very large number of features because you use one-hot encoding on high cardinality categorical variables. Note that one-hot is not very useful in this case. Whatever score you get from ridge regression may not indicative.
