### ISSUE TITLE
Clustering Validation Measures

### ISSUE THREAD

**Issue by rfalexandre** [haifengl/smile#629]
Dear,

first I would like to congratulate you on your work and contributions to the community. I'm looking for a lib to work with clustering and I realize that Smile has several algorithms implemented.

I researched the evaluation measures implemented by Smile and did not find the main techniques found in the literature. Among them I can mention: Root-mean-square standard deviation, R-squared (RS), Dunn’s indices (D), Silhouette index (S), among others. I would like to know if it was my fault for not having found it or if they are not really implemented? If not, is there any provision to make it available?

Thank you for your attention and once again, congratulations.

Rafael Alexandre.

**Comment by haifengl** [comment]
There are a few clustering metrics in `smile.validation.metric` package. Besides, centroid based clustering algorithms calculate `distortion`, which is aligned with root mean square standard deviation (no root and mean). R-squared is for regression. We don't have Dunn’s indices (D), Silhouette index (S) though. It would be great if you can make a PR on them. Thanks.
