### ISSUE TITLE
how to implement it 

### ISSUE THREAD

**Issue by nikkisingh111333** [haifengl/smile#633]
hello i m NEW here and currently trying to implement SMILE in my springboot app but classes not resolving dont know why.
heres my screenshot:
![Screenshot (46)](https://user-images.githubusercontent.com/49682940/103140469-d09c0e80-470c-11eb-91a7-f425e5f402d7.png)
RED lines indication cant resolve package.

heres my pom.xml:
![Screenshot (47)](https://user-images.githubusercontent.com/49682940/103140480-edd0dd00-470c-11eb-9863-98291b77425a.png)

HELP ME OUT PLEASE!!!

**Comment by rayeaster** [comment]
@nikkisingh111333 man, you should format your code like `pom.xml` and try add a dependency for `smile-io`

**Comment by nikkisingh111333** [comment]
hey i was waiting for your reply its late but ok.by the way i have tried everything in pom.xml as i could..but nothing is happening how can i add smile.io dependency there are others missing too.where i can find it.? help me i need to get started now.?
