### ISSUE TITLE
Dataset values are always string?? what should i do ?

### ISSUE THREAD

**Issue by nikkisingh111333** [haifengl/smile#634]
Hey i m new bie here ...i m importing CSV dataset and it contains Numeric columns but they are always string cant perform operations like scatterplotting and ml operations how can i convert them in Numeric..in other platform like rapidminer and Tribuo everything is working fine heres the result :
`[V1: String, V2: String, V3: String, V4: String, V5: String, V6: String, V7: String, V8: String, V9: String, V10: String, V11: String, V12: String, V13: String]
+-----+-------------+----------------+-----------+--------------+---------+-------------------+--------------------+-------+----+---------+-------+-------+
|   V1|           V2|              V3|         V4|            V5|       V6|                 V7|                  V8|     V9| V10|      V11|    V12|    V13|
+-----+-------------+----------------+-----------+--------------+---------+-------------------+--------------------+-------+----+---------+-------+-------+
| type|fixed acidity|volatile acidity|citric acid|residual sugar|chlorides|free sulfur dioxide|total sulfur dioxide|density|  pH|sulphates|alcohol|quality|
|white|            7|            0.27|       0.36|          20.7|    0.045|                 45|                 170|  1.001|   3|     0.45|    8.8|      6|
|white|          6.3|             0.3|       0.34|           1.6|    0.049|                 14|                 132|  0.994| 3.3|     0.49|    9.5|      6|
|white|          8.1|            0.28|        0.4|           6.9|     0.05|                 30|                  97| 0.9951|3.26|     0.44|   10.1|      6|
|white|          7.2|            0.23|       0.32|           8.5|    0.058|                 47|                 186| 0.9956|3.19|      0.4|    9.9|      6|
|white|          7.2|            0.23|       0.32|           8.5|    0.058|                 47|                 186| 0.9956|3.19|      0.4|    9.9|      6|
|white|          8.1|            0.28|        0.4|           6.9|     0.05|                 30|                  97| 0.9951|3.26|     0.44|   10.1|      6|
|white|          6.2|            0.32|       0.16|             7|    0.045|                 30|                 136| 0.9949|3.18|     0.47|    9.6|      6|
|white|            7|            0.27|       0.36|          20.7|    0.045|                 45|                 170|  1.001|   3|     0.45|    8.8|      6|
|white|          6.3|             0.3|       0.34|           1.6|    0.049|                 14|                 132|  0.994| 3.3|     0.49|    9.5|      6|
+-----+-------------+----------------+-----------+--------------+---------+-------------------+--------------------+-------+----+---------+-------+-------+
6488 more rows...`
eVERYTHING IS STRING HERE i can peform basic matchAny or filter methods but cant change dataframe from string to numeric ..how can i do that and also theres No one hot encoding feature...please help me..there is no comunity support i m getting .help me out.??

**Comment by haifengl** [comment]
Set the flag that the first row is header.

**Comment by nikkisingh111333** [comment]
i dont know how to do it any hint would be better please provide some code snippet for that i m struggling .

**Comment by haifengl** [comment]
check out core/src/test/smile/data. there are many examples.

**Comment by nikkisingh111333** [comment]
Thanks, I'll check it out.

**Comment by haifengl** [comment]
https://github.com/haifengl/smile/blob/d9918ced9edec03caab1c1700ebe51d8e3cabd1f/core/src/test/java/smile/data/USArrests.java#L35

**Comment by nikkisingh111333** [comment]
Thanks! i got it ... can i ask you one more thing its not tech related
..why its a late reply i  was waiting 3 days for this i mean .coz i m newly
started smile guy so thats why i m asking ?
