### ISSUE TITLE
Create DataFrame from array of arrays.

### ISSUE THREAD

**Issue by MagnusMG** [haifengl/smile#636]
I find it hard to believe that there is't any way of creating a DataFrame internally. Do I really have to export the data to csv or a database and then create a DataFrame from there?

I think it would be very good to have a few factory methods for creating a DataFrame, for example by giving the method a lists or arrays that will become columns in the DataFrame instance. In Kotlin, something like this: `fun createDataFrame(vararg col: List): DataFrame`

I realise that the typed nature of the involved languages makes it a bit tricky to make the factory methods high-level, but even a factory where you add one row at a time, and in the end create a DataFrame from all the added rows (as if it were a csv file) would be very useful:
`class DataFrameFactory {`
`fun addValueToCurrenRow(value: Any): Util`
`fun newRow(): Util`
`fun createDataFrameFromAddedData(): DataFrame`
`}`

**Comment by haifengl** [comment]
There are multiple `DataFrame.of()` methods to create data frames from `double[][]` or `Tuple[]` (or lists).

**Comment by MagnusMG** [comment]
Aha. I did not think of looking under "of". Silly me. Thanks.
