### ISSUE TITLE
MLP use ?

### ISSUE THREAD

**Issue by nikkisingh111333** [haifengl/smile#637]
hey i m playing around with MLP network and when i copied code from docs .net.setLearningrate(0.1) was taking Double value as param but in Real it change to TimeFunction now whats this TimeFunction i dont understand? how do i set set parameters for better acuracy currently my network is giving worst result?
here what i see in doc:
`net.setLearningRate(0.1);
    net.setMomentum(0.1);`
And heres what its asking for:
`net.setLearningRate(TimeFunction t);
net.setMomentum(TimeFunction t);`
Clear me with a good solution. please

**Comment by haifengl** [comment]
TimeFunction is in `smile.math` package. You can check MLP unit tests for examples.
