### ISSUE TITLE
ModelCriteria use ? no proper guidance ?

### ISSUE THREAD

**Issue by nikkisingh111333** [haifengl/smile#638]
hey i m using gradientBoosting for general purpose and want to compare my model with another one using ModelCriteria.BIC(),i dont know where i can find my model coeffeciant and other param to find log and pass it to BIC function..can you share me the code for how can use modelCriteria in smile for model validation ??

**Comment by haifengl** [comment]
gradient boosting is not a likelihood based algorithm. it doesn't make sense to use BIC on it.
