### ISSUE TITLE
CrossValidation with fixed partitions

### ISSUE THREAD

**Issue by owlmsj** [haifengl/smile#64]
Hi, 

already check a bunch of classes but with no luck to find an example of. 

SO, is there a "ready code" to run CrossValidation that return fixed partitions?

**Comment by haifengl** [comment]
What do you mean "fixed partitions"?

**Comment by owlmsj** [comment]
"Running example" at 5-fold cross validation (partitions A,B,C,D and E = the entire dataset).

fold 1) A,B,C,D = train and E = test
fold 2) A,B,C,E = train and D = test
fold 3) A,B,D,E = train and C = test
fold 4) A,C,D,E = train and B = test
fold 5) B,C,D,E = train and A = test

Probably this is not the best explanation and it is kind of a trivial code to do. Just to know if this feature in smile is already coded or should I implement something look like and make a pull request...

**Comment by haifengl** [comment]
smile.validation.CrossValidation is for that.

**Comment by owlmsj** [comment]
My mistake (because my code was shuffling the data at the beginning). Sorry.
