### ISSUE TITLE
Plots erroneously clip title and legend

### ISSUE THREAD

**Issue by robertvazan** [haifengl/smile#640]
This code in `Graphics` class is probably wrong:

```java
    public void clearClip() {
        if (originalClip != null) {
            g2d.setClip(originalClip);
            originalClip = null;
        }
    }
```

It will not clear clip if there wasn't any previous clip. If the clip is not cleared, plots are shown without title and legend.

**Comment by haifengl** [comment]
thanks. will look into it.

**Comment by haifengl** [comment]
The fix is in master branch.
