### ISSUE TITLE
Difference between SMILE and SciKit

### ISSUE THREAD

**Issue by MagnusMG** [haifengl/smile#642]
I'm moving from Python and SciKit to SMILE (with Kotlin), and as a way of learning I am implementing the same thing in SMILE as I have previously done in SciKit. And I cannot get the same results. They are similar, but not the same, and when I scale this up I run into problems.

I have created a very small dataset and simple code snippets for comparison.
Here is my input:
<code>
HST | FAKULTETSUPPDRAG | SOKANDE | BEH1HSOKANDE | ARBETSLOSHET1 | ANTALINVANAREIMEDIANALDER | HST_2 | HST_3
-- | -- | -- | -- | -- | -- | -- | --
57.3142861 | 3960 | 45 | 14 | 164900 | 116910 | 48.7392861 | 133.930123
23.0073691 | 3960 | 43 | 12 | 138633.333 | 116910 | 30.9357145 | 138.55321
43.8676314 | 4140 | 66 | 21 | 151266.667 | 120633.333 | 57.3142861 | 139.144051
20.0705358 | 4140 | 47 | 10 | 128500 | 120633.333 | 23.0073691 | 123.355951
27.6794644 | 4049 | 40 | 9 | 148766.667 | 122181.667 | 43.8676314 | 122.667478
27.4578573 | 4049 | 146 | 66 | 138566.667 | 126548.333 | 20.0705358 | 109.957522
15.9874061 | 3879 | 118 | 71 | 134733.333 | 128621.667 | 27.4578573 | 83.9544647
14.8142858 | 3765 | 138 | 63 | 127533.333 | 137826.333 | 15.9874061 | 43.041923
15.6678573 | 3775 | 150 | 86 | 109466.667 | 141869.667 | 14.8142858 | 35.7447188
14.3601192 | 3787.5 | 128 | 72 | 96800 | 141120.333 | 15.6678573 | 37.8162068
14.2407408 | 3790 | 145 | 81 | 97166.6667 | 144084.333 | 14.3601192 | 45.3637191
13.6261905 | 3811 | 134 | 70 | 98900 | 141082.333 | 14.2407408 | 39.4444231
14.1465714 | 3841 | 135 | 72 | 112233.333 | 127618 | 13.6261905 | 30.6519913
</code>

where HST is what I am trying to predict (y) and the other columns are my features (x).

In Python I write the following:
```df_raw = pandas.read_csv('smiletest.csv', sep='\t' )
features = ['BEH1HSOKANDE', 'SOKANDE', 'FAKULTETSUPPDRAG', 'ARBETSLOSHET1','ANTALINVANAREIMEDIANALDER','HST_2','HST_3']
train = df_raw[features + ["HST"]]
best_model = sklearn.linear_model.Lasso(1.0, normalize=False, tol=1e-4, max_iter=1000)
best_model.fit(train[features], train[["HST"]])
coefs = best_model.coef_
for c in coefs :
   print(c)
```

and I get the following parameters for the model (w):
```
-0.23771667572533828
0.21740902004302212
-0.025229374390463494
8.29241719938249e-05
-0.00019767697044341745
0.7155012309844838
0.06395336875454033
```

In Kotlin I write the following:

```
var csvFormat = CSVFormat.EXCEL.withDelimiter('\t').withFirstRecordAsHeader()
val df = Read.csv("smiletest.csv", csvFormat)
val lstFeatures = listOf("BEH1HSOKANDE", "SOKANDE", "FAKULTETSUPPDRAG", "ARBETSLOSHET1","ANTALINVANAREIMEDIANALDER","HST_2","HST_3")
var arrFeatures = lstFeatures.toTypedArray()
var frm = Formula.of("HST", *arrFeatures)
var lm = lasso(frm, df, 1.0, tol=1e-4, maxIter= 1000)
for ( dbl in lm.coefficients() ){
   println(dbl)
}
```

and that gives me the following list:

```
-0.2098661129846831
0.196350242876101
-0.022009054563421775
9.021780193559054E-5
-1.6620520003159705E-4
0.7163262340277853
0.05637525585524522
```

So, around 10 % difference between the parameters in each set.
Now, I don't really know what to expect. Perhaps these differences are to be expected due to minimal differences in rounding and implementation choices? Or am I doing something else wrong? I have tried increasing the maxIterations and decreasing the tolerance, but that does not really make any difference.

The API documentation of LASSO in SMILE suggests, perhaps, that the data are standardized before the regression takes place. I tried standardizing the data in SciKit as well, using a StandarScaler, but got very different results. (Only two of the parameter weights != 0.)

Any ideas?

(BTW, I don't see this as a bug report. More of a "help needed", but that was not available for me.)

**Comment by haifengl** [comment]
The training algorithms may be different. I suggest to focus on the objective function rather than the weight.

**Comment by MagnusMG** [comment]
I'm not sure I understand what you mean. 
1. I understand that the training algoritms may be different and that that can result in differences, but are they supposed to be so big? SciKit uses coordinate descent. I can't find out which algorithms is used in SMILE, but one of  the references suggests least angle regression. There is a [least angle regression version in SciKit](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoLars.html#sklearn.linear_model.LassoLars) too, and I tried that one too, and it did not make much difference.
2. 'Focus on the objective function'. The objective function in SciKit is defined [here](https://scikit-learn.org/stable/modules/linear_model.html#lasso) and it is, as far as I can see, the sum of squared errors divided by the number of samples TIMES 2, plus lambda times the L1 norm. That is the same as the objective function for LASSO that I find described anywhere else, including [Wikipedia](https://en.wikipedia.org/wiki/Lasso_(statistics)), with the exception of the TIMES 2, i.e. in SciKit the average squared error is divided by 2 before the "punishment term" is added. Assuming that SMILE uses the Wikipedia version one could compensate for this difference between SciKit and SMILE by setting lambda in SMILE to twice the size of lambda in SciKit. But I don't get any better results for that. But then again, I can't find information about the precise objective function used in SMILE LASSO. And perhaps I misunderstand your suggestion about focusing on the objective function altogether?

I could perhaps add, just to give a bit more information, that the difference in parameter weights between the two implementations grows larger with larger lambdas. With lambda = 0.0001 there is hardly any difference at all between the two implementations.

**Comment by haifengl** [comment]
1. The algorithm is in Seung-Jean Kim, K. Koh, M. Lustig, Stephen Boyd, and Dimitry Gorinevsky. An Interior-Point Method for Large-Scale L1-Regularized Least Squares. It is not least angle regression.
2. I mean check the difference of objective function values.
