### ISSUE TITLE
Inconsistent treatment of bias in regression algorithms

### ISSUE THREAD

**Issue by robertvazan** [haifengl/smile#644]
**Describe the bug**
My app allows switching regression algorithms. Some time ago, this worked fine as all of them produced `LinearModel` with the same structure, differing only in weights. Current version of smile produces inconsistently structured output.

**Expected behavior**
Method `fit()` in `OLS`, `RidgeRegression`, and `LASSO` produces `LinearModel` with the same structure.

**Actual behavior**
`OLS` includes the intercept as the first weight in `LinearModel.coefficients()`. `RidgeRegression` and `LASSO` leave intercept in `LinearModel.intercept()`.

**Code snippet**
```java
double[][] independent = /* ... */;
int[] dependent = /* ... */;
var frame = DataFrame.of(independent).merge(IntVector.of("y", dependent));
var formula = Formula.lhs("y");
var model1 = OLS.fit(formula, frame);
var model2 = RidgeRegression.fit(formula, frame);
assertEquals(model1.coefficients().length, model2.coefficients().length); // fails
```

**Additional context**
- Smile version: 2.6.0

**Likely cause**
I think the inconsistency is in this code (taken from the affected classes):

```java
// OLS.fit(...)
Matrix X = formula.matrix(data);

// RidgeRegression.fit(...)
Matrix X = formula.matrix(data, false);

// LASSO.fit(...)
Matrix X = formula.matrix(data, false);
```

**Comment by haifengl** [comment]
OLS may have no bias too if the model formula specifies so. All the difference is hidden in the model as long as you do `predict(Tuple)`. We prepare the data properly. I guess that you are doing `predict(double[])`, which need to have all feature engineering work done by yourself. It is more than just bias.

**Comment by robertvazan** [comment]
`LinearModel` is too heavy for my application, not to mention the overhead of `Tuple`. I am extracting weights and intercept into plain augmented vector (`double[]`) and applying it myself. I am also extracting weights from `LogisticRegression`, which is another reason not to use `LinearModel`.

Anyway, as the example above shows, all the models are generated from the same data using the same formula. To me, it looks like a bug when the resulting `LinearModel` has different structure for the same formula. Is there a way to enforce consistent output structure? My formula is trivial `Formula.lhs("y")`.

**Comment by haifengl** [comment]
I made some changes. Try master branch.
