### ISSUE TITLE
Parallel execution of multiple GradientBoostedTrees throws NPE in predict method

### ISSUE THREAD

**Issue by patrick-frank-bsi** [haifengl/smile#646]
**Describe the bug**
I am running the predict method of several trained instances of `GradientTreeBoost`, each in its own thread, in parallel. I ocassionally get NPEs in Formula::x, without any apparent reason.

**Expected behavior**
The inference should run in parallel without any NPE, because inference should only require read access on the models internal variables.

**Actual behavior**
Stack Trace:
```
java.lang.NullPointerException
	at smile.data.formula.Formula$2.getDouble(Formula.java:358)
	at smile.base.cart.OrdinalNode.predict(OrdinalNode.java:45)
	at smile.regression.RegressionTree.predict(RegressionTree.java:322)
	at smile.classification.GradientTreeBoost.predict(GradientTreeBoost.java:523)
```

**Code snippet**
Steps to reproduce:
1. Train a GradientTreeBoost  model on some data set (I used Titanic)
2. Start multiple threads, in each execute: (in this example binary classification)
```
probabilities = new double[2];
gradientTreeBoost.predict(sampleData, probabilities);
```
with different `samleData`.

Problem can be worked around by executing `smile.classification.GradientTreeBoost.predict` in a `synchronized` method, but that is very undesirable as it creates a significant bottleneck...

**Input data**
Depends on the dataset the classifier was trained on, I used samples like that:
{
  pclass: 1,
  age: 47,
  fare: 52.5542,
  sibsp: 1
}

**Additional context**
- Oracle JDK 11
- Smile 2.5.3
- Windows

**Comment by haifengl** [comment]
This was likely already fixed. Can you please try the master branch? Thanks.

**Comment by patrick-frank-bsi** [comment]
Yes you are probably right. When I run my code with the master branch smile version I do not get the NPE anymore. Thanks!

**Comment by patrick-frank-bsi** [comment]
When will smile 2.6.1 be available in Maven Central?
