### ISSUE TITLE
How to encode a new entry in a double array?

### ISSUE THREAD

**Issue by douglasArantes** [haifengl/smile#65]
For example, using the [Car Evaluation Data Set](https://archive.ics.uci.edu/ml/datasets/Car+Evaluation)  of categorical features from UCI ML Repository:

    val atts = new Array[Attribute](6)
    atts(0) = new NominalAttribute("V1")
    atts(1) = new NominalAttribute("V2")
    atts(2) = new NominalAttribute("V3")
    atts(3) = new NominalAttribute("V4")
    atts(4) = new NominalAttribute("V5")
    atts(5) = new NominalAttribute("V6")

    val parser = new DelimitedTextParser()
    parser.setDelimiter(",")
    parser.setResponseIndex(new NominalAttribute("class"), 6)

    val dataset = parser.parse("Test Dataset", atts, "src/main/resources/car.csv")

I'll have the data adequately represented in an `AttributeDataset` with `double[]` internally, so I can train a classifier with the data.

    val data = dataset.toArray(new Array[Array[Double]](dataset.size()))
    val labels = dataset.toArray(new Array[Int](dataset.size()))
    
    val classifier = new DecisionTree(data, labels, 30)

Now, my question is how to make new data entries in a `double[]`, staying in the same format as the AttributeDataset returned by `DelimitedTextParser :: parse(String, Attribute[], String)` method, so I can use it in the   `Classifier:: predict (double [])` method?

    val newData: Array[Double] = // vhigh,vhigh,2,more,small,med,unacc
    classifier.predict(newData)

**Comment by haifengl** [comment]
atts(0).valueOf("abc") will return the double value of a nominal string.

**Comment by douglasArantes** [comment]
Thanks!
