### ISSUE TITLE
Make FeatureTransform invertible

### ISSUE THREAD

**Issue by gciatto-unibo** [haifengl/smile#656]
It may be useful to make subtypes of `smile.feature.FeatureTransform` invertible, meaning that they also support the inverse transformations.
For instance, I may be willing to scale a dataset via an instance of `smile.feature.Scaler` and then scale back some of its rows to the original size.

One simple solution could be to add a `FeatureTransform invert()` method to `smile.feature.FeatureTransform` returning another instance of `smile.feature.FeatureTransform` carrying the inverse transform:
```java
public interface FeatureTransform extends Serializable {
    double[] transform(double[] x);
    default double[][] transform(double[][] data);
    Tuple transform(Tuple x);
    DataFrame transform(DataFrame data);

    FeatureTransform invert(); // new entry here
}
```

This may then imply a method to be added to 4 classes, namely: `MaxAbsScaler`, `Normalizer`, `Standardizer`, and `Scaler`

**Comment by haifengl** [comment]
added

**Comment by gciatto-unibo** [comment]
Have you released a new version containing this feature?

**Comment by haifengl** [comment]
No. We generally don't make a release for a small feature.
