### ISSUE TITLE
Recommended approach to save and restore nominal encoding

### ISSUE THREAD

**Issue by balajisraghavan** [haifengl/smile#657]
I'm building a random forest classifier with purely nominal features. I can factorize the columns, build the model and save it using xstream. But, when I deserialize the model back, the encoding information for nominal attributes that map them to 0..N is lost. 

Is there a recommended way to save and restore nominal attribute encoding data when saving a model? This is using Java 8 btw. This is required to build the model on one machine and execute the evaluation on another.

**Comment by haifengl** [comment]
What's smile version? Can you save the model with java serialization?

**Comment by balajisraghavan** [comment]
I'm using the latest smile version 2.6. Sure I can use Java serialization, if that'll preserve encoding. I thought if we don't save the dataframe, calling the dataframe's factorize during the run for predict would assign different indexes than what was used during training. Is the model alone sufficient to rehydrate encodings at a later date?

**Comment by balajisraghavan** [comment]
There model is to be used in a real time context. During evaluation, I won't have access to the training data. Planning to create a new 1 row dataframe, call factorize and then predict

**Comment by balajisraghavan** [comment]
@haifengl is there a way to save the encoding and run the prediction on another machine?

**Comment by haifengl** [comment]
People has been doing that for long time. You just need to save your model by java serialization.
