### ISSUE TITLE
Index Out Of Bounds Exception in MEC.fit 

### ISSUE THREAD

**Issue by adippold** [haifengl/smile#659]
After upgrading Smile from 1.5.2 to 2.6.0, I noticed that I'm getting Index-Out-of-Bounds exceptions from the MEC clusterer. Having a closer look, I traced it back to a parallel stream operation which is adding elements to an ArrayList, which, by default is not threadsafe. 
	
For me, simply wrapping the ArrayList in a synchronizedList wrapper solved the issue:	

MEC.java, Line 154: List<int[]> neighbors = Collections.synchronizedList( new ArrayList<>() );	

Kind regards,
Andras

**Comment by haifengl** [comment]
Thanks. I fix it in a different way. Please try master branch.

**Comment by adippold** [comment]
Thank you for the swift response. I tried it and it is working well!
