### ISSUE TITLE
Publish smile-scala to Maven

### ISSUE THREAD

**Issue by crockpotveggies** [haifengl/smile#66]
Noticed that smile-core is in Maven central but the Scala API has been left out :(

Can you help turn :( into :) ?

**Comment by haifengl** [comment]
We are still polishing the scala api. We will publish it to maven so. Stay tuned. Thanks!

**Comment by crockpotveggies** [comment]
@haifengl sounds good thanks for the update!

**Comment by haifengl** [comment]
it is there now. Thanks!
