### ISSUE TITLE
Input vector shapes throw unexpected error

### ISSUE THREAD

**Issue by mkffl** [haifengl/smile#662]
I try to fit any model using the Scala API and following the documentation examples. The class constructor throws an error that does not make sense to me, as it suggests that the vectors should have same length. However, if X is an array that contains an (m*n) matrix, then X.length is n and y.size is m, and in most cases m != n. Clearly I am missing something.

I wouldn't expect this particular size check.

Example following the [validation snippet](https://haifengl.github.io/validation.html)

```scala
val x: Array[Array[Double]] = Array(Array(1, 2, 3, 3), Array(4, 3, 3, 5)) 
val y: Array[int] = Array(0,0,1,1)
val model = logit(x, y, 0.1, 0.001)
```

```bash
java.lang.IllegalArgumentException: The sizes of X and Y don't match: 2 != 4
  smile.classification.LogisticRegression.binomial(LogisticRegression.java:359)
  smile.classification.LogisticRegression.fit(LogisticRegression.java:548)
  smile.classification.package$.$anonfun$logit$1(package.scala:268)
  smile.util.package$time$.apply(package.scala:57)
  smile.classification.package$.logit(package.scala:268)
  ammonite.$sess.cmd27$Helper.<init>(cmd27.sc:1)
  ammonite.$sess.cmd27$.<clinit>(cmd27.sc:7)
```

Scala version 2.13.3
smile-scala:2.6.0

**Comment by mkffl** [comment]
Thanks, it works great now. I should have thought about trying this approach.

**Comment by mkffl** [comment]
This is admittedly a new issue/question: can a model output a score? The LogisticRegression model has a score and an applyAsDouble methods but they both return `java.lang.UnsupportedOperationException`.

```scala
val model = LogisticRegression.fit(Xtrain, ytrain, 0.0, 1E-5, 500)
model.score(Xtest(1)) // returns an exception
```
It seems that the [Classifier parent](https://github.com/haifengl/smile/blob/e35d0396ef963da5c177cc5714bb7c7e87182c10/core/src/main/java/smile/classification/Classifier.java) class has an exception placeholder for the score method.

Is there a hack around this? The predict method has a `posteriori` argument referred to as "posteriori probabilities". This is really stretching my little knowledge of java so I struggle to understand what happens in the code.

**Comment by haifengl** [comment]
If you have 5 classes, create an array `posteriori = new double[5]`. Pass it to `predict()`. On the output, it contains the probabillities.

**Comment by mkffl** [comment]
Thanks a lot. `posteriori` seems to be a mutable, temporary storage for predictions that get replaced as I run `predict`against new unseen instances. This approach threw me off at first but it makes sense now. 
Great work on this library, very exciting project!
