### ISSUE TITLE
MathEx.median

### ISSUE THREAD

**Issue by guanmingwu** [haifengl/smile#663]
Thanks for a great package for Java!

Based on this URL, https://en.wikipedia.org/wiki/Median, and R implementation, when the number of observations is even, the mean of the middle two observations is calculated as the median. The implementation in MathEx.median doesn't work like this way.

**Comment by haifengl** [comment]
Our implementation is highly efficient by not fully sorting the data. Therefore we don't calculate the mean of middle two. I don't see any problem in practice so far.
