### ISSUE TITLE
updater funcion

### ISSUE THREAD

**Issue by ramarro123** [haifengl/smile#666]
Hello, i am doing some tests to compare deeplearning4j to smile with a simple MLP scenario.

i wonder if and what hyperparams are supported for the network.

for instance: 
updaters: what is the updaters of MLP used by smile? how can it be configured? i wonder if i can use Adam or Nadam updater.
weightinit: it's possible to configure it using RELU?
activation: it's leakyrelu supported?
 

many thanks!

**Comment by ramarro123** [comment]
also on output layer, the cost seems limited compared to deeplearning to likelihood/meansquarederror, i am right? it' s not possible to use LossMCXENT or any similar?

**Comment by haifengl** [comment]
You can checkout out the unit tests to learn how to use MLP. LossMCXENT is cross entropy, which is a special case of MLE. We support ReLU and leaky ReLU. There are a lot of options that you can set training algorithm.
