### ISSUE TITLE
latest openblas version

### ISSUE THREAD

**Issue by mdavis95** [haifengl/smile#668]
**Is your feature request related to a problem? Please describe.**
We have had issues with openblas / javacpp versions not matching across open source projects.  Specifically it would be nice if smiles javacpp would match deeplearning4j-1.0.0-milestone-1.  Since march smile has been on the version 1.5.5 of javacpp (https://github.com/haifengl/smile/commit/14e17625952c1149f98064b36ada5f1082afc59d) which is the latest version and also a matching version to deeplearning4j.  

**Describe the solution you'd like**
As heavy users of both, it would be great if it wasn't too much trouble to do a release soon to allow us to use the latest version and also a matching version.

**Describe alternatives you've considered**
Compile/use a snapshot release of smile but we have policies against this.

**Additional context**

**Comment by payammeyer** [comment]
+1

**Comment by haifengl** [comment]
We don't make a release just to pump dependency version. We are working on the next major release though. Stay tuned.
