### ISSUE TITLE
Smile update for Java 16 SIMD

### ISSUE THREAD

**Issue by eix128** [haifengl/smile#669]
Hi ,
Java 16 has released Vector API

You can look at the links for details:
https://metebalci.com/blog/what-is-new-in-java-16/
https://openjdk.java.net/jeps/338

Java 16's SIMD API has intrinsic capability.
Much faster then JNI.That directly converts these method calls to ARM NEON or AVX512 , RiscV simd etc..

It will be good to fit smile to new Java 16's Vector API

**Comment by haifengl** [comment]
That feature is far from mature and API is changing across releases. We won't use it in near future.
