### ISSUE TITLE
What's the format of movie.txt?

### ISSUE THREAD

**Issue by crockpotveggies** [haifengl/smile#67]
Really stoked about this library and currently attempting to do a short implementation with Smile.

I was looking at the [NaiveBayesTest.java](https://github.com/haifengl/smile/blob/master/core/src/test/java/smile/classification/NaiveBayesTest.java) file and found the data is being loaded from `movie.txt`. However, I browsed the `data/` folder and couldn't find such a file. Can you share the format of the file so I can better understand the test?

Thanks!

**Comment by haifengl** [comment]
data is the package of class attributes, dataset, parser, etc. It is not the directory of testing data. The testing data is in shell/src/universal/data.

**Comment by crockpotveggies** [comment]
Perfect solves my issue. Thanks :)
