### ISSUE TITLE
ArrayIndexOutOfBoundsException on negative label for svm cross validation

### ISSUE THREAD

**Issue by somebody86** [haifengl/smile#675]
**Describe the bug**
In the svm(LASVM) cross-validation process when using label values +1 -1 we catch an ArrayIndexOutOfBoundsException on fill ConfusionMatrix (when label = -1)

If the value of the labels will be 0 and 1 we catch an IllegalArgumentException from LASVM.java

**Expected behavior**

**Actual behavior**
`matrix[truth[i]][prediction[i]] += 1;`

`java.lang.ArrayIndexOutOfBoundsException: -1
	at smile.validation.metric.ConfusionMatrix.of(ConfusionMatrix.java:61)
	at smile.validation.ClassificationValidation.<init>(ClassificationValidation.java:69)
	at smile.validation.ClassificationValidation.<init>(ClassificationValidation.java:60)
	at smile.validation.ClassificationValidation.of(ClassificationValidation.java:138)
	at smile.validation.ClassificationValidation.of(ClassificationValidation.java:155)
	at smile.validation.CrossValidation.classification(CrossValidation.java:276)`

**Code snippet**
CrossValidation.classification(k, x, y, (x, y) -> {
            LASVM<double[]> lasvm = new LASVM<>(new LinearKernel(), c, tol);
            KernelMachine<double[]> svm = lasvm.fit(x, y);
            return new Classifier<double[]>() {
                final LinearKernelMachine model = LinearKernelMachine.of(svm);
                @Override
                public int predict(double[] x) {
                    return model.f(x) > 0 ? 1 : -1;
                }
            };
        });

**Input data**

**Additional context**
- Which Smile version 2.6.0

**Comment by haifengl** [comment]
ConfusionMatrix expects labels in `[0, k)`. You need to convert `-1` to `0` first.

**Comment by somebody86** [comment]
If I convert -1 to 0 I catch an IllegalArgumentException from LASVM.java 
```
  private boolean process(int i, T x, int y) { 
        if (y != +1 && y != -1) {
            throw new IllegalArgumentException("Invalid label: " + y);
        }
```

**Comment by haifengl** [comment]
All other classifiers expect labels in `[0, k]`. Therefore, `CrossValidation` expects it too. But LASVM expects `{+1, -1}` as it is the right labels for SVM. Currently, one cannot use cross validation with LASVM.
