### ISSUE TITLE
Multivariate Linear Regression (OLS)

### ISSUE THREAD

**Issue by patrick-frank-bsi** [haifengl/smile#676]
I want to use the provided `OLS.fit(Formula.lhs("y"), data)` to predict multiple response variables from multiple features.

Can I modify the `Formula` to make the model accept multiple outputs? Or is there another way to do this?

**Comment by haifengl** [comment]
There is no direct to fit multiple response variables. You may fit each one separately.

**Comment by patrick-frank-bsi** [comment]
I understand, thanks for the reply!

Could be a feature request, but otherwise that ticket can be closed.
