### ISSUE TITLE
documents not fit version 2.6.0

### ISSUE THREAD

**Issue by bingyunxl** [haifengl/smile#678]
import smile.clustering.*;
    import smile.clustering.linkage.*;

    var x = Read.csv("data/clustering/gaussian/six.txt", CSVFormat.DEFAULT.withDelimiter(' ')).toArray();
    var clusters = HierarchicalClustering.fit(CompleteLinkage.of(x));
    Dendrogram.plot(clusters.getTree(), clusters.getHeight()).window();

Dendrogram hasn't plot function

**Comment by haifengl** [comment]
```
Dendrogram plot = new Dendrogram(clusters.getTree(), clusters.getHeight());
plot.canvas().window();
```
