### ISSUE TITLE
Commercial License Usage is vague

### ISSUE THREAD

**Issue by laeubi** [haifengl/smile#679]
https://github.com/haifengl/smile/blob/master/LICENSE mentioned that there is a dual-license model available but does not describes how one could squire a "commercial license", e.g. the https://haifengl.github.io/ does not mentioned it at all nor is there any contact information for such purpose.

So I would suggest to give clear indication who to contact for getting more information and/or acquire such a "commercial license"

**Comment by haifengl** [comment]
Added. Thanks!
