### ISSUE TITLE
Probability of predicted class

### ISSUE THREAD

**Issue by douglasArantes** [haifengl/smile#68]
Is there any way to get the probability of predicted class?

**Comment by haifengl** [comment]
If the class supports SoftClassifier interface, you can use predict(x, prob) to get the posteriori probabilities. The parameter prob is an array of size # of classes. On output, it will hold the probabilities.

**Comment by douglasArantes** [comment]
Thank's.  
Congratulations for the work. Any number related to adoption of Smile? I watched the rise of stars here in github, I intend to soon make a series of posts to divulge this library.

**Comment by haifengl** [comment]
Thanks. I don't have a concrete number how many projects are using it. Given the stars and forks, I guess a lot. BTW, we have a website under construction http://haifengl.github.io/smile/ on various features of smile.

Thanks for divulging it in advance!!

**Comment by dineshdharme** [comment]
@haifengl : Shouldn't the `predict` function which takes Dataframe for RandomForest provide posteriori probabilities as RF is a soft classifier as well as implements DataFrameClassifier? If I need to get posteriori probabilities, how should I get it?
