### ISSUE TITLE
posteriori values returned in incorrect order from DataFrameClassifier.predict

### ISSUE THREAD

**Issue by adippold** [haifengl/smile#680]
When executing DataFrameClassifier.predict( dataFrame, posteriori ), the order of the returned posteriori probabilities does not match the order of the input  records in dataFrame. This makes the resulting posteriori scores unusable.

A closer look revealed that when the DataFrameClassifier.predict method calls the stream() method of DataFrameImpl, it assumes that the order of the records would be kept - but unfortunately the stream() method in DataFrameImpl creates a parallel stream which makes the ordering of elements undeterministic. 

Also: Because of the parallelism  of the stream, one must pass a SynchronizedList as the posteriori argument, otherwise the number of double[] arrays returned in the list could be less than the number of input elements.

I am currently using the master branch on Windows + Java16. 

I fixed the issue locally by disabling 'parallel' in DataFrameImpl.stream(), which solves all problems at once. Furthermore, as a bonus, it reduces the number of extra threads.

Please fix - Thank you.

**Comment by haifengl** [comment]
Fixed. Please try master. No need of `SynchronizedList` too.

**Comment by adippold** [comment]
Thank you, it looks good!
