### ISSUE TITLE
Able to specify an explanatory variable as numerical or categorical

### ISSUE THREAD

**Issue by davidzxc574** [haifengl/smile#698]
**Is your feature request related to a problem? Please describe.**
I have categorical features and would like to include them as expalanatory variables in random forest regression for instance.  

**Describe the solution you'd like**
Can we somehow designate an explanatory variable to be double or categorical variable? Like in R or spark ML.

**Comment by haifengl** [comment]
It is specified in DataFrame. If a column is of NominalScale, it will be treated as categorical.
