### ISSUE TITLE
Java modules

### ISSUE THREAD

**Issue by robertvazan** [haifengl/smile#704]
Please publish smile libraries as [Java modules](https://en.wikipedia.org/wiki/Java_Platform_Module_System). It will make it easier to use smile in downstream libs and apps that are Java modules themselves. Probably the easiest thing to do is to mark smile libraries as [automatic modules](https://stackoverflow.com/questions/46741907/what-is-an-automatic-module).

**Comment by haifengl** [comment]
I set automatic module name to "smile". Try the master branch. Thanks.

**Comment by robertvazan** [comment]
Wouldn't that set the same module name for all libraries published to Maven Central? For example, I am using smile-plot, which should have its own module name, something like `smile.plot`.

**Comment by haifengl** [comment]
It should be fine.

**Comment by robertvazan** [comment]
What do you mean when you say it's fine? I've run smile build and all the JARs contain `Automatic-Module-Name: smile` in their manifests. As I understand it, this will cause duplicate module errors in downstream projects.

**Comment by haifengl** [comment]
It is organized into `smile.base`, `smile.core`, and `smile.plot` modules.

**Comment by robertvazan** [comment]
Now it looks alright. Thank you. I will test only after release, because I don't have working Scala toolchain. Let me know if there are snapshot builds or other easy means of testing.
