### ISSUE TITLE
Integer overflow in hierarchical clustering when number of examples are equal or more than 46,341

### ISSUE THREAD

**Issue by sven-h** [haifengl/smile#707]
**Describe the bug**
I run hierarchical clusterings with a lot of examples and noticed that it does not compute it correctly.
After further analysis I found out that an integer overflow happens internally.
The corresponding line is: [`int length = n * (n+1) / 2;`](https://github.com/haifengl/smile/blob/339139502476bb71c63a96364fbdcd4160aa96fc/core/src/main/java/smile/clustering/linkage/Linkage.java#L156) .
If n is 46,341, then `n * (n+1)` is greater than [2^31-1 (int datatype)](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html). Therefore an integer overflow happens.
I suggest to use `long` troughout the whole function (it is also important to set `n`, `length`, and `k` to type long).
Then the overflow happens when using more than 3,037,000,499 examples which should be enough.

**Expected behavior**
Not overflow happening.

**Actual behavior**
`java.lang.NegativeArraySizeException` in case of choosing 46,341.
When using 65,536 then the calculation `n * (n+1)` is again positive and the overflow is undiscovered but the calculations are wrong.

**Code snippet**

```java
double[][] data = new double[46341][2];
        
int n = data.length;
int length = n * (n+1) / 2;
System.out.println(length);

//fill with random values
Random rnd = new Random(1234);
for (int i = 0; i < data.length; i++) {
    for (int j = 0; j < data[i].length; j++) {
        data[i][j] = rnd.nextDouble();
    }
}

//this call is also executed when running e.g. SingleLinkage.of(data)
float[] prox = Linkage.proximity(data);
```

**Comment by haifengl** [comment]
Thanks. It won't solve the problem by changing to long. Java array size is up to only Integer.MAX_VALUE. The array allocation will fail anyway for large data set.

**Comment by sven-h** [comment]
Yes, that is true.
If the number of examples are above 65535, the array generation is not possible anymore.

**Comment by haifengl** [comment]
I made some changes so that it works with up to 65535 rows. Please try master branch.
