### ISSUE TITLE
how to use spark dataframe in DBSCAN for spark and scala?

### ISSUE THREAD

**Issue by simonshiwt** [haifengl/smile#718]
i find that DBSCAN can handle the data type of  Array[Array[Double]],  but that can not support billions of data, so i what to know how to use dataframe(or RDD) when i  use DBSCAN in spark and scala, so that i can  handle data parallel .
thank you!

**Comment by haifengl** [comment]
The speed is determined by nearest neighbor search. Dataframe won't make it faster.

**Comment by simonshiwt** [comment]
get it .thank you for your contribution！
