### ISSUE TITLE
1.1.0

### ISSUE THREAD

**Issue by cranst0n** [haifengl/smile#72]
Seems as though 1.1.0 isn't showing up in [Maven](http://mvnrepository.com/artifact/com.github.haifengl).

**Comment by haifengl** [comment]
It was published yesterday and it shows that staging was successful. But it may take a couple of days to fully visible. Let's wait a little bit. Thanks!

**Comment by haifengl** [comment]
Meanwhile, you can download the prebuilt packages to try out the new shell and scala api. Thanks!

**Comment by haifengl** [comment]
Finally it shows up in the central maven. Have a try. Thanks!

**Comment by douglasArantes** [comment]
Very good, i also liked the introduction of SoftClassifier interface.

Do you have any idea in mind about the next features to be introduced in the project?

**Comment by haifengl** [comment]
We will expose more API to scala in short terms. Other enhancements are listed in this issues panel. Thanks!
