### ISSUE TITLE
ICA example request

### ISSUE THREAD

**Issue by LeXing1105** [haifengl/smile#730]
**Describe the bug**
I am creating a simulated multiple-channel EEG signal using random numbers, which has an array size of 'double[32][1250]' in Java. 

I want to use the ICA algorithm for computing the Independent Components for a quick test on Android Studio for smartphones. When I use the 'ICA' class, the results were all zeros, nothing comes out. 

**Expected behavior**
I would expect the algorithm can output 32 independent components, the same data size as the input.

**Actual behavior**
However, the results are wrong!  

Could you please help me with debugging or show me an example of how to use the code correctly? Your Java library is very good, the programming styles are easy to understand. Thank you very much if you could reply or help! Attached is my code.

<img width="498" alt="Capture" src="https://user-images.githubusercontent.com/73104004/207850229-9a9e6ba5-7a4d-40c8-ba07-ac8f82575575.PNG">

**Comment by LeXing1105** [comment]
double[][] ICA_results = new double[32][250*5];

ICA_results is an empty array, What I understand is: the ICA will return and store the ICs to the 'ICA_results' array

**Comment by haifengl** [comment]
Your code is wrong. ICA.fit is a static method and it returns the model. You should do something like

```
ICA model = ICA.fit(data, 32, ...);
double[][] ica_results = ice.components;
```

**Comment by haifengl** [comment]
See the example in https://github.com/haifengl/smile/blob/master/base/src/test/java/smile/ica/ICATest.java

**Comment by haifengl** [comment]
Note that you should build the master branch to use latest ICA. If it works as you expect, I will make a new release so that you can get it from maven.

**Comment by LeXing1105** [comment]
@haifengl Sir, thank you very much for your reply and example! Now I have changed the code a bit as you said, but something is still wrong here, making the program crash! I am using 'smile-base-3.0.0', by using 
Gradle: implementation 'com.github.haifengl:smile-core:3.0.0'

(The library imported is shown on the left of the screenshot)

<img width="963" alt="Capture" src="https://user-images.githubusercontent.com/73104004/208306178-34e7eab7-e4a7-4e44-8f1e-245180b9819e.PNG">

1. I simply simulated data, 32 rows, 1250 columns, (32*1250); so the expected number of components was set as 32 too;
2. I am not sure if I use the "public static ICA fit(double[][] data, int p, DifferentiableFunction contrast, double tol, int maxIter)" correctly? The 5 parameters;
3. Is my code still wrong? Or there are some differences between Java IDE and Android Studio, the platform issues?
4. My aim is just to calculate the ICA's processing time on a phone. 

Do you have any ideas for this issue? Your help will be highly appreciated! 

Best wishes,
Le

**Comment by haifengl** [comment]
Can you share the error message and stack trace?

**Comment by LeXing1105** [comment]
Thank you for coming back to me!

In my Android App, I click the button to execute the ICA algorithm, and then the App crashes, the error message and stack trace is attached here. 

<img width="962" alt="error message" src="https://user-images.githubusercontent.com/73104004/208922788-4b97467d-99ec-4846-997c-0f7c1571afed.PNG">

**Comment by haifengl** [comment]
You should add following libraries

```
libraryDependencies ++= Seq(
      "org.bytedeco" % "javacpp"   % "1.5.8"        classifier "android-arm64"
      "org.bytedeco" % "openblas"  % "0.3.21-1.5.8" classifier "android-arm64"
    )
```

**Comment by LeXing1105** [comment]
Hi Sir, I added the implementations to Gradle, like the attached screenshot, and then ran the program, but it still crashed. In Android, I cannot add libraries as you showed me, need to use gradle / maven.

Error message: Caused by: java.lang.UnsatisfiedLinkError: Could not find jniopenblas_nolapack in class, module, and library paths. What's the problem this time? Thank you for your help!

<img width="427" alt="gradle" src="https://user-images.githubusercontent.com/73104004/208954223-5b8a5808-e07d-49e2-9b26-ac6097b2788e.PNG">
<img width="959" alt="error2" src="https://user-images.githubusercontent.com/73104004/208954243-6f640cc8-6c8e-40fe-9a08-d8b078870a39.PNG">

**Comment by saudet** [comment]
If you're building Android App Bundles (AAB files), the Android plugin doesn't support native libraries in JAR files. We can use the Platform Plugin from Gradle JavaCPP to work around that though: https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by LeXing1105** [comment]
@saudet Perfect! problem solved! The program is working very well now, after adding the JavaCPP libraries as you said. Thank you very much for your help!

Also, thank you again for your help! @haifengl

Merry Christmas to both of you!!! :)
