### ISSUE TITLE
License changes from 2.6 to v3.0?

### ISSUE THREAD

**Issue by Ant-Phillips** [haifengl/smile#731]
Looking for some clarity on SmileML licensing.

Versions up to and including v2.6 have a license which includes LGPL. Starting with v3.0 it appears LGPL has been removed. Some commercial organisations are happy to include LGPL software, others not so much.

Confusingly I don't see any mention of this in the release notes (maybe I missed this?) and the v3.0 source distribution continues to contain a file referencing LGPL (COPYING.LESSER).

The JARs on Maven Central don't include the licensing information but these files are in the releases here:
https://github.com/haifengl/smile/releases

Here is the pertinent section of the v2.6 LICENSE file which makes it available under LGPL:

GNU Lesser General Public License Usage
  SMILE may be used under the terms of the GNU Lesser General Public
  License version 3 as published by the Free Software Foundation and
  appearing in the file COPYING.LESSER included in the Software.
  In order to preserve the true meaning of open development and uphold
  the spirit of free software, it is imperative that the rules and
  regulations of open source licenses required by the Free Software
  Foundation are followed. Learn more: http://www.gnu.org/licenses.

And then a more restrictive LICENSE file in v3.0 which says that any commercial usage must have a commercial agreement with some new organisation called SMILE.AI:

Commercial License Usage
  OEMs (Original Equipment Manufacturers), ISVs (Independent Software
  Vendors), VARs (Value Added Resellers) and other distributors that
  combine and distribute commercially licensed software with SMILE
  must enter into a commercial license agreement with SMILE.AI, LLC.

There is also the broader issue of the existing software which is part of v2.6 was available under a LGPL and therefore attempting to re-license that software under more restrictive terms would seem highly questionable.

**Comment by Ant-Phillips** [comment]
Looking back at the previous five releases I see the following:

v3.0 Dec 15, 2022
GNU General Public License (GPL)
Non GPL commercial licence available from SMILE.AI, LLC

v2.6 Dec 5, 2020
GNU Lesser General Public License (LGPL)
Non LGPL commercial licence available from SMILE.AI, LLC

v2.5.3 Sep 19, 2020
GNU Lesser General Public License (LGPL)
Non LGPL commercial licence available from SMILE.AI, LLC

v2.4 Apr 30, 2020
GNU Lesser General Public License (LGPL)
Non LGPL commercial licence available from SMILE.AI, LLC

v2.3 Apr 1, 2020
GNU Lesser General Public License (LGPL)
Non LGPL commercial licence available from SMILE.AI, LLC

As far as I can see these are documented in the LICENSE file not the README.

So the change is with the latest v3.0 release and it's change of license from LGPL to GPL which means that commercial organisations who cannot use GPL software and want to use Smile v3.0 and later must pay for a commercial license.

**Comment by awb99** [comment]
Hi @haifengl I want to let you know of something that happened when you switched from LGPL to GPL.
The clojure wrappers fastmath-clustering and scicloj-ml decided to drop support for smile, because they 
dont want to make their libraries available as GPL. I completely understand, that smile also needs to have 
commercial model; I just want to highlight that this switch resulted that some open source projects 
now no longer support smile.  Thanks.
