### ISSUE TITLE
Imports unresolved

### ISSUE THREAD

**Issue by ceecer1** [haifengl/smile#734]
Showing error on imports:
import smile.data.{Attribute, AttributeDataset, NumericAttribute}

Environment details:
- OpenJDK 17
- Scala 2.13.10
- Smile 3.0.0 core and scala
- Intellij
- MacOS

**Comment by DmytroMitin** [comment]
https://stackoverflow.com/questions/75398344/unresolved-imports-in-smile-machine-learning-library

**Comment by ceecer1** [comment]
[error]   not found: https://repo1.maven.org/maven2/com/github/haifengl/smile-plot_2.13/3.0.0/smile-plot_2.13-3.0.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/github/haifengl/smile-plot_2.13/3.0.0/smile-plot_2.13-3.0.0.pom

**Comment by ceecer1** [comment]
smile-plot is unresolved for version 3.0.0

**Comment by DmytroMitin** [comment]
@ceecer1 https://repo1.maven.org/maven2/com/github/haifengl/smile-plot/3.0.0/
Replace `%%` with `%`

**Comment by ceecer1** [comment]
Thanks bummer! I didn't notice that.
