### ISSUE TITLE
Can't merge 2 KMeans clustering trained models calculated in different locations in codes

### ISSUE THREAD

**Issue by ceecer1** [haifengl/smile#735]
val model1 = KMeans.fit(data1.x(), 3)

val model2 = KMeans.fit(data2.x(), 3)

How to merge this 2 models ? model1 and model2

Environment details:

OpenJDK 17
Scala 2.13.10
Smile 3.0.0 core and scala
Intellij
MacOS

**Comment by haifengl** [comment]
No such functionality. If you just want a union of centroids, you can do it by yourself as `model.centroids` is just an array.
