### ISSUE TITLE
404 error when accessing the kotlin api documentation in the project website

### ISSUE THREAD

**Issue by migueldoctor** [haifengl/smile#738]
**Describe the bug**
When trying to access the kotlin api documentation from the menu of the website (https://haifengl.github.io/api/kotlin/smile-kotlin/index.html) it shows a 404 error

**Expected behavior**
The user should be redirected to the kotlin API documentation.

**Actual behavior**
The web site displays  a 404 page

**Code snippet**
NA

**Input data**
NA

**Additional context**
NA

**Comment by haifengl** [comment]
Fixed. This was caused by new layout of kotlin doc generation. Thanks for reporting!
