### ISSUE TITLE
rbf kernel?

### ISSUE THREAD

**Issue by achuinard** [haifengl/smile#741]
I'm using your very useful SVR, porting a project over from Python / scikit-learn, but I notice their default kernel is 'rbf', and I see no mention of an rbf kernel in the Smile source code. Is this available? I'm using linear right now.

**Comment by haifengl** [comment]
It is called [GaussianKernel](http://haifengl.github.io/api/java/smile/math/kernel/GaussianKernel.html)

**Comment by achuinard** [comment]
@haifengl I really appreciate you following up here. I am trying to use the GaussianKernel now instead of the Linear one, but the results are terrible.

I have no idea what to set for sigma. My understanding is that scikit-learn calculates a gamma value as 1 / num_features.

What would I set the sigma to in Java?

**Comment by haifengl** [comment]
`gamma = 1 / (2 * sigma * sigma)`
