### ISSUE TITLE
Tree Representation for Regression Models in Google Earth Engine

### ISSUE THREAD

**Issue by thomaslauber** [haifengl/smile#744]
I am a researcher that works extensively with Google Earth Engine (GEE) and smile made a huge contribution to my work and to the work of many others! Thanks so much for that! 

Currently, I am working on implementing a python package that will download a tree-based model trained in GEE and fully replicate it in sklearn, which will allow researchers to compute SHAP values locally and help better understand the model's behaviour. 
I am in contact with Noel Gorelick, the chief software engineer at GEE, and we thought this could be a very valuable contribution. 

So far, the package works fine for Random Forests and a Decision Trees in Classification mode thanks to the (I think) compressed order representation. Is there a way to include this representation in the [Regression Tree](https://github.com/haifengl/smile/blob/v1/core/src/main/java/smile/regression/RegressionTree.java#L1281) as well? 
So, the ideal solution would be if the Regression Models would behave in the exact same way as the Classification models. 
This would be needed to be implemented in V1 of smile, which seems to be the current version GEE is using.

Here attached some screenshots that hopefully visually explain the problem: 

Output of a Classification Tree in GEE: 
![image](https://github.com/haifengl/smile/assets/48925137/1f4e1008-8e7b-4cc7-be8a-6e8655fd5e03)
(one can see the tree representation at the bottom)

Output of a Random Forest in Classification mode: 
![image](https://github.com/haifengl/smile/assets/48925137/4c66256b-84da-4a8d-9c93-b5cc11e1c6e6)
(one can see the tree representation at the bottom for both trees inside the forest)

Output of a Regression Tree in GEE:
![image](https://github.com/haifengl/smile/assets/48925137/3b8be07a-804f-4b31-9735-2f95d4fb043a)
(one can see there is no tree representation)

Output of a Random Forest in Regression mode: 
![image](https://github.com/haifengl/smile/assets/48925137/775d45aa-3497-443b-8466-04aa51a6c252)
(also here, there is no tree representation)

**Comment by lihaife** [comment]
Thanks. Smile v2+ already supports tree representation in compact text and graphviz format for both classification and regression trees.
