### ISSUE TITLE
Takes more memory for LSH model in NearestNeighborSearch

### ISSUE THREAD

**Issue by manju22412** [haifengl/smile#745]
I am using lsh nearest neighbors, it takes around 86mb for model storage by training with 20000 records.
Is there any way to reduce the sze..?

Can anyone please reply on the above issue please..

**Comment by manju22412** [comment]
can anyone reply on the above issue please..

**Comment by haifengl** [comment]
Multi probe LSH uses more memory by design. If memory is a concern, try plain LSH.

**Comment by manju22412** [comment]
i got this issue when i tried with plain LSH only..

**Comment by haifengl** [comment]
Your inference data vector size is different from training data's.

**Comment by manju22412** [comment]
i have used the libsvm format for training and inferencing. And getting output for only few cases and remaining it shows error like "Input vector sizes are different". When i try to pass the value other than 1017881 on below line, same error was displaying..

LSH<double[]> lsh = new LSH<>(x, x, 4.0, 1017881);

**Comment by haifengl** [comment]
The parameter w (1017881) is nothing to do with your data vector size.

**Comment by manju22412** [comment]
but, it is issue now..
