### ISSUE TITLE
Make it clearer what Smile is on the front page of http://haifengl.github.io/smile/index.html

### ISSUE THREAD

**Issue by alexeyr** [haifengl/smile#75]
It says "Smile is a fast and comprehensive machine learning system" and "The most complete machine learning engine". Both might bring to mind a framework rather than a library. I think "Smile is a fast and comprehensive machine learning system" can be usefully replaced by the first sentence of the README ("Smile (Statistical Machine Intelligence and Learning Engine) is a set of pure Java libraries of various state-of-art machine learning algorithms.").

**Comment by haifengl** [comment]
Smile has scala api and shell now. It is not just Java libraries any longer. And we will add web services etc.
