### ISSUE TITLE
FR: Compact "how to load dirty data" example

### ISSUE THREAD

**Issue by salamanders** [haifengl/smile#750]
arff format is great!  But for those of us dealing with crappy inputs, it might be helpful to have an example:

* For a CSV file
* With a header row
* And some extra lines at the end
* And some blanks
* And some Strings
* And some of the Strings are "T/F" and "Y/N"
* And some strings need splitting

What is the best (shortest?) path to a working RandomForest?

**Comment by haifengl** [comment]
There are test cases using csv files. you may search csv in code base.
