### ISSUE TITLE
BarPlot.getUpperBound() computes wrong bound.

### ISSUE THREAD

**Issue by pfeiferd** [haifengl/smile#752]
This is the fix (">" should be "<") - good luck!   

 @Override
    public double[] getUpperBound() {
        double[] bound = MathEx.colMax(bars[0].data);
        bound[0] += bars[0].width / 2;

        for (int k = 1; k < bars.length; k++) {
            for (double[] x : bars[k].data) {
                if (bound[0] < x[0] + bars[k].width / 2) {
                    bound[0] = x[0] + bars[k].width / 2;
                }
                if (bound[1] < x[1]) {
                    bound[1] = x[1];
                }
            }
        }

        return bound;
    }

**Comment by haifengl** [comment]
Thanks. Fixed.
