### ISSUE TITLE
HiddenLayerBuilder does not add dropout to HiddenLayer

### ISSUE THREAD

**Issue by hewitta** [haifengl/smile#759]
**Describe the bug**
The HiddenLayerBuilder class does not pass the dropout rate to the HiddenLayer with the build method

**Expected behavior**
Using Layer class .of method and specifying layers "input(50, 0.2)|relu(50, 0.2)" should apply 0.2 dropout to each layer

**Actual behavior**
The dropout rate is applied to the input layer but no subsequent layers

**Code snippet**
The code to reproduce the behavior.

**Input data**
The sample data

**Additional context**
- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version - OpenJDK 19.0.1
- Which Smile version - 3.0.1
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) - Windows
- Add any other context about the problem here.

**Comment by haifengl** [comment]
Hi, it is by design. Each layer may specify its own dropout rate.

**Comment by hewitta** [comment]
Yes, but even when the the hidden layer builder has a specified dropout rate it doesn't seem to pass from the HiddenLayerBuilder to the HiddenLayer. The build function from the HiddenLayerBuilder reads:

public HiddenLayer build(int p) {
        return new HiddenLayer(neurons, p, activation);
    }

**Comment by haifengl** [comment]
Fixed. Thanks for reporting.

**Comment by hewitta** [comment]
Thank you much!
