### ISSUE TITLE
Imputation of mixed data type

### ISSUE THREAD

**Issue by mohdbilal87** [haifengl/smile#76]
The imputation methods supports numeric data matrices. What is there are multiple categorical attributes in the data?

**Comment by haifengl** [comment]
It is not supported. Are you aware of good algorithms for that case? Thanks!

**Comment by mohdbilal87** [comment]
Sorry for the typos in the initial comment.
Two methods come to my mind which I have explored recently:

1) The generalized low rank method by (Madeleine Udell, Corinne Horn, Reza Zadeh, Stephen Boyd). 
Link: http://arxiv.org/abs/1410.0342.
It essentially is representation of data matrix in low dimension while simultaneously imputing the missing values, something similar to **softImpute ** method (by Hastie and Mazumder). However the latter works only for numeric data.
The GLRM on the other hand deals with numeric, Boolean, ordinal and categorical data types. This has several existing implementations as follows:
    a) Implementation in h20: http://learn.h2o.ai/content/tutorials/glrm/glrm-tutorial.html
    b) Implementation in python(by one of the co-author): https://github.com/cehorn/GLRM
    c) Implementation in spark(by another co-author):: https://github.com/rezazadeh/spark/tree/glrm/examples/src/main/scala/org/apache/spark/examples/glrm
    d) Implementation in julia(by the lead co-author): https://github.com/madeleineudell/LowRankModels.jl

2) The second method is not imputation itself but rather numerical coding of categorical data. Perhaps after such conversion, traditional methods of numeric data imputation could be applied. I have not tried this method yet.
Link: http://zeszyty-naukowe.wwsi.edu.pl/zeszyty/zeszyt12/Numerical_Coding_of_Nominal_Data.pdf
This one is quite recent. An arxiv print came out in early 2016.

**Comment by haifengl** [comment]
Thanks! Would like like to implement GLRM in smile?

**Comment by mohdbilal87** [comment]
I can definitely try. But I don't have experience in Scala. I work mostly in R and occasionally in python. If you don't have any problem with me having a slower pace than your usual turnaround time I surely will love to implement this in scala.

**Comment by haifengl** [comment]
Thank you very much! Most algorithms are implemented in Java. If you are familiar with Java, it is easy to start. If you prefer scala, it is also very welcome. Don't worry about turnaround time.
