### ISSUE TITLE
Making the plot module available in Java API

### ISSUE THREAD

**Issue by DiptenduIDEAS** [haifengl/smile#761]
The plot module that supports declarative visualizations via Vega-lite is currently available in the Scala API
https://haifengl.github.io/api/scala/smile/plot/index.html

However, it is not available in the Java API.

Any plans to support this anytime soon?

**Comment by haifengl** [comment]
It is added in `smile.plot.vega` package in smile-plot module. See [VegaTest](https://github.com/haifengl/smile/blob/master/plot/src/test/java/smile/plot/vega/VegaTest.java) for some example usage. Please play with it and provide feedback and bug reports. Thanks!

**Comment by DiptenduIDEAS** [comment]
Thanks for the immediate response. Shall use the functionality and give
feedback.

**Comment by haifengl** [comment]
3.1 is released with the Java API for declarative visualizations.
