### ISSUE TITLE
Incorrect spec generated for encoding channel sort

### ISSUE THREAD

**Issue by markuspeters** [haifengl/smile#764]
In smile-scala 3.1.0 this:

```
VegaLite.facet(
  jsan"""[
    {"day": "Wednesday", "v": 28},
    {"day": "Monday", "v": 55},
    {"day": "Tuesday", "v": 66}
  ]""").
  mark("rect").
  x(field = "day", `type` = "nominal", 
    sort = Some("""["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]""")).
  y(field = "v", `type` = "ordinal")
```

is converted to the following encoding channel spec:

```
"x": {
  "field": "day",
  "sort": "[\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\"]",
  "type": "nominal"
}
```

The escaped JsString for `sort` in the spec above should instead be a JsArray of JsStrings, i.e.:

```
  "sort": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
```

I'll be happy to try submit a PR if that seems useful.

**Comment by haifengl** [comment]
`sort` is currently `Option[String]`. In this case, you want to pass an array. We may need to chnage `sort` to Option[JsValue]`. Yes, your PR is very welcome. Thanks!

**Comment by haifengl** [comment]
I have revised the API to take `JsValue` for `sort` and a few other simplifications. Will push to master soon.

**Comment by markuspeters** [comment]
Thank you for handling this, I appreciate the quick change!

**Comment by haifengl** [comment]
Note that we remove unnecessary factory methods taking data parameter. `VegaLite.view()/facet()` now take optional `title` parameter. Call `data()` methods to specify data source or inline data.
