### ISSUE TITLE
How can I set up in Intellij or other IDE to compile and read code?

### ISSUE THREAD

**Issue by sluk3r** [haifengl/smile#765]
Hi， How can I set up in Intellij or other IDE to compile and read code?

**Comment by haifengl** [comment]
Simply import the project to Intellij or Eclipse should work. Make sure you have SBT plugin installed.

**Comment by sluk3r** [comment]
> Simply import the project to Intellij or Eclipse should work. Make sure you have SBT plugin installed.

Thanks for your help. 

As for specific SBT plugin, two plugins are found: 
1. https://plugins.jetbrains.com/plugin/5007-sbt/versions#tabs
2. https://plugins.jetbrains.com/plugin/7247-sbt-executor

it seems that the first one (https://plugins.jetbrains.com/plugin/5007-sbt/versions#tabs)  is not compatible new version IntelliJ, only compatible 15.0 — 2016.3.8, the second plugin(https://plugins.jetbrains.com/plugin/7247-sbt-executor) does not work. 

@haifengl more help needed, Thanks

**Comment by haifengl** [comment]
`Scala` plugin works.
