### ISSUE TITLE
Problems with project missing slf4j 

### ISSUE THREAD

**Issue by andrewpalumbo** [haifengl/smile#77]
Hello @haifengl, this is a very impressive project, I have been investigating integration of some parts of it with Apache Mahout, but have been running into some problems. 

I can't get it to build from the command line just to test out seemingly because there is no slf4j artifact in the `pom.xml` or `build.sbt`. I've tried adding:  
    
```
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
```

along with other slf4j artifacts but it doesn't seem to help.

**EDIT**: My other issue was a configuration error on my end,  I've deleted it.  Apologies.

**Comment by haifengl** [comment]
Pom.xml files are deprecated. We are using sbt now. Sorry for confusion.

I am on vacation. I will investigate the second problem when I am back.

**Comment by andrewpalumbo** [comment]
@haifengl thank you for yor response.  The second problem turned out to be a configuration error on my end (I had not added the classes to a assembly fIle where they were required).  I've updated the thread to reflect this.  Thanks alot.  Have a good vacation.

**Comment by haifengl** [comment]
I have removed pom.xml files. Please use sbt for building. Thanks! You will need to setup SBT PGP plugin. Please refer #78 for details. Thanks!

**Comment by andrewpalumbo** [comment]
Thank you very much for your answers @haifengl ,  I've followed your instructions on #78, and Smile is building without issue for me.   

We've begun (very basic so far) integration of `smile-plot` with Apache Mahout for use in plotting sampled data-points from Distributed Row Matrices, and it is going very well, the plots from this library are great!  Thank you very much.
