### ISSUE TITLE
Is there any possibility to use ID3 or C4.5 via the Smile Package in Java?

### ISSUE THREAD

**Issue by seedorf93** [haifengl/smile#770]
Hi, sorry I don't have enough reputation on stackoverflow to create the tag "smile-ai":

 I want to dive a bit deeper in Smile/Java, specifying the algorithms or other rules in this ML-package for decision trees in java. I can't find how to do it:

https://haifengl.github.io/api/java/smile/classification/DecisionTree.html

Can anyone help me out? Is there any support for ID3 or C4.5? Thanks in advance

**Comment by haili-equinix** [comment]
You can see some examples [here](https://github.com/haifengl/smile/blob/master/core/src/test/java/smile/classification/DecisionTreeTest.java).
