### ISSUE TITLE
sbt error "not found: value useGpg" when running 'pkg.sh'

### ISSUE THREAD

**Issue by AndreiBarsan** [haifengl/smile#78]
I am on OSX 10.10.5, trying to build smile from source using the 'pkg.sh' helper script, as suggested in the [quick start guide][1].

My version info:
 * sbt: stable 0.13.11
 * java: "1.8.0_51", 64-Bit Server VM (build 25.51-b03, mixed mode)
 * scala: 2.11.8

However, while running the build script, I get the following error?

```
[info] Loading project definition from /Users/andrei/workspace/smile/project
/Users/andrei/workspace/smile/build.sbt:3: error: object pgp is not a member of package com.typesafe.sbt
import com.typesafe.sbt.pgp.PgpKeys.{useGpg, publishSigned, publishLocalSigned}
                        ^
/Users/andrei/workspace/smile/build.sbt:27: error: not found: value useGpg
  useGpg := true,
  ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

I've tried searching GitHub and StackOverflow, but I didn't find anything that seemed relevant to this use case. Any pointers?

[1]: https://haifengl.github.io/smile/index.html#quickstart

**Comment by haifengl** [comment]
Sorry for misleading. You should use smile.sh script. Pkg.sh is for me to publish the project. I will update the webpage.

**Comment by AndreiBarsan** [comment]
Thanks for the reply! I also tried using `smile.sh` (even on a fresh clone), and I still get basically the same error:

```
$ ./smile.sh
[info] Loading project definition from /Users/andrei/workspace/smile/project
[info] Updating {file:/Users/andrei/workspace/smile/project/}smile-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
/Users/andrei/workspace/smile/build.sbt:3: error: object pgp is not a member of package com.typesafe.sbt
import com.typesafe.sbt.pgp.PgpKeys.{useGpg, publishSigned, publishLocalSigned}
                        ^
/Users/andrei/workspace/smile/build.sbt:27: error: not found: value useGpg
  useGpg := true,
  ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by haifengl** [comment]
I am on vacation right now and cannot provide detailed info of pgp plugin setup. Sorry.

Currently the easiest way for you is probably to remove line 3 and 27 in the build.sbt file.

**Comment by AndreiBarsan** [comment]
Oh, no rush. I was able to add Smile as a Maven dependency to my Scala project and everything is in order. Building the toolkit from scratch was just an add-on activity for me. Thank you for your replies!

**Comment by haifengl** [comment]
PGP settings for SBT is per user, not per project. So I cannot add it here. But it is very easy to setup it. You can follow the instruction at

http://www.scala-sbt.org/sbt-pgp/

I assume that you are using the latest sbt. So basically add the following to your ~/.sbt/0.13/plugins/gpg.sbt file:

addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")

**Comment by haifengl** [comment]
I make this plugin dependency local now. Hopefully you don't need to configure it by yourself any more.
