### ISSUE TITLE
DataFrame为什么提供那么多功能类似的接口

### ISSUE THREAD

**Issue by Yee-Zone** [haifengl/smile#783]
DataFrame为什么提供那么多功能类似的接口？
比如column和apply，还有getXXX各种数据类型的接口。。
这些能否优化一下，虽然这可能是无关紧要的事，但希望有更简洁数据操作方式。
如果这些都是必要的接口，那就忽略我这个请求。

**Comment by haifengl** [comment]
Apply is a helper function for scala so that you can do df(“column name”), which is same as df.column(“column name”) in Java. Because Java is strong typed, we have to use getXXX to distinguish the return type when get a field value.

**Comment by Yee-Zone** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
