### ISSUE TITLE
Make RandomForest (and ideally all classifiers) serializable 

### ISSUE THREAD

**Issue by quertenmont** [haifengl/smile#79]
Dear Authors,

I am discovering your framework and I find it extremely convenient and powerful
However, I am facing an issue related to the classifiers (and in particular the RandomForest) not being serializable.  I would like to run a large number of random forest on a computing cluster and save/retrieve back the trained forest, but to do so I need the object to implement serializable 

Can you think about fixing this?

Thanks,
Loic

**Comment by haifengl** [comment]
Please use our scala api write() to save any models. Later you can read it back by read(). Under the hood, we use XStream to serialize the models.  Please checkout the [FAQ](http://haifengl.github.io/smile/index.html#faq), which has a section on model serialization.

**Comment by quertenmont** [comment]
yes, I found the faq right after posting (sorry).
However, i am running with spark and it would be convenient not to save the model on disk but keeping simply keeping it in memory.  I switched to Kryo serializer in spark instead of default java serializer and that seems to work (it's just a bit less efficient).

**Comment by haifengl** [comment]
I see. So it is preferred to use Java serialization in spark? Originally we make all models support Serializable interface. But it also have many issues as we discuss in the readme. So we removed that support later. But if there is a need, we definitely can add it back.

**Comment by quertenmont** [comment]
yes...
Eventually adding a wrapper class would be an intermediate solution.
It might be enough to add a wrapper that implement serializable in the scala smile.io.package ?

**Comment by haifengl** [comment]
How about [scala pickling](https://github.com/scala/pickling)?

**Comment by haifengl** [comment]
I have enabled all classifiers with Serializable

https://github.com/haifengl/smile/commit/d627d3a6efab668ad498f370c5c781ec41a218e1

To use it, you need build by yourself. If everything is fine, we can release a new version.

**Comment by quertenmont** [comment]
Thanks!

2016-05-19 21:30 GMT+02:00 Haifeng Li <notifications@github.com>:

> I have enabled all classifiers with Serializable
>
> d627d3a
> <https://github.com/haifengl/smile/commit/d627d3a6efab668ad498f370c5c781ec41a218e1>
>
> To use it, you need build by yourself. If everything is fine, we can
> release a new version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/haifengl/smile/issues/79#issuecomment-220426884>
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by stuz5000** [comment]
I'm also interested this.

However a new release with this hasn't been published yet. I was hoping that I could make my sbt depend on the active master here on github. However, this [doesn't seem straightforward](http://stackoverflow.com/questions/38907340/sbt-how-to-depend-on-sub-module-of-a-git-project).

Until then, 
- is there a way to serialize directly to memory (smile.io.write saves to file -- which is no good for many applications, including spark), or
- is there a way to get sbt to build to master, or
- can we get a new release
?

**Comment by haifengl** [comment]
I will release 1.2 to include this soon.

**Comment by haifengl** [comment]
@stuz5000 and @quertenmont:  smile 1.2 is just released with these changes. please have a try. thanks!

**Comment by stuz5000** [comment]
Wonderful. Thank you

**Comment by purnendu23** [comment]
Hello,
This is helpful. Are all the models now serializable? I am using gbm. 

thanks,
purnendu

**Comment by haifengl** [comment]
yes, all models are serializable.
