### ISSUE TITLE
library "libjniopenblas_nolapack.so" not found

### ISSUE THREAD

**Issue by KirillFPV** [haifengl/smile#794]
Hello everyone, I'm trying to embed mlp into the andrpid app on kotlin. An error appears when trying to compile:
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniopenblas_nolapack.so" not found

use smile-kotlin v4.0.0

```
val layers = arrayOf(Layer.input(2), Layer.sigmoid(10), Layer.mle(1, OutputFunction.SOFTMAX))
val model = mlp(features, labels, layers)
```

macos (m1 chip), Android Studio

Please help, I've already tried many options, but nothing helped

**Comment by haifengl** [comment]
try add the following to your project
```
            <groupId>org.bytedeco</groupId>
            <artifactId>openblas-platform</artifactId>
            <version>0.3.28-1.5.11</version>
```

**Comment by KirillFPV** [comment]
Thank you
