### ISSUE TITLE
Model update from Smile 2.6.0 to 4.0.0

### ISSUE THREAD

**Issue by kellox** [haifengl/smile#798]
I've a question about best practices of updating Smile models from an older version to a newer version (in my case from 2.6.0 to 4.0.0).

I'm currently using Smile 2.6.0 in multiple projects. All models were persisted using Java serialization.
When trying to upgrade to the latest Smile 4.0.0 version, I noticed that some of the classes have been changed (completely). Therefore, the models serialized with 2.6.0 cannot be deserialized with 4.0.0, e.g. smile.projection.PCA (in 2.6.0) was moved to smile.feature.extraction.PCA (in 4..0.0), so compatibility is broken due to the package name refactoring.

My question is: **What are the recommended best practices to update models from Smile 2.6.0 to version 4.0.0 or latest version in general**? Retraining is unfortunately not an option.

I could think of the following approach:
1. Deserialize all persisted models with Smile 2.6.0 and serialize them with Xstream to have textual representation of the model which could make the migration a little bit easier.
2. Update Smile to 4.0.0.
3. Check how the affected models in XML (Xstream) representation can be mapped to the latest Smile model classes.
4. Write a generic migrator which parses the models in XML representation and creates the new Smile 4.0.0 model. 
5. Serialize the 4.0.0 model with Xstream to be able to migrate to the next Smile major version in the future.

**Comment by kklioss** [comment]
Hi, retraining is actually the easiest way, especially ML models should be regularly retrained given the changes of data. But if retraining is not an option, the process you layout makes sense. Good luck!
