### ISSUE TITLE
Android Studio, Invalid build configuration

### ISSUE THREAD

**Issue by CircaLucid** [haifengl/smile#799]
Encountered with Android Studio 2024.1.1 and 2024.2.1 on Ubuntu 24.10. Created new project with Empty Activity. Added 
```
dependencies {
     implementation("com.github.haifengl:smile-kotlin:4.0.0")
}
```
to build.gradle.kts. Build app and get "> Task :app:mergeExtDexDebug FAILED" and "Invalid build configuration. Attempt to create a global synthetic for 'Record desugaring' without a global-synthetics consumer." Also getting "> Task :app:mergeDebugJavaResource FAILED" and "> 2 files found with path 'META-INF/native-image/macosx-arm64/jnijavacpp/jni-config.json' from inputs:".

Changed to
```
dependencies {
     implementation("com.github.haifengl:smile-kotlin:3.1.1")
}
```
, "desugaring" error is gone but "2 files" error persists. Added 
```
packaging {
    resources {
        excludes += "META-INF/native-image/*/jnijavacpp/jni-config.json"
        excludes += "META-INF/native-image/*/jnijavacpp/reflect-config.json"
    }
}
```
and app is now compiling and running.

While this works for me, I'm sure it breaks something for others. Is there a correct fix?

**Comment by kklioss** [comment]
Smile 4.0 requires Java 21 now. I don't think that Android supports Java 21 yet.

**Comment by CircaLucid** [comment]
Odd. In smile/kotlin/build.gradle.kts, I see `kotlinOptions.jvmTarget = "21"` and would assume that that would bubble up in Android Studio at compile time.
