### ISSUE TITLE
how to add a column?

### ISSUE THREAD

**Issue by li-fcb1899** [haifengl/smile#800]
Dataframe's property column is private

**Additional context**
- Orack JDK 23
- Smile version 4.0.0
- Windows

**Comment by kklioss** [comment]
Use [merge](https://haifengl.github.io/api/java/smile/data/DataFrame.html#merge(smile.data.vector.BaseVector...)) to add columns. It is also overloaded to merge dataframes.

**Comment by li-fcb1899** [comment]
> Use [merge](https://haifengl.github.io/api/java/smile/data/DataFrame.html#merge(smile.data.vector.BaseVector...)) to add columns. It is also overloaded to merge dataframes.

thanks very much👏

**Comment by li-fcb1899** [comment]
> Use [merge](https://haifengl.github.io/api/java/smile/data/DataFrame.html#merge(smile.data.vector.BaseVector...)) to add columns. It is also overloaded to merge dataframes.

thanks very much👏

**Comment by kklioss** [comment]
You are welcome. More information can be found at project [website](https://haifengl.github.io/data.html).
