### ISSUE TITLE
Getting Started Question with non-static error

### ISSUE THREAD

**Issue by pacozaa** [haifengl/smile#82]
I write this main method in java and run it on netbeans
```java

import java.io.IOException;
import java.text.ParseException;
import smile.classification.AdaBoost;
import smile.data.AttributeDataset;
import smile.data.parser.ArffParser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Kickoff {

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String[] args) throws IOException, ParseException {
        ArffParser arffParser = new ArffParser();
        arffParser.setResponseIndex(4);
        AttributeDataset weather = arffParser.parse(this.getClass().getResourceAsStream("/smile/data/weka/weather.nominal.arff"));
        double[][] x = weather.toArray(new double[weather.size()][]);
        int[] y = weather.toArray(new int[weather.size()]);
        AdaBoost forest = new AdaBoost(weather.attributes(), x, y, 200, 4);
    }
    
}
```
From above code I got the error at line  `AttributeDataset weather = arffParser.parse(this.getClass().getResourceAsStream("/smile/data/weka/weather.nominal.arff"));`

like this 

> Error : non-static variable this cannot be referenced from a static context

How can I solve this? 

Do you have some getting start example code? I would like to get familiar with smile fast. It looks like snippet in README.md is not enough for me. What do you think?

**Comment by haifengl** [comment]
Have you checked out our [website](http://haifengl.github.io/smile/)? We have a lot of examples there. If you start with the shell, it is much easier to use. You do need to know some scala.

For this example, it assumes the data file is packaged into the jar, which is not any more. Instead, you have to open it as a file. If you clone the project, the file is in shell/src/universal/data. The sample data are available in the download package too.

**Comment by pacozaa** [comment]
Thank you. 
Yes, I have checked it. Do you mean in User Guide tab? If not please give me some example link.
Can I use this library in JAVA or I need to use it by Scala only?
I updated my question again for more information.

Do you mean I have to use some java's file reader?
I don't think my error in the question is about file stuff as [I search it on google](https://www.google.co.th/search?q=non-static+variable+this+cannot+be+referenced+from+a+static+context&rlz=1C1CHWA_enTH625TH625&oq=non-static+variable+this+cannot+be+referenced+from+a+static+context&aqs=chrome..69i57j0l5.390j0j7&sourceid=chrome&ie=UTF-8).

Any further question would be appreciate.

**Comment by haifengl** [comment]
I don't have to use scala, although our scala api is much easier to use.

I have update ReadME on the code example. You need to have the data files download first. They are included in the packages on releases pages.

**Comment by haifengl** [comment]
Your particular is that you call

this.getClass()

in a static function `main`. There is no `this` in a static context. First of all, the data file is not in the jar, so you should not use this.getClass().getResourceAsStream(). Instead, use FileInputStream and make sure the path pointing to the correct file.

**Comment by pacozaa** [comment]
Thank you. I will try this and give a feedback as soon as possible.
