### ISSUE TITLE
Documentation missing for smile.data

### ISSUE THREAD

**Issue by douglasArantes** [haifengl/smile#85]
The smile.data package is missing in the online documentation.

http://haifengl.github.io/smile/api/scala/index.html#smile.package

**Comment by haifengl** [comment]
Smile.data is pure Java. Check out its doc in java doc.

**Comment by douglasArantes** [comment]
But I refer to Scala API (high-level operators).

https://github.com/haifengl/smile/blob/master/scala/src/main/scala/smile/data/package.scala

**Comment by haifengl** [comment]
It is actually a bug with scaladoc. If a package has only the package object, it doesn't generate the doc. Btw, this package isn't really about the high level api of java smile.data. It is some implicit helper functions on divulge arrays.

**Comment by douglasArantes** [comment]
Ok, thanks!

**Comment by haifengl** [comment]
Btw, I will add a scala api for matrix computation with runtime optimization. Some of this package object will move there.

**Comment by douglasArantes** [comment]
Cool! You will use some library for this?

**Comment by haifengl** [comment]
We already have a lot of matrix computation stuffs in smile.math.matrix. I will add a nice scala api so that you can use them just like write math formula.
