### ISSUE TITLE
SMILE modifies passed data in-place

### ISSUE THREAD

**Issue by lukehutch** [haifengl/smile#87]
SMILE (at least, the LASSO regressor) modifies data in-place (i.e. the contents of the feature vectors that are passed in are directly modified). I didn't check to see if other regressors or classifiers do the same thing.

https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/regression/LASSO.java#L258

This is surprising! It should at least be mentioned clearly in the comments that the passed data matrix will be normalized/standardized on exit.

Having to make a copy of the dataset is undesirable, but undocumented side effects are much more undesirable.

**Comment by haifengl** [comment]
I added warning in the web site too

http://haifengl.github.io/smile/index.html#regression

**Comment by haifengl** [comment]
BTW, matrix decomposition operations LU, QR, and Cholesky in smile.math.matrix all work in place.

**Comment by lukehutch** [comment]
Thanks. I only looked at one regression class, you probably want to double-check all the other regression and classification classes to be safe.

**Comment by haifengl** [comment]
I did quickly double check other classifier and regression algorithms. Will do more go through later. Thanks!

**Comment by alexeygrigorev** [comment]
Maybe there should be a flag, something similar to `inplace=True` in pandas?

**Comment by haifengl** [comment]
Wait a second, a second look shows that we don't modify data in place.

        if (n > p) {
            center = Math.colMean(x);
            X = new double[n][p];
....


As shown, if we normalize the data, we allocate a new matrix. So it is not a bug.

**Comment by lukehutch** [comment]
Oops, my bad, I don't know how I missed that. Sorry for the false alarm.
