### ISSUE TITLE
NaNs in LASSO

### ISSUE THREAD

**Issue by alexeygrigorev** [haifengl/smile#89]
LASSO always produces NaN's for me. What am I doing wrong?

The code:

    double[][] X = { { 1, 1 }, { 1, 2 }, { 1, 3 }, { 1, 4 }, { 1, 5 } };
    double[] y = { 2.1, 2.9, 3.9, 5.1, 7.1 };

    OLS ols = new OLS(X, y);
    System.out.println(ols.adjustedRSquared());

    double lambda = 1.0;
    LASSO lasso = new LASSO(X, y, lambda, 0.01, 100);
    System.out.println(lasso.RSS());

OLS works as expected, but LASSO produces a lot of NaNs (see sysout output here: http://pastebin.com/Qzeew9yz)

The version I use is 1.1.0 from maven central.

**Comment by alexeygrigorev** [comment]
I also tried Ridge and it also outputs NaNs for many different values of alpha

**Comment by alexeygrigorev** [comment]
Possibly related to #86

**Comment by haifengl** [comment]
The first column is constant, which has zero variance, which cause NaN. I will improve the code to handle this.

**Comment by alexeygrigorev** [comment]
@haifengl isn't it a common practice to have the constant in the first (or last) column to account for bias? 

By a quick look at the code I see that both the predictors and the target are mean-normalized, so the constant term isn't really needed. Maybe it should be reflected in the java docs somewhere?

**Comment by haifengl** [comment]
we handle bias automatically. you should not include this column. I will update the comments to reflect it. Thanks!

**Comment by haifengl** [comment]
I improve the code to handle constant columns, which is in the master branch now. Before we release a new version, please git clone and build by yourself. Thanks!

Although no need to include bias column, some data do have constant columns as shown in #86. We can handle it now :)

**Comment by alexeygrigorev** [comment]
Thanks
