### ISSUE TITLE
Lasso can get stuck in NaN state

### ISSUE THREAD

**Issue by lukehutch** [haifengl/smile#91]
I tried running LASSO with lambda values of 1.0 and 0.001 with the dataset posted in another recent bug report.

Occasionally LASSO reports NaN values, and then gets stuck there (since it can't evaluate the stopping criteria).

Here is an example from a single run -- the learner seems to restart at some point, and gets stuck at NaN. (Sometimes it will randomly start in that state.)

I have removed the zero columns from the dataset.

--------------

INFO: LASSO: primal and dual objective function value after   0 iterations: 2.3831e+05	0.0042565

Jun 16, 2016 6:17:11 PM smile.math.Math solve
INFO: BCG: the error after   7 iterations: 0.088020
Jun 16, 2016 6:17:29 PM smile.math.Math solve
INFO: BCG: the error after  10 iterations: 0.28909
Jun 16, 2016 6:17:44 PM smile.math.Math solve
INFO: BCG: the error after  20 iterations: 0.051904
Jun 16, 2016 6:17:59 PM smile.math.Math solve
INFO: BCG: the error after  30 iterations: 0.0090969
Jun 16, 2016 6:17:59 PM smile.math.Math solve
INFO: BCG: the error after  30 iterations: 0.0090969
Jun 16, 2016 6:18:20 PM smile.math.Math solve
INFO: BCG: the error after  10 iterations: 25.013
Jun 16, 2016 6:18:35 PM smile.math.Math solve
INFO: BCG: the error after  20 iterations: 4.6102
Jun 16, 2016 6:18:50 PM smile.math.Math solve
INFO: BCG: the error after  30 iterations: 0.65362
Jun 16, 2016 6:19:05 PM smile.math.Math solve
INFO: BCG: the error after  40 iterations: 0.16297
Jun 16, 2016 6:19:20 PM smile.math.Math solve
INFO: BCG: the error after  50 iterations: 0.063640
Jun 16, 2016 6:19:35 PM smile.math.Math solve
INFO: BCG: the error after  60 iterations: 0.033595
Jun 16, 2016 6:19:50 PM smile.math.Math solve
INFO: BCG: the error after  70 iterations: 0.013194
Jun 16, 2016 6:19:51 PM smile.math.Math solve
INFO: BCG: the error after  71 iterations: 0.0079209
Jun 16, 2016 6:20:09 PM smile.math.Math solve
INFO: BCG: the error after  10 iterations: 161.79
Jun 16, 2016 6:20:25 PM smile.math.Math solve
INFO: BCG: the error after  20 iterations: 46.267
Jun 16, 2016 6:20:40 PM smile.math.Math solve
INFO: BCG: the error after  30 iterations: 25.900
Jun 16, 2016 6:20:55 PM smile.math.Math solve
INFO: BCG: the error after  40 iterations: 5.7949
Jun 16, 2016 6:21:11 PM smile.math.Math solve
INFO: BCG: the error after  50 iterations: 3.8326
Jun 16, 2016 6:21:28 PM smile.math.Math solve
INFO: BCG: the error after  60 iterations: 1.2685
Jun 16, 2016 6:21:44 PM smile.math.Math solve
INFO: BCG: the error after  70 iterations: 0.68144
Jun 16, 2016 6:22:02 PM smile.math.Math solve
INFO: BCG: the error after  80 iterations: 2.1731
Jun 16, 2016 6:22:19 PM smile.math.Math solve
INFO: BCG: the error after  90 iterations: 9.0057
Jun 16, 2016 6:22:37 PM smile.math.Math solve
INFO: BCG: the error after 100 iterations: 15.446
Jun 16, 2016 6:22:52 PM smile.math.Math solve
INFO: BCG: the error after 110 iterations: 8.6861
Jun 16, 2016 6:23:07 PM smile.math.Math solve
INFO: BCG: the error after 120 iterations: 1.7096
Jun 16, 2016 6:23:22 PM smile.math.Math solve
INFO: BCG: the error after 130 iterations: 0.73958
Jun 16, 2016 6:23:38 PM smile.math.Math solve
INFO: BCG: the error after 140 iterations: 0.10112
Jun 16, 2016 6:23:53 PM smile.math.Math solve
INFO: BCG: the error after 150 iterations: 0.029828
Jun 16, 2016 6:24:00 PM smile.math.Math solve
INFO: BCG: the error after 154 iterations: 0.0080286
Jun 16, 2016 6:24:19 PM smile.math.Math solve
INFO: BCG: the error after  10 iterations: 85.857
Jun 16, 2016 6:24:35 PM smile.math.Math solve
INFO: BCG: the error after  20 iterations: 61.842
Jun 16, 2016 6:24:51 PM smile.math.Math solve
INFO: BCG: the error after  30 iterations: 18.563
Jun 16, 2016 6:25:09 PM smile.math.Math solve
INFO: BCG: the error after  40 iterations: 13.444
Jun 16, 2016 6:25:26 PM smile.math.Math solve
INFO: BCG: the error after  50 iterations: 18.216
Jun 16, 2016 6:25:41 PM smile.math.Math solve
INFO: BCG: the error after  60 iterations: 72.348
Jun 16, 2016 6:25:56 PM smile.math.Math solve
INFO: BCG: the error after  70 iterations: 133.29
Jun 16, 2016 6:26:11 PM smile.math.Math solve
INFO: BCG: the error after  80 iterations: 236.88
Jun 16, 2016 6:26:25 PM smile.math.Math solve
INFO: BCG: the error after  90 iterations: 233.28
Jun 16, 2016 6:26:40 PM smile.math.Math solve
INFO: BCG: the error after 100 iterations: 37.535
Jun 16, 2016 6:26:55 PM smile.math.Math solve
INFO: BCG: the error after 110 iterations: 22.891
Jun 16, 2016 6:27:10 PM smile.math.Math solve
INFO: BCG: the error after 120 iterations: 2.3307
Jun 16, 2016 6:27:24 PM smile.math.Math solve
INFO: BCG: the error after 130 iterations: 0.67815
Jun 16, 2016 6:27:38 PM smile.math.Math solve
INFO: BCG: the error after 140 iterations: 0.090790
Jun 16, 2016 6:27:54 PM smile.math.Math solve
INFO: BCG: the error after 150 iterations: 0.016043
Jun 16, 2016 6:27:59 PM smile.math.Math solve
INFO: BCG: the error after 154 iterations: 0.0086919
Jun 16, 2016 6:28:00 PM smile.regression.LASSO <init>
INFO: LASSO: primal and dual objective function value after   5 iterations: 1.0221e+05	1.0221e+05

Jun 16, 2016 6:28:02 PM smile.regression.LASSO <init>
INFO: LASSO: primal and dual objective function value after   0 iterations: NaN	NaN

Jun 16, 2016 6:28:15 PM smile.math.Math solve
INFO: BCG: the error after  10 iterations: NaN
Jun 16, 2016 6:28:26 PM smile.math.Math solve
INFO: BCG: the error after  20 iterations: NaN
Jun 16, 2016 6:28:37 PM smile.math.Math solve
INFO: BCG: the error after  30 iterations: NaN
Jun 16, 2016 6:28:50 PM smile.math.Math solve
INFO: BCG: the error after  40 iterations: NaN
Jun 16, 2016 6:29:02 PM smile.math.Math solve
INFO: BCG: the error after  50 iterations: NaN
Jun 16, 2016 6:29:13 PM smile.math.Math solve
INFO: BCG: the error after  60 iterations: NaN
Jun 16, 2016 6:29:25 PM smile.math.Math solve
INFO: BCG: the error after  70 iterations: NaN
Jun 16, 2016 6:29:37 PM smile.math.Math solve
INFO: BCG: the error after  80 iterations: NaN
Jun 16, 2016 6:29:49 PM smile.math.Math solve
INFO: BCG: the error after  90 iterations: NaN
Jun 16, 2016 6:30:00 PM smile.math.Math solve
INFO: BCG: the error after 100 iterations: NaN
[...gets stuck here...]

**Comment by haifengl** [comment]
Are you using 1.1 or master?

**Comment by lukehutch** [comment]
I'm still using 1.1.

**Comment by haifengl** [comment]
Each iteration needs to call BCG, which is an iterative algorithm too. It is not a restart. I tried on both data you provided with master code. I have not observed this problem yet. Will keep trying.

**Comment by haifengl** [comment]
Did you see my comments on SparseMatrix with Lasso in another thread? It is a lot faster.

**Comment by haifengl** [comment]
Cannot replicate this issue with Oracle JDK and latest code. Will keep an eye on this if it happens. Thanks!
