### ISSUE TITLE
PMML support suggestion (instead of serialization)

### ISSUE THREAD

**Issue by Xyclade** [haifengl/smile#95]
I saw #79, maybe Predictive markup model language ([PMML](https://en.wikipedia.org/wiki/Predictive_Model_Markup_Language)) is a better option rather than serialization?

**Comment by haifengl** [comment]
PMML is most useful to exchange models with other systems, which seems not a strong need right now. Besides, PMML doesn't cover all of our algorithms. Also, our implementations may contain additional information, which will be lost when exposed to PMML.

**Comment by Xyclade** [comment]
I see, I had expected the PMML to be rather complete by now since it was first proposed in 1999, and currently is in version 4.  

I'll use the serialization of models instead, thank you for enabling this!
